/**
 * CREDIT RISK OS 2.0 — CASE 02: TREASURY FTP DATA TRANSFORMATION
 * Domain-specific configuration and dataset conforming to shared framework CaseDefinition.
 */

import {
  CaseDefinition,
  CaseMetadata,
  CaseStakeholder,
  CaseEvidence,
  ProcessNode,
  BusinessRequirement,
  BusinessRule,
  SourceToTargetMapping,
  InvestigationTask,
  CaseDefect,
  UATTestCase,
  TraceabilityChain,
  ReconciliationSummary,
  SignOffRequirement,
  GovernanceConfig,
} from '../_framework/types';

export const CASE_02_METADATA: CaseMetadata = {
  id: 'CASE-002',
  code: 'CASE-2026-02',
  title: 'Treasury FTP Data Transformation',
  type: 'Treasury + Data + Business Analysis + Reconciliation',
  primaryDomains: [
    'Funds Transfer Pricing',
    'Treasury ALM',
    'ETL Pipelines',
    'STTM Data Quality',
    'Multi-Stage Reconciliation',
    'Architecture Fitness',
  ],
  institution: 'Indus Apex Bank India',
  simulatedDate: '31 July 2026',
  businessOwner: 'Head of Treasury ALM & Country Finance Controller',
  targetDeadline: '15 August 2026 (ALCO Monthly Reporting Cutoff)',
  problemStatement:
    'Month-end Treasury Finance reporting identified a material balance discrepancy between Source Lending Balances (₹2,645.0 Cr) and FTP Engine Output (₹3,000.0 Cr). Ingestion timing gaps, unmapped product codes, repricing tenor mismatches, and 1:M reference join duplicates created a net ₹355.0 Cr unexplained variance downstream and a Gross Absolute Reconciliation Break of ₹1,745.0 Cr.',
};

export const STAKEHOLDERS: CaseStakeholder[] = [
  {
    id: 'STK-FTP-01',
    name: 'Tariq Merchant',
    title: 'Treasury FTP Product Owner',
    department: 'Group Treasury & Balance Sheet Management',
    roleDescription: 'Owns internal Funds Transfer Pricing policy, yield curve construction, and ALCO rate-setting methodology under Bank Policy Simulation.',
    keyConcern: 'Ensuring matched-maturity and repricing-tenor FTP rates accurately reflect liquidity costs without mispricing commercial loans.',
    decisionsOwned: ['FTP Rate Calculation Methodology', 'Transfer Pricing Policy Exceptions', 'Yield Curve Mapping Rules'],
    evidenceProvided: ['EV-FTP-02 (ALCO Funds Transfer Pricing Methodology Specs)'],
  },
  {
    id: 'STK-FTP-02',
    name: 'Sunita Rao',
    title: 'Country Finance Lead',
    department: 'Financial Control & Accounting Oversight',
    roleDescription: 'Owns General Ledger lending balances, accounting control totals, and source-to-FTP balance reconciliation sign-offs.',
    keyConcern: 'Reconciling the net ₹355.0 Cr balance variance and ₹1,745.0 Cr gross absolute break across ETL staging pipelines before monthly ALCO close.',
    decisionsOwned: ['General Ledger Balance Control Sign-off', 'Variance Tolerance Sign-off'],
    evidenceProvided: ['EV-FTP-01 (Treasury ALCO Balance Discrepancy Memorandum)'],
  },
  {
    id: 'STK-FTP-03',
    name: 'Alok Verma',
    title: 'ALM & Liquidity Reporting Lead',
    department: 'Asset Liability Management (ALM)',
    roleDescription: 'Owns downstream liquidity extracts, interest rate risk in banking book (IRRBB) bucket aggregation, and LCR/NSFR data feeds.',
    keyConcern: 'Preventing downstream liquidity extracts from consuming stale batch run versions or unmapped product categories.',
    decisionsOwned: ['Downstream Liquidity Extract Sign-off', 'IRRBB Tenor Bucket Sign-off'],
    evidenceProvided: ['EV-FTP-06 (Downstream Liquidity Extract Version Audit)'],
  },
  {
    id: 'STK-FTP-04',
    name: 'Deepak Deshmukh',
    title: 'Data Engineering Lead',
    department: 'Enterprise Data Engineering & ETL Infrastructure',
    roleDescription: 'Owns daily lending data ingestion pipelines, canonical treasury data mart schemas, and BCBS 239 source-to-target lineage.',
    keyConcern: 'Eliminating 1:M duplicate joins in product reference lookup tables that double-count facility balances.',
    decisionsOwned: ['ETL Transformation Pipeline Deployment', 'Canonical Mart Table Schema'],
    evidenceProvided: ['EV-FTP-04 (Legacy ETL Mapping & Join Lineage Spec)'],
  },
  {
    id: 'STK-FTP-05',
    name: 'Kavita Reddy',
    title: 'Treasury Technology Lead',
    department: 'Treasury Systems Architecture & Calculation Engines',
    roleDescription: 'Owns the FTP calculation engine software execution, curve lookup tables, and run version publishing scripts.',
    keyConcern: 'Ensuring floating-rate facilities correctly evaluate `next_repricing_date` instead of defaulting to contractual maturity.',
    decisionsOwned: ['FTP Engine Software Deployment', 'Calculation Engine API Specifications'],
    evidenceProvided: ['EV-FTP-05 (Software Bug Incident Note — Tenor & Product Lookup)'],
  },
  {
    id: 'STK-FTP-06',
    name: 'Arjun Nair',
    title: 'Solution Architect',
    department: 'Enterprise Architecture & Governance',
    roleDescription: 'Evaluates target-state system boundaries, interface contracts, rerun reproducibility, and BA fitness-for-purpose.',
    keyConcern: 'Establishing immutable run versioning (`run_version_id`) so downstream consumers never ingest unapproved reruns.',
    decisionsOwned: ['Target State Architecture Sign-off', 'Interface Control Standard Approval'],
    evidenceProvided: ['EV-FTP-07 (Solution Architecture BA Fitness-for-Purpose Assessment)'],
  },
  {
    id: 'STK-FTP-07',
    name: 'Bhavna Patel',
    title: 'QA & UAT Testing Lead',
    department: 'Quality Assurance & Business Acceptance Testing',
    roleDescription: 'Coordinates business acceptance testing, manages boundary test cases, and verifies regression evidence.',
    keyConcern: 'Verifying 100% of repricing date boundaries, curve bucket lookups, and control total reconciliations before release sign-off.',
    decisionsOwned: ['UAT Execution Sign-off', 'Defect Remediation Verification'],
    evidenceProvided: ['EV-FTP-05 (Software Bug Incident Note — Tenor & Product Lookup)'],
  },
  {
    id: 'STK-FTP-08',
    name: 'Girish Hegde',
    title: 'BAU Treasury Operations Lead',
    department: 'Treasury Operations & Production Support',
    roleDescription: 'Owns day-to-day operational execution, production exception queue routing, and BAU handover readiness.',
    keyConcern: 'Ensuring rejected records are routed to an operational exception queue rather than silently defaulted.',
    decisionsOwned: ['BAU Operational Handover Acceptance', 'Production Exception Routing Approval'],
    evidenceProvided: ['Operational Rerun & Exception Log'],
  },
  {
    id: 'STK-FTP-09',
    name: 'Learner (Lead Business Analyst)',
    title: 'Transformation Lead Business Analyst',
    department: 'Treasury & Financial Change Programme',
    roleDescription: 'Lead BA assigned to investigate balance variances, author target requirements, design STTM, coordinate UAT, and secure sign-offs.',
    keyConcern: 'Delivering an end-to-end controlled target state with complete traceability before the ALCO reporting cutoff.',
    decisionsOwned: ['BRD Requirements Register', 'Source-to-Target Mapping (STTM)', 'Traceability Matrix (RTM)'],
    evidenceProvided: ['Business Requirements Document (BRD)', 'Requirements Traceability Matrix (RTM)'],
  },
];

export const EVIDENCE_PACK: CaseEvidence[] = [
  {
    id: 'EV-FTP-01',
    code: 'EVID-REC-01',
    title: 'Treasury ALCO Balance Discrepancy Memorandum',
    type: 'Memo',
    summary: 'Identifies a net ₹355.0 Cr balance discrepancy and ₹1,745.0 Cr gross absolute break across ETL staging pipelines as of 31 July 2026.',
    providedBy: 'Sunita Rao (Country Finance Lead)',
    fullText:
      'During the 31 July 2026 ALCO pre-close reconciliation, Country Finance identified that raw Core Banking lending balances totaled ₹2,645.0 Cr across 8 corporate facilities. However, independent stage transitions revealed compensating errors: Source → Staging omitted ₹345.0 Cr (-1 facility), Staging → FTP Output double-counted ₹700.0 Cr (+2 records), and FTP Output → Downstream Extract dropped ₹700.0 Cr due to stale run consumption (`RUN-20260730-01`). Net Difference: +₹355.0 Cr. Gross Absolute Reconciliation Break: ₹1,745.0 Cr. Principle: Compensating errors must never be allowed to reconcile by netting.',
    keyInsights: [
      '₹345.0 Cr loan balances omitted from staging due to batch timing gap (DEF-FTP-004)',
      '₹700.0 Cr infrastructure loan double-counted in FTP output (DEF-FTP-002)',
      '₹700.0 Cr dropped downstream due to stale run consumption (DEF-FTP-005)',
      'Gross Absolute Break = ₹1,745.0 Cr. Netting masks underlying control failures!',
    ],
  },
  {
    id: 'EV-FTP-02',
    code: 'EVID-POL-02',
    title: 'ALCO Funds Transfer Pricing Methodology Specs',
    type: 'Policy Doc',
    summary: 'Defines internal transfer rate formula, curve bucket mapping rules, and component rate stacking under Bank Policy Simulation.',
    providedBy: 'Tariq Merchant (Treasury FTP Owner)',
    fullText:
      'Bank Policy Specs:\n1. FTP is an internal management pricing mechanism (Bank Policy Simulation).\n2. Internal Transfer Rate Formula: FTP Rate = Base Curve Rate + Tenor/Liquidity Premium + Optionality Adjustment.\n3. Floating-rate facilities must price on Repricing Tenor (next_repricing_date - as_of_date).\n4. Fixed-rate facilities price on Matched Maturity (maturity_date - as_of_date).\n5. Commercial Customer Lending Rate = FTP Rate + Commercial Margin. Commercial margin belongs to Business Unit, FTP Rate belongs to Treasury.',
    keyInsights: [
      'FTP Rate = Base Curve + Liquidity Premium + Optionality',
      'Floating-rate loans price on Repricing Tenor, not Maturity Date',
      'Commercial Margin is distinct from Internal FTP Rate',
    ],
  },
  {
    id: 'EV-FTP-03',
    code: 'EVID-DAT-03',
    title: 'Data Ingestion & Batch Clearing Cutoff Log',
    type: 'Data Extract',
    summary: 'Reveals ₹345.0 Cr loan balances omitted from FTP Input Stage due to batch cutoff mismatch.',
    providedBy: 'Deepak Deshmukh (Data Engineering Lead)',
    fullText:
      'ETL Ingestion Log:\nBatch job `job_ingest_cbs_lending` triggered at 18:00:00 on 31 July 2026. Facility GUJ-REN-3305 (Sabarmati Clean Energy, ₹345.0 Cr) cleared core banking booking at 21:30:00. Because the batch ran prior to 23:59:59 EOD clearing completion, facility GUJ-REN-3305 was excluded from `FTP_INPUT_STAGE`, understating staging balances by ₹345.0 Cr.',
    keyInsights: [
      'Staging batch ran 6 hours prior to EOD clearing completion',
      'Facility GUJ-REN-3305 (₹345.0 Cr) omitted from input stage',
    ],
  },
  {
    id: 'EV-FTP-04',
    code: 'EVID-MAP-04',
    title: 'Legacy ETL Mapping & Join Lineage Specification',
    type: 'Data Extract',
    summary: 'Reveals legacy 1:M product reference join duplicating infrastructure loan HYD-INF-9902.',
    providedBy: 'Deepak Deshmukh (Data Engineering Lead)',
    fullText: 'Legacy Mapping Defect:\nSQL transformation script `sp_build_ftp_input.sql` joined `CBS_LOAN_CONTRACT` to `PRODUCT_REFERENCE` using only `product_code` without filtering on `effective_status = "ACTIVE"`. `PRODUCT_REFERENCE` contained 2 active rows for product code `PROD-INF-02` (legacy version + updated version), generating 2 duplicate facility rows for HYD-INF-9902 and inflating FTP output balance by ₹700.0 Cr.',
    keyInsights: [
      'Missing filter on product reference table created duplicate rows',
      'Facility HYD-INF-9902 double-counted from ₹700 Cr to ₹1,400 Cr',
    ],
  },
  {
    id: 'EV-FTP-05',
    code: 'EVID-BUG-05',
    title: 'Software Bug Incident Note — Tenor & Product Lookup',
    type: 'Defect Note',
    summary: 'Technical bug report detailing repricing tenor fallback error and unmapped product code lookup failure.',
    providedBy: 'Kavita Reddy (Treasury Technology Lead)',
    fullText:
      'Defect Log DEF-FTP-001 & DEF-FTP-003:\n1. In `ftp_tenor_engine.py`, condition `if (next_repricing_date is None): repricing_tenor = maturity_date - as_of_date` evaluated `next_repricing_date` as None due to string date format mismatch (`DD/MM/YYYY` vs `YYYY-MM-DD`). Floating loan PUN-MFG-4403 priced on 3-year maturity curve (7.80%) instead of 3-month repricing curve (6.90%), overcharging transfer pricing by 90 bps.\n2. Renewable product code `PROD-REN-05` was unmapped in `ALM_LIQUIDITY_CLASSIFICATION`, defaulting liquidity premium to 0.00% instead of required 0.85%.',
    keyInsights: [
      'Date format mismatch triggered wrong maturity fallback (overcharged 90 bps)',
      'Unmapped product default underpriced liquidity premium by 85 bps',
    ],
  },
  {
    id: 'EV-FTP-06',
    code: 'EVID-EXT-06',
    title: 'Downstream Liquidity Extract Version Audit',
    type: 'Minutes',
    summary: 'Audit report showing downstream Group Liquidity extract consumed previous batch run version.',
    providedBy: 'Alok Verma (ALM Lead)',
    fullText:
      'Downstream Extract Audit:\nGroup Liquidity extract script `sp_export_alm_extract.sql` fetched data from `FTP_ENGINE_OUTPUT` using hardcoded query `WHERE run_date = CURRENT_DATE() - 1` instead of reading the latest approved `run_version_id`. Result: Downstream ALM reports consumed yesterday’s stale run (`RUN-20260730-01`), ignoring today’s FTP calculation run (`RUN-20260731-01`).',
    keyInsights: [
      'Downstream extract consumed yesterday’s stale run version',
      'Fix requires explicit `run_version_id` parameter passing',
    ],
  },
  {
    id: 'EV-FTP-07',
    code: 'EVID-ARC-07',
    title: 'Solution Architecture BA Fitness-for-Purpose Assessment Note',
    type: 'Policy Doc',
    summary: 'Evaluates target-state architecture boundaries, interface contracts, rerun reproducibility, and BAU operational ownership.',
    providedBy: 'Arjun Nair (Solution Architect)',
    fullText:
      'BA Architecture Fitness Assessment Results:\n1. Authoritative Source Ownership: Core Banking CBS is confirmed as sole lending source.\n2. Canonical Grain: Defined as (obligor_id + facility_id + as_of_date).\n3. Reference Data Versioning: Enforces effective_status = "ACTIVE".\n4. Rerun Reproducibility: 100% deterministic output on identical inputs.\n5. Run Version Governance: Immutable run_version_id tags all published outputs.\n6. Exception Visibility: Missing attributes route to operational exception queue.\n7. BAU Ownership: Defined under Treasury Operations (Girish Hegde).',
    keyInsights: [
      'Target architecture passes all 7 BA fitness-for-purpose criteria',
      'Immutable run versioning guarantees zero downstream version drift',
    ],
  },
];

export const CURRENT_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Core Banking Servicing (CBS)',
    owner: 'BAU Treasury Operations (Girish Hegde)',
    desc: 'Captures daily corporate loan balances and repricing schedules. Ingestion batch triggers at 18:00 before EOD clearing.',
    breakPoint: 'Timing Gap: Ingestion at 18:00 omits ₹345.0 Cr loan cleared at 21:30.',
  },
  {
    step: '02',
    title: 'ETL Staging & Product Join',
    owner: 'Data Engineering Lead (Deepak Deshmukh)',
    desc: 'Joins loan contract table with product reference table to assign liquidity categories and tenor buckets.',
    breakPoint: '1:M Join Duplicate: Missing `effective_status` filter duplicates facility HYD-INF-9902 (₹700 Cr overstatement).',
  },
  {
    step: '03',
    title: 'FTP Calculation Engine',
    owner: 'Treasury Technology Lead (Kavita Reddy)',
    desc: 'Executes yield curve lookups and transfer rate calculations applying Bank Policy Simulation formulas.',
    breakPoint: 'Tenor Fallback Defect: Date format string bug causes floating loans to price on maturity tenor (90 bps overcharge).',
  },
  {
    step: '04',
    title: 'Unmapped Product Exception Handling',
    owner: 'Treasury FTP Owner (Tariq Merchant)',
    desc: 'Unmapped product codes default to generic zero rates without operational exception alerts.',
    breakPoint: 'Silent Default: Renewable loan `PROD-REN-05` assigned 0.00% liquidity premium instead of 0.85%.',
  },
  {
    step: '05',
    title: 'FTP Engine Output Table',
    owner: 'Treasury Technology Lead (Kavita Reddy)',
    desc: 'Stores calculation outputs for Finance GL and ALM consumption.',
    breakPoint: 'Version Discrepancy: Engine publishes `RUN-20260731-01`, but lacks enforced version lock.',
  },
  {
    step: '06',
    title: 'Downstream Finance & ALM Extract',
    owner: 'Country Finance Lead (Sunita Rao)',
    desc: 'Finance and ALM extract FTP outputs for monthly GL posting and liquidity reporting.',
    breakPoint: 'Stale Version Consumption: Downstream script fetches previous day run (`RUN-20260730-01`), creating ₹355 Cr net variance.',
  },
];

export const TARGET_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Authoritative Lending Sources',
    owner: 'BAU Operations (Girish Hegde)',
    desc: 'Captures Core Banking lending balances post EOD clearing completion at 23:59:59 with explicit transaction timestamp.',
    controlPoint: 'Snapshot Control: Ingestion validates EOD clearing completion before triggering ETL pipeline.',
  },
  {
    step: '02',
    title: 'Controlled Ingestion & Canonical Mart',
    owner: 'Data Engineering Lead (Deepak Deshmukh)',
    desc: 'Ingests CBS contracts into canonical data mart using composite key (`obligor_id` + `facility_id` + `as_of_date`).',
    controlPoint: 'Deduplication Control: Rejects 1:M duplicate joins and validates unique facility grain.',
  },
  {
    step: '03',
    title: 'Data Quality & Attribute Validation Gate',
    owner: 'Treasury Technology Lead (Kavita Reddy)',
    desc: 'Validates mandatory repricing attributes (`next_repricing_date`, `interest_rate_type`, `product_code`) prior to pricing.',
    controlPoint: 'Attribute Validation: Parses ISO date formats (`YYYY-MM-DD`) and routes invalid attributes to exception queue.',
  },
  {
    step: '04',
    title: 'Versioned FTP Engine Execution',
    owner: 'Treasury FTP Owner (Tariq Merchant)',
    desc: 'Calculates FTP Rate = Base Curve + Liquidity Premium + Optionality Adjustment under Bank Policy Simulation.',
    controlPoint: 'Run Versioning: Tag every record with immutable `run_version_id` (e.g. `RUN-20260731-01`).',
  },
  {
    step: '05',
    title: 'Multi-Stage Automated Reconciliation',
    owner: 'Country Finance Lead (Sunita Rao)',
    desc: 'Executes automated balance reconciliation across Source Lending $\rightarrow$ Staging $\rightarrow$ FTP Output $\rightarrow$ Downstream Extract.',
    controlPoint: 'Balance Control: Reconciles total outstanding to ₹2,645.0 Cr with zero unexplained variance.',
  },
  {
    step: '06',
    title: 'Finance & ALM Approved Publication',
    owner: 'ALM & Liquidity Lead (Alok Verma)',
    desc: 'Publishes approved run version directly to Country Finance GL and ALM Liquidity reporting returns.',
    controlPoint: 'Downstream Version Lock: Downstream scripts validate approved `run_version_id` before GL posting.',
  },
];

export const BUSINESS_REQUIREMENTS: BusinessRequirement[] = [
  {
    id: 'REQ-FTP-001',
    title: 'Authoritative Source Balance Ingestion',
    requirementText: 'The ingestion pipeline shall capture Core Banking lending balances post EOD clearing completion at 23:59:59 to ensure 100% of active facilities are ingested into staging.',
    owner: 'Sunita Rao (Country Finance Lead)',
    regulatoryDriver: 'BCBS 239 Data Completeness & Timeliness Principle 6',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Staging balance matches Core Banking GL lending balance exactly (₹2,645.0 Cr) with zero timing omission.',
    linkedRuleId: 'RULE-FTP-01',
    linkedMappingId: 'MAP-FTP-01',
    linkedTestId: 'UAT-FTP-001',
  },
  {
    id: 'REQ-FTP-002',
    title: 'Floating-Rate Repricing Tenor Derivation',
    requirementText: 'The engine shall derive repricing tenor for floating-rate facilities as (next_repricing_date - as_of_date) in months to ensure accurate yield curve pricing.',
    owner: 'Tariq Merchant (Treasury FTP Owner)',
    regulatoryDriver: 'ALCO Funds Transfer Pricing Policy Sec 3.2',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Floating loan PUN-MFG-4403 (next repricing in 3 months) prices on 3-month curve (6.90%) instead of maturity tenor.',
    linkedRuleId: 'RULE-FTP-02',
    linkedMappingId: 'MAP-FTP-04',
    linkedTestId: 'UAT-FTP-002',
  },
  {
    id: 'REQ-FTP-003',
    title: 'Fixed-Rate Matched Maturity Tenor Derivation',
    requirementText: 'The engine shall derive matched maturity tenor for fixed-rate bullet facilities as (maturity_date - as_of_date) in months.',
    owner: 'Tariq Merchant (Treasury FTP Owner)',
    regulatoryDriver: 'ALCO Funds Transfer Pricing Policy Sec 3.1',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Fixed loan MUM-CRE-8801 (maturity in 36 months) prices on 3-year curve bucket (7.80%).',
    linkedRuleId: 'RULE-FTP-03',
    linkedMappingId: 'MAP-FTP-04',
    linkedTestId: 'UAT-FTP-003',
  },
  {
    id: 'REQ-FTP-004',
    title: 'Mandatory Attribute Validation & Exception Routing',
    requirementText: 'The data quality gate shall validate mandatory repricing attributes and route missing/invalid records to an operational exception queue rather than applying silent defaults.',
    owner: 'Girish Hegde (BAU Operations Lead)',
    regulatoryDriver: 'BCBS 239 Risk Data Aggregation Principle 3',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Record with missing next_repricing_date triggers validation alert and routes to exception queue; zero silent rate miscalculations.',
    linkedRuleId: 'RULE-FTP-04',
    linkedMappingId: 'MAP-FTP-03',
    linkedTestId: 'UAT-FTP-004',
  },
  {
    id: 'REQ-FTP-005',
    title: 'Composite Key Deduplication & Unique Record Control',
    requirementText: 'Data mapping pipelines shall join contract tables to product reference tables using composite key (`obligor_id` + `facility_id` + `as_of_date`) with active status filtering.',
    owner: 'Deepak Deshmukh (Data Engineering Lead)',
    regulatoryDriver: 'BCBS 239 Data Aggregation Integrity Principle 3',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Zero duplicate facility rows in FTP output; total priced balance equals ₹2,645.0 Cr.',
    linkedRuleId: 'RULE-FTP-05',
    linkedMappingId: 'MAP-FTP-02',
    linkedTestId: 'UAT-FTP-005',
  },
  {
    id: 'REQ-FTP-006',
    title: 'Treasury Curve Lookup Rules',
    requirementText: 'The engine shall look up base funding curve rates using Currency + Derived Repricing Bucket + Effective Date.',
    owner: 'Tariq Merchant (Treasury FTP Owner)',
    regulatoryDriver: 'ALCO Yield Curve Policy Standard',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'INR 3-month bucket retrieves exact 6.90% base rate; INR 3-year bucket retrieves exact 7.80% base rate.',
    linkedRuleId: 'RULE-FTP-06',
    linkedMappingId: 'MAP-FTP-07',
    linkedTestId: 'UAT-FTP-006',
  },
  {
    id: 'REQ-FTP-007',
    title: 'Product Code Liquidity Category Reference Mapping',
    requirementText: 'All active product codes shall map to an approved liquidity category in `ALM_LIQUIDITY_CLASSIFICATION` to derive mandatory liquidity premiums.',
    owner: 'Alok Verma (ALM Lead)',
    regulatoryDriver: 'ALCO Liquidity Premium Framework',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Product `PROD-REN-05` maps to Renewable Energy category with mandatory 0.85% liquidity premium; zero generic 0.00% defaults.',
    linkedRuleId: 'RULE-FTP-07',
    linkedMappingId: 'MAP-FTP-06',
    linkedTestId: 'UAT-FTP-007',
  },
  {
    id: 'REQ-FTP-008',
    title: 'FTP Component Rate Transparency',
    requirementText: 'Every output record shall store explicit rate components: Base Curve Rate, Liquidity Premium, Optionality Adjustment, and Final FTP Rate.',
    owner: 'Tariq Merchant (Treasury FTP Owner)',
    regulatoryDriver: 'BCBS 239 Transparency & Auditability Principle 8',
    priority: 'MEDIUM',
    status: 'Approved',
    acceptanceCriteria: 'FTP Rate breakdown explicitly displays 6.90% Base + 0.80% Liquidity + 0.00% Optionality = 7.70% FTP Rate.',
    linkedRuleId: 'RULE-FTP-08',
    linkedMappingId: 'MAP-FTP-09',
    linkedTestId: 'UAT-FTP-008',
  },
  {
    id: 'REQ-FTP-009',
    title: 'Immutable Run Version Tagging',
    requirementText: 'The FTP calculation engine shall tag every output record with an immutable `run_version_id` (e.g. `RUN-20260731-01`).',
    owner: 'Kavita Reddy (Treasury Technology Lead)',
    regulatoryDriver: 'Bank Auditability & Governance Standard',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: '100% of output records populate valid `run_version_id`; re-runs create distinct new version IDs.',
    linkedRuleId: 'RULE-FTP-09',
    linkedMappingId: 'MAP-FTP-11',
    linkedTestId: 'UAT-FTP-009',
  },
  {
    id: 'REQ-FTP-010',
    title: 'Downstream Extract Version Lock Enforcement',
    requirementText: 'Downstream Finance and ALM extraction scripts shall parameterize query filtering on approved `run_version_id` to prevent ingestion of stale or draft batch runs.',
    owner: 'Alok Verma (ALM Lead)',
    regulatoryDriver: 'BCBS 239 Reporting Integrity Principle 10',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Downstream extract fetches exact approved run `RUN-20260731-01` with zero stale run consumption.',
    linkedRuleId: 'RULE-FTP-10',
    linkedMappingId: 'MAP-FTP-12',
    linkedTestId: 'UAT-FTP-010',
  },
  {
    id: 'REQ-FTP-011',
    title: 'Multi-Stage Automated Balance Reconciliation',
    requirementText: 'The target system shall execute automated balance reconciliation across Source Lending $\rightarrow$ Staging $\rightarrow$ FTP Output $\rightarrow$ Downstream Extract.',
    owner: 'Sunita Rao (Country Finance Lead)',
    regulatoryDriver: 'Financial Control Reconciliation Standard',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Reconciliation report confirms ₹2,645.0 Cr across all 4 stages with zero unexplained variance.',
    linkedRuleId: 'RULE-FTP-01',
    linkedMappingId: 'MAP-FTP-01',
    linkedTestId: 'UAT-FTP-011',
  },
  {
    id: 'REQ-FTP-012',
    title: 'BAU Rerun Reproducibility & Handover Controls',
    requirementText: 'The system shall provide operational rerun controls allowing BAU Treasury Operations to re-execute runs with identical inputs and produce 100% reproducible rates.',
    owner: 'Girish Hegde (BAU Operations Lead)',
    regulatoryDriver: 'Operational Risk & Production Continuity Mandate',
    priority: 'MEDIUM',
    status: 'Approved',
    acceptanceCriteria: 'Rerun of `RUN-20260731-01` produces identical 100% match on transfer rates and charges.',
    linkedRuleId: 'RULE-FTP-09',
    linkedMappingId: 'MAP-FTP-11',
    linkedTestId: 'UAT-FTP-012',
  },
];

export const BUSINESS_RULES: BusinessRule[] = [
  { id: 'RULE-FTP-01', ruleCode: 'RULE-FTP-01', category: 'Treasury', condition: 'EODClearingStatus == "COMPLETED"', outputClassification: 'Authoritative Source Ingestion', provisionRatePercent: 0.0, reasonCode: 'FTP_SRC_EOD_CLEARED', priority: 1 },
  { id: 'RULE-FTP-02', ruleCode: 'RULE-FTP-02', category: 'Treasury', condition: 'InterestRateType == "FLOATING" AND NextRepricingDate IS NOT NULL', outputClassification: 'Repricing Tenor Pricing', provisionRatePercent: 0.0, reasonCode: 'FTP_TENOR_REPRICING', priority: 2 },
  { id: 'RULE-FTP-03', ruleCode: 'RULE-FTP-03', category: 'Treasury', condition: 'InterestRateType == "FIXED"', outputClassification: 'Matched Maturity Pricing', provisionRatePercent: 0.0, reasonCode: 'FTP_TENOR_MATCHED_MATURITY', priority: 3 },
  { id: 'RULE-FTP-04', ruleCode: 'RULE-FTP-04', category: 'Data Quality', condition: 'NextRepricingDate IS NULL AND InterestRateType == "FLOATING"', outputClassification: 'DQ Exception Route', provisionRatePercent: 0.0, reasonCode: 'FTP_DQ_MISSING_REPRICING_DATE', priority: 4 },
  { id: 'RULE-FTP-05', ruleCode: 'RULE-FTP-05', category: 'Data Quality', condition: 'Count(obligor_id + facility_id + as_of_date) > 1', outputClassification: 'Deduplicated Record', provisionRatePercent: 0.0, reasonCode: 'FTP_DQ_DEDUPLICATED', priority: 5 },
  { id: 'RULE-FTP-06', ruleCode: 'RULE-FTP-06', category: 'Treasury', condition: 'BaseCurveLookup(Currency, RepricingBucket, EffectiveDate)', outputClassification: 'Yield Curve Base Rate', provisionRatePercent: 0.0, reasonCode: 'FTP_CURVE_BASE_LOOKUP', priority: 6 },
  { id: 'RULE-FTP-07', ruleCode: 'RULE-FTP-07', category: 'Treasury', condition: 'LiquidityCategoryLookup(ProductCode)', outputClassification: 'Liquidity Premium Add-On', provisionRatePercent: 0.0, reasonCode: 'FTP_LIQUIDITY_PREMIUM_ADDON', priority: 7 },
  { id: 'RULE-FTP-08', ruleCode: 'RULE-FTP-08', category: 'Treasury', condition: 'FTPRate = BaseRate + LiquidityPremium + Optionality', outputClassification: 'FTP Rate Breakdown Published', provisionRatePercent: 0.0, reasonCode: 'FTP_RATE_STACK_DERIVED', priority: 8 },
  { id: 'RULE-FTP-09', ruleCode: 'RULE-FTP-09', category: 'Override', condition: 'EngineOutputPublished == true', outputClassification: 'Immutable Run Version Tag', provisionRatePercent: 0.0, reasonCode: 'FTP_RUN_VERSION_TAGGED', priority: 9 },
  { id: 'RULE-FTP-10', ruleCode: 'RULE-FTP-10', category: 'Reconciliation', condition: 'DownstreamRunVersion == ApprovedRunVersion', outputClassification: 'Downstream Version Lock Verified', provisionRatePercent: 0.0, reasonCode: 'FTP_DOWNSTREAM_VERSION_LOCKED', priority: 10 },
];

export const SOURCE_TARGET_MAPPINGS: SourceToTargetMapping[] = [
  {
    id: 'MAP-FTP-01',
    sourceSystem: 'CBS_LOAN_BALANCE',
    sourceTable: 'tbl_loan_account_bal',
    sourceColumn: 'current_outstanding_bal',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'FILTER EOD_CLEARING_STATUS = "COMPLETED"; MAP to outstanding_inr_cr',
    targetTable: 'FTP_INPUT_STAGE',
    targetField: 'outstanding_inr_cr',
    nullRule: 'Reject record if null',
    effectiveDateRule: 'Snapshot as at 23:59:59',
    dqRule: 'outstanding_inr_cr >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-02',
    sourceSystem: 'CBS_LOAN_CONTRACT',
    sourceTable: 'tbl_contract_master',
    sourceColumn: 'facility_id',
    dataType: 'VARCHAR(30)',
    grain: 'Facility Level',
    transformationLogic: 'JOIN PRODUCT_REFERENCE ON product_code AND effective_status = "ACTIVE" (Composite Key)',
    targetTable: 'FTP_INPUT_STAGE',
    targetField: 'facility_id',
    nullRule: 'Reject record if null',
    effectiveDateRule: 'Current Contract Effective Date',
    dqRule: 'UNIQUE(obligor_id, facility_id, as_of_date)',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-03',
    sourceSystem: 'CBS_LOAN_CONTRACT',
    sourceTable: 'tbl_contract_master',
    sourceColumn: 'next_repricing_date',
    dataType: 'DATE',
    grain: 'Facility Level',
    transformationLogic: 'PARSE_DATE(next_repricing_date, "YYYY-MM-DD"); IF NULL ROUTE TO EXCEPTION QUEUE',
    targetTable: 'FTP_INPUT_STAGE',
    targetField: 'next_repricing_date',
    nullRule: 'Route to exception queue if floating rate',
    effectiveDateRule: 'Contractual Repricing Date',
    dqRule: 'next_repricing_date >= as_of_date',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-04',
    sourceSystem: 'FTP_INPUT_STAGE',
    sourceTable: 'tbl_ftp_input_stage',
    sourceColumn: 'next_repricing_date',
    dataType: 'INTEGER',
    grain: 'Facility Level',
    transformationLogic: 'CASE WHEN interest_rate_type = "FLOATING" THEN DATEDIFF(month, as_of_date, next_repricing_date) ELSE DATEDIFF(month, as_of_date, maturity_date) END',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'repricing_tenor_months',
    nullRule: 'Must derive valid integer months',
    effectiveDateRule: 'Derived as of Pricing Date',
    dqRule: 'repricing_tenor_months >= 1',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-05',
    sourceSystem: 'CBS_LOAN_CONTRACT',
    sourceTable: 'tbl_contract_master',
    sourceColumn: 'product_code',
    dataType: 'VARCHAR(20)',
    grain: 'Facility Level',
    transformationLogic: 'LOOKUP PRODUCT_REFERENCE WHERE product_code AND status = "ACTIVE"',
    targetTable: 'FTP_INPUT_STAGE',
    targetField: 'product_code',
    nullRule: 'Reject record if unmapped',
    effectiveDateRule: 'Origination Product Code',
    dqRule: 'IN ("PROD-CRE-01", "PROD-INF-02", "PROD-MFG-03", "PROD-SME-04", "PROD-REN-05", "PROD-MED-06", "PROD-RES-07", "PROD-TEC-08")',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-06',
    sourceSystem: 'PRODUCT_REFERENCE',
    sourceTable: 'tbl_product_ref',
    sourceColumn: 'liquidity_category',
    dataType: 'VARCHAR(30)',
    grain: 'Product Level',
    transformationLogic: 'LOOKUP ALM_LIQUIDITY_CLASSIFICATION ON product_code',
    targetTable: 'FTP_INPUT_STAGE',
    targetField: 'liquidity_category',
    nullRule: 'Default to exception queue if unmapped',
    effectiveDateRule: 'Active Reference Policy',
    dqRule: 'NOT NULL',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-07',
    sourceSystem: 'TREASURY_CURVE_MASTER',
    sourceTable: 'tbl_yield_curve',
    sourceColumn: 'base_rate_percent',
    dataType: 'NUMERIC(6,4)',
    grain: 'Tenor Bucket Level',
    transformationLogic: 'LOOKUP TREASURY_CURVE WHERE currency = "INR" AND tenor_bucket = derived_bucket AND effective_date <= as_of_date',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'base_curve_rate_percent',
    nullRule: 'Reject calculation if curve missing',
    effectiveDateRule: 'Current Approved Yield Curve',
    dqRule: 'base_rate_percent > 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-08',
    sourceSystem: 'ALM_LIQUIDITY_CLASSIFICATION',
    sourceTable: 'tbl_liquidity_premium',
    sourceColumn: 'liquidity_premium_percent',
    dataType: 'NUMERIC(6,4)',
    grain: 'Liquidity Category Level',
    transformationLogic: 'LOOKUP LIQUIDITY_PREMIUM WHERE liquidity_category = target_category',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'liquidity_premium_percent',
    nullRule: 'Default to exception queue',
    effectiveDateRule: 'ALCO Approved Premium Schedule',
    dqRule: 'liquidity_premium_percent >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-09',
    sourceSystem: 'FTP_ENGINE_OUTPUT',
    sourceTable: 'tbl_ftp_engine_output',
    sourceColumn: 'ftp_rate_percent',
    dataType: 'NUMERIC(6,4)',
    grain: 'Facility Level',
    transformationLogic: 'base_curve_rate_percent + liquidity_premium_percent + optionality_adjustment_percent',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'ftp_rate_percent',
    nullRule: 'Must compute non-null rate',
    effectiveDateRule: 'Pricing Calculation Date',
    dqRule: 'ftp_rate_percent > 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-10',
    sourceSystem: 'FTP_ENGINE_OUTPUT',
    sourceTable: 'tbl_ftp_engine_output',
    sourceColumn: 'ftp_charge_inr_cr',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'outstanding_inr_cr * (ftp_rate_percent / 100.0)',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'ftp_charge_inr_cr',
    nullRule: 'Must compute non-null charge',
    effectiveDateRule: 'Pricing Calculation Date',
    dqRule: 'ftp_charge_inr_cr >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-11',
    sourceSystem: 'FTP_ENGINE_OUTPUT',
    sourceTable: 'tbl_ftp_engine_output',
    sourceColumn: 'run_version_id',
    dataType: 'VARCHAR(30)',
    grain: 'Run Batch Instance',
    transformationLogic: 'GENERATE_RUN_ID("RUN", as_of_date, batch_sequence)',
    targetTable: 'FTP_ENGINE_OUTPUT',
    targetField: 'run_version_id',
    nullRule: 'Reject publish if null',
    effectiveDateRule: 'Execution Timestamp',
    dqRule: 'FORMAT ("RUN-YYYYMMDD-SS")',
    status: 'Target Approved',
  },
  {
    id: 'MAP-FTP-12',
    sourceSystem: 'FINANCE_CONTROL_TOTAL',
    sourceTable: 'tbl_gl_extract',
    sourceColumn: 'run_version_id',
    dataType: 'VARCHAR(30)',
    grain: 'Downstream Extract',
    transformationLogic: 'FILTER WHERE run_version_id = APPROVED_RUN_VERSION_ID',
    targetTable: 'LIQUIDITY_REPORTING_EXTRACT',
    targetField: 'consumed_run_version_id',
    nullRule: 'Reject extract if unapproved version',
    effectiveDateRule: 'ALCO Reporting Cutoff',
    dqRule: 'EQUALS APPROVED_RUN_VERSION_ID',
    status: 'Target Approved',
  },
];

export const INVESTIGATION_TASKS: InvestigationTask[] = [
  {
    id: 'INV-FTP-A',
    code: 'INVESTIGATION-A',
    title: 'Source Lending vs FTP Input Stage Balance Reconciliation',
    description: 'Reconcile raw Core Banking lending balances against FTP Input Stage tables to detect omitted loan facilities.',
    sampleQuery: 'SELECT cbs.facility_number, cbs.outstanding_inr_cr, ftp.outstanding_inr_cr FROM tbl_cbs_lending cbs LEFT JOIN tbl_ftp_input_stage ftp ON cbs.facility_id = ftp.facility_id WHERE ftp.facility_id IS NULL;',
    sampleResultRows: [
      { facility_number: 'GUJ-REN-3305', obligor_name: 'Sabarmati Clean Energy Ltd', cbs_outstanding: 345.0, staging_outstanding: 0.0, variance: 'Missing ₹345.0 Cr Ingestion Omission' },
    ],
    expectedFinding: 'Staging batch ran 6 hours prior to EOD clearing completion, omitting facility GUJ-REN-3305 (₹345.0 Cr).',
    discoveredDefectId: 'DEF-FTP-004',
  },
  {
    id: 'INV-FTP-B',
    code: 'INVESTIGATION-B',
    title: 'Duplicate Facility Records in FTP Engine Output',
    description: 'Detect duplicate facility rows in FTP engine output tables caused by 1:M joins on product reference tables.',
    sampleQuery: 'SELECT facility_number, COUNT(*) as row_count, SUM(outstanding_inr_cr) FROM tbl_ftp_engine_output GROUP BY facility_number HAVING COUNT(*) > 1;',
    sampleResultRows: [
      { facility_number: 'HYD-INF-9902', obligor_name: 'Deccan Power & Infrastructure', row_count: 2, outstanding_inr_cr: 1400.0, variance: 'Double-counted ₹700.0 Cr Outstanding' },
    ],
    expectedFinding: 'Missing `effective_status = "ACTIVE"` filter duplicated facility HYD-INF-9902 from ₹700 Cr to ₹1,400 Cr in output.',
    discoveredDefectId: 'DEF-FTP-002',
  },
  {
    id: 'INV-FTP-C',
    code: 'INVESTIGATION-C',
    title: 'Floating-Rate Facilities Repricing Tenor Fallback Audit',
    description: 'Identify floating-rate loan facilities priced on contractual maturity tenor instead of next repricing date.',
    sampleQuery: 'SELECT facility_number, interest_rate_type, repricing_tenor_months, maturity_tenor_months, applied_base_rate FROM tbl_ftp_engine_output WHERE interest_rate_type = "FLOATING" AND repricing_tenor_months = maturity_tenor_months;',
    sampleResultRows: [
      { facility_number: 'PUN-MFG-4403', interest_rate_type: 'FLOATING', applied_repricing_tenor: '36 Months (Maturity)', correct_repricing_tenor: '3 Months', applied_rate: 7.80, correct_rate: 6.90, variance: 'Overcharged 90 bps' },
    ],
    expectedFinding: 'Date string format mismatch caused floating loan PUN-MFG-4403 to fall back to maturity tenor, overcharging FTP by 90 bps.',
    discoveredDefectId: 'DEF-FTP-001',
  },
  {
    id: 'INV-FTP-D',
    code: 'INVESTIGATION-D',
    title: 'Unmapped Product Code Liquidity Premium Audit',
    description: 'Audit product code lookups against `ALM_LIQUIDITY_CLASSIFICATION` to verify liquidity premium add-ons.',
    sampleQuery: 'SELECT facility_number, product_code, liquidity_category, applied_liquidity_premium FROM tbl_ftp_engine_output WHERE applied_liquidity_premium = 0.00;',
    sampleResultRows: [
      { facility_number: 'GUJ-REN-3305', product_code: 'PROD-REN-05', liquidity_category: 'UNMAPPED_DEFAULT', applied_liquidity_premium: 0.00, required_liquidity_premium: 0.85, variance: 'Underpriced 85 bps' },
    ],
    expectedFinding: 'Product code `PROD-REN-05` defaulted to 0.00% liquidity premium due to missing reference mapping, underpricing FTP by 85 bps.',
    discoveredDefectId: 'DEF-FTP-003',
  },
  {
    id: 'INV-FTP-E',
    code: 'INVESTIGATION-E',
    title: 'Yield Curve Bucket Alignment & Rate Stacking Verification',
    description: 'Verify mathematical consistency of Base Curve + Liquidity Premium = FTP Rate.',
    sampleQuery: 'SELECT facility_number, base_curve_rate, liquidity_premium, ftp_rate, (base_curve_rate + liquidity_premium) as calculated_total FROM tbl_ftp_engine_output;',
    sampleResultRows: [
      { facility_number: 'MUM-CRE-8801', base_curve_rate: 7.80, liquidity_premium: 1.00, ftp_rate: 8.80, customer_rate: 10.50, commercial_margin: 1.70, status: 'VERIFIED MATCH' },
    ],
    expectedFinding: 'FTP Rate component stacking verified; Commercial Margin (1.70%) clearly separated from Internal FTP Rate (8.80%).',
    discoveredDefectId: 'NONE',
  },
  {
    id: 'INV-FTP-F',
    code: 'INVESTIGATION-F',
    title: 'Downstream Liquidity Extract Run Version Mismatch',
    description: 'Verify whether downstream Finance and Liquidity extracts consumed the approved batch run version.',
    sampleQuery: 'SELECT extract_name, consumed_run_version_id, approved_run_version_id FROM tbl_downstream_extract_log;',
    sampleResultRows: [
      { extract_name: 'LIQUIDITY_ALM_EXTRACT', consumed_run_version_id: 'RUN-20260730-01', approved_run_version_id: 'RUN-20260731-01', variance: 'Consumed Yesterday Stale Run' },
    ],
    expectedFinding: 'Downstream ALM extract consumed yesterday’s stale run (`RUN-20260730-01`), omitting today’s approved calculation.',
    discoveredDefectId: 'DEF-FTP-005',
  },
];

export const SEEDED_DEFECTS: CaseDefect[] = [
  {
    id: 'DEF-FTP-001',
    code: 'DEF-2026-01',
    title: 'Repricing Tenor Fallback Error — Floating Loan Overcharged 90 bps',
    severity: 'BLOCKER',
    category: 'Calculation Tenor',
    facilityNumber: 'PUN-MFG-4403',
    obligorName: 'Western Precision Auto Components Ltd',
    linkedEvidenceId: 'EV-FTP-05',
    linkedReqId: 'REQ-FTP-002',
    linkedMappingId: 'MAP-FTP-04',
    linkedTestId: 'UAT-FTP-004',
    expectedBehaviour: 'Floating-rate loan prices on 3-month repricing tenor (6.90% base rate).',
    actualBehaviour: 'Date format string bug evaluated next repricing date as None, falling back to 36-month maturity tenor (7.80% base rate).',
    rootCause: 'Date parser string mismatch (`DD/MM/YYYY` vs `YYYY-MM-DD`) in `ftp_tenor_engine.py`.',
    remediationFix: 'Enforce strict ISO date parsing (`YYYY-MM-DD`) before evaluating repricing tenor.',
    regressionTest: 'UAT-FTP-004 (Verify floating loan PUN-MFG-4403 prices on 3-month curve 6.90%).',
    financialImpactInrCr: 2.7,
    status: 'Open',
  },
  {
    id: 'DEF-FTP-002',
    code: 'DEF-2026-02',
    title: 'Duplicate 1:M Product Join — Infrastructure Loan Overstated ₹700 Cr',
    severity: 'BLOCKER',
    category: 'Data Quality',
    facilityNumber: 'HYD-INF-9902',
    obligorName: 'Deccan Power & Infrastructure Ltd',
    linkedEvidenceId: 'EV-FTP-04',
    linkedReqId: 'REQ-FTP-005',
    linkedMappingId: 'MAP-FTP-02',
    linkedTestId: 'UAT-FTP-005',
    expectedBehaviour: 'Facility HYD-INF-9902 appears once with ₹700.0 Cr outstanding balance.',
    actualBehaviour: 'Missing status filter in `PRODUCT_REFERENCE` join generated 2 duplicate rows, reporting ₹1,400.0 Cr outstanding.',
    rootCause: 'Missing `effective_status = "ACTIVE"` filter in `sp_build_ftp_input.sql`.',
    remediationFix: 'Add composite key join `ON obligor_id AND facility_id AND as_of_date` with `effective_status = "ACTIVE"`.',
    regressionTest: 'UAT-FTP-005 (Verify deduplication & exact ₹700.0 Cr outstanding).',
    financialImpactInrCr: 700.0,
    status: 'Open',
  },
  {
    id: 'DEF-FTP-003',
    code: 'DEF-2026-03',
    title: 'Unmapped Product Code Default — Liquidity Premium Underpriced 85 bps',
    severity: 'CRITICAL',
    category: 'Reference Data',
    facilityNumber: 'GUJ-REN-3305',
    obligorName: 'Sabarmati Clean Energy Ltd',
    linkedEvidenceId: 'EV-FTP-05',
    linkedReqId: 'REQ-FTP-007',
    linkedMappingId: 'MAP-FTP-06',
    linkedTestId: 'UAT-FTP-007',
    expectedBehaviour: 'Product `PROD-REN-05` maps to Renewable Energy category with 0.85% liquidity premium.',
    actualBehaviour: 'Unmapped product code defaulted to generic 0.00% liquidity premium, underpricing FTP by 85 bps.',
    rootCause: 'Product reference table missing mapping row for `PROD-REN-05`.',
    remediationFix: 'Insert active mapping row for `PROD-REN-05` into `ALM_LIQUIDITY_CLASSIFICATION`.',
    regressionTest: 'UAT-FTP-007 (Verify 0.85% liquidity premium applied to renewable loan).',
    financialImpactInrCr: 2.9,
    status: 'Open',
  },
  {
    id: 'DEF-FTP-004',
    code: 'DEF-2026-04',
    title: 'Batch Timing Cutoff Mismatch — ₹345 Cr Balances Omitted',
    severity: 'CRITICAL',
    category: 'Effective Date',
    facilityNumber: 'GUJ-REN-3305',
    obligorName: 'Sabarmati Clean Energy Ltd',
    linkedEvidenceId: 'EV-FTP-03',
    linkedReqId: 'REQ-FTP-001',
    linkedMappingId: 'MAP-FTP-01',
    linkedTestId: 'UAT-FTP-001',
    expectedBehaviour: 'Staging batch ingests 100% Core Banking cleared lending balances (₹2,645.0 Cr).',
    actualBehaviour: '18:00 ingestion cutoff omitted ₹345.0 Cr loan cleared at 21:30, understating staging balances.',
    rootCause: 'Batch cron job triggered prior to 23:59:59 EOD clearing completion.',
    remediationFix: 'Reschedule ingestion batch trigger to 23:59:59 post EOD clearing run.',
    regressionTest: 'UAT-FTP-001 (Verify staging balance equals ₹2,645.0 Cr).',
    financialImpactInrCr: 345.0,
    status: 'Open',
  },
  {
    id: 'DEF-FTP-005',
    code: 'DEF-2026-05',
    title: 'Downstream Extract Stale Version Consumption',
    severity: 'MAJOR',
    category: 'Interface / Versioning',
    facilityNumber: 'ALL-FACILITIES',
    obligorName: 'Portfolio Aggregate Extract',
    linkedEvidenceId: 'EV-FTP-06',
    linkedReqId: 'REQ-FTP-010',
    linkedMappingId: 'MAP-FTP-12',
    linkedTestId: 'UAT-FTP-010',
    expectedBehaviour: 'Downstream ALM extract consumes current approved run `RUN-20260731-01`.',
    actualBehaviour: 'Extract script fetched yesterday’s stale run (`RUN-20260730-01`), ignoring today’s output.',
    rootCause: 'Hardcoded query `WHERE run_date = CURRENT_DATE() - 1` in `sp_export_alm_extract.sql`.',
    remediationFix: 'Parameterize extract query on explicit approved `run_version_id`.',
    regressionTest: 'UAT-FTP-010 (Verify downstream extract consumes `RUN-20260731-01`).',
    financialImpactInrCr: 0.0,
    status: 'Open',
  },
];

export const UAT_TEST_PACK: UATTestCase[] = [
  { id: 'UAT-FTP-001', code: 'UAT-FTP-001', title: 'Verify Staging Ingestion Source Balance Match', linkedReqId: 'REQ-FTP-001', precondition: 'EOD clearing completed at 23:59', testInput: 'CBS Lending Balance: ₹2,645.0 Cr', expectedResult: 'Staging Balance: ₹2,645.0 Cr (100% Match)', actualResult: 'Staging Balance: ₹2,300.0 Cr (Omitted ₹345 Cr)', status: 'FAILED', linkedDefectId: 'DEF-FTP-004' },
  { id: 'UAT-FTP-002', code: 'UAT-FTP-002', title: 'Verify Floating-Rate 3-Month Repricing Tenor Derivation', linkedReqId: 'REQ-FTP-002', precondition: 'Floating loan PUN-MFG-4403', testInput: 'Next Repricing: 31-Oct-2026', expectedResult: 'Derived Tenor: 3 Months (6.90% Base Rate)', actualResult: 'Derived Tenor: 3 Months (6.90% Base Rate)', status: 'PASSED' },
  { id: 'UAT-FTP-003', code: 'UAT-FTP-003', title: 'Verify Fixed-Rate 36-Month Matched Maturity Derivation', linkedReqId: 'REQ-FTP-003', precondition: 'Fixed loan MUM-CRE-8801', testInput: 'Maturity: 31-Jul-2029', expectedResult: 'Derived Tenor: 36 Months (7.80% Base Rate)', actualResult: 'Derived Tenor: 36 Months (7.80% Base Rate)', status: 'PASSED' },
  { id: 'UAT-FTP-004', code: 'UAT-FTP-004', title: 'Verify Missing Repricing Date Exception Routing', linkedReqId: 'REQ-FTP-004', precondition: 'Floating loan missing next_repricing_date', testInput: 'Date Format: DD/MM/YYYY', expectedResult: 'Exception Routed to Queue; Zero Maturity Fallback', actualResult: 'Maturity Fallback Triggered (Applied 7.80% instead of 6.90%)', status: 'FAILED', linkedDefectId: 'DEF-FTP-001' },
  { id: 'UAT-FTP-005', code: 'UAT-FTP-005', title: 'Verify 1:M Reference Join Composite Deduplication', linkedReqId: 'REQ-FTP-005', precondition: 'Single facility HYD-INF-9902', testInput: 'Composite Join: obligor + facility + as_of_date', expectedResult: 'Rows: 1, Outstanding: ₹700.0 Cr', actualResult: 'Rows: 2, Outstanding: ₹1,400.0 Cr', status: 'FAILED', linkedDefectId: 'DEF-FTP-002' },
  { id: 'UAT-FTP-006', code: 'UAT-FTP-006', title: 'Verify Treasury Curve Base Rate Lookup (INR 3M)', linkedReqId: 'REQ-FTP-006', precondition: 'Tenor = 3 Months', testInput: 'Currency: INR, Tenor: 3M', expectedResult: 'Base Rate: 6.90%', actualResult: 'Base Rate: 6.90%', status: 'PASSED' },
  { id: 'UAT-FTP-007', code: 'UAT-FTP-007', title: 'Verify Renewable Product Liquidity Premium Add-On', linkedReqId: 'REQ-FTP-007', precondition: 'Product Code: PROD-REN-05', testInput: 'Product: PROD-REN-05', expectedResult: 'Liquidity Premium: 0.85%', actualResult: 'Liquidity Premium: 0.00% (Unmapped Default)', status: 'FAILED', linkedDefectId: 'DEF-FTP-003' },
  { id: 'UAT-FTP-008', code: 'UAT-FTP-008', title: 'Verify FTP Rate Component Breakdown Publishing', linkedReqId: 'REQ-FTP-008', precondition: 'Facility MUM-CRE-8801', testInput: 'Base: 7.80%, Liquidity: 1.00%', expectedResult: 'FTP Rate: 8.80% (Base + Liquidity)', actualResult: 'FTP Rate: 8.80% (Base + Liquidity)', status: 'PASSED' },
  { id: 'UAT-FTP-009', code: 'UAT-FTP-009', title: 'Verify Immutable Run Version Tagging', linkedReqId: 'REQ-FTP-009', precondition: 'Engine calculation run complete', testInput: 'Batch Sequence: 01', expectedResult: 'Run Version: RUN-20260731-01', actualResult: 'Run Version: RUN-20260731-01', status: 'PASSED' },
  { id: 'UAT-FTP-010', code: 'UAT-FTP-010', title: 'Verify Downstream Extract Run Version Lock', linkedReqId: 'REQ-FTP-010', precondition: 'Downstream ALM extract execution', testInput: 'Approved Version: RUN-20260731-01', expectedResult: 'Consumed Version: RUN-20260731-01', actualResult: 'Consumed Version: RUN-20260730-01 (Stale Run)', status: 'FAILED', linkedDefectId: 'DEF-FTP-005' },
  { id: 'UAT-FTP-011', code: 'UAT-FTP-011', title: 'Verify Multi-Stage 4-Point Balance Reconciliation', linkedReqId: 'REQ-FTP-011', precondition: 'End-of-period close execution', testInput: 'Source vs Staging vs Output vs Extract', expectedResult: '₹2,645.0 Cr across all 4 stages (0 Variance)', actualResult: 'Discrepancy Alert (₹355.0 Cr Net Variance)', status: 'PASSED' },
  { id: 'UAT-FTP-012', code: 'UAT-FTP-012', title: 'Verify BAU Operational Rerun Reproducibility', linkedReqId: 'REQ-FTP-012', precondition: 'Rerun trigger on RUN-20260731-01', testInput: 'Same Inputs & Curve Master', expectedResult: '100% Identical Rate & Charge Output', actualResult: '100% Identical Rate & Charge Output', status: 'PASSED' },
  { id: 'UAT-FTP-013', code: 'UAT-FTP-013', title: 'Verify Fixed-Rate Treasury Rate Lock', linkedReqId: 'REQ-FTP-003', precondition: 'Fixed-rate loan origination', testInput: 'Fixed Rate: 8.80%', expectedResult: 'Transfer Rate Locked for 36 Months', actualResult: 'Transfer Rate Locked for 36 Months', status: 'PASSED' },
  { id: 'UAT-FTP-014', code: 'UAT-FTP-014', title: 'Verify Commercial Margin Separation from FTP Rate', linkedReqId: 'REQ-FTP-008', precondition: 'Customer Rate = 10.50%, FTP = 8.80%', testInput: 'Customer: 10.50%, FTP: 8.80%', expectedResult: 'Commercial Margin: 1.70% (Business Unit Yield)', actualResult: 'Commercial Margin: 1.70% (Business Unit Yield)', status: 'PASSED' },
  { id: 'UAT-FTP-015', code: 'UAT-FTP-015', title: 'Verify CRE Category Liquidity Premium Add-On (1.00%)', linkedReqId: 'REQ-FTP-007', precondition: 'Category: Commercial Real Estate', testInput: 'Product: PROD-CRE-01', expectedResult: 'Liquidity Premium: 1.00%', actualResult: 'Liquidity Premium: 1.00%', status: 'PASSED' },
  { id: 'UAT-FTP-016', code: 'UAT-FTP-016', title: 'Verify Infrastructure Category Liquidity Premium Add-On (0.50%)', linkedReqId: 'REQ-FTP-007', precondition: 'Category: Infrastructure', testInput: 'Product: PROD-INF-02', expectedResult: 'Liquidity Premium: 0.50%', actualResult: 'Liquidity Premium: 0.50%', status: 'PASSED' },
  { id: 'UAT-FTP-017', code: 'UAT-FTP-017', title: 'Verify Zero Silent Default on Unmapped Product Code', linkedReqId: 'REQ-FTP-004', precondition: 'Unmapped product ingestion', testInput: 'Product: UNMAPPED-X', expectedResult: 'Operational Exception Alert; Staging Blocked', actualResult: 'Operational Exception Alert; Staging Blocked', status: 'PASSED' },
  { id: 'UAT-FTP-018', code: 'UAT-FTP-018', title: 'Verify FTP Charge Calculation Accuracy', linkedReqId: 'REQ-FTP-008', precondition: 'Outstanding: ₹450 Cr, FTP Rate: 8.80%', testInput: 'Outstanding: ₹450 Cr, Rate: 8.80%', expectedResult: 'Annual FTP Charge: ₹39.60 Cr', actualResult: 'Annual FTP Charge: ₹39.60 Cr', status: 'PASSED' },
];

export const TRACEABILITY_MATRIX: TraceabilityChain[] = [
  { id: 'RTM-FTP-01', regulatoryDriver: 'BCBS 239 Data Timeliness Principle 6', reqId: 'REQ-FTP-001', ruleId: 'RULE-FTP-01', mappingId: 'MAP-FTP-01', component: 'ETL Ingestion `job_ingest_cbs_lending`', testId: 'UAT-FTP-001', defectId: 'DEF-FTP-004', signoffOwner: 'Sunita Rao' },
  { id: 'RTM-FTP-02', regulatoryDriver: 'ALCO FTP Policy Sec 3.2', reqId: 'REQ-FTP-002', ruleId: 'RULE-FTP-02', mappingId: 'MAP-FTP-04', component: 'Engine Script `ftp_tenor_engine.py`', testId: 'UAT-FTP-004', defectId: 'DEF-FTP-001', signoffOwner: 'Tariq Merchant' },
  { id: 'RTM-FTP-03', regulatoryDriver: 'ALCO FTP Policy Sec 3.1', reqId: 'REQ-FTP-003', ruleId: 'RULE-FTP-03', mappingId: 'MAP-FTP-04', component: 'Engine Script `ftp_tenor_engine.py`', testId: 'UAT-FTP-003', signoffOwner: 'Tariq Merchant' },
  { id: 'RTM-FTP-04', regulatoryDriver: 'BCBS 239 Data Aggregation Principle 3', reqId: 'REQ-FTP-005', ruleId: 'RULE-FTP-05', mappingId: 'MAP-FTP-02', component: 'ETL Mapping `sp_build_ftp_input.sql`', testId: 'UAT-FTP-005', defectId: 'DEF-FTP-002', signoffOwner: 'Deepak Deshmukh' },
  { id: 'RTM-FTP-05', regulatoryDriver: 'ALCO Liquidity Premium Framework', reqId: 'REQ-FTP-007', ruleId: 'RULE-FTP-07', mappingId: 'MAP-FTP-06', component: 'Reference Table `ALM_LIQUIDITY_CLASSIFICATION`', testId: 'UAT-FTP-007', defectId: 'DEF-FTP-003', signoffOwner: 'Alok Verma' },
  { id: 'RTM-FTP-06', regulatoryDriver: 'BCBS 239 Transparency Principle 8', reqId: 'REQ-FTP-008', ruleId: 'RULE-FTP-08', mappingId: 'MAP-FTP-09', component: 'Engine Script `ftp_pricing_engine.py`', testId: 'UAT-FTP-008', signoffOwner: 'Tariq Merchant' },
  { id: 'RTM-FTP-07', regulatoryDriver: 'Bank Auditability Governance Standard', reqId: 'REQ-FTP-009', ruleId: 'RULE-FTP-09', mappingId: 'MAP-FTP-11', component: 'Publishing Script `sp_publish_ftp_run.sql`', testId: 'UAT-FTP-009', signoffOwner: 'Kavita Reddy' },
  { id: 'RTM-FTP-08', regulatoryDriver: 'BCBS 239 Reporting Integrity Principle 10', reqId: 'REQ-FTP-010', ruleId: 'RULE-FTP-10', mappingId: 'MAP-FTP-12', component: 'Extract Script `sp_export_alm_extract.sql`', testId: 'UAT-FTP-010', defectId: 'DEF-FTP-005', signoffOwner: 'Alok Verma' },
];

export const RECONCILIATION_SUMMARY: ReconciliationSummary = {
  asOfDate: '31 July 2026',
  beforeFix: {
    facilityCount: 9, // Includes 1 duplicate row
    grossOutstandingInrCr: 3000.0, // Includes ₹700 Cr duplicate, missing ₹345 Cr
    npaOutstandingInrCr: 80.0,
    requiredProvisionInrCr: 231.5,
    unexplainedVarianceInrCr: 355.0, // Net Difference (masks gross absolute break!)
    grossAbsoluteVarianceInrCr: 1745.0, // |-345| + |+700| + |-700| = ₹1,745 Cr
    pricedPopulationCount: 7,
    rejectedPopulationCount: 1, // Omitted by DEF-FTP-004
    consumedRunVersionId: 'RUN-20260730-01',
    approvedRunVersionId: 'RUN-20260731-01',
    isVersionLocked: false,
    reconciliationStatus: 'COMPENSATING BREAK ALERT (GROSS BREAK = ₹1,745.0 Cr)',
    stageBreaks: [
      {
        stageName: 'Source Lending → FTP Input Stage',
        sourceCount: 8,
        targetCount: 7,
        sourceAmountInrCr: 2645.0,
        targetAmountInrCr: 2300.0,
        varianceAmountInrCr: -345.0,
        reason: 'Ingestion batch timestamp cutoff at 18:00 omitted facility GUJ-REN-3305 (₹345 Cr) cleared at 21:30.',
        linkedDefectId: 'DEF-FTP-004',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'FTP Input Stage → FTP Engine Output',
        sourceCount: 7,
        targetCount: 9,
        sourceAmountInrCr: 2300.0,
        targetAmountInrCr: 3000.0,
        varianceAmountInrCr: 700.0,
        reason: '1:M product reference join without active status filter generated 2 duplicate rows for HYD-INF-9902.',
        linkedDefectId: 'DEF-FTP-002',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'FTP Engine Output → Downstream Extract',
        sourceCount: 9,
        targetCount: 7,
        sourceAmountInrCr: 3000.0,
        targetAmountInrCr: 2300.0,
        varianceAmountInrCr: -700.0,
        reason: 'Downstream extract script consumed yesterday’s stale run (RUN-20260730-01) instead of approved run.',
        linkedDefectId: 'DEF-FTP-005',
        runVersionId: 'RUN-20260730-01 (STALE)',
      },
    ],
  },
  afterFix: {
    facilityCount: 8, // Exact 8 deduplicated facilities
    grossOutstandingInrCr: 2645.0, // Exact Core Banking GL lending balance
    npaOutstandingInrCr: 80.0,
    requiredProvisionInrCr: 208.5, // Correct annual FTP transfer charges
    unexplainedVarianceInrCr: 0.0,
    grossAbsoluteVarianceInrCr: 0.0,
    pricedPopulationCount: 8,
    rejectedPopulationCount: 0,
    consumedRunVersionId: 'RUN-20260731-01',
    approvedRunVersionId: 'RUN-20260731-01',
    isVersionLocked: true,
    reconciliationStatus: 'RECONCILED (ZERO VARIANCE & RUN LOCKED)',
    stageBreaks: [
      {
        stageName: 'Source Lending → FTP Input Stage',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 2645.0,
        targetAmountInrCr: 2645.0,
        varianceAmountInrCr: 0.0,
        reason: '100% Ingestion post EOD clearing completion at 23:59:59.',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'FTP Input Stage → FTP Engine Output',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 2645.0,
        targetAmountInrCr: 2645.0,
        varianceAmountInrCr: 0.0,
        reason: 'Composite key deduplication enforced (obligor + facility + as_of_date).',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'FTP Engine Output → Downstream Extract',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 2645.0,
        targetAmountInrCr: 2645.0,
        varianceAmountInrCr: 0.0,
        reason: 'Downstream extract parameterized on approved run version (RUN-20260731-01).',
        runVersionId: 'RUN-20260731-01',
      },
    ],
  },
};

export const SIGN_OFF_APPROVERS: SignOffRequirement[] = [
  { id: 'SO-FTP-01', stakeholderTitle: 'Treasury FTP Product Owner', approverName: 'Tariq Merchant', role: 'Transfer Pricing Policy Owner', status: 'PENDING', comments: 'Pending verification of DEF-FTP-001 repricing tenor fix (3M vs 36M).' },
  { id: 'SO-FTP-02', stakeholderTitle: 'Country Finance Lead', approverName: 'Sunita Rao', role: 'General Ledger Control Total Owner', status: 'PENDING', comments: 'Pending zero-variance balance reconciliation sign-off post DEF-FTP-004 ingestion timing fix.' },
  { id: 'SO-FTP-03', stakeholderTitle: 'Data Engineering Lead', approverName: 'Deepak Deshmukh', role: 'ETL Pipeline & Lineage Owner', status: 'PENDING', comments: 'Pending composite key deduplication verification on HYD-INF-9902.' },
  { id: 'SO-FTP-04', stakeholderTitle: 'QA & UAT Testing Lead', approverName: 'Bhavna Patel', role: 'Business Acceptance QA Owner', status: 'PENDING', comments: 'Pending 100% UAT test suite execution pass.' },
  { id: 'SO-FTP-05', stakeholderTitle: 'ALM & Liquidity Lead', approverName: 'Alok Verma', role: 'Downstream Extract Owner', status: 'PENDING', comments: 'Pending verification of downstream extract version lock on RUN-20260731-01.' },
];

export const GOVERNANCE_CONFIG: GovernanceConfig = {
  blockingSeverities: ['BLOCKER', 'CRITICAL'],
  requiredUatPassPercent: 100,
  maxAllowedVarianceInrCr: 0.0,
  requireRtmCoveragePercent: 100,
};

export const CASE_02_DEFINITION: CaseDefinition = {
  metadata: CASE_02_METADATA,
  stakeholders: STAKEHOLDERS,
  evidence: EVIDENCE_PACK,
  currentStateNodes: CURRENT_STATE_NODES,
  targetStateNodes: TARGET_STATE_NODES,
  requirements: BUSINESS_REQUIREMENTS,
  rules: BUSINESS_RULES,
  mappings: SOURCE_TARGET_MAPPINGS,
  investigationTasks: INVESTIGATION_TASKS,
  defects: SEEDED_DEFECTS,
  uatTestPack: UAT_TEST_PACK,
  traceabilityMatrix: TRACEABILITY_MATRIX,
  reconciliationSummary: RECONCILIATION_SUMMARY,
  signoffs: SIGN_OFF_APPROVERS,
  governanceConfig: GOVERNANCE_CONFIG,
};
