import { AtlasUniverse } from "./types";

export const ATLAS_UNIVERSES: AtlasUniverse[] = [
  {
    id: "wellness",
    title: "Wellness",
    description: "A unified archive for longitudinal health understanding, preventive thinking, clinical interpretation, and the architecture of systemic vitality.",
    moduleCount: 0,
    contentType: "Health Masterclass",
    status: "live",
    universeClass: "sequential_core",
    sectionGrouping: "Core Health Ladder",
    order: 1,
    hasLiveContent: false,
    domainGroup: "health",
    learningMode: "sequential",
    contentStyle: "masterclass",
    charterSummary: "The unified engine for health literacy and systems understanding. Focuses on the core physiological towers: metabolism, anatomy, and longevity biology merged with applied prevention.",
    futureIntent: "Consolidate all foundational health tracks into one high-signal knowledge core.",
    currentState: "Live / Strategic Merge In Progress",
    isSequential: true,
    isFlagship: true,
    teaserTopics: ["Metabolic Health", "Longevity Protocols", "Systems Physiology", "Pattern Recognition"],
    legacyIds: ["wellness"]
  },
  {
    id: "cognition",
    title: "Cognition",
    description: "Thinking better, learning better, reasoning better. An exploration of source evaluation, decision quality, mental models, and internal cognitive performance.",
    moduleCount: 0,
    contentType: "Mental Models",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 2,
    hasLiveContent: false,
    domainGroup: "cognition",
    learningMode: "flexible",
    contentStyle: "lab",
    charterSummary: "Targeting the mental engine. Developing systems for better decision quality, reasoning frameworks, and cognitive performance architecture.",
    futureIntent: "Establish the primary cognitive auxiliary wing for operational thinking.",
    currentState: "Live / Growing Archive",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Decision Quality", "Reasoning Architecture", "Source Evaluation"],
    legacyIds: ["cognition"]
  },
  {
    id: "reasoning",
    title: "Reasoning",
    description: "Daily puzzles, logic drills, estimation, and applied pattern practice. Low-friction structural practice for the modern polymath.",
    moduleCount: 0,
    contentType: "Applied Logic",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 3,
    hasLiveContent: false,
    domainGroup: "puzzle",
    learningMode: "daily",
    contentStyle: "drills",
    charterSummary: "Active structural practice for the mind. Daily drills for pattern recognition, estimation, and applied logic.",
    futureIntent: "Develop into a high-frequency reasoning gym and applied logic store.",
    currentState: "Live / First Entries Pending",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Estimation Drills", "Logic Puzzles", "Pattern Practice"],
    legacyIds: ["reasoning"]
  },
  {
    id: "human-ecosystem",
    title: "Human Ecosystem",
    description: "Systems of modern life: institutions, relationships, incentives, society, and the architectural coordination of human effort.",
    moduleCount: 0,
    contentType: "Systems Thinking",
    status: "locked",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Preview",
    order: 4,
    hasLiveContent: false,
    domainGroup: "puzzle", // Temporary domain mapping
    learningMode: "flexible",
    contentStyle: "exploratory_archive",
    charterSummary: "The study of human-scale systems. From institutional incentives to the architecture of relationship models.",
    futureIntent: "Synthesize systems-thinking with human-centric operational design.",
    currentState: "Architecture In Progress",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Institutional Logic", "Relationship Systems", "Social Coordination"],
    legacyIds: ["human-ecosystem"]
  },
  {
    id: "sandbox",
    title: "Sandbox",
    description: "Useful exploratory topics, rapid experiments, and flexible life-relevant material. The overflow zone for intellectual curiosity and rapid prototyping.",
    moduleCount: 0,
    contentType: "Experimental",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 5,
    hasLiveContent: false,
    domainGroup: "sandbox",
    learningMode: "exploratory",
    contentStyle: "exploratory_archive",
    charterSummary: "The flexible exploratory wing of the Atlas core. A place for rapid prototyping of health concepts and overflow life-systems thinking.",
    futureIntent: "Remain as the primary rapid-turnaround experimentation zone.",
    currentState: "Live / Exploratory Archive",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Rapid Prototyping", "Life-Systems Thinking", "Experimental Topics"],
    legacyIds: ["sandbox"]
  }
];
