import { AtlasUniverse } from "./types";

export const ATLAS_UNIVERSES: AtlasUniverse[] = [
  {
    id: "foundations-of-human-health",
    title: "Foundations of Human Health",
    description: "An inquiry into the core physiological systems that govern longitudinal vitality. This universe synthesizes modern clinical insights with fundamental biological protocols.",
    moduleCount: 12,
    contentType: "Scientific Masterclass",
    status: "live",
    universeClass: "sequential_core",
    sectionGrouping: "Core Health Ladder",
    order: 1,
    hasLiveContent: true,
    domainGroup: "health",
    learningMode: "sequential",
    contentStyle: "masterclass",
    charterSummary: "The first-principles engine for health literacy and systems understanding. Focuses on the core physiological towers: metabolism, anatomy, and longevity biology.",
    futureIntent: "Maintain as the flagship knowledge core of the health ladder.",
    currentState: "Live / Content Complete",
    isSequential: true,
    isFlagship: true,
    teaserTopics: ["Metabolic Health", "Longevity Protocols", "Systems Physiology"]
  },
  {
    id: "applied-preventive-health",
    title: "Applied Preventive Health",
    description: "The transition from theory to practice: real-world interpretation, prevention, pattern recognition, risk management, and clinical action.",
    moduleCount: 0,
    contentType: "Clinical Practice",
    status: "locked",
    universeClass: "sequential_core",
    sectionGrouping: "Core Health Ladder",
    badge: "Coming Soon",
    order: 2,
    hasLiveContent: false,
    domainGroup: "health",
    learningMode: "sequential",
    contentStyle: "lab",
    charterSummary: "Translating Foundations into actual preventive protocols. Focuses on risk management, pattern recognition, and longitudinal clinical bridges.",
    futureIntent: "Develop as the second layer of the health ladder.",
    currentState: "Locked / Synthesis Layer",
    isSequential: true,
    isFlagship: false,
    teaserTopics: ["Risk Management", "Pattern Recognition", "Clinical Action"]
  },
  {
    id: "longitudinal-health-architecture",
    title: "Longitudinal Health Architecture",
    description: "Deepest systems-level health thinking, longitudinal reasoning, and the architecture of multi-decade vitality.",
    moduleCount: 0,
    contentType: "Systems Thinking",
    status: "locked",
    universeClass: "sequential_core",
    sectionGrouping: "Core Health Ladder",
    badge: "Coming Soon",
    order: 3,
    hasLiveContent: false,
    domainGroup: "health",
    learningMode: "sequential",
    contentStyle: "masterclass",
    charterSummary: "The deepest systems-level health integration. Orchestrating long-horizon biological vitality over multi-decade architectures.",
    futureIntent: "The final layer of the foundational health ladder.",
    currentState: "Locked / Deep Layer Ahead",
    isSequential: true,
    isFlagship: false,
    teaserTopics: ["Systems Architecture", "Multi-Decade Vitality", "Long-Horizon Reasoning"]
  },
  {
    id: "cognition-lab",
    title: "Cognition Lab",
    description: "Thinking better, learning better, reasoning better. An exploration of source evaluation, decision quality, and cognitive performance.",
    moduleCount: 0,
    contentType: "Mental Models",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 4,
    hasLiveContent: false,
    domainGroup: "cognition",
    learningMode: "flexible",
    contentStyle: "lab",
    charterSummary: "Targeting the mental engine. Developing systems for better decision quality, reasoning frameworks, and cognitive performance.",
    futureIntent: "Establish the primary cognitive auxiliary wing.",
    currentState: "Live / Growing Archive",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Decision Quality", "Reasoning Architecture", "Source Evaluation"]
  },
  {
    id: "puzzle-gym",
    title: "Puzzle Gym",
    description: "Daily puzzles, logic drills, estimation, and pattern practice. Applied reasoning for the modern polymath.",
    moduleCount: 0,
    contentType: "Applied Logic",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 5,
    hasLiveContent: false,
    domainGroup: "puzzle",
    learningMode: "daily",
    contentStyle: "drills",
    charterSummary: "Active structural practice for the mind. Daily drills for pattern recognition, estimation, and applied logic.",
    futureIntent: "Develop into a high-frequency reasoning gym.",
    currentState: "Live / First Entries Pending",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Estimation Drills", "Logic Puzzles", "Pattern Practice"]
  },
  {
    id: "sandbox",
    title: "Sandbox",
    description: "Useful exploratory topics, experiments, and flexible life-relevant material. The overflow zone for intellectual curiosity.",
    moduleCount: 0,
    contentType: "Experimental",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Growing",
    order: 6,
    hasLiveContent: false,
    domainGroup: "sandbox",
    learningMode: "exploratory",
    contentStyle: "exploratory_archive",
    charterSummary: "The flexible exploratory wing of the Atlas core. A place for rapid prototyping of health concepts and overflow life-systems thinking.",
    futureIntent: "The overflow zone for intellectual curiosity.",
    currentState: "Live / Exploratory Archive",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Rapid Prototyping", "Life-Systems Thinking", "Experimental Topics"]
  }
];
