import { LifeLabUniverse } from "./types";

export const LIFE_LAB_UNIVERSES: LifeLabUniverse[] = [
  {
    id: "wellness",
    title: "Wellness",
    description: "The flagship archive for health literacy, prevention, recovery, and long-term vitality.",
    moduleCount: 0,
    contentType: "Health Core",
    status: "live",
    universeClass: "sequential_core",
    sectionGrouping: "Core Health Ladder",
    order: 1,
    hasLiveContent: false,
    domainGroup: "health",
    learningMode: "sequential",
    contentStyle: "masterclass",
    charterSummary: "The active core of Life Lab. I am building a serious beginner-friendly archive around sleep, movement, nutrition, stress, recovery, biomarkers, and preventive health thinking.",
    futureIntent: "This universe is currently my flagship buildout. Foundational modules are being developed first, with clarity, evidence discipline, and long-term usefulness as the priority.",
    currentState: "LIVE / ACTIVE CORE",
    isSequential: true,
    isFlagship: true,
    teaserTopics: ["Metabolic Health", "Longevity Protocols", "Systems Physiology", "Pattern Recognition"],
    legacyIds: ["wellness"]
  },
  {
    id: "cognition",
    title: "Cognition",
    description: "The mental backbone of Life Lab: learning science, decision quality, source evaluation, and clear thinking.",
    moduleCount: 0,
    contentType: "Cognitive Systems",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Backbone",
    order: 2,
    hasLiveContent: false,
    domainGroup: "cognition",
    learningMode: "flexible",
    contentStyle: "lab",
    charterSummary: "The intellectual backbone of Life Lab. Covers learning science, bias correction, source evaluation, decision quality, and reusable mental models.",
    futureIntent: "This universe is open and growing. I am building foundational entries as a reusable operating layer that strengthens every other part of the archive.",
    currentState: "LIVE / BACKBONE BUILDOUT",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Decision Quality", "Reasoning Architecture", "Source Evaluation"],
    legacyIds: ["cognition"]
  },
  {
    id: "reasoning",
    title: "Reasoning",
    description: "The practice arena for logic, estimation, quantitative intuition, and structural problem solving.",
    moduleCount: 0,
    contentType: "Applied Reasoning",
    status: "live",
    universeClass: "parallel_wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Rigor",
    order: 3,
    hasLiveContent: false,
    domainGroup: "puzzle",
    learningMode: "daily",
    contentStyle: "drills",
    charterSummary: "The rigor-training layer of Life Lab. Built around drills, puzzles, estimation, argument structure, and repeatable reasoning reps.",
    futureIntent: "This universe is open and growing. Early modules stay compact, practice-first, and easier to publish consistently.",
    currentState: "LIVE / PRACTICE WING",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Estimation Drills", "Logic Puzzles", "Pattern Practice"],
    legacyIds: ["reasoning"]
  },
  {
    id: "human-ecosystem",
    title: "Human Ecosystem",
    description: "The human layer of Life Lab: communication, trust, relationships, incentives, and the systems that shape real-world coordination.",
    moduleCount: 0,
    contentType: "Human Systems",
    status: "live",
    universeClass: "architecture wing",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Systems",
    order: 4,
    hasLiveContent: false,
    domainGroup: "human-ecosystem",
    learningMode: "flexible",
    contentStyle: "human systems archive",
    charterSummary: "A grounded archive for becoming clearer, warmer, harder to manipulate, and better at functioning with real people.",
    futureIntent: "I am still architecting this universe carefully. The goal is to build a mature, useful library on human coordination before scaling volume.",
    currentState: "LIVE / ARCHITECTURE IN PROGRESS",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Communication", "Relationship Architecture", "Trust Systems", "Institutional Logic"],
    legacyIds: ["human-ecosystem"]
  },
  {
    id: "sandbox",
    title: "Sandbox",
    description: "An intentionally open mystery box inside Life Lab. No fixed syllabus—just a low-pressure buffer for off-script ideas and creative recovery.",
    moduleCount: 0,
    contentType: "Mystery Box",
    status: "live",
    universeClass: "mystery box",
    sectionGrouping: "Parallel Auxiliary Universes",
    badge: "Open Buffer",
    order: 5,
    hasLiveContent: false,
    domainGroup: "sandbox",
    learningMode: "open",
    contentStyle: "mystery box",
    charterSummary: "The empty buffer box of the system. Used when energy is low, focus is drifting, or a topic does not yet deserve a permanent home.",
    futureIntent: "This universe is intentionally sparse. Nothing here needs to resolve into a formal series unless it later proves it belongs somewhere else.",
    currentState: "LIVE / MYSTERY BOX",
    isSequential: false,
    isFlagship: false,
    teaserTopics: ["Off-script Ideas", "Experimental Topics", "Creative Recovery"],
    legacyIds: ["sandbox"]
  }
];
