import {
  BankEntity,
  Obligor,
  Facility,
  PortfolioTotals,
  InternalRating,
  IndiaSector,
} from '../_types';
import { classifyIRACPAsset, calculateIRACPProvision } from '../_engine/iracp';
import { calculateRBIRWA } from '../_engine/rbiCapital';

export const INDUS_APEX_BANK_ENTITY: BankEntity = {
  name: 'Indus Apex Bank India',
  legalEntityCode: 'LEI-IND-213800IAB99120',
  jurisdiction: 'India',
  regulator: 'Reserve Bank of India (RBI)',
  baseCurrency: 'INR',
  simulationDate: '31 July 2026',
  totalAssetsInrCr: 38500, // ₹38,500 Cr Balance Sheet Assets
  wholeBankCet1CapitalInrCr: 4200, // ₹4,200 Cr CET1 Capital
  tier1CapitalInrCr: 4800, // ₹4,800 Cr Tier 1 Capital
  wholeBankTotalRwaInrCr: 28000, // ₹28,000 Cr Whole-Bank Total RWA
  wholeBankCet1RatioPercent: 15.00, // 15.00% CET1 Ratio
  wholeBankTier1RatioPercent: 17.14, // 17.14% Tier 1 Ratio
  wholeBankCrarPercent: 16.50, // 16.50% Total CRAR
  // Backwards compatibility aliases
  totalAssetsGBP: 38500,
  wholeBankCet1CapitalGBP: 4200,
  tier1CapitalGBP: 4800,
  wholeBankTotalRwaGBP: 28000,
};

export const SYNTHETIC_INDIA_OBLIGORS: Obligor[] = [
  {
    id: 'OBL-IND-101',
    name: 'Sahyadri Commercial Logistics Group Ltd',
    groupName: 'Sahyadri Group India',
    groupCode: 'GRP-SAHYADRI-01',
    registrationNumber: 'CIN-L60200MH2012PLC084729',
    sector: 'Commercial Real Estate',
    geography: 'Mumbai, Maharashtra',
    internalRating: 'BBB',
    externalRating: 'CRISIL BBB+',
    annualTurnoverInrCr: 1450,
    annualTurnoverGBP: 145,
    watchlistStatus: false,
  },
  {
    id: 'OBL-IND-102',
    name: 'Deccan Power & Infrastructure Ltd',
    groupName: 'Deccan Infrastructure Holdings',
    groupCode: 'GRP-DECCAN-04',
    registrationNumber: 'CIN-L40100TG2015PLC192837',
    sector: 'Infrastructure & Energy',
    geography: 'Hyderabad, Telangana',
    internalRating: 'A',
    externalRating: 'ICRA A+',
    annualTurnoverInrCr: 2200,
    annualTurnoverGBP: 220,
    watchlistStatus: false,
  },
  {
    id: 'OBL-IND-103',
    name: 'Western Precision Auto Components Ltd',
    groupName: 'Western Industrial Group',
    groupCode: 'GRP-WESTERN-02',
    registrationNumber: 'CIN-L28910MH2010PLC048201',
    sector: 'Manufacturing & Industrial',
    geography: 'Pune, Maharashtra',
    internalRating: 'BB',
    externalRating: 'CARE BB+',
    annualTurnoverInrCr: 680,
    annualTurnoverGBP: 68,
    watchlistStatus: true,
    watchlistReason: 'LTV breached 70% covenant threshold; 38 DPD overdue (SMA-1).',
  },
  {
    id: 'OBL-IND-104',
    name: 'Kaveri Precision Engineering Pvt Ltd',
    groupName: 'Kaveri Tech Group',
    groupCode: 'GRP-KAVERI-01',
    registrationNumber: 'CIN-U29100KA2018PTC093820',
    sector: 'MSME & SME Enterprise',
    geography: 'Bengaluru, Karnataka',
    internalRating: 'BBB',
    externalRating: 'CRISIL BBB',
    annualTurnoverInrCr: 340,
    annualTurnoverGBP: 34,
    watchlistStatus: false,
  },
  {
    id: 'OBL-IND-105',
    name: 'Sabarmati Clean Energy & Solar Ltd',
    groupName: 'Sabarmati Power Group',
    groupCode: 'GRP-SABAR-09',
    registrationNumber: 'CIN-L40300GJ2016PLC057391',
    sector: 'Renewable Energy',
    geography: 'Ahmedabad, Gujarat',
    internalRating: 'AA',
    externalRating: 'CARE AA',
    annualTurnoverInrCr: 1800,
    annualTurnoverGBP: 180,
    watchlistStatus: false,
  },
  {
    id: 'OBL-IND-106',
    name: 'Aethel Healthcare & Hospitals Ltd',
    groupName: 'Aethel Medicare Group',
    groupCode: 'GRP-AETHEL-03',
    registrationNumber: 'CIN-L85110DL2014PLC209481',
    sector: 'Healthcare & Pharma',
    geography: 'Delhi NCR',
    internalRating: 'CCC',
    externalRating: 'ICRA C',
    annualTurnoverInrCr: 140,
    annualTurnoverGBP: 14,
    watchlistStatus: true,
    watchlistReason: 'Overdue >90 DPD (112 DPD). Classified as Substandard NPA.',
  },
  {
    id: 'OBL-IND-107',
    name: 'Coromandel Residential Developers Ltd',
    groupName: 'Coromandel Housing Group',
    groupCode: 'GRP-CORO-05',
    registrationNumber: 'CIN-L45200TN2017PLC073910',
    sector: 'Residential Housing',
    geography: 'Chennai, Tamil Nadu',
    internalRating: 'B',
    externalRating: 'CRISIL B+',
    annualTurnoverInrCr: 420,
    annualTurnoverGBP: 42,
    watchlistStatus: true,
    watchlistReason: '38 DPD overdue (SMA-1); construction cost inflation.',
  },
  {
    id: 'OBL-IND-108',
    name: 'Indus Digital Systems & Tech Ltd',
    groupName: 'Indus Tech Holdings',
    groupCode: 'GRP-INTECH-01',
    registrationNumber: 'CIN-L72200GJ2019PLC109283',
    sector: 'Technology Services',
    geography: 'Ahmedabad, Gujarat',
    internalRating: 'A',
    externalRating: 'ICRA A',
    annualTurnoverInrCr: 950,
    annualTurnoverGBP: 95,
    watchlistStatus: false,
  },
];

export const SYNTHETIC_INDIA_FACILITIES: Facility[] = [
  {
    id: 'FAC-2026-IND-01',
    facilityNumber: 'MUM-CRE-8801',
    obligorId: 'OBL-IND-101',
    obligorName: 'Sahyadri Commercial Logistics Group Ltd',
    product: 'Term Loan',
    currency: 'INR',
    sanctionedLimitInrCr: 500,
    outstandingInrCr: 450,
    undrawnInrCr: 50,
    drawingPowerInrCr: 450,
    daysPastDue: 0,
    dpd: 0,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'CRE',
    ccf: 0.50,
    originationDate: '2022-03-15',
    maturityDate: '2028-03-15',
    collateral: {
      id: 'COL-IND-901',
      type: 'Property',
      valuationGBP: 65,
      valuationInrCr: 650,
      lastValuationDate: '2025-11-30',
      haircut: 0.15,
      realisableValueInrCr: 552.5,
    },
    securedFlag: true,
    realisableSecurityInrCr: 552.5,
    pd: 0.012,
    lgd: 0.25,
    eadInrCr: 475, // 450 + 0.50 * 50
    ifrs9Stage: 1,
    sicrTriggered: false,
    iracpProvisionRatePercent: 1.00,
    iracpProvisionRequiredInrCr: 4.50, // 1% of 450
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 100.0,
    riskWeight: 1.00,
    rwaInrCr: 475.0,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 500,
    drawnGBP: 450,
    undrawnGBP: 50,
    ead: 475,
    ecl12mGBP: 1.425,
    eclLifetimeGBP: 4.275,
    provisionGBP: 4.50,
    rwaGBP: 475.0,
  },
  {
    id: 'FAC-2026-IND-02',
    facilityNumber: 'HYD-INF-9902',
    obligorId: 'OBL-IND-102',
    obligorName: 'Deccan Power & Infrastructure Ltd',
    product: 'Term Loan',
    currency: 'INR',
    sanctionedLimitInrCr: 800,
    outstandingInrCr: 700,
    undrawnInrCr: 100,
    drawingPowerInrCr: 700,
    daysPastDue: 0,
    dpd: 0,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    ccf: 0.50,
    originationDate: '2023-01-10',
    maturityDate: '2030-01-10',
    collateral: {
      id: 'COL-IND-902',
      type: 'Equipment',
      valuationGBP: 95,
      valuationInrCr: 950,
      lastValuationDate: '2025-10-15',
      haircut: 0.20,
      realisableValueInrCr: 760,
    },
    securedFlag: true,
    realisableSecurityInrCr: 760,
    pd: 0.008,
    lgd: 0.20,
    eadInrCr: 750,
    ifrs9Stage: 1,
    sicrTriggered: false,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 2.80, // 0.40% of 700
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 50.0,
    riskWeight: 0.50,
    rwaInrCr: 375.0,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 800,
    drawnGBP: 700,
    undrawnGBP: 100,
    ead: 750,
    ecl12mGBP: 1.20,
    eclLifetimeGBP: 3.60,
    provisionGBP: 2.80,
    rwaGBP: 375.0,
  },
  {
    id: 'FAC-2026-IND-03',
    facilityNumber: 'PUN-MFG-4403',
    obligorId: 'OBL-IND-103',
    obligorName: 'Western Precision Auto Components Ltd',
    product: 'Revolving Credit',
    currency: 'INR',
    sanctionedLimitInrCr: 350,
    outstandingInrCr: 300,
    undrawnInrCr: 50,
    drawingPowerInrCr: 300,
    daysPastDue: 42,
    dpd: 42,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'SMA-1',
    smaStatus: 'SMA-1',
    exposureCategory: 'Other-Commercial',
    ccf: 0.75,
    originationDate: '2021-06-20',
    maturityDate: '2026-06-20',
    collateral: {
      id: 'COL-IND-903',
      type: 'Property',
      valuationGBP: 38,
      valuationInrCr: 380,
      lastValuationDate: '2025-12-01',
      haircut: 0.25,
      realisableValueInrCr: 285,
    },
    securedFlag: true,
    realisableSecurityInrCr: 285,
    pd: 0.065,
    lgd: 0.40,
    eadInrCr: 337.5,
    ifrs9Stage: 2,
    sicrTriggered: true,
    sicrReason: '38 DPD overdue (SMA-1) and relative PD ratio increased by 3.6x.',
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 1.20, // Standard 0.40% for SMA-1
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 100.0,
    riskWeight: 1.00,
    rwaInrCr: 337.5,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 350,
    drawnGBP: 300,
    undrawnGBP: 50,
    ead: 337.5,
    ecl12mGBP: 8.775,
    eclLifetimeGBP: 26.325,
    provisionGBP: 1.20,
    rwaGBP: 337.5,
  },
  {
    id: 'FAC-2026-IND-04',
    facilityNumber: 'BLR-SME-1104',
    obligorId: 'OBL-IND-104',
    obligorName: 'Kaveri Precision Engineering Pvt Ltd',
    product: 'Term Loan',
    currency: 'INR',
    sanctionedLimitInrCr: 120,
    outstandingInrCr: 100,
    undrawnInrCr: 20,
    drawingPowerInrCr: 100,
    daysPastDue: 0,
    dpd: 0,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Farm-MSE-Housing',
    ccf: 0.50,
    originationDate: '2022-09-01',
    maturityDate: '2027-09-01',
    collateral: {
      id: 'COL-IND-904',
      type: 'Equipment',
      valuationGBP: 14,
      valuationInrCr: 140,
      lastValuationDate: '2025-08-20',
      haircut: 0.20,
      realisableValueInrCr: 112,
    },
    securedFlag: true,
    realisableSecurityInrCr: 112,
    pd: 0.018,
    lgd: 0.30,
    eadInrCr: 110,
    ifrs9Stage: 1,
    sicrTriggered: false,
    iracpProvisionRatePercent: 0.25,
    iracpProvisionRequiredInrCr: 0.25, // 0.25% MSE rate
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 75.0,
    riskWeight: 0.75,
    rwaInrCr: 82.5,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 120,
    drawnGBP: 100,
    undrawnGBP: 20,
    ead: 110,
    ecl12mGBP: 0.594,
    eclLifetimeGBP: 1.782,
    provisionGBP: 0.25,
    rwaGBP: 82.5,
  },
  {
    id: 'FAC-2026-IND-05',
    facilityNumber: 'GUJ-REN-3305',
    obligorId: 'OBL-IND-105',
    obligorName: 'Sabarmati Clean Energy & Solar Ltd',
    product: 'Term Loan',
    currency: 'INR',
    sanctionedLimitInrCr: 600,
    outstandingInrCr: 550,
    undrawnInrCr: 50,
    drawingPowerInrCr: 550,
    daysPastDue: 0,
    dpd: 0,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    ccf: 0.50,
    originationDate: '2020-04-15',
    maturityDate: '2029-04-15',
    collateral: {
      id: 'COL-IND-905',
      type: 'Property',
      valuationGBP: 85,
      valuationInrCr: 850,
      lastValuationDate: '2025-11-10',
      haircut: 0.15,
      realisableValueInrCr: 722.5,
    },
    securedFlag: true,
    realisableSecurityInrCr: 722.5,
    pd: 0.005,
    lgd: 0.18,
    eadInrCr: 575,
    ifrs9Stage: 1,
    sicrTriggered: false,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 2.20,
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 50.0,
    riskWeight: 0.50,
    rwaInrCr: 287.5,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 600,
    drawnGBP: 550,
    undrawnGBP: 50,
    ead: 575,
    ecl12mGBP: 0.5175,
    eclLifetimeGBP: 1.5525,
    provisionGBP: 2.20,
    rwaGBP: 287.5,
  },
  {
    id: 'FAC-2026-IND-06',
    facilityNumber: 'DEL-MED-7706',
    obligorId: 'OBL-IND-106',
    obligorName: 'Aethel Healthcare & Hospitals Ltd',
    product: 'Overdraft',
    currency: 'INR',
    sanctionedLimitInrCr: 80,
    outstandingInrCr: 80,
    undrawnInrCr: 0,
    drawingPowerInrCr: 80,
    daysPastDue: 112,
    dpd: 112,
    isDefaulted: true,
    isNPA: true,
    assetQualityStatus: 'Substandard',
    smaStatus: 'SMA-2',
    exposureCategory: 'Other-Commercial',
    npaSinceDate: '2026-04-10',
    ccf: 1.00,
    originationDate: '2019-11-01',
    maturityDate: '2024-11-01',
    collateral: {
      id: 'COL-IND-906',
      type: 'Unsecured',
      valuationGBP: 0,
      valuationInrCr: 0,
      lastValuationDate: '2025-01-01',
      haircut: 1.00,
      realisableValueInrCr: 0,
    },
    securedFlag: false,
    realisableSecurityInrCr: 0,
    pd: 1.00,
    lgd: 0.65,
    eadInrCr: 80,
    ifrs9Stage: 3,
    sicrTriggered: true,
    sicrReason: 'Substandard NPA declared (>90 DPD overdue & insolvency filing).',
    iracpProvisionRatePercent: 25.0, // Unsecured Substandard = 25%
    iracpProvisionRequiredInrCr: 20.0, // 25% of ₹80 Cr
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 150.0,
    riskWeight: 1.50,
    rwaInrCr: 90.0, // 150% on net unprovisioned (80 - 20 = 60 * 150% = 90)
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 80,
    drawnGBP: 80,
    undrawnGBP: 0,
    ead: 80,
    ecl12mGBP: 52.0,
    eclLifetimeGBP: 52.0,
    provisionGBP: 20.0,
    rwaGBP: 90.0,
  },
  {
    id: 'FAC-2026-IND-07',
    facilityNumber: 'CHN-RES-5507',
    obligorId: 'OBL-IND-107',
    obligorName: 'Coromandel Residential Developers Ltd',
    product: 'Term Loan',
    currency: 'INR',
    sanctionedLimitInrCr: 220,
    outstandingInrCr: 200,
    undrawnInrCr: 20,
    drawingPowerInrCr: 200,
    daysPastDue: 38,
    dpd: 38,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'SMA-1',
    smaStatus: 'SMA-1',
    exposureCategory: 'CRE-Residential',
    ccf: 0.50,
    originationDate: '2023-05-10',
    maturityDate: '2028-05-10',
    collateral: {
      id: 'COL-IND-907',
      type: 'Property',
      valuationGBP: 24,
      valuationInrCr: 240,
      lastValuationDate: '2025-10-01',
      haircut: 0.20,
      realisableValueInrCr: 192,
    },
    securedFlag: true,
    realisableSecurityInrCr: 192,
    pd: 0.085,
    lgd: 0.45,
    eadInrCr: 210,
    ifrs9Stage: 2,
    sicrTriggered: true,
    sicrReason: '38 DPD overdue (SMA-1) and relative PD ratio > 3.0x.',
    iracpProvisionRatePercent: 0.75,
    iracpProvisionRequiredInrCr: 1.50, // 0.75% CRE Resi rate
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 75.0,
    riskWeight: 0.75,
    rwaInrCr: 157.5,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 220,
    drawnGBP: 200,
    undrawnGBP: 20,
    ead: 210,
    ecl12mGBP: 8.0325,
    eclLifetimeGBP: 24.0975,
    provisionGBP: 1.50,
    rwaGBP: 157.5,
  },
  {
    id: 'FAC-2026-IND-08',
    facilityNumber: 'AMD-TECH-2208',
    obligorId: 'OBL-IND-108',
    obligorName: 'Indus Digital Systems & Tech Ltd',
    product: 'Revolving Credit',
    currency: 'INR',
    sanctionedLimitInrCr: 400,
    outstandingInrCr: 250,
    undrawnInrCr: 150,
    drawingPowerInrCr: 250,
    daysPastDue: 0,
    dpd: 0,
    isDefaulted: false,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    ccf: 0.50,
    originationDate: '2024-02-01',
    maturityDate: '2029-02-01',
    collateral: {
      id: 'COL-IND-908',
      type: 'Cash',
      valuationGBP: 10,
      valuationInrCr: 100,
      lastValuationDate: '2025-12-01',
      haircut: 0.00,
      realisableValueInrCr: 100,
    },
    securedFlag: true,
    realisableSecurityInrCr: 100,
    pd: 0.010,
    lgd: 0.22,
    eadInrCr: 325,
    ifrs9Stage: 1,
    sicrTriggered: false,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 1.00, // 0.40% of 250
    regulatoryApproach: 'Standardised',
    riskWeightPercent: 20.0,
    riskWeight: 0.20,
    rwaInrCr: 65.0,
    reportingStatus: 'Verified',
    // Compatibility fields
    limitGBP: 400,
    drawnGBP: 250,
    undrawnGBP: 150,
    ead: 325,
    ecl12mGBP: 0.715,
    eclLifetimeGBP: 2.145,
    provisionGBP: 1.00,
    rwaGBP: 65.0,
  },
];

export function getIndiaPortfolioTotals(facilities: Facility[] = SYNTHETIC_INDIA_FACILITIES): PortfolioTotals {
  const facilityCount = facilities.length;
  const uniqueObligors = new Set(facilities.map((f) => f.obligorId));
  const obligorCount = uniqueObligors.size;

  const totalLimitInrCr = facilities.reduce((sum, f) => sum + (f.sanctionedLimitInrCr || f.limitGBP), 0);
  const totalOutstandingInrCr = facilities.reduce((sum, f) => sum + (f.outstandingInrCr || f.drawnGBP), 0);
  const totalUndrawnInrCr = facilities.reduce((sum, f) => sum + (f.undrawnInrCr || f.undrawnGBP), 0);
  const totalEadInrCr = facilities.reduce((sum, f) => sum + (f.eadInrCr || f.ead), 0);

  const totalIracpProvisionInrCr = facilities.reduce((sum, f) => {
    const prov = calculateIRACPProvision({
      outstandingInrCr: f.outstandingInrCr || f.drawnGBP,
      realisableSecurityInrCr: f.realisableSecurityInrCr || (f.collateral?.valuationInrCr * (1 - f.collateral?.haircut)) || 0,
      assetQualityStatus: f.assetQualityStatus || 'Standard',
      exposureCategory: f.exposureCategory || 'Other-Commercial',
      isSecured: f.securedFlag ?? true,
    });
    return sum + prov.totalRequiredProvisionInrCr;
  }, 0);

  const totalRwaInrCr = facilities.reduce((sum, f) => {
    const rwaResult = calculateRBIRWA({
      exposureInrCr: f.eadInrCr || f.ead,
      riskWeightPercent: f.riskWeightPercent || (f.riskWeight * 100),
      provisionInrCr: f.iracpProvisionRequiredInrCr || f.provisionGBP,
      isNPA: f.isNPA || f.isDefaulted,
    });
    return sum + rwaResult.rwaInrCr;
  }, 0);

  const attributableCapitalReqInrCr = (totalRwaInrCr * 9.0) / 100;

  const grossNpaInrCr = facilities
    .filter((f) => f.isNPA || f.isDefaulted)
    .reduce((sum, f) => sum + (f.outstandingInrCr || f.drawnGBP), 0);

  const grossNpaRatioPercent =
    totalOutstandingInrCr > 0 ? (grossNpaInrCr / totalOutstandingInrCr) * 100 : 0;

  const standardCount = facilities.filter((f) => f.assetQualityStatus === 'Standard' || f.smaStatus === 'Standard').length;
  const sma0Count = facilities.filter((f) => f.smaStatus === 'SMA-0').length;
  const sma1Count = facilities.filter((f) => f.smaStatus === 'SMA-1').length;
  const sma2Count = facilities.filter((f) => f.smaStatus === 'SMA-2' && !f.isNPA).length;
  const npaCount = facilities.filter((f) => f.isNPA || f.isDefaulted).length;
  const watchlistCount = facilities.filter((f) => f.sicrTriggered || f.isNPA).length;

  return {
    facilityCount,
    obligorCount,
    totalLimitInrCr,
    totalOutstandingInrCr,
    totalUndrawnInrCr,
    totalEadInrCr,
    totalIracpProvisionInrCr,
    totalRwaInrCr,
    attributableCapitalReqInrCr,
    grossNpaInrCr,
    grossNpaRatioPercent,
    standardCount,
    sma0Count,
    sma1Count,
    sma2Count,
    npaCount,
    watchlistCount,

    // Backwards compatibility aliases
    totalLimitGBP: totalLimitInrCr,
    totalDrawnGBP: totalOutstandingInrCr,
    totalUndrawnGBP: totalUndrawnInrCr,
    totalEadGBP: totalEadInrCr,
    totalProvisionGBP: totalIracpProvisionInrCr,
    totalRwaGBP: totalRwaInrCr,
    attributablePillar1CapitalGBP: attributableCapitalReqInrCr,
    stage1Count: standardCount,
    stage2Count: sma1Count + sma2Count,
    stage3Count: npaCount,
    defaultCount: npaCount,
  };
}

export function getIndiaCustomerById(id: string): Obligor | undefined {
  return SYNTHETIC_INDIA_OBLIGORS.find((o) => o.id === id);
}

export function getIndiaFacilityById(id: string): Facility | undefined {
  return SYNTHETIC_INDIA_FACILITIES.find((f) => f.id === id);
}
