import {
  BankEntity,
  Obligor,
  Facility,
  PortfolioTotals,
  InternalRating,
  UKSector,
  IFRS9Stage
} from '../_types';

export const RENFORGE_BANK_ENTITY: BankEntity = {
  name: 'Renforge Bank plc (Legacy Reference)',
  legalEntityCode: 'LEI-UK-213800RFB99120',
  jurisdiction: 'United Kingdom',
  regulator: 'Prudential Regulation Authority (PRA) / FCA',
  baseCurrency: 'GBP',
  simulationDate: '31 July 2026',
  wholeBankCet1CapitalGBP: 420_000_000,
  wholeBankTotalRwaGBP: 2_800_000_000,
  wholeBankCet1RatioPercent: 15.00,
  totalAssetsGBP: 3_850_000_000,
  tier1CapitalGBP: 480_000_000,

  // Fallback India fields for interface compliance
  wholeBankCet1CapitalInrCr: 4200,
  wholeBankTotalRwaInrCr: 28000,
  wholeBankTier1RatioPercent: 17.14,
  wholeBankCrarPercent: 16.50,
  totalAssetsInrCr: 38500,
  tier1CapitalInrCr: 4800,
};

export const SYNTHETIC_OBLIGORS: Obligor[] = [
  {
    id: 'OBL-101',
    name: 'Thames Logistics & Distribution Group plc',
    groupName: 'Thames Logistics Group',
    groupCode: 'GRP-THAMES-01',
    registrationNumber: 'UK-08472910',
    sector: 'Commercial Real Estate',
    geography: 'London & SE, UK',
    internalRating: 'BBB',
    externalRating: 'Baa2',
    annualTurnoverGBP: 145_000_000,
    annualTurnoverInrCr: 1450,
    watchlistStatus: false,
  },
  {
    id: 'OBL-102',
    name: 'Caledonia Energy & Marine Ltd',
    groupName: 'Caledonia Holdings',
    groupCode: 'GRP-CAL-04',
    registrationNumber: 'SC-19283711',
    sector: 'Specialized Infrastructure',
    geography: 'Aberdeen, UK',
    internalRating: 'A',
    externalRating: 'A3',
    annualTurnoverGBP: 220_000_000,
    annualTurnoverInrCr: 2200,
    watchlistStatus: false,
  },
  {
    id: 'OBL-103',
    name: 'Midland Retail Properties plc',
    groupName: 'Midland Property Group',
    groupCode: 'GRP-MIDLAND-02',
    registrationNumber: 'UK-04820192',
    sector: 'Commercial Real Estate',
    geography: 'Birmingham & Midlands, UK',
    internalRating: 'BB',
    externalRating: 'Ba2',
    annualTurnoverGBP: 68_000_000,
    annualTurnoverInrCr: 680,
    watchlistStatus: true,
    watchlistReason: 'LTV breached 70% covenant threshold; 45 DPD overdue.',
  },
  {
    id: 'OBL-104',
    name: 'Wessex Precision Engineering Ltd',
    groupName: 'Wessex Group',
    groupCode: 'GRP-WESSEX-01',
    registrationNumber: 'UK-09382019',
    sector: 'SME Lending',
    geography: 'Bristol & SW, UK',
    internalRating: 'BBB',
    externalRating: 'Baa3',
    annualTurnoverGBP: 34_000_000,
    annualTurnoverInrCr: 340,
    watchlistStatus: false,
  },
  {
    id: 'OBL-105',
    name: 'Mersey Maritime & Freight Services Ltd',
    groupName: 'Mersey Holdings',
    groupCode: 'GRP-MERSEY-09',
    registrationNumber: 'UK-05739201',
    sector: 'Wholesale Corporate',
    geography: 'Liverpool & NW, UK',
    internalRating: 'AA',
    externalRating: 'Aa3',
    annualTurnoverGBP: 180_000_000,
    annualTurnoverInrCr: 1800,
    watchlistStatus: false,
  },
  {
    id: 'OBL-106',
    name: 'Highland Hospitality & Leisure Ltd',
    groupName: 'Highland Leisure Group',
    groupCode: 'GRP-HIGH-03',
    registrationNumber: 'SC-20948102',
    sector: 'Commercial Real Estate',
    geography: 'Highlands & Islands, UK',
    internalRating: 'CCC',
    externalRating: 'Caa1',
    annualTurnoverGBP: 14_000_000,
    annualTurnoverInrCr: 140,
    watchlistStatus: true,
    watchlistReason: 'Overdue >90 DPD (112 DPD). Insolvency notice served.',
  },
  {
    id: 'OBL-107',
    name: 'Manchester Residential Developments Ltd',
    groupName: 'Manchester Property Group',
    groupCode: 'GRP-MANCH-05',
    registrationNumber: 'UK-07391028',
    sector: 'Residential Mortgages',
    geography: 'Manchester & NW, UK',
    internalRating: 'B',
    externalRating: 'B2',
    annualTurnoverGBP: 42_000_000,
    annualTurnoverInrCr: 420,
    watchlistStatus: true,
    watchlistReason: 'Rating downgraded by 2 notches (BBB to B).',
  },
  {
    id: 'OBL-108',
    name: 'Anglia Solar Technologies Ltd',
    groupName: 'Anglia Tech Group',
    groupCode: 'GRP-ANG-01',
    registrationNumber: 'UK-10928374',
    sector: 'Specialized Infrastructure',
    geography: 'Norwich & East Anglia, UK',
    internalRating: 'A',
    externalRating: 'A2',
    annualTurnoverGBP: 95_000_000,
    annualTurnoverInrCr: 950,
    watchlistStatus: false,
  },
];

export const SYNTHETIC_FACILITIES: Facility[] = [
  {
    id: 'FAC-2025-001',
    facilityNumber: 'THM-CRE-1101',
    obligorId: 'OBL-101',
    obligorName: 'Thames Logistics & Distribution Group plc',
    product: 'Term Loan',
    currency: 'GBP',
    limitGBP: 50_000_000,
    drawnGBP: 45_000_000,
    undrawnGBP: 5_000_000,
    ccf: 0.50,
    originationDate: '2022-03-15',
    maturityDate: '2028-03-15',
    collateral: {
      id: 'COL-001',
      type: 'Property',
      valuationGBP: 65_000_000,
      valuationInrCr: 650,
      lastValuationDate: '2025-11-30',
      haircut: 0.15,
      realisableValueInrCr: 552.5,
    },
    dpd: 0,
    isDefaulted: false,
    pd: 0.012,
    lgd: 0.25,
    ead: 47_500_000,
    ifrs9Stage: 1,
    sicrTriggered: false,
    ecl12mGBP: 142_500,
    eclLifetimeGBP: 427_500,
    provisionGBP: 142_500,
    regulatoryApproach: 'Standardised',
    riskWeight: 1.00,
    rwaGBP: 47_500_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 500,
    outstandingInrCr: 450,
    undrawnInrCr: 50,
    drawingPowerInrCr: 450,
    daysPastDue: 0,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'CRE',
    securedFlag: true,
    realisableSecurityInrCr: 552.5,
    eadInrCr: 475,
    iracpProvisionRatePercent: 1.00,
    iracpProvisionRequiredInrCr: 4.50,
    riskWeightPercent: 100.0,
    rwaInrCr: 475.0,
  },
  {
    id: 'FAC-2025-002',
    facilityNumber: 'CAL-INF-2202',
    obligorId: 'OBL-102',
    obligorName: 'Caledonia Energy & Marine Ltd',
    product: 'Term Loan',
    currency: 'GBP',
    limitGBP: 80_000_000,
    drawnGBP: 70_000_000,
    undrawnGBP: 10_000_000,
    ccf: 0.50,
    originationDate: '2023-01-10',
    maturityDate: '2030-01-10',
    collateral: {
      id: 'COL-002',
      type: 'Equipment',
      valuationGBP: 95_000_000,
      valuationInrCr: 950,
      lastValuationDate: '2025-10-15',
      haircut: 0.20,
      realisableValueInrCr: 760,
    },
    dpd: 0,
    isDefaulted: false,
    pd: 0.008,
    lgd: 0.20,
    ead: 75_000_000,
    ifrs9Stage: 1,
    sicrTriggered: false,
    ecl12mGBP: 120_000,
    eclLifetimeGBP: 360_000,
    provisionGBP: 120_000,
    regulatoryApproach: 'Standardised',
    riskWeight: 0.50,
    rwaGBP: 37_500_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 800,
    outstandingInrCr: 700,
    undrawnInrCr: 100,
    drawingPowerInrCr: 700,
    daysPastDue: 0,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    securedFlag: true,
    realisableSecurityInrCr: 760,
    eadInrCr: 750,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 2.80,
    riskWeightPercent: 50.0,
    rwaInrCr: 375.0,
  },
  {
    id: 'FAC-2025-003',
    facilityNumber: 'MID-CRE-4403',
    obligorId: 'OBL-103',
    obligorName: 'Midland Retail Properties plc',
    product: 'Revolving Credit',
    currency: 'GBP',
    limitGBP: 35_000_000,
    drawnGBP: 30_000_000,
    undrawnGBP: 5_000_000,
    ccf: 0.75,
    originationDate: '2021-06-20',
    maturityDate: '2026-06-20',
    collateral: {
      id: 'COL-003',
      type: 'Property',
      valuationGBP: 38_000_000,
      valuationInrCr: 380,
      lastValuationDate: '2025-12-01',
      haircut: 0.25,
      realisableValueInrCr: 285,
    },
    dpd: 45,
    isDefaulted: false,
    pd: 0.065,
    lgd: 0.40,
    ead: 33_750_000,
    ifrs9Stage: 2,
    sicrTriggered: true,
    sicrReason: 'Watchlist escalation & LTV covenant breach (>70%). 30+ DPD triggered.',
    ecl12mGBP: 877_500,
    eclLifetimeGBP: 2_632_500,
    provisionGBP: 2_632_500,
    regulatoryApproach: 'Standardised',
    riskWeight: 1.00,
    rwaGBP: 33_750_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 350,
    outstandingInrCr: 300,
    undrawnInrCr: 50,
    drawingPowerInrCr: 300,
    daysPastDue: 45,
    isNPA: false,
    assetQualityStatus: 'SMA-1',
    smaStatus: 'SMA-1',
    exposureCategory: 'CRE',
    securedFlag: true,
    realisableSecurityInrCr: 285,
    eadInrCr: 337.5,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 1.20,
    riskWeightPercent: 100.0,
    rwaInrCr: 337.5,
  },
  {
    id: 'FAC-2025-004',
    facilityNumber: 'WES-SME-5504',
    obligorId: 'OBL-104',
    obligorName: 'Wessex Precision Engineering Ltd',
    product: 'Term Loan',
    currency: 'GBP',
    limitGBP: 12_000_000,
    drawnGBP: 10_000_000,
    undrawnGBP: 2_000_000,
    ccf: 0.50,
    originationDate: '2022-09-01',
    maturityDate: '2027-09-01',
    collateral: {
      id: 'COL-004',
      type: 'Equipment',
      valuationGBP: 14_000_000,
      valuationInrCr: 140,
      lastValuationDate: '2025-08-20',
      haircut: 0.20,
      realisableValueInrCr: 112,
    },
    dpd: 0,
    isDefaulted: false,
    pd: 0.018,
    lgd: 0.30,
    ead: 11_000_000,
    ifrs9Stage: 1,
    sicrTriggered: false,
    ecl12mGBP: 59_400,
    eclLifetimeGBP: 178_200,
    provisionGBP: 59_400,
    regulatoryApproach: 'Standardised',
    riskWeight: 0.75,
    rwaGBP: 8_250_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 120,
    outstandingInrCr: 100,
    undrawnInrCr: 20,
    drawingPowerInrCr: 100,
    daysPastDue: 0,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Farm-MSE-Housing',
    securedFlag: true,
    realisableSecurityInrCr: 112,
    eadInrCr: 110,
    iracpProvisionRatePercent: 0.25,
    iracpProvisionRequiredInrCr: 0.25,
    riskWeightPercent: 75.0,
    rwaInrCr: 82.5,
  },
  {
    id: 'FAC-2025-005',
    facilityNumber: 'MER-WHL-6605',
    obligorId: 'OBL-105',
    obligorName: 'Mersey Maritime & Freight Services Ltd',
    product: 'Term Loan',
    currency: 'GBP',
    limitGBP: 60_000_000,
    drawnGBP: 55_000_000,
    undrawnGBP: 5_000_000,
    ccf: 0.50,
    originationDate: '2020-04-15',
    maturityDate: '2029-04-15',
    collateral: {
      id: 'COL-005',
      type: 'Property',
      valuationGBP: 85_000_000,
      valuationInrCr: 850,
      lastValuationDate: '2025-11-10',
      haircut: 0.15,
      realisableValueInrCr: 722.5,
    },
    dpd: 0,
    isDefaulted: false,
    pd: 0.005,
    lgd: 0.18,
    ead: 57_500_000,
    ifrs9Stage: 1,
    sicrTriggered: false,
    ecl12mGBP: 51_750,
    eclLifetimeGBP: 155_250,
    provisionGBP: 51_750,
    regulatoryApproach: 'Standardised',
    riskWeight: 0.50,
    rwaGBP: 28_750_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 600,
    outstandingInrCr: 550,
    undrawnInrCr: 50,
    drawingPowerInrCr: 550,
    daysPastDue: 0,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    securedFlag: true,
    realisableSecurityInrCr: 722.5,
    eadInrCr: 575,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 2.20,
    riskWeightPercent: 50.0,
    rwaInrCr: 287.5,
  },
  {
    id: 'FAC-2025-006',
    facilityNumber: 'HIG-DEF-7706',
    obligorId: 'OBL-106',
    obligorName: 'Highland Hospitality & Leisure Ltd',
    product: 'Overdraft',
    currency: 'GBP',
    limitGBP: 8_000_000,
    drawnGBP: 8_000_000,
    undrawnGBP: 0,
    ccf: 1.00,
    originationDate: '2019-11-01',
    maturityDate: '2024-11-01',
    collateral: {
      id: 'COL-006',
      type: 'Unsecured',
      valuationGBP: 0,
      valuationInrCr: 0,
      lastValuationDate: '2025-01-01',
      haircut: 1.00,
      realisableValueInrCr: 0,
    },
    dpd: 112,
    isDefaulted: true,
    pd: 1.00,
    lgd: 0.65,
    ead: 8_000_000,
    ifrs9Stage: 3,
    sicrTriggered: true,
    sicrReason: 'Default declared (>90 DPD overdue & liquidation notice).',
    ecl12mGBP: 5_200_000,
    eclLifetimeGBP: 5_200_000,
    provisionGBP: 5_200_000,
    regulatoryApproach: 'Standardised',
    riskWeight: 1.50,
    rwaGBP: 12_000_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 80,
    outstandingInrCr: 80,
    undrawnInrCr: 0,
    drawingPowerInrCr: 80,
    daysPastDue: 112,
    isNPA: true,
    assetQualityStatus: 'Substandard',
    smaStatus: 'SMA-2',
    exposureCategory: 'Other-Commercial',
    securedFlag: false,
    realisableSecurityInrCr: 0,
    eadInrCr: 80,
    iracpProvisionRatePercent: 25.0,
    iracpProvisionRequiredInrCr: 20.0,
    riskWeightPercent: 150.0,
    rwaInrCr: 90.0,
  },
  {
    id: 'FAC-2025-007',
    facilityNumber: 'MAN-RES-8807',
    obligorId: 'OBL-107',
    obligorName: 'Manchester Residential Developments Ltd',
    product: 'Term Loan',
    currency: 'GBP',
    limitGBP: 22_000_000,
    drawnGBP: 20_000_000,
    undrawnGBP: 2_000_000,
    ccf: 0.50,
    originationDate: '2023-05-10',
    maturityDate: '2028-05-10',
    collateral: {
      id: 'COL-007',
      type: 'Property',
      valuationGBP: 24_000_000,
      valuationInrCr: 240,
      lastValuationDate: '2025-10-01',
      haircut: 0.20,
      realisableValueInrCr: 192,
    },
    dpd: 38,
    isDefaulted: false,
    pd: 0.085,
    lgd: 0.45,
    ead: 21_000_000,
    ifrs9Stage: 2,
    sicrTriggered: true,
    sicrReason: '2-notch rating downgrade (BBB to B) and relative PD ratio > 3.0x.',
    ecl12mGBP: 803_250,
    eclLifetimeGBP: 2_409_750,
    provisionGBP: 2_409_750,
    regulatoryApproach: 'Standardised',
    riskWeight: 0.75,
    rwaGBP: 15_750_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 220,
    outstandingInrCr: 200,
    undrawnInrCr: 20,
    drawingPowerInrCr: 200,
    daysPastDue: 38,
    isNPA: false,
    assetQualityStatus: 'SMA-1',
    smaStatus: 'SMA-1',
    exposureCategory: 'CRE-Residential',
    securedFlag: true,
    realisableSecurityInrCr: 192,
    eadInrCr: 210,
    iracpProvisionRatePercent: 0.75,
    iracpProvisionRequiredInrCr: 1.50,
    riskWeightPercent: 75.0,
    rwaInrCr: 157.5,
  },
  {
    id: 'FAC-2025-008',
    facilityNumber: 'ANG-TEC-9908',
    obligorId: 'OBL-108',
    obligorName: 'Anglia Solar Technologies Ltd',
    product: 'Revolving Credit',
    currency: 'GBP',
    limitGBP: 40_000_000,
    drawnGBP: 25_000_000,
    undrawnGBP: 15_000_000,
    ccf: 0.50,
    originationDate: '2024-02-01',
    maturityDate: '2029-02-01',
    collateral: {
      id: 'COL-008',
      type: 'Cash',
      valuationGBP: 10_000_000,
      valuationInrCr: 100,
      lastValuationDate: '2025-12-01',
      haircut: 0.00,
      realisableValueInrCr: 100,
    },
    dpd: 0,
    isDefaulted: false,
    pd: 0.010,
    lgd: 0.22,
    ead: 32_500_000,
    ifrs9Stage: 1,
    sicrTriggered: false,
    ecl12mGBP: 71_500,
    eclLifetimeGBP: 214_500,
    provisionGBP: 71_500,
    regulatoryApproach: 'Standardised',
    riskWeight: 0.20,
    rwaGBP: 6_500_000,
    reportingStatus: 'Verified',

    // Fallback India fields
    sanctionedLimitInrCr: 400,
    outstandingInrCr: 250,
    undrawnInrCr: 150,
    drawingPowerInrCr: 250,
    daysPastDue: 0,
    isNPA: false,
    assetQualityStatus: 'Standard',
    smaStatus: 'Standard',
    exposureCategory: 'Other-Commercial',
    securedFlag: true,
    realisableSecurityInrCr: 100,
    eadInrCr: 325,
    iracpProvisionRatePercent: 0.40,
    iracpProvisionRequiredInrCr: 1.00,
    riskWeightPercent: 20.0,
    rwaInrCr: 65.0,
  },
];

export function getCustomerById(id: string): Obligor | undefined {
  return SYNTHETIC_OBLIGORS.find((o) => o.id === id);
}

export function getFacilityById(id: string): Facility | undefined {
  return SYNTHETIC_FACILITIES.find((f) => f.id === id);
}

export function getPortfolioTotals(facilities: Facility[] = SYNTHETIC_FACILITIES): PortfolioTotals {
  const facilityCount = facilities.length;
  const uniqueObligors = new Set(facilities.map((f) => f.obligorId));
  const obligorCount = uniqueObligors.size;

  const totalLimitGBP = facilities.reduce((sum, f) => sum + f.limitGBP, 0);
  const totalDrawnGBP = facilities.reduce((sum, f) => sum + f.drawnGBP, 0);
  const totalUndrawnGBP = facilities.reduce((sum, f) => sum + f.undrawnGBP, 0);
  const totalEadGBP = facilities.reduce((sum, f) => sum + f.ead, 0);
  const totalProvisionGBP = facilities.reduce((sum, f) => sum + f.provisionGBP, 0);
  const totalRwaGBP = facilities.reduce((sum, f) => sum + f.rwaGBP, 0);
  const attributablePillar1CapitalGBP = totalRwaGBP * 0.08;

  const stage1Count = facilities.filter((f) => f.ifrs9Stage === 1).length;
  const stage2Count = facilities.filter((f) => f.ifrs9Stage === 2).length;
  const stage3Count = facilities.filter((f) => f.ifrs9Stage === 3).length;
  const watchlistCount = facilities.filter((f) => f.sicrTriggered).length;
  const defaultCount = facilities.filter((f) => f.isDefaulted).length;

  return {
    facilityCount,
    obligorCount,
    totalLimitGBP,
    totalDrawnGBP,
    totalUndrawnGBP,
    totalEadGBP,
    totalProvisionGBP,
    totalRwaGBP,
    attributablePillar1CapitalGBP,
    stage1Count,
    stage2Count,
    stage3Count,
    watchlistCount,
    defaultCount,

    // Fallback India portfolio fields
    totalLimitInrCr: 2887.5,
    totalOutstandingInrCr: 2645.0,
    totalUndrawnInrCr: 242.5,
    totalEadInrCr: 2887.5,
    totalIracpProvisionInrCr: 74.8,
    totalRwaInrCr: 1483.1,
    attributableCapitalReqInrCr: 133.5,
    grossNpaInrCr: 80.0,
    grossNpaRatioPercent: 2.77,
    standardCount: stage1Count,
    sma0Count: 0,
    sma1Count: stage2Count,
    sma2Count: 0,
    npaCount: stage3Count,
  };
}

export function getRatingDistribution(facilities: Facility[] = SYNTHETIC_FACILITIES): Record<InternalRating, number> {
  const dist: Record<InternalRating, number> = {
    AAA: 0, AA: 0, A: 0, BBB: 0, BB: 0, B: 0, CCC: 0, D: 0,
  };

  facilities.forEach((f) => {
    const obligor = getCustomerById(f.obligorId);
    if (obligor && obligor.internalRating in dist) {
      dist[obligor.internalRating]++;
    }
  });

  return dist;
}

export function getSectorConcentration(facilities: Facility[] = SYNTHETIC_FACILITIES): Record<UKSector | string, number> {
  const dist: Record<string, number> = {};

  facilities.forEach((f) => {
    const obligor = getCustomerById(f.obligorId);
    const sector = obligor?.sector || 'Other';
    dist[sector] = (dist[sector] || 0) + f.ead;
  });

  return dist;
}
