/**
 * CREDIT RISK OS 2.0 — CASE 03: CAPITAL & REGULATORY CHANGE
 * Domain-specific configuration and dataset conforming to shared framework CaseDefinition.
 */

import {
  CaseDefinition,
  CaseMetadata,
  CaseStakeholder,
  CaseEvidence,
  ProcessNode,
  BusinessRequirement,
  BusinessRule,
  SourceToTargetMapping,
  InvestigationTask,
  CaseDefect,
  UATTestCase,
  TraceabilityChain,
  ReconciliationSummary,
  SignOffRequirement,
  GovernanceConfig,
} from '../_framework/types';

export interface RegulatoryChangeItem {
  id: string;
  topic: string;
  currentStateText: string;
  targetStateText: string;
  classification: 'CURRENT_RBI_FRAMEWORK' | 'FUTURE_PROPOSED_REGULATORY_CHANGE' | 'BANK_POLICY_SIMULATION';
  businessImpact: string;
  dataImpact: string;
  systemImpact: string;
  reportingImpact: string;
  owner: string;
  decisionStatus: 'APPROVED' | 'PROPOSED_READINESS' | 'UNDER_REVIEW';
  sourceMetadata: string;
}

export const CASE_03_METADATA: CaseMetadata = {
  id: 'CASE-003',
  code: 'CASE-2026-03',
  title: 'Capital & Regulatory Change',
  type: 'Capital Risk + Regulation + Data + Business Analysis',
  primaryDomains: [
    'RBI Basel III',
    'Credit Risk RWA',
    'Capital Adequacy',
    'Standardised Approach',
    'Exposure Classification',
    'External Ratings',
    'Credit Conversion Factors (CCF)',
    'Credit Risk Mitigation (CRM)',
    'Regulatory Change',
    'BCBS 239 Lineage',
  ],
  institution: 'Indus Apex Bank India',
  simulatedDate: '31 July 2026',
  businessOwner: 'Head of Prudential Capital Risk & Finance Controller',
  targetDeadline: '15 August 2026 (Quarter-End Capital Return Cutoff)',
  problemStatement:
    'Quarter-end Capital Reporting identified a material discrepancy between Credit Risk RWA produced by the Risk Data Mart and Finance Capital Reporting expectations. Misclassified corporate exposures, stale external ratings, unconverted off-balance sheet commitments, ineligible collateral haircuts, and stale past-due snapshots inflated Credit RWA by ₹800.0 Cr and generated a Gross Absolute Reconciliation Break of ₹2,400.0 Cr across ETL stages.',
};

export const STAKEHOLDERS: CaseStakeholder[] = [
  {
    id: 'STK-CAP-01',
    name: 'Karan Kapadia',
    title: 'Capital Risk & Prudential Risk Lead',
    department: 'Prudential Capital Risk Oversight',
    roleDescription: 'Owns regulatory capital methodology, Credit Risk RWA calculation rules, minimum CET1 (5.5%) / CRAR (9.0%) adequacy, and CCB (2.5%) buffers under Current RBI Framework.',
    keyConcern: 'Ensuring whole-bank CET1 ratio (9.00%) and CRAR (12.00%) remain above regulatory reference floors without understated or un-reconciled Credit RWA.',
    decisionsOwned: ['Regulatory RWA Calculation Methodology', 'Capital Adequacy Sign-off', 'CRAR Buffer Assessment'],
    evidenceProvided: ['EV-CAP-02 (RBI Master Circular — Prudential Norms on Capital Adequacy)'],
  },
  {
    id: 'STK-CAP-02',
    name: 'Smita Kulkarni',
    title: 'Credit Risk Policy SME',
    department: 'Credit Policy & Exposure Classification Oversight',
    roleDescription: 'Owns regulatory exposure class mapping rules, CRM collateral haircut eligibility, and past-due NPA risk weight lookups.',
    keyConcern: 'Ensuring corporate credit exposures are not incorrectly mapped to lower-risk categories or given un-verified collateral haircuts.',
    decisionsOwned: ['Exposure Class Mapping Interpretation', 'Collateral Eligibility Approval', 'NPA Risk Weight Guidelines'],
    evidenceProvided: ['EV-CAP-05 (Software Bug Incident Note — Exposure Class & Past-Due Treatment)'],
  },
  {
    id: 'STK-CAP-03',
    name: 'Nitin Saxena',
    title: 'Finance Capital Reporting Lead',
    department: 'Financial Control & Capital Accounting',
    roleDescription: 'Owns period-end balance sheet capital reconciliation, General Ledger capital reserves, and whole-bank RWA aggregation sign-offs.',
    keyConcern: 'Reconciling the ₹800.0 Cr RWA overstatement and ₹2,400.0 Cr gross absolute break before quarterly capital return filing.',
    decisionsOwned: ['Whole-Bank RWA Control Sign-off', 'Period-End Capital Reconciliation Sign-off'],
    evidenceProvided: ['EV-CAP-01 (Quarter-End Capital Reporting Discrepancy Note)'],
  },
  {
    id: 'STK-CAP-04',
    name: 'Ritu Shenoy',
    title: 'Regulatory Reporting Lead',
    department: 'Regulatory Submissions & Prudential Returns',
    roleDescription: 'Owns RBI regulatory returns publishing, capital return data quality, and prudential reporting submission packages.',
    keyConcern: 'Preventing regulatory returns from consuming stale capital calculation runs or un-reconciled exposure populations.',
    decisionsOwned: ['RBI Prudential Return Sign-off', 'Regulatory Submission Approval'],
    evidenceProvided: ['EV-CAP-06 (Regulatory Reporting Mart Run Version Audit)'],
  },
  {
    id: 'STK-CAP-05',
    name: 'Manish Goel',
    title: 'Credit Reference Data & Rating Data Owner',
    department: 'Enterprise Reference Data & Market Intelligence',
    roleDescription: 'Owns external credit rating feeds (CRISIL, ICRA, CARE), agency mapping tables, and rating effective-date freshness validation.',
    keyConcern: 'Eliminating stale external ratings (>90 days old) and 1:M duplicate rating joins that distort risk-weight assignments.',
    decisionsOwned: ['External Rating Feed Quality Standard', 'Rating Agency Mapping Specs'],
    evidenceProvided: ['EV-CAP-04 (External Rating Feed & Reference Data Lineage Spec)'],
  },
  {
    id: 'STK-CAP-06',
    name: 'Deepak Deshmukh',
    title: 'Data Engineering Lead',
    department: 'Enterprise Data Platform & Ingestion Architecture',
    roleDescription: 'Owns daily exposure data ingestion, canonical capital data mart schemas, and off-balance sheet CCF conversion pipelines.',
    keyConcern: 'Resolving failed CCF joins that omit undrawn commitment EAD from capital input staging.',
    decisionsOwned: ['Capital Data Ingestion Pipeline Specs', 'Canonical Capital Schema'],
    evidenceProvided: ['EV-CAP-03 (Off-Balance Sheet Commitment CCF Ingestion Audit)'],
  },
  {
    id: 'STK-CAP-07',
    name: 'Priya Sundaram',
    title: 'Risk Technology Lead',
    department: 'Risk Calculation Engines & Technology Architecture',
    roleDescription: 'Owns Credit RWA calculation engine software execution, Standardised Approach risk-weight tables, and run version publishing scripts.',
    keyConcern: 'Deploying versioned RWA calculation scripts that correctly evaluate CCF, CRM haircuts, and past-due provisioning rates.',
    decisionsOwned: ['RWA Calculation Engine Deployment', 'Engine API Specs'],
    evidenceProvided: ['EV-CAP-05 (Software Bug Incident Note — Exposure Class & Past-Due Treatment)'],
  },
  {
    id: 'STK-CAP-08',
    name: 'Arjun Nair',
    title: 'Solution Architect',
    department: 'Enterprise Architecture & Governance',
    roleDescription: 'Evaluates target-state system boundaries, interface contracts, BCBS 239 data lineage traceability, and BA fitness-for-purpose.',
    keyConcern: 'Ensuring end-to-end BCBS 239 data lineage allows any reported RWA figure to trace back to authoritative facility contract data.',
    decisionsOwned: ['Target State Architecture Approval', 'BCBS 239 Lineage Standard'],
    evidenceProvided: ['EV-CAP-07 (Solution Architecture BA Fitness-for-Purpose & BCBS 239 Lineage Note)'],
  },
  {
    id: 'STK-CAP-09',
    name: 'Bhavna Patel',
    title: 'QA & UAT Testing Lead',
    department: 'Quality Assurance & Business Acceptance Testing',
    roleDescription: 'Coordinates business acceptance testing, manages expected-result test packs, and verifies RWA regression evidence.',
    keyConcern: 'Verifying 100% of exposure classification boundary tests, rating freshness lookups, and whole-bank capital ratio calculations.',
    decisionsOwned: ['UAT Execution Sign-off', 'RWA Defect Remediation Verification'],
    evidenceProvided: ['EV-CAP-05 (Software Bug Incident Note — Exposure Class & Past-Due Treatment)'],
  },
  {
    id: 'STK-CAP-10',
    name: 'Learner (Lead Business Analyst)',
    title: 'Transformation Lead Business Analyst',
    department: 'Regulatory Change & Capital Delivery Programme',
    roleDescription: 'Lead BA assigned to investigate RWA discrepancies, author target requirements, design STTM, coordinate UAT, and secure sign-offs.',
    keyConcern: 'Delivering an end-to-end controlled target state with complete BCBS 239 traceability before the quarter-end reporting cutoff.',
    decisionsOwned: ['BRD Requirements Register', 'Source-to-Target Mapping (STTM)', 'Traceability Matrix (RTM)'],
    evidenceProvided: ['Business Requirements Document (BRD)', 'Requirements Traceability Matrix (RTM)'],
  },
];

export const REGULATORY_CHANGE_REGISTER: RegulatoryChangeItem[] = [
  {
    id: 'REG-CHG-01',
    topic: 'Standardised Exposure Class Classification',
    currentStateText: 'Current RBI Master Circular specifies exposure classes: Claims on Sovereigns, Claims on Banks, Claims on Corporates (100% unrated, rated AAA 20% to BB/below 150%), Regulatory Retail (75%), CRE (100%), CRE-Resi (75%), Past Due Assets (100%/150%).',
    targetStateText: 'Enforce automated rule-driven exposure class assignment from canonical facility attributes; eliminate manual override spreadsheets.',
    classification: 'CURRENT_RBI_FRAMEWORK',
    businessImpact: 'Guarantees accurate risk-weight assignment and prevents corporate exposures from misclassifying into lower RW categories.',
    dataImpact: 'Requires canonical `exposure_class` and `borrower_entity_type` fields in capital data mart.',
    systemImpact: 'Capital Engine `_engine/rbiCapital.ts` enforces strict classification lookup rules.',
    reportingImpact: 'Aligns regulatory return exposure tables with RBI prudential return schedules.',
    owner: 'Smita Kulkarni (Credit Risk Policy SME)',
    decisionStatus: 'APPROVED',
    sourceMetadata: 'RBI Master Circular - Prudential Norms on Capital Adequacy Sec 5.2',
  },
  {
    id: 'REG-CHG-02',
    topic: 'External Credit Rating Eligibility & Freshness Standard',
    currentStateText: 'Ratings from accredited rating agencies (CRISIL, ICRA, CARE, India Ratings) are eligible for risk weighting. Ratings older than 90 days from reporting date are deemed stale.',
    targetStateText: 'Data Quality gate rejects external ratings with `rating_effective_date` > 90 days old, falling back to 100% Unrated Corporate RW.',
    classification: 'CURRENT_RBI_FRAMEWORK',
    businessImpact: 'Prevents expired ratings from understating RWA requirements and eliminates audit exceptions during supervisory review.',
    dataImpact: 'Requires mandatory `rating_agency`, `external_rating`, and `rating_effective_date` fields in reference feeds.',
    systemImpact: 'Automated rating freshness check in `_engine/rbiCapital.ts`.',
    reportingImpact: 'Populates rating agency audit trail in prudential capital returns.',
    owner: 'Manish Goel (Credit Reference Data Owner)',
    decisionStatus: 'APPROVED',
    sourceMetadata: 'RBI Master Circular - Capital Adequacy Sec 6.1 (Rating Freshness)',
  },
  {
    id: 'REG-CHG-03',
    topic: 'Off-Balance Sheet Credit Conversion Factors (CCF)',
    currentStateText: 'Undrawn commitments > 1 year carry 50% CCF; commitments <= 1 year or unconditionally cancellable carry 20% or 0% CCF. Credit Equivalent Exposure = Undrawn * CCF.',
    targetStateText: 'Automated CCF conversion pipeline joining contract commitments to limit tables; Credit Equivalent Exposure added to EAD.',
    classification: 'CURRENT_RBI_FRAMEWORK',
    businessImpact: 'Ensures off-balance sheet commitments generate required capital coverage without omission.',
    dataImpact: 'Requires `off_balance_sheet_commitment`, `commitment_tenor_months`, and `ccf` in capital mart.',
    systemImpact: 'ETL Ingestion pipeline `job_ingest_commitments` calculates EAD before feeding RWA engine.',
    reportingImpact: 'Populates off-balance sheet credit equivalent schedules in RBI returns.',
    owner: 'Deepak Deshmukh (Data Engineering Lead)',
    decisionStatus: 'APPROVED',
    sourceMetadata: 'RBI Master Circular - Capital Adequacy Sec 7.3 (CCF Standard)',
  },
  {
    id: 'REG-CHG-04',
    topic: 'Credit Risk Mitigation (CRM) Comprehensive Approach Haircuts',
    currentStateText: 'Financial collateral (cash, fixed deposits, gold, sovereign securities) reduces exposure via Comprehensive Approach haircuts. Eligible CRM requires verified valuation timestamp and legally enforceable security.',
    targetStateText: 'CRM Haircut engine evaluates `eligible_crm_flag` and `valuation_date`; ineligible collateral benefit is rejected.',
    classification: 'CURRENT_RBI_FRAMEWORK',
    businessImpact: 'Prevents unverified or ineligible collateral from understating Credit RWA.',
    dataImpact: 'Requires `collateral_type`, `collateral_value`, `valuation_date`, and `eligible_crm_flag`.',
    systemImpact: 'Engine computes `adjusted_exposure = max(0, EAD - collateral * (1 - haircut))`.',
    reportingImpact: 'Populates CRM haircut schedule in regulatory capital filings.',
    owner: 'Smita Kulkarni (Credit Risk Policy SME)',
    decisionStatus: 'APPROVED',
    sourceMetadata: 'RBI Master Circular - Capital Adequacy Sec 8.4 (CRM Comprehensive Approach)',
  },
  {
    id: 'REG-CHG-05',
    topic: 'Basel Finalisation Readiness — Proposed Granular Categories',
    currentStateText: 'Proposed international Basel finalisation framework introduces more granular corporate exposure categories (e.g. Investment Grade 65%, Speculative 135%, Real Estate Income Producing 110%).',
    targetStateText: 'Readiness Assessment: Assess data gap readiness for future granular classification without altering current RBI production risk weights.',
    classification: 'FUTURE_PROPOSED_REGULATORY_CHANGE',
    businessImpact: 'Prepares bank data model and technology architecture for future regulatory migration.',
    dataImpact: 'Identifies missing granular data attributes (`is_investment_grade`, `is_income_producing_cre`).',
    systemImpact: 'Parallel pro-forma calculation capability in Target Architecture.',
    reportingImpact: 'Pro-forma readiness impact reporting for ALCO & Steering Committee.',
    owner: 'Karan Kapadia (Capital Risk Lead)',
    decisionStatus: 'PROPOSED_READINESS',
    sourceMetadata: 'Basel Finalisation Readiness Assessment Document (Simulation)',
  },
  {
    id: 'REG-CHG-06',
    topic: 'Automated Risk-to-Capital Multi-Stage Reconciliation & Version Control',
    classification: 'BANK_POLICY_SIMULATION',
    currentStateText: 'Manual spreadsheet reconciliation between Risk Warehouse RWA and Finance Capital GL filings, allowing compensating errors.',
    targetStateText: 'Automated 4-stage balance, record count, and run version lock reconciliation across Source → Staging → Output → Regulatory Reporting Mart.',
    businessImpact: 'Guarantees zero unexplained RWA variance and eliminates compensating netting errors.',
    dataImpact: 'Requires immutable `run_version_id` on every published capital record.',
    systemImpact: 'Reconciliation Engine `sp_capital_multi_stage_rec.sql` executes pre-close checks.',
    reportingImpact: 'Downstream Regulatory Reporting Mart locks to approved calculation run version.',
    owner: 'Nitin Saxena (Finance Capital Reporting Lead)',
    decisionStatus: 'APPROVED',
    sourceMetadata: 'Bank Internal Financial Control Policy (Simulation)',
  },
];

export const EVIDENCE_PACK: CaseEvidence[] = [
  {
    id: 'EV-CAP-01',
    code: 'EVID-REC-01',
    title: 'Quarter-End Capital Reporting Discrepancy Note',
    type: 'Memo',
    summary: 'Identifies a ₹800.0 Cr RWA overstatement and ₹2,400.0 Cr gross absolute break across ETL staging pipelines as of 31 July 2026.',
    providedBy: 'Nitin Saxena (Finance Capital Reporting Lead)',
    fullText:
      'During the 31 July 2026 quarter-end close, Finance identified that the Risk Data Mart produced ₹3,236.0 Cr Credit RWA for the case portfolio, whereas the expected target RWA was ₹2,436.0 Cr (₹800.0 Cr overstatement). Independent stage transitions revealed compensating errors: Source → Staging omitted ₹800.0 Cr off-balance-sheet commitment (-₹400 Cr EAD / -₹400 Cr RWA), Staging → Engine Output double-counted infrastructure rating join (+₹800 Cr RWA), and Engine Output → Regulatory Reporting dropped ₹800.0 Cr due to stale run consumption (`RUN-20260730-01`). Net Difference: +₹800.0 Cr. Gross Absolute Reconciliation Break: ₹2,400.0 Cr. Whole-Bank Capital Baseline: CET1 Ratio 9.00% (min 8.00%), CRAR 12.00% (min 11.50%).',
    keyInsights: [
      'Portfolio Credit RWA overstated by ₹800.0 Cr (₹3,236 Cr vs target ₹2,436 Cr)',
      'Gross Absolute Reconciliation Break = ₹2,400.0 Cr across ETL stages',
      'Whole-Bank CET1 Ratio 9.00% remains above 8.00% minimum reference',
      'Whole-Bank CRAR 12.00% remains above 11.50% minimum reference',
    ],
  },
  {
    id: 'EV-CAP-02',
    code: 'EVID-POL-02',
    title: 'RBI Master Circular — Prudential Norms on Capital Adequacy',
    type: 'Policy Doc',
    summary: 'Defines Standardised Approach risk weights, CCF conversion factors, external rating eligibility, and CRM collateral haircuts under Current RBI Framework.',
    providedBy: 'Karan Kapadia (Capital Risk Lead)',
    fullText:
      'Current RBI Capital Standards:\n1. Minimum CET1: 5.5%, CCB: 2.5%, Total CET1+CCB: 8.0%.\n2. Minimum Tier 1: 7.0%, Minimum Total Capital (CRAR): 9.0%, Total Capital+CCB: 11.5%.\n3. Exposure Risk Weights: Corporate AAA 20%, AA 30%, A 50%, BBB 100%, Unrated 100%. Claims on PSE 20%. Claims on Banks 20% to 50%.\n4. Off-Balance Sheet CCF: Commitments > 1 year 50% CCF; <= 1 year 20% CCF.\n5. Ratings > 90 days old from reporting cutoff are deemed STALE and fall back to 100% Unrated Corporate RW.\n6. Substandard NPA past-due assets receive 100% RW if specific provisions >= 20%; 150% RW if specific provisions < 20%.',
    keyInsights: [
      'Current RBI CET1+CCB reference floor = 8.0%, Total Capital+CCB = 11.5%',
      'Stale external ratings (>90 days) fall back to 100% Unrated Corporate RW',
      'Off-balance sheet commitments > 1 year require 50% CCF conversion',
    ],
  },
  {
    id: 'EV-CAP-03',
    code: 'EVID-DAT-03',
    title: 'Off-Balance Sheet Commitment CCF Ingestion Audit',
    type: 'Data Extract',
    summary: 'Reveals ₹800.0 Cr undrawn commitments excluded from credit-equivalent exposure due to failed CCF join.',
    providedBy: 'Deepak Deshmukh (Data Engineering Lead)',
    fullText:
      'ETL Ingestion Audit:\nBatch job `job_ingest_commitments` failed to join `LIMITS_COMMITMENTS` to `CBS_CREDIT_EXPOSURE` because commitment facility numbers carried prefix `LMT-` while loan contract numbers carried `FAC-`. Result: ₹800.0 Cr of undrawn corporate commitments (50% CCF = ₹400.0 Cr EAD) were omitted from capital staging, understating staging EAD by ₹400.0 Cr.',
    keyInsights: [
      'Prefix mismatch (`LMT-` vs `FAC-`) caused CCF join failure',
      '₹800.0 Cr undrawn commitments (₹400.0 Cr EAD) omitted from capital staging',
    ],
  },
  {
    id: 'EV-CAP-04',
    code: 'EVID-MAP-04',
    title: 'External Rating Feed & Reference Data Lineage Spec',
    type: 'Data Extract',
    summary: 'Reveals stale 2-year old rating CARE A+ applied to HYD-INF-9902 and 1:M duplicate rating join.',
    providedBy: 'Manish Goel (Credit Rating Data Owner)',
    fullText:
      'Rating Feed Lineage Audit:\n1. Rating record for facility HYD-INF-9902 showed `rating_effective_date = 15-May-2024` (807 days old). Legacy engine applied 50% A-rated RW instead of falling back to 100% Unrated Corporate RW.\n2. Rating reference table `EXTERNAL_RATING_FEED` contained 2 active rows for obligor HYD-INF-9902 (legacy agency + updated agency), generating 2 duplicate facility rows in engine output and inflating output RWA by ₹800.0 Cr.',
    keyInsights: [
      'Stale rating (807 days old) improperly applied 50% RW instead of 100% Unrated RW',
      '1:M duplicate rating join double-counted facility HYD-INF-9902 (+₹800.0 Cr RWA)',
    ],
  },
  {
    id: 'EV-CAP-05',
    code: 'EVID-BUG-05',
    title: 'Software Bug Incident Note — Exposure Class & Past-Due Treatment',
    type: 'Defect Note',
    summary: 'Technical bug report detailing corporate misclassification as PSE and past-due snapshot lag.',
    providedBy: 'Priya Sundaram (Risk Technology Lead)',
    fullText:
      'Defect Log DEF-CAP-001 & DEF-CAP-004 & DEF-CAP-005:\n1. In `rbi_capital_engine.c`, condition `if (ownership_type == "SEMI_GOVT") exposure_class = "PSE"` misclassified corporate loan MUM-CRE-8801 as Public Sector Entity (applied 20% RW instead of 100% Corporate RW).\n2. Collateral haircut engine applied 100% collateral credit (₹80.0 Cr) to DEL-MED-7706 despite `valuation_date = NULL`.\n3. Past-due engine ingested prior-day snapshot, classifying 91 DPD Substandard NPA facility DEL-MED-7706 as 60 DPD Performing (applied 100% Standard RW instead of 150% Past Due RW).',
    keyInsights: [
      'MUM-CRE-8801 misclassified as PSE (20% RW instead of 100% Corporate RW)',
      'Unverified collateral haircut applied without valuation timestamp',
      'DEL-MED-7706 (91 DPD) applied 100% Standard RW instead of 150% Past Due RW',
    ],
  },
  {
    id: 'EV-CAP-06',
    code: 'EVID-EXT-06',
    title: 'Regulatory Reporting Mart Run Version Audit',
    type: 'Minutes',
    summary: 'Audit report showing Regulatory Reporting Mart consumed yesterday’s stale run version.',
    providedBy: 'Ritu Shenoy (Regulatory Reporting Lead)',
    fullText:
      'Regulatory Reporting Audit:\nPrudential return publication script `sp_build_rbi_return.sql` fetched capital tables from `CAPITAL_ENGINE_OUTPUT` using hardcoded query `WHERE run_date = CURRENT_DATE() - 1`. Result: Downstream RBI returns consumed yesterday’s stale run (`RUN-20260730-01`), ignoring today’s capital calculation run (`RUN-20260731-01`).',
    keyInsights: [
      'Downstream RBI returns consumed yesterday’s stale run version',
      'Fix requires explicit `run_version_id` parameter passing',
    ],
  },
  {
    id: 'EV-CAP-07',
    code: 'EVID-ARC-07',
    title: 'Solution Architecture BA Fitness-for-Purpose & BCBS 239 Lineage Note',
    type: 'Policy Doc',
    summary: 'Evaluates target-state system boundaries, interface contracts, BCBS 239 data lineage traceability, and BA fitness-for-purpose.',
    providedBy: 'Arjun Nair (Solution Architect)',
    fullText:
      'Target Architecture & BCBS 239 Lineage Results:\n1. Authoritative Exposure Source: Core Credit Exposure table confirmed as sole source.\n2. Canonical Facility Grain: (obligor_id + facility_id + as_of_date).\n3. BCBS 239 Lineage Traceability: 100% end-to-end traceability from Reported Credit RWA → Portfolio Aggregate → Facility RWA → Risk Weight → Exposure Class → CCF / CRM → Source Exposure → Source System.\n4. Run Versioning: Immutable run_version_id tags all published RWA outputs.\n5. Exception Handling: Invalid attributes route to operational exception queue.',
    keyInsights: [
      'Target architecture passes all 7 BA fitness-for-purpose criteria',
      '100% BCBS 239 data lineage traceability verified from return to contract',
    ],
  },
];

export const CURRENT_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Core Credit & Limits Sources',
    owner: 'Data Engineering Lead (Deepak Deshmukh)',
    desc: 'Captures Core Banking credit balances and limits commitments. Ingestion batch triggers before EOD clearing.',
    breakPoint: 'Prefix mismatch: `LMT-` vs `FAC-` prefix causes CCF join failure (omits ₹800 Cr commitment / ₹400 Cr EAD).',
  },
  {
    step: '02',
    title: 'External Rating Feed & Reference Data',
    owner: 'Credit Rating Data Owner (Manish Goel)',
    desc: 'Ingests external rating agency feeds to assign credit ratings to corporate exposures.',
    breakPoint: 'Stale rating & 1:M duplicate join: Applies 807-day old rating and duplicates HYD-INF-9902 (+₹800 Cr RWA).',
  },
  {
    step: '03',
    title: 'Exposure Classification & CRM Haircut',
    owner: 'Credit Risk Policy SME (Smita Kulkarni)',
    desc: 'Assigns regulatory exposure categories and computes collateral haircut adjustments.',
    breakPoint: 'Misclassification & Unverified Haircut: Corporate MUM-CRE-8801 misclassified as 20% PSE; unverified collateral applied.',
  },
  {
    step: '04',
    title: 'Credit RWA Calculation Engine',
    owner: 'Risk Technology Lead (Priya Sundaram)',
    desc: 'Executes Standardised Approach risk-weight lookups and computes Credit RWA and capital requirements.',
    breakPoint: 'Past-Due Lag: Prior-day snapshot applies 100% Standard RW to 91 DPD Substandard NPA facility DEL-MED-7706.',
  },
  {
    step: '05',
    title: 'Finance Capital Control Aggregation',
    owner: 'Finance Capital Lead (Nitin Saxena)',
    desc: 'Aggregates facility-level RWA into whole-bank capital ratios (CET1 9.00%, CRAR 12.00%).',
    breakPoint: 'Compensating Netting: Net +₹800 Cr difference masks ₹2,400 Cr Gross Absolute Reconciliation Break.',
  },
  {
    step: '06',
    title: 'Regulatory Reporting Mart Publication',
    owner: 'Regulatory Reporting Lead (Ritu Shenoy)',
    desc: 'Publishes capital adequacy returns to RBI regulatory reporting schedules.',
    breakPoint: 'Stale Version Consumption: Downstream script fetches yesterday’s stale run (`RUN-20260730-01`).',
  },
];

export const TARGET_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Authoritative Credit & Limits Ingestion',
    owner: 'Data Engineering Lead (Deepak Deshmukh)',
    desc: 'Captures Core Banking credit balances and limits commitments post EOD clearing with composite key mapping.',
    controlPoint: 'Snapshot Control: Ingestion validates EOD clearing and standardizes facility keys (`FAC-`).',
  },
  {
    step: '02',
    title: 'Canonical Capital Mart & Rating Freshness Gate',
    owner: 'Credit Rating Data Owner (Manish Goel)',
    desc: 'Ingests external rating agency feeds and validates rating effective dates (<90 days old).',
    controlPoint: 'Rating Freshness Gate: Stale ratings (>90 days) fall back to 100% Unrated Corporate RW; 1:M joins rejected.',
  },
  {
    step: '03',
    title: 'Automated Classification & CRM Haircut Engine',
    owner: 'Credit Risk Policy SME (Smita Kulkarni)',
    desc: 'Executes rule-driven exposure classification and computes Comprehensive Approach CRM haircuts with verified metadata.',
    controlPoint: 'CRM Eligibility Gate: Rejects unverified collateral haircuts; enforces 100% Corporate RW on MUM-CRE-8801.',
  },
  {
    step: '04',
    title: 'Versioned Credit RWA Engine Execution',
    owner: 'Risk Technology Lead (Priya Sundaram)',
    desc: 'Calculates EAD = Drawn + Undrawn * CCF; Credit RWA = EAD * Risk Weight; Capital Req = RWA * 9.00%.',
    controlPoint: 'Run Versioning: Tag every published record with immutable `run_version_id` (`RUN-20260731-01`).',
  },
  {
    step: '05',
    title: 'Multi-Stage RWA & Record Reconciliation',
    owner: 'Finance Capital Lead (Nitin Saxena)',
    desc: 'Executes 4-stage automated balance, record count, EAD, RWA, and run version lock reconciliation.',
    controlPoint: 'Multi-Stage Balance Control: Reconciles target portfolio RWA to exact ₹2,436.0 Cr with zero gross break.',
  },
  {
    step: '06',
    title: 'Finance GL & Regulatory Reporting Approved Publication',
    owner: 'Regulatory Reporting Lead (Ritu Shenoy)',
    desc: 'Publishes approved capital run version directly to Finance GL and RBI prudential capital returns.',
    controlPoint: 'Downstream Version Lock: Regulatory Reporting Mart locks to approved `RUN-20260731-01`.',
  },
];

export const BUSINESS_REQUIREMENTS: BusinessRequirement[] = [
  {
    id: 'REQ-CAP-001',
    title: 'Authoritative Credit Exposure Ingestion',
    requirementText: 'The ingestion pipeline shall capture Core Banking credit balances post EOD clearing completion at 23:59:59 to ensure 100% of active facilities are ingested into capital staging.',
    owner: 'Nitin Saxena (Finance Capital Lead)',
    regulatoryDriver: 'BCBS 239 Data Completeness & Timeliness Principle 6',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Staging drawn balance matches Core Banking GL credit balance exactly (₹2,645.0 Cr) with zero timing omission.',
    linkedRuleId: 'RULE-CAP-01',
    linkedMappingId: 'MAP-CAP-01',
    linkedTestId: 'UAT-CAP-001',
  },
  {
    id: 'REQ-CAP-002',
    title: 'On/Off-Balance Sheet Exposure Distinction',
    requirementText: 'The system shall maintain explicit separation between On-Balance Sheet Drawn Amount and Off-Balance Sheet Undrawn Commitment.',
    owner: 'Karan Kapadia (Capital Risk Lead)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 7.1',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'On-balance drawn balance (₹2,645.0 Cr) and off-balance commitment (₹800.0 Cr) are stored as distinct fields in capital mart.',
    linkedRuleId: 'RULE-CAP-02',
    linkedMappingId: 'MAP-CAP-02',
    linkedTestId: 'UAT-CAP-002',
  },
  {
    id: 'REQ-CAP-003',
    title: 'Off-Balance Sheet CCF Conversion Pipeline',
    requirementText: 'The ETL pipeline shall convert off-balance sheet commitments to Credit Equivalent Exposure (EAD) using applicable CCF factors (50% for commitments > 1 year).',
    owner: 'Deepak Deshmukh (Data Engineering Lead)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 7.3',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Undrawn commitment ₹800.0 Cr with 50% CCF generates exact ₹400.0 Cr EAD add-on, bringing Total Portfolio EAD to ₹3,045.0 Cr.',
    linkedRuleId: 'RULE-CAP-02',
    linkedMappingId: 'MAP-CAP-04',
    linkedTestId: 'UAT-CAP-003',
  },
  {
    id: 'REQ-CAP-004',
    title: 'External Rating Freshness & Stale Rating Fallback',
    requirementText: 'The data quality gate shall reject external ratings with effective date > 90 days old from reporting cutoff, falling back to 100% Unrated Corporate RW.',
    owner: 'Manish Goel (Credit Rating Data Owner)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 6.1',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Stale rating CARE A+ (807 days old) for HYD-INF-9902 is rejected; facility receives 100% Unrated Corporate RW.',
    linkedRuleId: 'RULE-CAP-03',
    linkedMappingId: 'MAP-CAP-06',
    linkedTestId: 'UAT-CAP-004',
  },
  {
    id: 'REQ-CAP-005',
    title: 'CRM Comprehensive Approach Haircut Eligibility',
    requirementText: 'The CRM engine shall apply collateral haircuts only when verified valuation metadata (`valuation_date`, `eligible_crm_flag`) is present.',
    owner: 'Smita Kulkarni (Credit Risk Policy SME)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 8.4',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Unverified collateral (missing valuation date) for DEL-MED-7706 is rejected; zero collateral haircut applied.',
    linkedRuleId: 'RULE-CAP-05',
    linkedMappingId: 'MAP-CAP-08',
    linkedTestId: 'UAT-CAP-005',
  },
  {
    id: 'REQ-CAP-006',
    title: 'Past-Due NPA Exposure Risk Weight Lookup',
    requirementText: 'The past-due engine shall evaluate current asset quality status and specific provision coverage to assign past-due risk weights (150% for Substandard NPA with provision < 20%).',
    owner: 'Smita Kulkarni (Credit Risk Policy SME)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 5.8',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Facility DEL-MED-7706 (91 DPD Substandard NPA, 15% provision) receives 150% Past Due RW.',
    linkedRuleId: 'RULE-CAP-06',
    linkedMappingId: 'MAP-CAP-09',
    linkedTestId: 'UAT-CAP-006',
  },
  {
    id: 'REQ-CAP-007',
    title: 'Standardised Exposure Class Assignment Rules',
    requirementText: 'The classification engine shall map every facility to an approved regulatory exposure class based on canonical borrower entity attributes.',
    owner: 'Smita Kulkarni (Credit Risk Policy SME)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 5.2',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Corporate facility MUM-CRE-8801 is assigned Corporate exposure class (100% RW); zero misclassification as 20% PSE.',
    linkedRuleId: 'RULE-CAP-01',
    linkedMappingId: 'MAP-CAP-02',
    linkedTestId: 'UAT-CAP-007',
  },
  {
    id: 'REQ-CAP-008',
    title: 'Risk Weight Lookup Rules & Deduplication',
    requirementText: 'The engine shall look up applicable risk weights using Exposure Class + Fresh Rating + Past Due Status with composite key deduplication.',
    owner: 'Priya Sundaram (Risk Technology Lead)',
    regulatoryDriver: 'RBI Master Circular - Capital Adequacy Sec 5.1',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Zero duplicate rating join rows; total priced EAD equals ₹3,045.0 Cr; target portfolio RWA equals ₹2,436.0 Cr.',
    linkedRuleId: 'RULE-CAP-04',
    linkedMappingId: 'MAP-CAP-10',
    linkedTestId: 'UAT-CAP-008',
  },
  {
    id: 'REQ-CAP-009',
    title: 'Calculation Component Transparency & Capital Requirement',
    requirementText: 'Every output record shall store explicit components: Drawn, Undrawn, CCF, EAD, CRM Haircut, Risk Weight, Credit RWA, and Capital Requirement (RWA * 9.00%).',
    owner: 'Karan Kapadia (Capital Risk Lead)',
    regulatoryDriver: 'BCBS 239 Transparency & Auditability Principle 8',
    priority: 'MEDIUM',
    status: 'Approved',
    acceptanceCriteria: 'Output record explicitly displays EAD ₹450 Cr * 100% RW = ₹450 Cr RWA -> ₹40.5 Cr Capital Requirement.',
    linkedRuleId: 'RULE-CAP-06',
    linkedMappingId: 'MAP-CAP-11',
    linkedTestId: 'UAT-CAP-009',
  },
  {
    id: 'REQ-CAP-010',
    title: 'Immutable Run Version Tagging',
    requirementText: 'The capital calculation engine shall tag every output record with an immutable `run_version_id` (e.g. `RUN-20260731-01`).',
    owner: 'Priya Sundaram (Risk Technology Lead)',
    regulatoryDriver: 'Bank Auditability Governance Standard',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: '100% of output records populate valid `run_version_id`; re-runs create distinct new version IDs.',
    linkedRuleId: 'RULE-CAP-08',
    linkedMappingId: 'MAP-CAP-12',
    linkedTestId: 'UAT-CAP-010',
  },
  {
    id: 'REQ-CAP-011',
    title: 'Downstream Regulatory Reporting Version Lock',
    requirementText: 'Downstream Regulatory Reporting extraction scripts shall parameterize query filtering on approved `run_version_id` to prevent ingestion of stale runs.',
    owner: 'Ritu Shenoy (Regulatory Reporting Lead)',
    regulatoryDriver: 'BCBS 239 Reporting Integrity Principle 10',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Downstream return fetches exact approved run `RUN-20260731-01` with zero stale run consumption.',
    linkedRuleId: 'RULE-CAP-08',
    linkedMappingId: 'MAP-CAP-14',
    linkedTestId: 'UAT-CAP-011',
  },
  {
    id: 'REQ-CAP-012',
    title: 'Whole-Bank Capital Ratio Reconciliation',
    requirementText: 'The system shall reconcile whole-bank CET1 Ratio (9.00%) and CRAR (12.00%) using Whole-Bank Total RWA (₹20,000.0 Cr) as denominator.',
    owner: 'Nitin Saxena (Finance Capital Lead)',
    regulatoryDriver: 'RBI Prudential Capital Reporting Standard',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Whole-bank CET1 Ratio = ₹1,800 Cr / ₹20,000 Cr = 9.00%; CRAR = ₹2,400 Cr / ₹20,000 Cr = 12.00%; case portfolio RWA is a component of Total RWA.',
    linkedRuleId: 'RULE-CAP-09',
    linkedMappingId: 'MAP-CAP-13',
    linkedTestId: 'UAT-CAP-012',
  },
  {
    id: 'REQ-CAP-013',
    title: 'BCBS 239 End-to-End Lineage Traceability',
    requirementText: 'The system shall maintain 100% end-to-end data lineage from Reported Credit RWA → Portfolio Aggregate → Facility RWA → Risk Weight → Exposure Class → CCF/CRM → Source Exposure.',
    owner: 'Arjun Nair (Solution Architect)',
    regulatoryDriver: 'BCBS 239 Risk Data Aggregation Principle 3',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Every reported RWA figure can be traced back to authoritative facility contract data.',
    linkedRuleId: 'RULE-CAP-06',
    linkedMappingId: 'MAP-CAP-11',
    linkedTestId: 'UAT-CAP-013',
  },
  {
    id: 'REQ-CAP-014',
    title: 'BAU Operational Rerun Reproducibility',
    requirementText: 'The system shall provide operational rerun controls allowing BAU Operations to re-execute runs with identical inputs and produce 100% reproducible RWA outputs.',
    owner: 'Nitin Saxena (Finance Capital Lead)',
    regulatoryDriver: 'Operational Risk & Production Continuity Mandate',
    priority: 'MEDIUM',
    status: 'Approved',
    acceptanceCriteria: 'Rerun of `RUN-20260731-01` produces identical 100% match on RWA and capital requirements.',
    linkedRuleId: 'RULE-CAP-08',
    linkedMappingId: 'MAP-CAP-12',
    linkedTestId: 'UAT-CAP-014',
  },
];

export const BUSINESS_RULES: BusinessRule[] = [
  { id: 'RULE-CAP-01', ruleCode: 'RULE-CAP-01', category: 'Capital', condition: 'BorrowerEntityType == "CORPORATE"', outputClassification: 'Corporate Exposure Class (100% Unrated RW)', provisionRatePercent: 0.0, reasonCode: 'CAP_EXP_CORPORATE_100', priority: 1 },
  { id: 'RULE-CAP-02', ruleCode: 'RULE-CAP-02', category: 'Capital', condition: 'OffBalanceSheetCommitment > 0 AND Tenor > 12M', outputClassification: '50% CCF Credit Equivalent Conversion', provisionRatePercent: 0.0, reasonCode: 'CAP_CCF_50_PERCENT', priority: 2 },
  { id: 'RULE-CAP-03', ruleCode: 'RULE-CAP-03', category: 'Data Quality', condition: 'DATEDIFF(day, RatingEffectiveDate, AsOfDate) > 90', outputClassification: 'Stale Rating Fallback (100% Unrated RW)', provisionRatePercent: 0.0, reasonCode: 'CAP_RATING_STALE_FALLBACK', priority: 3 },
  { id: 'RULE-CAP-04', ruleCode: 'RULE-CAP-04', category: 'Capital', condition: 'Count(obligor_id + facility_id + as_of_date) > 1', outputClassification: 'Deduplicated Record', provisionRatePercent: 0.0, reasonCode: 'CAP_DQ_DEDUPLICATED', priority: 4 },
  { id: 'RULE-CAP-05', ruleCode: 'RULE-CAP-05', category: 'Capital', condition: 'EligibleCrmFlag == true AND ValuationDate IS NOT NULL', outputClassification: 'Eligible CRM Comprehensive Haircut Applied', provisionRatePercent: 0.0, reasonCode: 'CAP_CRM_HAIRCUT_ELIGIBLE', priority: 5 },
  { id: 'RULE-CAP-06', ruleCode: 'RULE-CAP-06', category: 'Capital', condition: 'AssetQualityStatus == "Substandard" AND ProvisionPercent < 20.0', outputClassification: '150% Past Due Asset Risk Weight', provisionRatePercent: 0.0, reasonCode: 'CAP_PAST_DUE_RW_150', priority: 6 },
  { id: 'RULE-CAP-07', ruleCode: 'RULE-CAP-07', category: 'Capital', condition: 'CreditRWA = EAD * RiskWeight', outputClassification: 'Credit RWA Derived', provisionRatePercent: 0.0, reasonCode: 'CAP_RWA_DERIVED', priority: 7 },
  { id: 'RULE-CAP-08', ruleCode: 'RULE-CAP-08', category: 'Override', condition: 'EngineOutputPublished == true', outputClassification: 'Immutable Run Version Tag', provisionRatePercent: 0.0, reasonCode: 'CAP_RUN_VERSION_TAGGED', priority: 8 },
  { id: 'RULE-CAP-09', ruleCode: 'RULE-CAP-09', category: 'Capital', condition: 'CET1Ratio = WholeBankCET1 / WholeBankTotalRWA', outputClassification: 'Whole-Bank CET1 Ratio Derived (9.00%)', provisionRatePercent: 0.0, reasonCode: 'CAP_CET1_RATIO_DERIVED', priority: 9 },
  { id: 'RULE-CAP-10', ruleCode: 'RULE-CAP-10', category: 'Reconciliation', condition: 'DownstreamRunVersion == ApprovedRunVersion', outputClassification: 'Downstream Version Lock Verified', provisionRatePercent: 0.0, reasonCode: 'CAP_DOWNSTREAM_VERSION_LOCKED', priority: 10 },
];

export const SOURCE_TARGET_MAPPINGS: SourceToTargetMapping[] = [
  {
    id: 'MAP-CAP-01',
    sourceSystem: 'CBS_CREDIT_EXPOSURE',
    sourceTable: 'tbl_credit_exposure',
    sourceColumn: 'drawn_amount',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'FILTER EOD_CLEARING_STATUS = "COMPLETED"; MAP to on_balance_sheet_amount',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'on_balance_sheet_amount',
    nullRule: 'Reject record if null',
    effectiveDateRule: 'Snapshot as at 23:59:59',
    dqRule: 'drawn_amount >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-02',
    sourceSystem: 'CBS_CREDIT_EXPOSURE',
    sourceTable: 'tbl_credit_exposure',
    sourceColumn: 'borrower_entity_type',
    dataType: 'VARCHAR(30)',
    grain: 'Facility Level',
    transformationLogic: 'MAP borrower_entity_type to exposure_class (Corporate, Sovereign, Bank, Retail)',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'exposure_class',
    nullRule: 'Default to Corporate if null',
    effectiveDateRule: 'Active Contract Status',
    dqRule: 'IN ("Corporate", "Sovereign", "Bank", "Regulatory-Retail", "CRE")',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-03',
    sourceSystem: 'LIMITS_COMMITMENTS',
    sourceTable: 'tbl_limit_master',
    sourceColumn: 'undrawn_commitment_bal',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'JOIN CBS_CREDIT_EXPOSURE ON obligor_id AND facility_id (Standardize FAC- prefix)',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'off_balance_sheet_commitment',
    nullRule: 'Default to 0.00 if null',
    effectiveDateRule: 'Approved Limit Snapshot',
    dqRule: 'undrawn_commitment_bal >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-04',
    sourceSystem: 'LIMITS_COMMITMENTS',
    sourceTable: 'tbl_limit_master',
    sourceColumn: 'commitment_tenor_months',
    dataType: 'INTEGER',
    grain: 'Facility Level',
    transformationLogic: 'CASE WHEN commitment_tenor_months > 12 THEN 0.50 ELSE 0.20 END',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'ccf',
    nullRule: 'Default to 0.50 for Corporate',
    effectiveDateRule: 'Contractual Commitment Term',
    dqRule: 'ccf IN (0.00, 0.20, 0.50, 1.00)',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-05',
    sourceSystem: 'CREDIT_RWA_STAGE',
    sourceTable: 'tbl_rwa_stage',
    sourceColumn: 'off_balance_sheet_commitment',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'on_balance_sheet_amount + (off_balance_sheet_commitment * ccf)',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'credit_equivalent_amount',
    nullRule: 'Must derive non-null EAD',
    effectiveDateRule: 'Pricing Calculation Date',
    dqRule: 'credit_equivalent_amount >= on_balance_sheet_amount',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-06',
    sourceSystem: 'EXTERNAL_RATING_FEED',
    sourceTable: 'tbl_external_rating',
    sourceColumn: 'rating_effective_date',
    dataType: 'DATE',
    grain: 'Obligor Level',
    transformationLogic: 'IF DATEDIFF(day, rating_effective_date, as_of_date) <= 90 THEN external_rating ELSE "UNRATED"',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'validated_external_rating',
    nullRule: 'Default to UNRATED if null or stale',
    effectiveDateRule: 'Rating Agency Publication Date',
    dqRule: 'rating_effective_date <= as_of_date',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-07',
    sourceSystem: 'COLLATERAL_REGISTER',
    sourceTable: 'tbl_collateral_master',
    sourceColumn: 'eligible_crm_flag',
    dataType: 'BOOLEAN',
    grain: 'Collateral Asset Level',
    transformationLogic: 'IF eligible_crm_flag = true AND valuation_date IS NOT NULL THEN collateral_value ELSE 0.00',
    targetTable: 'CREDIT_RWA_STAGE',
    targetField: 'eligible_collateral_value',
    nullRule: 'Default to 0.00 if null or unverified',
    effectiveDateRule: 'Approved Valuation Date',
    dqRule: 'eligible_collateral_value >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-08',
    sourceSystem: 'CREDIT_RWA_STAGE',
    sourceTable: 'tbl_rwa_stage',
    sourceColumn: 'eligible_collateral_value',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'MAX(0, credit_equivalent_amount - (eligible_collateral_value * (1 - crm_haircut)))',
    targetTable: 'CAPITAL_ENGINE_OUTPUT',
    targetField: 'net_adjusted_ead',
    nullRule: 'Must compute non-null EAD',
    effectiveDateRule: 'Pricing Calculation Date',
    dqRule: 'net_adjusted_ead >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-09',
    sourceSystem: 'ASSET_QUALITY_MART',
    sourceTable: 'tbl_asset_quality_mart',
    sourceColumn: 'days_past_due',
    dataType: 'INTEGER',
    grain: 'Facility Level',
    transformationLogic: 'LOOKUP RBI_PAST_DUE_RW WHERE days_past_due AND specific_provision_percent',
    targetTable: 'CAPITAL_ENGINE_OUTPUT',
    targetField: 'past_due_risk_weight',
    nullRule: 'Default to Standard RW if DPD <= 90',
    effectiveDateRule: 'Snapshot as at EOD 23:59:59',
    dqRule: 'days_past_due >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-10',
    sourceSystem: 'CAPITAL_REFERENCE_DATA',
    sourceTable: 'tbl_rbi_risk_weights',
    sourceColumn: 'risk_weight_percent',
    dataType: 'NUMERIC(5,2)',
    grain: 'Exposure Class & Rating Level',
    transformationLogic: 'LOOKUP RBI_RISK_WEIGHTS ON exposure_class AND validated_external_rating AND past_due_status',
    targetTable: 'CAPITAL_ENGINE_OUTPUT',
    targetField: 'risk_weight',
    nullRule: 'Default to 100% for Corporate',
    effectiveDateRule: 'Current RBI Master Circular',
    dqRule: 'risk_weight IN (20.0, 30.0, 50.0, 75.0, 100.0, 150.0)',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-11',
    sourceSystem: 'CAPITAL_ENGINE_OUTPUT',
    sourceTable: 'tbl_capital_engine_output',
    sourceColumn: 'rwa_amount',
    dataType: 'NUMERIC(18,2)',
    grain: 'Facility Level',
    transformationLogic: 'net_adjusted_ead * (risk_weight / 100.0)',
    targetTable: 'CAPITAL_ENGINE_OUTPUT',
    targetField: 'rwa_amount',
    nullRule: 'Must compute non-null RWA',
    effectiveDateRule: 'Pricing Calculation Date',
    dqRule: 'rwa_amount >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-12',
    sourceSystem: 'CAPITAL_ENGINE_OUTPUT',
    sourceTable: 'tbl_capital_engine_output',
    sourceColumn: 'run_version_id',
    dataType: 'VARCHAR(30)',
    grain: 'Run Batch Instance',
    transformationLogic: 'GENERATE_RUN_ID("RUN", as_of_date, batch_sequence)',
    targetTable: 'CAPITAL_ENGINE_OUTPUT',
    targetField: 'run_version_id',
    nullRule: 'Reject publish if null',
    effectiveDateRule: 'Execution Timestamp',
    dqRule: 'FORMAT ("RUN-YYYYMMDD-SS")',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-13',
    sourceSystem: 'FINANCE_CAPITAL_CONTROL',
    sourceTable: 'tbl_whole_bank_capital',
    sourceColumn: 'cet1_ratio_percent',
    dataType: 'NUMERIC(5,2)',
    grain: 'Whole-Bank Aggregation',
    transformationLogic: 'whole_bank_cet1_capital / whole_bank_total_rwa',
    targetTable: 'REGULATORY_REPORTING_MART',
    targetField: 'cet1_ratio_percent',
    nullRule: 'Must compute non-null ratio',
    effectiveDateRule: 'Reporting Cutoff',
    dqRule: 'cet1_ratio_percent >= 5.50',
    status: 'Target Approved',
  },
  {
    id: 'MAP-CAP-14',
    sourceSystem: 'REGULATORY_REPORTING_MART',
    sourceTable: 'tbl_rbi_prudential_return',
    sourceColumn: 'run_version_id',
    dataType: 'VARCHAR(30)',
    grain: 'Downstream Extract',
    transformationLogic: 'FILTER WHERE run_version_id = APPROVED_RUN_VERSION_ID',
    targetTable: 'REGULATORY_REPORTING_MART',
    targetField: 'consumed_run_version_id',
    nullRule: 'Reject return if unapproved version',
    effectiveDateRule: 'Reporting Cutoff',
    dqRule: 'EQUALS APPROVED_RUN_VERSION_ID',
    status: 'Target Approved',
  },
];

export const INVESTIGATION_TASKS: InvestigationTask[] = [
  {
    id: 'INV-CAP-A',
    code: 'INVESTIGATION-A',
    title: 'Source Exposure Class Mismatch Audit',
    description: 'Find exposures where raw borrower entity type differs from capital staging exposure class assignment.',
    sampleQuery: 'SELECT facility_number, obligor_name, borrower_entity_type, staging_exposure_class FROM tbl_rwa_stage WHERE borrower_entity_type = "CORPORATE" AND staging_exposure_class = "PSE";',
    sampleResultRows: [
      { facility_number: 'MUM-CRE-8801', obligor_name: 'Sahyadri Commercial Logistics', borrower_type: 'CORPORATE', staging_class: 'PSE (20% RW)', correct_class: 'Corporate (100% RW)', variance: 'Understated ₹360.0 Cr RWA' },
    ],
    expectedFinding: 'Corporate facility MUM-CRE-8801 misclassified as PSE, understating risk weight from 100% to 20%.',
    discoveredDefectId: 'DEF-CAP-001',
  },
  {
    id: 'INV-CAP-B',
    code: 'INVESTIGATION-B',
    title: 'Stale External Rating Feed Lookup Audit',
    description: 'Identify external ratings used in capital calculation that are >90 days old from reporting cutoff.',
    sampleQuery: 'SELECT facility_number, obligor_name, external_rating, rating_effective_date, DATEDIFF(day, rating_effective_date, "2026-07-31") as rating_age_days FROM tbl_external_rating WHERE DATEDIFF(day, rating_effective_date, "2026-07-31") > 90;',
    sampleResultRows: [
      { facility_number: 'HYD-INF-9902', obligor_name: 'Deccan Power & Infrastructure', external_rating: 'CARE A+', effective_date: '15-May-2024', rating_age_days: 807, applied_rw: 50.0, fallback_rw: 100.0, status: 'STALE RATING EXPIRED' },
    ],
    expectedFinding: 'Rating CARE A+ for HYD-INF-9902 is 807 days old. Data Quality gate must fall back to 100% Unrated Corporate RW.',
    discoveredDefectId: 'DEF-CAP-002',
  },
  {
    id: 'INV-CAP-C',
    code: 'INVESTIGATION-C',
    title: 'Off-Balance Sheet Commitment CCF Ingestion Failure',
    description: 'Reconcile undrawn commitments in limit tables against capital staging EAD records to find omitted CCF conversions.',
    sampleQuery: 'SELECT lim.facility_number, lim.undrawn_commitment_bal, stg.off_balance_sheet_commitment FROM tbl_limit_master lim LEFT JOIN tbl_rwa_stage stg ON lim.facility_id = stg.facility_id WHERE stg.off_balance_sheet_commitment IS NULL OR stg.off_balance_sheet_commitment = 0;',
    sampleResultRows: [
      { facility_number: 'MUM-CRE-8801', obligor_name: 'Sahyadri Commercial Logistics', limit_undrawn: 800.0, staging_undrawn: 0.0, variance: 'Missing ₹800.0 Cr Commitment (₹400 Cr EAD)' },
    ],
    expectedFinding: 'Prefix mismatch (`LMT-` vs `FAC-`) caused CCF join failure, omitting ₹800 Cr commitment (50% CCF = ₹400 Cr EAD).',
    discoveredDefectId: 'DEF-CAP-003',
  },
  {
    id: 'INV-CAP-D',
    code: 'INVESTIGATION-D',
    title: 'Ineligible Collateral Haircut Audit',
    description: 'Identify CRM collateral haircut deductions applied without verified valuation timestamps.',
    sampleQuery: 'SELECT facility_number, obligor_name, collateral_type, collateral_value, valuation_date FROM tbl_collateral_master WHERE collateral_value > 0 AND valuation_date IS NULL;',
    sampleResultRows: [
      { facility_number: 'DEL-MED-7706', obligor_name: 'Aethel Healthcare & Hospitals', collateral_value: 80.0, valuation_date: 'NULL', applied_haircut_credit: 80.0, status: 'UNVERIFIED COLLATERAL REJECTED' },
    ],
    expectedFinding: 'Collateral haircut applied to DEL-MED-7706 despite missing valuation timestamp; CRM gate must reject collateral deduction.',
    discoveredDefectId: 'DEF-CAP-004',
  },
  {
    id: 'INV-CAP-E',
    code: 'INVESTIGATION-E',
    title: 'Past-Due Snapshot Lag Risk Weight Audit',
    description: 'Verify risk weight assigned to 90+ DPD Substandard NPA facilities against past-due snapshot date.',
    sampleQuery: 'SELECT facility_number, days_past_due, asset_quality_status, specific_provision_percent, applied_risk_weight FROM tbl_rwa_stage WHERE days_past_due > 90 AND applied_risk_weight < 150;',
    sampleResultRows: [
      { facility_number: 'DEL-MED-7706', days_past_due: 91, status: 'Substandard NPA', provision_percent: 15.0, applied_rw: 100.0, correct_rw: 150.0, variance: 'Understated 50% Past Due RW' },
    ],
    expectedFinding: 'Prior-day snapshot lag applied 100% Standard RW to 91 DPD Substandard NPA facility DEL-MED-7706 instead of 150% Past Due RW.',
    discoveredDefectId: 'DEF-CAP-005',
  },
  {
    id: 'INV-CAP-F',
    code: 'INVESTIGATION-F',
    title: 'Regulatory Reporting Mart Run Version Audit',
    description: 'Verify whether downstream RBI prudential returns consumed the approved capital calculation run version.',
    sampleQuery: 'SELECT return_name, consumed_run_version_id, approved_run_version_id FROM tbl_rbi_prudential_return_log;',
    sampleResultRows: [
      { return_name: 'RBI_CAPITAL_RETURN_Q2', consumed_run_version_id: 'RUN-20260730-01', approved_run_version_id: 'RUN-20260731-01', variance: 'Consumed Yesterday Stale Run' },
    ],
    expectedFinding: 'Downstream RBI return consumed yesterday’s stale run (`RUN-20260730-01`), omitting today’s approved RWA output.',
    discoveredDefectId: 'DEF-CAP-006',
  },
];

export const SEEDED_DEFECTS: CaseDefect[] = [
  {
    id: 'DEF-CAP-001',
    code: 'DEF-2026-01',
    title: 'Corporate Exposure Misclassification — Applied 20% PSE RW Instead of 100%',
    severity: 'BLOCKER',
    category: 'Exposure Classification',
    facilityNumber: 'MUM-CRE-8801',
    obligorName: 'Sahyadri Commercial Logistics Group Ltd',
    linkedEvidenceId: 'EV-CAP-05',
    linkedReqId: 'REQ-CAP-007',
    linkedMappingId: 'MAP-CAP-02',
    linkedTestId: 'UAT-CAP-007',
    expectedBehaviour: 'Corporate facility MUM-CRE-8801 maps to Corporate exposure class (100% Unrated RW = ₹450 Cr RWA).',
    actualBehaviour: 'Rule condition `if (ownership_type == "SEMI_GOVT")` misclassified loan as PSE (20% RW = ₹90 Cr RWA), understating RWA by ₹360 Cr.',
    rootCause: 'Incorrect ownership type lookup in exposure classification table `tbl_exposure_class_rules`.',
    remediationFix: 'Update borrower entity mapping rule to classify MUM-CRE-8801 as Corporate (100% RW).',
    regressionTest: 'UAT-CAP-007 (Verify MUM-CRE-8801 maps to Corporate 100% RW).',
    financialImpactInrCr: 360.0,
    status: 'Open',
  },
  {
    id: 'DEF-CAP-002',
    code: 'DEF-2026-02',
    title: 'Stale External Rating & Duplicate Rating Join — Overstated ₹800 Cr RWA',
    severity: 'BLOCKER',
    category: 'Reference Data',
    facilityNumber: 'HYD-INF-9902',
    obligorName: 'Deccan Power & Infrastructure Ltd',
    linkedEvidenceId: 'EV-CAP-04',
    linkedReqId: 'REQ-CAP-004',
    linkedMappingId: 'MAP-CAP-06',
    linkedTestId: 'UAT-CAP-004',
    expectedBehaviour: 'Rating CARE A+ (807 days old) is rejected by freshness gate; facility falls back to 100% Unrated Corporate RW (1 row = ₹700 Cr RWA).',
    actualBehaviour: 'Engine applied stale rating (50% RW). 1:M duplicate rating join generated 2 output rows (2 * ₹700 Cr * 50% = ₹700 Cr RWA + duplicate = ₹1,400 Cr RWA).',
    rootCause: 'Missing rating freshness filter (>90 days) and missing status filter in rating reference table join.',
    remediationFix: 'Enforce rating freshness gate (<90 days) and composite key deduplication on `EXTERNAL_RATING_FEED`.',
    regressionTest: 'UAT-CAP-004 (Verify rating fallback to 100% Unrated RW & single facility row).',
    financialImpactInrCr: 700.0,
    status: 'Open',
  },
  {
    id: 'DEF-CAP-003',
    code: 'DEF-2026-03',
    title: 'Off-Balance Sheet CCF Ingestion Omission — Missing ₹400 Cr EAD',
    severity: 'CRITICAL',
    category: 'ETL Pipeline',
    facilityNumber: 'MUM-CRE-8801',
    obligorName: 'Sahyadri Commercial Logistics Group Ltd',
    linkedEvidenceId: 'EV-CAP-03',
    linkedReqId: 'REQ-CAP-003',
    linkedMappingId: 'MAP-CAP-04',
    linkedTestId: 'UAT-CAP-003',
    expectedBehaviour: 'Undrawn commitment ₹800.0 Cr with 50% CCF generates ₹400.0 Cr EAD (Total EAD = ₹850 Cr, RWA = ₹850 Cr).',
    actualBehaviour: 'Prefix mismatch (`LMT-` vs `FAC-`) failed CCF join, omitting ₹800 Cr commitment from staging (-₹400 Cr EAD / -₹400 Cr RWA).',
    rootCause: 'Key transformation error in ETL script `job_ingest_commitments.sql`.',
    remediationFix: 'Standardize facility join key across limits and exposure tables in ETL pipeline.',
    regressionTest: 'UAT-CAP-003 (Verify ₹800 Cr commitment converts to ₹400 Cr EAD at 50% CCF).',
    financialImpactInrCr: 400.0,
    status: 'Open',
  },
  {
    id: 'DEF-CAP-004',
    code: 'DEF-2026-04',
    title: 'Unverified Collateral Haircut Application — Understated ₹40 Cr RWA',
    severity: 'CRITICAL',
    category: 'CRM Eligibility',
    facilityNumber: 'DEL-MED-7706',
    obligorName: 'Aethel Healthcare & Hospitals Ltd',
    linkedEvidenceId: 'EV-CAP-05',
    linkedReqId: 'REQ-CAP-005',
    linkedMappingId: 'MAP-CAP-08',
    linkedTestId: 'UAT-CAP-005',
    expectedBehaviour: 'Collateral haircut deduction rejected due to missing valuation date (`valuation_date = NULL`), leaving EAD at ₹80.0 Cr.',
    actualBehaviour: 'Engine applied ₹80.0 Cr collateral credit without valuation timestamp, reducing net EAD to ₹0.0 Cr.',
    rootCause: 'CRM engine evaluated `collateral_value > 0` without checking `valuation_date IS NOT NULL`.',
    remediationFix: 'Enforce strict valuation timestamp check before applying collateral haircut deductions.',
    regressionTest: 'UAT-CAP-005 (Verify unverified collateral is rejected and EAD remains ₹80.0 Cr).',
    financialImpactInrCr: 40.0,
    status: 'Open',
  },
  {
    id: 'DEF-CAP-005',
    code: 'DEF-2026-05',
    title: 'Past-Due Snapshot Lag — Applied 100% Standard RW Instead of 150% Past Due RW',
    severity: 'MAJOR',
    category: 'Asset Quality Interface',
    facilityNumber: 'DEL-MED-7706',
    obligorName: 'Aethel Healthcare & Hospitals Ltd',
    linkedEvidenceId: 'EV-CAP-05',
    linkedReqId: 'REQ-CAP-006',
    linkedMappingId: 'MAP-CAP-09',
    linkedTestId: 'UAT-CAP-006',
    expectedBehaviour: 'Facility DEL-MED-7706 (91 DPD Substandard NPA, 15% provision) receives 150% Past Due RW (₹120.0 Cr RWA).',
    actualBehaviour: 'Prior-day snapshot lag ingested DPD = 60 days (Standard), applying 100% Standard RW (₹80.0 Cr RWA), understating RWA by ₹40 Cr.',
    rootCause: 'Snapshot timestamp lag between Asset Quality Mart and Capital Engine.',
    remediationFix: 'Synchronize Asset Quality snapshot date with Capital Engine execution timestamp.',
    regressionTest: 'UAT-CAP-006 (Verify DEL-MED-7706 receives 150% Past Due RW = ₹120.0 Cr RWA).',
    financialImpactInrCr: 40.0,
    status: 'Open',
  },
  {
    id: 'DEF-CAP-006',
    code: 'DEF-2026-06',
    title: 'Regulatory Reporting Mart Stale Run Version Consumption',
    severity: 'MAJOR',
    category: 'Interface / Versioning',
    facilityNumber: 'ALL-FACILITIES',
    obligorName: 'Whole-Bank Capital Return Extract',
    linkedEvidenceId: 'EV-CAP-06',
    linkedReqId: 'REQ-CAP-011',
    linkedMappingId: 'MAP-CAP-14',
    linkedTestId: 'UAT-CAP-011',
    expectedBehaviour: 'Downstream Regulatory Reporting Mart consumes current approved run `RUN-20260731-01`.',
    actualBehaviour: 'Return publishing script fetched yesterday’s stale run (`RUN-20260730-01`), ignoring today’s capital output.',
    rootCause: 'Hardcoded query `WHERE run_date = CURRENT_DATE() - 1` in `sp_build_rbi_return.sql`.',
    remediationFix: 'Parameterize return extraction script on explicit approved `run_version_id`.',
    regressionTest: 'UAT-CAP-011 (Verify regulatory return consumes `RUN-20260731-01`).',
    financialImpactInrCr: 0.0,
    status: 'Open',
  },
];

export const UAT_TEST_PACK: UATTestCase[] = [
  { id: 'UAT-CAP-001', code: 'UAT-CAP-001', title: 'Verify Staging Exposure Ingestion Match', linkedReqId: 'REQ-CAP-001', precondition: 'EOD clearing completed at 23:59', testInput: 'CBS Credit Balance: ₹2,645.0 Cr', expectedResult: 'Staging Balance: ₹2,645.0 Cr (100% Match)', actualResult: 'Staging Balance: ₹2,645.0 Cr (100% Match)', status: 'PASSED' },
  { id: 'UAT-CAP-002', code: 'UAT-CAP-002', title: 'Verify On/Off-Balance Sheet Attribute Separation', linkedReqId: 'REQ-CAP-002', precondition: 'Facility MUM-CRE-8801', testInput: 'Drawn: ₹450 Cr, Undrawn: ₹800 Cr', expectedResult: 'Drawn & Undrawn stored as distinct fields', actualResult: 'Drawn & Undrawn stored as distinct fields', status: 'PASSED' },
  { id: 'UAT-CAP-003', code: 'UAT-CAP-003', title: 'Verify Off-Balance Sheet CCF 50% Conversion', linkedReqId: 'REQ-CAP-003', precondition: 'Undrawn Commitment: ₹800.0 Cr, Tenor > 1 yr', testInput: 'Commitment: ₹800 Cr, CCF: 50%', expectedResult: 'Credit Equivalent EAD: ₹400.0 Cr Add-On', actualResult: 'CCF Join Failed (Omitted ₹800 Cr Commitment / ₹400 Cr EAD)', status: 'FAILED', linkedDefectId: 'DEF-CAP-003' },
  { id: 'UAT-CAP-004', code: 'UAT-CAP-004', title: 'Verify Stale Rating Fallback to 100% Unrated Corporate RW', linkedReqId: 'REQ-CAP-004', precondition: 'Rating CARE A+ (807 days old)', testInput: 'Rating Age: 807 Days', expectedResult: 'Stale Rating Rejected; Applied 100% Unrated RW', actualResult: 'Applied 50% A-Rating RW; 2 Duplicate Rows Generated', status: 'FAILED', linkedDefectId: 'DEF-CAP-002' },
  { id: 'UAT-CAP-005', code: 'UAT-CAP-005', title: 'Verify Unverified Collateral Haircut Rejection', linkedReqId: 'REQ-CAP-005', precondition: 'Facility DEL-MED-7706 (valuation_date = NULL)', testInput: 'Collateral: ₹80 Cr, Valuation Date: NULL', expectedResult: 'Collateral Haircut Rejected; EAD = ₹80.0 Cr', actualResult: 'Applied ₹80 Cr Collateral Haircut (EAD = ₹0 Cr)', status: 'FAILED', linkedDefectId: 'DEF-CAP-004' },
  { id: 'UAT-CAP-006', code: 'UAT-CAP-006', title: 'Verify 91 DPD Substandard NPA 150% Past Due RW', linkedReqId: 'REQ-CAP-006', precondition: 'DEL-MED-7706 (91 DPD NPA, 15% provision)', testInput: 'DPD: 91, Provision: 15.0%', expectedResult: 'Risk Weight: 150% Past Due RW (₹120.0 Cr RWA)', actualResult: 'Risk Weight: 100% Standard RW (Snapshot Lag)', status: 'FAILED', linkedDefectId: 'DEF-CAP-005' },
  { id: 'UAT-CAP-007', code: 'UAT-CAP-007', title: 'Verify Corporate Exposure Class 100% RW Assignment', linkedReqId: 'REQ-CAP-007', precondition: 'Facility MUM-CRE-8801', testInput: 'Borrower Type: CORPORATE', expectedResult: 'Exposure Class: Corporate (100% RW = ₹450 Cr RWA)', actualResult: 'Exposure Class: PSE (20% RW = ₹90 Cr RWA)', status: 'FAILED', linkedDefectId: 'DEF-CAP-001' },
  { id: 'UAT-CAP-008', code: 'UAT-CAP-008', title: 'Verify Composite Key Rating Deduplication', linkedReqId: 'REQ-CAP-008', precondition: 'Single facility HYD-INF-9902', testInput: 'Composite Join: obligor + facility + as_of_date', expectedResult: 'Rows: 1, Target RWA: ₹700.0 Cr', actualResult: 'Rows: 2, RWA: ₹1,400.0 Cr (Duplicate Join)', status: 'FAILED', linkedDefectId: 'DEF-CAP-002' },
  { id: 'UAT-CAP-009', code: 'UAT-CAP-009', title: 'Verify Capital Requirement Output Calculation (9.00%)', linkedReqId: 'REQ-CAP-009', precondition: 'Facility MUM-CRE-8801 (RWA = ₹450 Cr)', testInput: 'RWA: ₹450 Cr, CRAR Rate: 9.00%', expectedResult: 'Capital Requirement: ₹40.50 Cr', actualResult: 'Capital Requirement: ₹40.50 Cr', status: 'PASSED' },
  { id: 'UAT-CAP-010', code: 'UAT-CAP-010', title: 'Verify Immutable Run Version Tagging', linkedReqId: 'REQ-CAP-010', precondition: 'Engine calculation run complete', testInput: 'Batch Sequence: 01', expectedResult: 'Run Version: RUN-20260731-01', actualResult: 'Run Version: RUN-20260731-01', status: 'PASSED' },
  { id: 'UAT-CAP-011', code: 'UAT-CAP-011', title: 'Verify Regulatory Reporting Mart Version Lock', linkedReqId: 'REQ-CAP-011', precondition: 'Regulatory return publication', testInput: 'Approved Version: RUN-20260731-01', expectedResult: 'Consumed Version: RUN-20260731-01', actualResult: 'Consumed Version: RUN-20260730-01 (Stale Run)', status: 'FAILED', linkedDefectId: 'DEF-CAP-006' },
  { id: 'UAT-CAP-012', code: 'UAT-CAP-012', title: 'Verify Whole-Bank CET1 Ratio & CRAR Calculation', linkedReqId: 'REQ-CAP-012', precondition: 'Whole-Bank CET1 = ₹1,800 Cr, Total RWA = ₹20,000 Cr', testInput: 'Whole-Bank Total RWA: ₹20,000 Cr', expectedResult: 'CET1 Ratio: 9.00%, CRAR: 12.00%', actualResult: 'CET1 Ratio: 9.00%, CRAR: 12.00%', status: 'PASSED' },
  { id: 'UAT-CAP-013', code: 'UAT-CAP-013', title: 'Verify BCBS 239 End-to-End Lineage Traceability', linkedReqId: 'REQ-CAP-013', precondition: 'Reported Credit RWA output', testInput: 'Facility: PUN-MFG-4403', expectedResult: '100% Traceability to Core Contract', actualResult: '100% Traceability to Core Contract', status: 'PASSED' },
  { id: 'UAT-CAP-014', code: 'UAT-CAP-014', title: 'Verify BAU Rerun Reproducibility', linkedReqId: 'REQ-CAP-014', precondition: 'Rerun trigger on RUN-20260731-01', testInput: 'Same Inputs & Rating Master', expectedResult: '100% Identical RWA Output', actualResult: '100% Identical RWA Output', status: 'PASSED' },
  { id: 'UAT-CAP-015', code: 'UAT-CAP-015', title: 'Verify Unrated Corporate 100% Risk Weight Default', linkedReqId: 'REQ-CAP-008', precondition: 'Unrated corporate loan BLR-SME-1104', testInput: 'Rating: NULL, Class: Corporate', expectedResult: 'Risk Weight: 100% Unrated Corporate RW', actualResult: 'Risk Weight: 100% Unrated Corporate RW', status: 'PASSED' },
  { id: 'UAT-CAP-016', code: 'UAT-CAP-016', title: 'Verify CRE Category 100% Risk Weight Assignment', linkedReqId: 'REQ-CAP-007', precondition: 'Commercial Real Estate loan', testInput: 'Category: CRE', expectedResult: 'Risk Weight: 100% CRE RW', actualResult: 'Risk Weight: 100% CRE RW', status: 'PASSED' },
  { id: 'UAT-CAP-017', code: 'UAT-CAP-017', title: 'Verify CRE Residential 75% Risk Weight Assignment', linkedReqId: 'REQ-CAP-007', precondition: 'CRE Residential loan CHN-RES-5507', testInput: 'Category: CRE-Residential', expectedResult: 'Risk Weight: 75% CRE Resi RW', actualResult: 'Risk Weight: 75% CRE Resi RW', status: 'PASSED' },
  { id: 'UAT-CAP-018', code: 'UAT-CAP-018', title: 'Verify Sovereign Exposure 0% Risk Weight Assignment', linkedReqId: 'REQ-CAP-007', precondition: 'Indian Sovereign Security', testInput: 'Borrower: Government of India', expectedResult: 'Risk Weight: 0% Sovereign RW', actualResult: 'Risk Weight: 0% Sovereign RW', status: 'PASSED' },
  { id: 'UAT-CAP-019', code: 'UAT-CAP-019', title: 'Verify Eligible Cash Collateral 0% Haircut Deduction', linkedReqId: 'REQ-CAP-005', precondition: 'Fixed Deposit Collateral with verified valuation', testInput: 'Collateral: FD, Valuation: Verified', expectedResult: 'CRM Haircut Applied (0% Haircut on Cash FD)', actualResult: 'CRM Haircut Applied (0% Haircut on Cash FD)', status: 'PASSED' },
  { id: 'UAT-CAP-020', code: 'UAT-CAP-020', title: 'Verify Total Portfolio Target RWA Aggregation (₹2,436 Cr)', linkedReqId: 'REQ-CAP-012', precondition: 'All 8 facilities remediated', testInput: 'Drawn: ₹2,645 Cr, Undrawn EAD: ₹400 Cr', expectedResult: 'Total Target Portfolio RWA: ₹2,436.0 Cr', actualResult: 'Total Target Portfolio RWA: ₹2,436.0 Cr', status: 'PASSED' },
];

export const TRACEABILITY_MATRIX: TraceabilityChain[] = [
  { id: 'RTM-CAP-01', regulatoryDriver: 'BCBS 239 Data Timeliness Principle 6', reqId: 'REQ-CAP-001', ruleId: 'RULE-CAP-01', mappingId: 'MAP-CAP-01', component: 'ETL Ingestion `job_ingest_credit_exposure`', testId: 'UAT-CAP-001', signoffOwner: 'Nitin Saxena' },
  { id: 'RTM-CAP-02', regulatoryDriver: 'RBI Master Circular Capital Adequacy Sec 7.3', reqId: 'REQ-CAP-003', ruleId: 'RULE-CAP-02', mappingId: 'MAP-CAP-04', component: 'ETL Pipeline `job_ingest_commitments`', testId: 'UAT-CAP-003', defectId: 'DEF-CAP-003', signoffOwner: 'Deepak Deshmukh' },
  { id: 'RTM-CAP-03', regulatoryDriver: 'RBI Master Circular Capital Adequacy Sec 6.1', reqId: 'REQ-CAP-004', ruleId: 'RULE-CAP-03', mappingId: 'MAP-CAP-06', component: 'Data Quality Gate `sp_check_rating_freshness.sql`', testId: 'UAT-CAP-004', defectId: 'DEF-CAP-002', signoffOwner: 'Manish Goel' },
  { id: 'RTM-CAP-04', regulatoryDriver: 'RBI Master Circular Capital Adequacy Sec 8.4', reqId: 'REQ-CAP-005', ruleId: 'RULE-CAP-05', mappingId: 'MAP-CAP-08', component: 'CRM Engine `sp_calc_crm_haircuts.sql`', testId: 'UAT-CAP-005', defectId: 'DEF-CAP-004', signoffOwner: 'Smita Kulkarni' },
  { id: 'RTM-CAP-05', regulatoryDriver: 'RBI Master Circular Capital Adequacy Sec 5.8', reqId: 'REQ-CAP-006', ruleId: 'RULE-CAP-06', mappingId: 'MAP-CAP-09', component: 'Past Due Engine `sp_calc_past_due_rw.sql`', testId: 'UAT-CAP-006', defectId: 'DEF-CAP-005', signoffOwner: 'Smita Kulkarni' },
  { id: 'RTM-CAP-06', regulatoryDriver: 'RBI Master Circular Capital Adequacy Sec 5.2', reqId: 'REQ-CAP-007', ruleId: 'RULE-CAP-01', mappingId: 'MAP-CAP-02', component: 'Classification Engine `sp_classify_exposure.sql`', testId: 'UAT-CAP-007', defectId: 'DEF-CAP-001', signoffOwner: 'Smita Kulkarni' },
  { id: 'RTM-CAP-07', regulatoryDriver: 'BCBS 239 Transparency Principle 8', reqId: 'REQ-CAP-009', ruleId: 'RULE-CAP-07', mappingId: 'MAP-CAP-11', component: 'RWA Calculation Engine `_engine/rbiCapital.ts`', testId: 'UAT-CAP-009', signoffOwner: 'Karan Kapadia' },
  { id: 'RTM-CAP-08', regulatoryDriver: 'BCBS 239 Reporting Integrity Principle 10', reqId: 'REQ-CAP-011', ruleId: 'RULE-CAP-10', mappingId: 'MAP-CAP-14', component: 'Return Publication `sp_build_rbi_return.sql`', testId: 'UAT-CAP-011', defectId: 'DEF-CAP-006', signoffOwner: 'Ritu Shenoy' },
];

export const RECONCILIATION_SUMMARY: ReconciliationSummary = {
  asOfDate: '31 July 2026',
  beforeFix: {
    facilityCount: 9, // Includes 1 duplicate rating join row
    grossOutstandingInrCr: 3445.0, // Includes ₹800 Cr duplicate, missing ₹800 Cr commitment
    npaOutstandingInrCr: 80.0,
    requiredProvisionInrCr: 291.24, // Capital Requirement = RWA * 9.00%
    unexplainedVarianceInrCr: 800.0, // Net Difference (₹3,236 Cr output RWA vs ₹2,436 Cr target RWA)
    grossAbsoluteVarianceInrCr: 2400.0, // |-800| + |+800| + |-800| = ₹2,400.0 Cr Gross Absolute Break
    pricedPopulationCount: 7,
    rejectedPopulationCount: 1, // Omitted by CCF join defect DEF-CAP-003
    consumedRunVersionId: 'RUN-20260730-01',
    approvedRunVersionId: 'RUN-20260731-01',
    isVersionLocked: false,
    reconciliationStatus: 'COMPENSATING RWA BREAK ALERT (GROSS BREAK = ₹2,400.0 Cr)',
    stageBreaks: [
      {
        stageName: 'Source Credit Exposure → Capital Input Stage',
        sourceCount: 8,
        targetCount: 7,
        sourceAmountInrCr: 3445.0,
        targetAmountInrCr: 2645.0,
        varianceAmountInrCr: -800.0,
        reason: 'Prefix mismatch (`LMT-` vs `FAC-`) omitted ₹800 Cr commitment (₹400 Cr EAD / ₹400 Cr RWA).',
        linkedDefectId: 'DEF-CAP-003',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'Capital Input Stage → Capital Engine Output',
        sourceCount: 7,
        targetCount: 9,
        sourceAmountInrCr: 2645.0,
        targetAmountInrCr: 3445.0,
        varianceAmountInrCr: 800.0,
        reason: '1:M duplicate rating join on HYD-INF-9902 generated duplicate row (+₹800 Cr RWA).',
        linkedDefectId: 'DEF-CAP-002',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'Capital Engine Output → Regulatory Reporting Mart',
        sourceCount: 9,
        targetCount: 7,
        sourceAmountInrCr: 3445.0,
        targetAmountInrCr: 2645.0,
        varianceAmountInrCr: -800.0,
        reason: 'Downstream return publication script consumed yesterday’s stale run (RUN-20260730-01).',
        linkedDefectId: 'DEF-CAP-006',
        runVersionId: 'RUN-20260730-01 (STALE)',
      },
    ],
  },
  afterFix: {
    facilityCount: 8, // Exact 8 deduplicated facilities
    grossOutstandingInrCr: 3045.0, // Total EAD = Drawn ₹2,645 Cr + Undrawn EAD ₹400 Cr
    npaOutstandingInrCr: 80.0,
    requiredProvisionInrCr: 219.24, // Target Capital Requirement (₹2,436 Cr RWA * 9.00%)
    unexplainedVarianceInrCr: 0.0,
    grossAbsoluteVarianceInrCr: 0.0,
    pricedPopulationCount: 8,
    rejectedPopulationCount: 0,
    consumedRunVersionId: 'RUN-20260731-01',
    approvedRunVersionId: 'RUN-20260731-01',
    isVersionLocked: true,
    reconciliationStatus: 'RECONCILED (ZERO VARIANCE & RUN LOCKED)',
    stageBreaks: [
      {
        stageName: 'Source Credit Exposure → Capital Input Stage',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 3045.0,
        targetAmountInrCr: 3045.0,
        varianceAmountInrCr: 0.0,
        reason: '100% Ingestion including ₹800 Cr commitment (50% CCF = ₹400 Cr EAD).',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'Capital Input Stage → Capital Engine Output',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 3045.0,
        targetAmountInrCr: 3045.0,
        varianceAmountInrCr: 0.0,
        reason: 'Rating freshness gate enforced (<90 days) & composite key deduplication verified.',
        runVersionId: 'RUN-20260731-01',
      },
      {
        stageName: 'Capital Engine Output → Regulatory Reporting Mart',
        sourceCount: 8,
        targetCount: 8,
        sourceAmountInrCr: 3045.0,
        targetAmountInrCr: 3045.0,
        varianceAmountInrCr: 0.0,
        reason: 'Regulatory Reporting Mart parameterized on approved run version (RUN-20260731-01).',
        runVersionId: 'RUN-20260731-01',
      },
    ],
  },
};

export const SIGN_OFF_APPROVERS: SignOffRequirement[] = [
  { id: 'SO-CAP-01', stakeholderTitle: 'Capital Risk & Prudential Lead', approverName: 'Karan Kapadia', role: 'Regulatory RWA Policy Owner', status: 'PENDING', comments: 'Pending verification of DEF-CAP-001 corporate classification fix (100% vs 20% RW).' },
  { id: 'SO-CAP-02', stakeholderTitle: 'Finance Capital Reporting Lead', approverName: 'Nitin Saxena', role: 'General Ledger Capital Accounting Owner', status: 'PENDING', comments: 'Pending zero-variance balance reconciliation sign-off post DEF-CAP-003 CCF ingestion fix.' },
  { id: 'SO-CAP-03', stakeholderTitle: 'Credit Rating Data Owner', approverName: 'Manish Goel', role: 'External Rating Feed & Freshness Owner', status: 'PENDING', comments: 'Pending rating freshness gate verification on HYD-INF-9902.' },
  { id: 'SO-CAP-04', stakeholderTitle: 'QA & UAT Testing Lead', approverName: 'Bhavna Patel', role: 'Business Acceptance QA Owner', status: 'PENDING', comments: 'Pending 100% UAT test suite execution pass.' },
  { id: 'SO-CAP-05', stakeholderTitle: 'Regulatory Reporting Lead', approverName: 'Ritu Shenoy', role: 'RBI Prudential Returns Owner', status: 'PENDING', comments: 'Pending verification of downstream return version lock on RUN-20260731-01.' },
];

export const GOVERNANCE_CONFIG: GovernanceConfig = {
  blockingSeverities: ['BLOCKER', 'CRITICAL'],
  requiredUatPassPercent: 100,
  maxAllowedVarianceInrCr: 0.0,
  requireRtmCoveragePercent: 100,
};

export const CASE_03_DEFINITION: CaseDefinition = {
  metadata: CASE_03_METADATA,
  stakeholders: STAKEHOLDERS,
  evidence: EVIDENCE_PACK,
  currentStateNodes: CURRENT_STATE_NODES,
  targetStateNodes: TARGET_STATE_NODES,
  requirements: BUSINESS_REQUIREMENTS,
  rules: BUSINESS_RULES,
  mappings: SOURCE_TARGET_MAPPINGS,
  investigationTasks: INVESTIGATION_TASKS,
  defects: SEEDED_DEFECTS,
  uatTestPack: UAT_TEST_PACK,
  traceabilityMatrix: TRACEABILITY_MATRIX,
  reconciliationSummary: RECONCILIATION_SUMMARY,
  signoffs: SIGN_OFF_APPROVERS,
  governanceConfig: GOVERNANCE_CONFIG,
};
