export interface RecallItem {
  id: string;
  term: string;
  acronym?: string;
  meaning: string;
  remember: string;
  project: "Credit Risk" | "Churn" | "Time Series" | "NIFTY" | "Client Equity" | "LOC-IQ" | "Build" | "BA / Data";
  category: "Credit Risk" | "BA / Data" | "ML" | "Time Series" | "Portfolio" | "Equity" | "Product / AI" | "Build";
  href: string;
  formula?: string;
  comparison?: {
    vsTerm: string;
    diff: string;
  };
  trap?: {
    wrong: string;
    correction: string;
  };
  tags: string[];
}

export const recallItems: RecallItem[] = [
  // CREDIT RISK
  {
    id: "pd",
    term: "Probability of Default",
    acronym: "PD",
    meaning: "The likelihood that a borrower defaults on financial obligations over a 12-month or lifetime horizon.",
    remember: "Probability that a loan defaults within the timeframe.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    formula: "PD = 1 / (1 + e^-(score))",
    comparison: { vsTerm: "Score", diff: "Score is a scaled integer ranking; PD is a calibrated statistical probability." },
    trap: { wrong: "Higher score means higher risk.", correction: "Higher scorecard points represent lower credit risk." },
    tags: ["credit", "pd", "scorecard", "risk"],
  },
  {
    id: "lgd",
    term: "Loss Given Default",
    acronym: "LGD",
    meaning: "Percentage of total exposure lost if a borrower defaults after accounting for recoveries and costs.",
    remember: "LGD = 1 - Recovery Rate.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    formula: "LGD = (Default Amount - Recoveries + Costs) / Default Amount",
    comparison: { vsTerm: "Downturn LGD", diff: "LGD is average economic loss; Downturn LGD reflects severe economic stress." },
    tags: ["lgd", "recovery", "loss", "credit"],
  },
  {
    id: "ead",
    term: "Exposure at Default",
    acronym: "EAD",
    meaning: "Total gross dollar amount outstanding when default occurs, including drawn balance and CCF on undrawn lines.",
    remember: "Drawn balance plus expected drawdown on remaining limit.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    formula: "EAD = Drawn + (Undrawn × CCF)",
    tags: ["ead", "exposure", "credit"],
  },
  {
    id: "el",
    term: "Expected Loss",
    acronym: "EL",
    meaning: "Anticipated financial credit loss calculated as the product of PD, LGD, and EAD.",
    remember: "Expected credit loss = PD × LGD × EAD.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    formula: "EL = PD × LGD × EAD",
    comparison: { vsTerm: "RWA", diff: "EL represents expected provisions; RWA represents capital reserves for unexpected loss." },
    tags: ["el", "expected loss", "pd", "lgd", "ead"],
  },
  {
    id: "woe",
    term: "Weight of Evidence",
    acronym: "WoE",
    meaning: "Logarithmic ratio measuring the relative distribution of good vs bad borrowers in a specific attribute bin.",
    remember: "WoE converts raw categorical bins into monotonic continuous log-odds numbers.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    formula: "WoE = ln( %Goods / %Bads )",
    tags: ["woe", "binning", "scorecard"],
  },
  {
    id: "sicr",
    term: "Significant Increase in Credit Risk",
    acronym: "SICR",
    meaning: "IFRS 9 staging trigger moving a loan from Stage 1 (12M ECL) to Stage 2 (Lifetime ECL).",
    remember: "Triggers lifetime ECL provision when credit risk deteriorates significantly.",
    project: "Credit Risk",
    category: "Credit Risk",
    href: "/notebook/masterclasses/credit-risk",
    comparison: { vsTerm: "Default", diff: "SICR is Stage 2 deterioration; Default is Stage 3 objective impairment." },
    trap: { wrong: "30 DPD is the sole definition of Stage 2.", correction: "30 DPD is a backstop; quantitative PD ratio increases trigger Stage 2 earlier." },
    tags: ["sicr", "ifrs9", "stage2", "ecl"],
  },

  // CHURN
  {
    id: "churn_recall",
    term: "Recall (Sensitivity)",
    acronym: "Recall",
    meaning: "Proportion of actual positive churners correctly identified by the model.",
    remember: "Of all true churners, how many did we catch?",
    project: "Churn",
    category: "ML",
    href: "/notebook/masterclasses/churn",
    formula: "Recall = TP / (TP + FN)",
    comparison: { vsTerm: "Precision", diff: "Recall measures capture rate; Precision measures purity rate." },
    trap: { wrong: "High accuracy means a good churn model.", correction: "79.63% accuracy can be achieved by naively predicting everyone stays." },
    tags: ["recall", "churn", "tp", "fn"],
  },
  {
    id: "churn_precision",
    term: "Precision",
    meaning: "Proportion of predicted churners who actually ended up churning.",
    remember: "Of everyone we flagged as a churner, how many were real?",
    project: "Churn",
    category: "ML",
    href: "/notebook/masterclasses/churn",
    formula: "Precision = TP / (TP + FP)",
    tags: ["precision", "fp", "tp"],
  },
  {
    id: "smote",
    term: "Synthetic Minority Over-sampling Technique",
    acronym: "SMOTE",
    meaning: "Generates synthetic minority class examples by interpolating between neighboring minority feature space points.",
    remember: "SMOTE balances training classes via synthetic feature space interpolation.",
    project: "Churn",
    category: "ML",
    href: "/notebook/masterclasses/churn",
    trap: { wrong: "Apply SMOTE before train/test split.", correction: "SMOTE must be applied ONLY to training data to prevent test set data leakage." },
    tags: ["smote", "imbalance", "churn"],
  },

  // TIME SERIES
  {
    id: "stationarity",
    term: "Stationarity",
    meaning: "Property of a time series where statistical parameters (mean, variance, autocorrelation) remain constant over time.",
    remember: "Stationarity means stable statistical structure, not a flat line.",
    project: "Time Series",
    category: "Time Series",
    href: "/notebook/masterclasses/time-series",
    comparison: { vsTerm: "No Movement", diff: "Stationarity allows fluctuations around a stable statistical mean/variance." },
    tags: ["stationarity", "adf", "time series"],
  },
  {
    id: "adf",
    term: "Augmented Dickey–Fuller Test",
    acronym: "ADF",
    meaning: "Statistical unit-root test evaluating whether a time series is non-stationary (H₀: unit root exists).",
    remember: "Low p-value (< 0.05) rejects unit root and supports stationarity.",
    project: "Time Series",
    category: "Time Series",
    href: "/notebook/masterclasses/time-series",
    tags: ["adf", "unit root", "stationarity"],
  },
  {
    id: "sarima",
    term: "Seasonal ARIMA",
    acronym: "SARIMA",
    meaning: "Extends ARIMA with seasonal autoregressive (P), differencing (D), and moving-average (Q) terms at lag m.",
    remember: "SARIMA(p,d,q)(P,D,Q)m models trend + annual seasonality.",
    project: "Time Series",
    category: "Time Series",
    href: "/notebook/masterclasses/time-series",
    formula: "SARIMA(p,d,q)(P,D,Q)m",
    tags: ["sarima", "arima", "forecasting"],
  },
  {
    id: "mape",
    term: "Mean Absolute Percentage Error",
    acronym: "MAPE",
    meaning: "Average of absolute percentage errors between forecast and actual observed values across evaluation periods.",
    remember: "MAPE ≈ average percentage forecast miss.",
    project: "Time Series",
    category: "Time Series",
    href: "/notebook/masterclasses/time-series",
    formula: "MAPE = mean( |(y - ŷ) / y| ) × 100",
    tags: ["mape", "forecast error", "baseline"],
  },

  // NIFTY PORTFOLIO
  {
    id: "log_return",
    term: "Log Return",
    meaning: "Continuously compounded return calculated as the natural logarithm of current price divided by previous price.",
    remember: "Prices tell level; returns tell movement.",
    project: "NIFTY",
    category: "Portfolio",
    href: "/notebook/masterclasses/nifty",
    formula: "r_t = ln( P_t / P_t-1 )",
    comparison: { vsTerm: "Simple Return", diff: "Simple return is (P_t - P_t-1)/P_t-1; Log return is additive over time." },
    tags: ["log return", "nifty", "prices"],
  },
  {
    id: "covariance",
    term: "Covariance",
    meaning: "Measure of joint directional movement between two asset return series.",
    remember: "Covariance is the cross-asset ingredient in portfolio risk.",
    project: "NIFTY",
    category: "Portfolio",
    href: "/notebook/masterclasses/nifty",
    comparison: { vsTerm: "Correlation", diff: "Covariance is scale-dependent; Correlation is standardized between -1 and +1." },
    tags: ["covariance", "risk", "nifty"],
  },
  {
    id: "portfolio_score",
    term: "Simplified Return/Volatility Score",
    meaning: "Project objective ratio defined as expected portfolio return divided by portfolio volatility.",
    remember: "Expected return / volatility without explicit risk-free rate subtraction.",
    project: "NIFTY",
    category: "Portfolio",
    href: "/notebook/masterclasses/nifty",
    formula: "score = E[R_p] / σ_p",
    comparison: { vsTerm: "Sharpe Ratio", diff: "Full Sharpe Ratio subtracts risk-free rate R_f from expected return." },
    trap: { wrong: "0.7707 is the Sharpe ratio of the project.", correction: "Project score has no explicit risk-free rate subtraction." },
    tags: ["score", "sharpe", "nifty"],
  },

  // CLIENT EQUITY
  {
    id: "cross_sectional",
    term: "Cross-Sectional Analysis",
    meaning: "Evaluation comparing multiple securities simultaneously at a single point in time.",
    remember: "Time series asks 'how did asset change?'; Cross-sectional asks 'which asset looks strongest now?'",
    project: "Client Equity",
    category: "Equity",
    href: "/notebook/masterclasses/client-equity",
    comparison: { vsTerm: "Time Series", diff: "Time series tracks one asset through time; cross-sectional compares many assets at one date." },
    tags: ["cross-sectional", "ranking", "equity"],
  },
  {
    id: "survivorship_bias",
    term: "Survivorship Bias",
    meaning: "Backtest distortion caused by using only securities that survive to the end of the sample period.",
    remember: "Backtest the portfolio you could have owned then — not the winners you see now.",
    project: "Client Equity",
    category: "Equity",
    href: "/notebook/masterclasses/client-equity",
    tags: ["survivorship", "backtest", "crsp"],
  },
  {
    id: "sector_neutral",
    term: "Sector Neutralisation",
    meaning: "Ranking securities within sector peer groups to isolate stock selection from broad macro sector bets.",
    remember: "Sector neutralisation separates stock selection from sector exposure.",
    project: "Client Equity",
    category: "Equity",
    href: "/notebook/masterclasses/client-equity",
    tags: ["sector neutral", "ranking", "equity"],
  },
  {
    id: "cvxpy_opt",
    term: "L1 / L2 cvxpy Optimisation",
    acronym: "cvxpy",
    meaning: "Convex optimization modelling in Python balancing signal alignment against weight turnover penalties.",
    remember: "L1 penalises absolute movement; L2 penalises squared movement.",
    project: "Client Equity",
    category: "Equity",
    href: "/notebook/masterclasses/client-equity",
    formula: "L1 = Σ |w_new - w_old|,  L2 = Σ (w_new - w_old)²",
    tags: ["cvxpy", "l1", "l2", "optimisation"],
  },
  {
    id: "tracking_error",
    term: "Tracking Error",
    meaning: "Standard deviation of active returns (strategy return minus benchmark return).",
    remember: "Volatility = absolute risk. Tracking error = benchmark-relative risk.",
    project: "Client Equity",
    category: "Equity",
    href: "/notebook/masterclasses/client-equity",
    formula: "Tracking Error = StdDev( R_strategy - R_benchmark )",
    tags: ["tracking error", "active risk", "benchmark"],
  },

  // LOC-IQ
  {
    id: "identifier",
    term: "Applicant Identifier",
    meaning: "Key known about an applicant (e.g. PAN, Phone, Address) used to query external sources.",
    remember: "Identifier = lookup key.",
    project: "LOC-IQ",
    category: "Product / AI",
    href: "/notebook/masterclasses/loc-iq",
    tags: ["identifier", "loc-iq", "graph"],
  },
  {
    id: "composite_weight",
    term: "Composite Edge Weighting",
    meaning: "Edge weight formula multiplying base relationship importance by recency decay and network trust factors.",
    remember: "effective weight = base weight × recency factor × IP-trust factor.",
    project: "LOC-IQ",
    category: "Product / AI",
    href: "/notebook/masterclasses/loc-iq",
    formula: "effective weight = base × recency × trust",
    tags: ["weighting", "proxy ip", "loc-iq"],
  },
  {
    id: "proxy_ip",
    term: "Proxy-IP Down-Weighting",
    meaning: "Logic scaling down the trust multiplier when a proxy IP or VPN intermediary is detected.",
    remember: "Weak evidence contributes less; it does not automatically disappear.",
    project: "LOC-IQ",
    category: "Product / AI",
    href: "/notebook/masterclasses/loc-iq",
    trap: { wrong: "LOC-IQ connects 46 live APIs.", correction: "46 is the mapped architectural catalogue count; demo runs static JSON traces." },
    tags: ["proxy ip", "trust", "loc-iq"],
  },

  // BUILD & AI SYSTEMS
  {
    id: "rag",
    term: "Retrieval-Augmented Generation",
    acronym: "RAG",
    meaning: "Architecture retrieving relevant domain knowledge and supplying it as prompt context to an LLM at runtime.",
    remember: "Retrieve first, generate with context second.",
    project: "Build",
    category: "Build",
    href: "/notebook/build",
    comparison: { vsTerm: "Fine-Tuning", diff: "RAG injects dynamic external knowledge at request time; fine-tuning changes model weights permanently." },
    tags: ["rag", "llm", "ai"],
  },
  {
    id: "workflow_vs_agent",
    term: "Workflow vs Agent",
    meaning: "Workflows follow developer-defined paths; Agents use model-directed loops to choose tools dynamically.",
    remember: "Known path → workflow. Dynamic path → consider agent.",
    project: "Build",
    category: "Build",
    href: "/notebook/build",
    comparison: { vsTerm: "Agent", diff: "Workflow has hardcoded path; Agent lets model decide next action dynamically." },
    trap: { wrong: "An LLM workflow is automatically an agent.", correction: "An agent specifically requires model-directed dynamic tool selection." },
    tags: ["agent", "workflow", "ai"],
  },
  {
    id: "guardrail",
    term: "System Guardrail",
    meaning: "Constraint on input, output, or action enforced in code close to system execution.",
    remember: "Model decides. Tool does. Guardrails enforce rules in code.",
    project: "Build",
    category: "Build",
    href: "/notebook",
    tags: ["guardrail", "eval", "trace"],
  },
];

export const projectFlowsList = [
  { project: "Credit Risk", flow: "Default → PD → Validate → LGD/EAD → ECL → RWA → Monitor", href: "/notebook" },
  { project: "Churn", flow: "Data → Network → Probability → Threshold → Confusion Matrix → Trade-off", href: "/notebook" },
  { project: "Time Series", flow: "Series → Stationarity → Differencing → SARIMA → Residuals → Holdout", href: "/notebook" },
  { project: "NIFTY", flow: "Prices → Returns → Covariance → Weights → Risk/Return Cloud", href: "/notebook" },
  { project: "Client Equity", flow: "Universe → Signals → Rank → Portfolio → Turnover → Robustness", href: "/notebook" },
  { project: "LOC-IQ", flow: "Identifiers → Sources → Fields → Signals → Candidates → Truth Flag", href: "/notebook" },
  { project: "How I Build", flow: "Frame → Map → Ground → Method → Build → Evidence → Interface", href: "/notebook" },
];

export const compactMetricCards = [
  { project: "Credit Risk", stats: "466,285 loans · $278.48M ECL · $2.295B RWA", href: "/notebook" },
  { project: "Churn", stats: "10,000 customers · 0.48 → 0.75 recall · 0.51 SMOTE precision", href: "/notebook" },
  { project: "Time Series", stats: "204 months · 625 models · 12.69% → 7.90% MAPE", href: "/notebook" },
  { project: "NIFTY", stats: "82 stocks · 10,000 portfolios · 0.7707 simplified score", href: "/notebook" },
  { project: "Client Equity", stats: "CRSP 500 · 10 years · 4 scripts · No performance claim", href: "/notebook" },
  { project: "LOC-IQ", stats: "6 identifiers · 46 mapped sources · 42 fields · Static scenarios", href: "/notebook" },
];
