import type { Concept } from '../types';

// PLACEHOLDER concepts (verified: false). The architect's content pack replaces this file.
const c = (x: Omit<Concept, 'verified' | 'links'> & { links?: string[] }): Concept => ({ links: [], ...x, verified: false });

export const concepts: Concept[] = [
  c({ id: 'balance-sheet', district: 'mint', layer: 'F', name: 'The bank balance sheet', anchor: 'mint-scales', prerequisites: [],
    oneLiner: 'Loans are the bank’s assets; deposits are its liabilities; equity absorbs losses.',
    explanation: 'A bank borrows (deposits, funding) and lends (loans). **Assets = liabilities + equity.** When a loan loses value, equity shrinks first — that is why capital matters.',
    whyItMatters: 'Every credit number you will build ends up on one line of this sheet.' }),
  c({ id: 'time-value', district: 'mint', layer: 'F', name: 'Time value of money', anchor: 'mint-clock', prerequisites: [],
    oneLiner: 'Money received later is worth less today; discounting converts it back.',
    explanation: 'Present value = future cash ÷ (1 + rate)^years. A recovery of ₹100 in one year at 10% is worth ₹90.91 today.',
    whyItMatters: 'Loss estimates discount recoveries, so slow recoveries cost more.' }),
  c({ id: 'obligor-facility', district: 'market', layer: 'F', name: 'Obligor → facility → account', anchor: 'market-boxes', prerequisites: [],
    oneLiner: 'Who owes (obligor), under which agreement (facility), recorded where (account).',
    explanation: 'One obligor can hold several facilities; a facility can have several accounts. Default is usually judged at obligor level, so trouble on one facility can pull the others in.',
    whyItMatters: 'Wrong grain = double-counted or missing exposure in every report.' }),
  c({ id: 'funded-unfunded', district: 'market', layer: 'F', name: 'Funded vs unfunded exposure', anchor: 'market-tap', prerequisites: ['obligor-facility'],
    oneLiner: 'Drawn money is funded; undrawn commitments and guarantees are unfunded but still risky.',
    explanation: 'A ₹10 crore line with ₹6 crore drawn has ₹4 crore undrawn. Borrowers in trouble tend to draw more, so the undrawn part is converted into exposure with a conversion factor.',
    whyItMatters: 'Limits, EAD and capital all treat the undrawn part differently.' }),
  c({ id: 'repayment-capacity', district: 'branch', layer: 'F', name: 'Repayment capacity (DSCR)', anchor: 'branch-gauge', prerequisites: [],
    oneLiner: 'Loans are repaid from cash, so compare cash available with debt service due.',
    explanation: 'DSCR = cash available for debt service ÷ scheduled interest + principal. Below 1.0 the borrower cannot pay from operations alone.',
    whyItMatters: 'It is the first test in almost every commercial credit policy.',
    misconception: '“Profitable means able to repay.” Profit is not cash; timing and working capital matter.' }),
  c({ id: 'risk-based-pricing', district: 'branch', layer: 'W', name: 'Risk-based pricing', anchor: 'branch-stamp', prerequisites: ['repayment-capacity'],
    oneLiner: 'Rate = funding cost + expected loss + capital charge + costs + margin.',
    explanation: 'Each component is an annual rate on exposure. Riskier loans need more for expected loss and consume more capital.',
    whyItMatters: 'Pricing engines and their data feeds are frequent BA projects.' }),
  c({ id: 'collateral-haircut', district: 'registry', layer: 'F', name: 'Collateral and haircuts', anchor: 'registry-scissors', prerequisites: [],
    oneLiner: 'Collateral reduces loss if default happens, after cutting its value for sale risk.',
    explanation: 'Recoverable value = market value × (1 − haircut). Collateral lowers loss severity, not the chance of default.',
    whyItMatters: 'Allocation of shared collateral is a classic data-mapping trap.',
    misconception: '“Collateral makes the borrower safe.” It reduces LGD, not PD.' }),
  c({ id: 'dpd-delinquency', district: 'watchtower', layer: 'F', name: 'Days past due and delinquency', anchor: 'watch-clock', prerequisites: ['obligor-facility'],
    oneLiner: 'Days past due counts how late the oldest unpaid instalment is.',
    explanation: 'Buckets: current, 1–30, 31–60, 61–90, 90+. More than 90 days past due is the common payment trigger for default.',
    whyItMatters: 'DPD logic drives staging, default and reporting — and payment-allocation bugs break it.' }),
  c({ id: 'early-warning', district: 'watchtower', layer: 'W', name: 'Early-warning indicators', anchor: 'watch-board', prerequisites: ['dpd-delinquency'],
    oneLiner: 'Signals of stress that appear before missed payments.',
    explanation: 'Rating downgrades, covenant breaches, falling sales, heavy line usage and adverse news can put a borrower on a watchlist.',
    whyItMatters: 'Watchlist flags feed staging rules the BA must specify.' }),
  c({ id: 'default-definition', district: 'recovery', layer: 'F', name: 'Default definition', anchor: 'recovery-gate', prerequisites: ['dpd-delinquency'],
    oneLiner: 'Default = more than 90 days past due or judged unlikely to pay.',
    explanation: 'Unlikeliness to pay (UTP) catches borrowers before 90 days. Default is usually obligor-level: every facility of that borrower is treated as defaulted.',
    whyItMatters: 'One definition must feed accounting, capital and reporting consistently.' }),
  c({ id: 'lgd-realised', district: 'recovery', layer: 'F', name: 'Realised loss and write-off', anchor: 'recovery-crane', prerequisites: ['default-definition'],
    oneLiner: 'Loss = what was owed minus the present value of what was recovered.',
    explanation: 'Recoveries arrive late and cost money. A write-off removes the unrecoverable balance from the books; it does not cancel the legal debt.',
    whyItMatters: 'Realised losses are the evidence used to build and test LGD models.' }),
  c({ id: 'pd', district: 'observatory', layer: 'F', name: 'Probability of default (PD)', anchor: 'obs-telescope', prerequisites: [],
    oneLiner: 'The chance a borrower defaults within a stated horizon.',
    explanation: 'Always state the horizon (12-month or lifetime) and the default definition. A 2% PD does not mean exactly 2 defaults in every 100.',
    whyItMatters: 'Every PD field needs horizon, definition and as-of date in the data model.' }),
  c({ id: 'expected-loss', district: 'observatory', layer: 'F', name: 'Expected loss', anchor: 'obs-scale', prerequisites: ['pd'],
    oneLiner: 'EL = PD × LGD × EAD, with consistent horizons and definitions.',
    explanation: 'PD is the chance, LGD the share lost if default happens, EAD the exposure at that time. Their product is an average, not a forecast of any single loan.',
    whyItMatters: 'The same three parameters feed pricing, provisions and capital.' }),
  c({ id: 'discrimination-calibration', district: 'modellab', layer: 'F', name: 'Discrimination vs calibration', anchor: 'lab-roc', prerequisites: ['pd'],
    oneLiner: 'Ranking risk well is different from predicting the right level of risk.',
    explanation: 'Gini/AUC measure ranking. Calibration checks predicted PDs against observed default rates. A model can rank well and still be badly calibrated.',
    whyItMatters: 'Validation findings usually come down to one of these two.' }),
  c({ id: 'counterparty-exposure', district: 'trading', layer: 'F', name: 'Counterparty exposure', anchor: 'trading-seesaw', prerequisites: ['obligor-facility'],
    oneLiner: 'A derivative’s exposure is its replacement cost, not its notional.',
    explanation: 'A swap with ₹100 crore notional may be worth ₹2 crore to you today; that positive value is what you lose if the counterparty defaults, and it moves with markets.',
    whyItMatters: 'Netting and collateral data decide the exposure the bank reports.' }),
  c({ id: 'ifrs9-stages', district: 'vault', layer: 'F', name: 'IFRS 9 stages', anchor: 'vault-doors', prerequisites: ['expected-loss'],
    oneLiner: 'Stage 1: 12-month ECL. Stage 2: lifetime ECL. Stage 3: credit-impaired, lifetime ECL.',
    explanation: 'Every loan starts in Stage 1 with a day-1 provision. A significant increase in credit risk moves it to Stage 2; default moves it to Stage 3.',
    whyItMatters: 'Stage rules are among the most-specified logic in any ECL engine.',
    misconception: '“Stage 2 means default.” Stage 2 is deterioration; Stage 3 is default.' }),
  c({ id: 'sicr', district: 'vault', layer: 'F', name: 'Significant increase in credit risk (SICR)', anchor: 'vault-door2', prerequisites: ['ifrs9-stages'],
    oneLiner: 'Compare today’s default risk with the risk at origination.',
    explanation: 'Triggers include a relative PD increase, more than 30 days past due (a rebuttable backstop) and watchlist status. Curing out of Stage 2 needs the triggers to clear.',
    whyItMatters: 'A BA writes these triggers as testable rules with thresholds and probation.' }),
  c({ id: 'provisions-vs-capital', district: 'fortress', layer: 'F', name: 'Provisions vs capital', anchor: 'fort-walls', prerequisites: ['expected-loss'],
    oneLiner: 'Provisions cover expected loss; capital absorbs unexpected loss.',
    explanation: 'Under IRB, capital is calibrated to losses at a high confidence level above expected loss. This is the calibration intuition; buffers, Pillar 2 and the leverage ratio sit on top.',
    whyItMatters: 'Mixing the two is the most common conceptual error in credit reporting.' }),
  c({ id: 'rwa-capital-ratio', district: 'fortress', layer: 'F', name: 'RWA and the capital ratio', anchor: 'fort-weights', prerequisites: ['provisions-vs-capital'],
    oneLiner: 'Capital ratio = eligible capital ÷ risk-weighted assets.',
    explanation: 'RWA = exposure × risk weight. Losses reduce capital; riskier or defaulted exposures raise RWA — both push the ratio down.',
    whyItMatters: 'Exposure class, CCF and risk-weight mappings are BA-owned rules.' }),
  c({ id: 'concentration', district: 'storm', layer: 'F', name: 'Concentration', anchor: 'storm-pie', prerequisites: [],
    oneLiner: 'Many loans exposed to the same driver can fail together.',
    explanation: 'Concentration by name, group, sector or region defeats diversification when a shared shock arrives.',
    whyItMatters: 'Limit frameworks need clean group and sector hierarchies.' }),
  c({ id: 'securitisation', district: 'port', layer: 'D', name: 'Securitisation', anchor: 'port-containers', prerequisites: ['expected-loss'],
    oneLiner: 'Pool loans and pass their cash flows and losses to investors in tranches.',
    explanation: 'Junior tranches take losses first. Accounting derecognition and regulatory risk transfer are separate tests.',
    whyItMatters: 'Deep topic for now — know where it sits in the city.' }),
  c({ id: 'reporting-purpose', district: 'reporting', layer: 'F', name: 'Reporting purposes', anchor: 'report-clock', prerequisites: [],
    oneLiner: 'Financial statements, prudential returns and management reports answer different questions.',
    explanation: 'The same loan can show different numbers in each because definitions, scope and timing differ. Reconcile differences; never force them to match.',
    whyItMatters: 'Explaining reconciling items is core BA work.' }),
  c({ id: 'data-lineage', district: 'engineroom', layer: 'F', name: 'Data lineage', anchor: 'engine-pipes', prerequisites: [],
    oneLiner: 'Trace any number from source record, through each transformation, to the report.',
    explanation: 'Lineage records source fields, rules applied, and the target. Without it, nobody can explain or correct a reported figure.',
    whyItMatters: 'BCBS 239 expects banks to evidence it.' }),
  c({ id: 'three-lines', district: 'townhall', layer: 'F', name: 'Three lines of defence', anchor: 'hall-table', prerequisites: [],
    oneLiner: 'Business owns risk, risk management challenges it, audit assures independently.',
    explanation: 'The first line originates and manages risk, the second sets limits and challenges, the third tests the whole system.',
    whyItMatters: 'Knowing who signs off prevents requirements from stalling.' }),
  c({ id: 'jurisdiction-rulebooks', district: 'embassy', layer: 'F', name: 'Global standards vs local rulebooks', anchor: 'embassy-flags', prerequisites: [],
    oneLiner: 'Basel and IFRS set standards; each country implements its own version and dates.',
    explanation: 'Always check which rulebook, version and effective date apply before encoding a rule.',
    whyItMatters: 'Rule provenance is a requirement, not an afterthought.',
    embassy: { IN: 'RBI IRAC norms define NPAs; the RBI ECL framework has its own start date.', UK: 'PRA rules implement Basel 3.1.', EU: 'CRR3/CRD6.', US: 'CECL for accounting; US capital rules separately.' } }),
  c({ id: 'requirement-to-test', district: 'studio', layer: 'F', name: 'Rule → requirement → test → evidence', anchor: 'studio-thread', prerequisites: [],
    oneLiner: 'Translate each business rule into a testable requirement with evidence of passing.',
    explanation: 'A good requirement states the rule, the data it needs, thresholds, precedence, edge cases, and acceptance criteria a tester can prove.',
    whyItMatters: 'This is the BA’s core deliverable in every credit risk change.' }),
];
