import type { Item } from '../types';

export const branchItems: Item[] = [
  { id: 'anchor-branch', conceptIds: ['repayment-capacity'], difficulty: 1, prompt: 'Palace Walk: where does the DSCR gauge live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'branch-gauge', options: ['The Branch', 'The Watchtower', 'The Registry', 'The Mint'], answerIndex: 0 },
    explanation: 'Repayment capacity is judged at the analyst’s desk in the Branch.' },
  { id: 'branch-5cs-classify', conceptIds: ['five-cs'], difficulty: 1, prompt: 'Which C does each fact speak to?',
    payload: { type: 'classify', buckets: ['Character', 'Capacity', 'Capital', 'Collateral', 'Conditions'], entries: [
      { text: 'The promoter has repaid every past loan on time', bucket: 0 }, { text: 'DSCR of 1.4×', bucket: 1 }, { text: 'Net worth of ₹12 crore invested in the business', bucket: 2 },
      { text: 'The factory is mortgaged to the bank', bucket: 3 }, { text: 'Steel prices are falling sharply', bucket: 4 }] },
    explanation: 'Will pay, can pay, own money at stake, fallback, and the world around the borrower.' },
  { id: 'branch-5cs-recall', conceptIds: ['five-cs'], difficulty: 1, prompt: 'From memory: name the five Cs of credit.',
    payload: { type: 'recall', modelAnswer: 'Character, capacity, capital, collateral, conditions.',
      keyPoints: [{ text: 'Character', essential: false }, { text: 'Capacity', essential: true }, { text: 'Capital', essential: false }, { text: 'Collateral', essential: false }, { text: 'Conditions', essential: false }] },
    explanation: 'Capacity is the one that repays the loan.' },
  { id: 'branch-profit-spot', conceptIds: ['repayment-capacity'], difficulty: 2, prompt: 'Repayment capacity: which statement is wrong?',
    payload: { type: 'spot', options: ['DSCR compares cash with scheduled debt service.', 'A profitable borrower can always repay.', 'Working-capital needs can absorb operating cash.', 'DSCR below 1.0 means operations alone cannot cover debt service.'], answerIndex: 1 },
    explanation: 'Profit is not cash. Timing, working capital and existing debts can leave a profitable firm unable to pay.' },
  { id: 'branch-dscr-calc', conceptIds: ['repayment-capacity'], difficulty: 2, prompt: 'Cash available for debt service is ₹9 crore. Interest due is ₹3 crore and principal due is ₹4.5 crore. What is the DSCR?',
    payload: { type: 'calculate', answer: 1.2, tolerance: { kind: 'abs', value: 0.005 }, unit: '×', worked: ['Debt service = 3 + 4.5 = 7.5', 'DSCR = 9 ÷ 7.5', '= 1.2'] },
    explanation: 'Principal counts too: 9 ÷ 7.5 = 1.2×.' },
  { id: 'branch-lev-calc', conceptIds: ['financial-ratios'], difficulty: 1, prompt: 'Total debt ₹30 crore, EBITDA ₹7.5 crore. What is debt ÷ EBITDA?',
    payload: { type: 'calculate', answer: 4, tolerance: { kind: 'abs', value: 0.01 }, unit: '×', worked: ['Leverage = 30 ÷ 7.5', '= 4.0×'] },
    explanation: 'Four years of EBITDA to repay the debt.' },
  { id: 'branch-icr-calc', conceptIds: ['financial-ratios'], difficulty: 1, prompt: 'EBITDA ₹10 crore, interest expense ₹4 crore. What is the interest cover?',
    payload: { type: 'calculate', answer: 2.5, tolerance: { kind: 'abs', value: 0.01 }, unit: '×', worked: ['Interest cover = EBITDA ÷ interest', '= 10 ÷ 4', '= 2.5×'] },
    explanation: 'Earnings cover interest 2.5 times.' },
  { id: 'branch-ratio-classify', conceptIds: ['financial-ratios'], difficulty: 2, prompt: 'Which question does each ratio answer?',
    payload: { type: 'classify', buckets: ['How much debt?', 'Is interest covered?', 'Can short-term bills be paid?'], entries: [
      { text: 'Debt ÷ EBITDA', bucket: 0 }, { text: 'EBITDA ÷ interest expense', bucket: 1 }, { text: 'Current assets ÷ current liabilities', bucket: 2 }] },
    explanation: 'Leverage, coverage, liquidity.' },
  { id: 'branch-decision-sequence', conceptIds: ['credit-decision'], difficulty: 2, prompt: 'Put a credit decision in order.',
    payload: { type: 'sequence', steps: ['Policy knock-out rules', 'Score or rating', 'Structure and pricing', 'Approval at the right authority level', 'Documentation and disbursement'] },
    explanation: 'Eligibility first, then risk, then terms, then the right person signs, then money moves.' },
  { id: 'branch-decision-spot', conceptIds: ['credit-decision'], difficulty: 2, prompt: 'Credit decisioning: which statement is wrong?',
    payload: { type: 'spot', options: ['Hard policy rules are checked before the score.', 'A high score automatically overrides a hard policy knock-out.', 'Approval authority depends on amount and risk.', 'Overrides of the model must be recorded.'], answerIndex: 1 },
    explanation: 'Knock-outs are knock-outs. Overrides go through authority and are logged, never automatic.' },
  { id: 'branch-decision-recall', conceptIds: ['credit-decision'], difficulty: 2, prompt: 'From memory: in what order does a credit decision run, and what happens to overrides?',
    payload: { type: 'recall', modelAnswer: 'Policy knock-out rules first, then the score or rating, then structure and pricing, then approval by someone with enough delegated authority for the amount and risk. Overrides of the model are allowed but recorded and monitored.',
      keyPoints: [{ text: 'Policy rules before the score', essential: true }, { text: 'Approval by delegated authority for amount and risk', essential: true }, { text: 'Overrides recorded and monitored', essential: false }] },
    explanation: 'Order and authority are the rules a decision engine must enforce.' },
  { id: 'branch-cov-choice', conceptIds: ['covenants'], difficulty: 2, prompt: 'Debt ÷ EBITDA rises to 4.5× against a covenant maximum of 4.0×. What follows?',
    payload: { type: 'choice', options: ['The loan is automatically in regulatory default', 'A covenant breach: the bank gains rights under the agreement, and it is an early-warning signal', 'Nothing happens until a payment is missed', 'The collateral is sold immediately'], answerIndex: 1 },
    explanation: 'A breach gives the bank options (waive, reprice, tighten, call) and a signal — not an automatic default.' },
  { id: 'branch-cov-recall', conceptIds: ['covenants'], difficulty: 2, prompt: 'From memory: name three kinds of covenant with an example of each.',
    payload: { type: 'recall', modelAnswer: 'Financial (maximum debt ÷ EBITDA, minimum DSCR), information (audited financials within a deadline), negative (no pledging assets to other lenders).',
      keyPoints: [{ text: 'Financial covenant with a ratio', essential: true }, { text: 'Information covenant', essential: false }, { text: 'Negative covenant', essential: false }] },
    explanation: 'Limits, disclosure and restrictions.' },
  { id: 'branch-pricing-choice', conceptIds: ['risk-based-pricing'], difficulty: 2, prompt: 'Two loans have the same funding cost and margin. Borrower B has a higher PD. Under risk-based pricing, B’s rate is higher because…',
    payload: { type: 'choice', options: ['It must cover higher expected loss and more capital', 'Riskier borrowers pay higher fees by law', 'Its funding is more expensive', 'The branch wants a higher margin'], answerIndex: 0 },
    explanation: 'Expected loss and the capital charge both rise with risk.' },
];
