import type { Item } from '../types';

const i = (x: Omit<Item, 'placeholder'>): Item => ({ ...x, placeholder: true });

// PLACEHOLDER case items for the placeholder SME case (the real case replaces these).
export const caseItems: Item[] = [
  i({ id: 'case-apply-obligor', conceptIds: ['obligor-facility'], difficulty: 1, prompt: 'The auto-parts maker asks for a term loan and a working-capital line. How many obligors and facilities is that?',
    payload: { type: 'choice', options: ['One obligor, one facility', 'One obligor, two facilities', 'Two obligors, two facilities', 'Two obligors, one facility'], answerIndex: 1 },
    explanation: 'One legal borrower (obligor) holding two separate agreements (facilities).' }),
  i({ id: 'case-analyse-dscr', conceptIds: ['repayment-capacity'], difficulty: 1, prompt: 'Cash available for debt service is ₹6.0 crore a year; scheduled interest plus principal is ₹4.8 crore. What is the DSCR?',
    payload: { type: 'calculate', answer: 1.25, tolerance: { kind: 'abs', value: 0.005 }, unit: '×', worked: ['DSCR = cash available ÷ debt service', '= 6.0 ÷ 4.8', '= 1.25'] },
    explanation: '6.0 ÷ 4.8 = 1.25: cash covers debt service 1.25 times.' }),
  i({ id: 'case-decide-price', conceptIds: ['risk-based-pricing'], difficulty: 3,
    prompt: 'Price the term loan (annual %). FTP 7%, PD 0.5%, LGD 40%, SME risk weight 85%, target CET1 11%, hurdle 15%, opex 1%, margin 0.8%.',
    payload: { type: 'calculate', answer: 10.4025, tolerance: { kind: 'abs', value: 0.05 }, unit: '%',
      worked: ['Expected loss = 0.5% × 40% = 0.20%', 'Capital charge = 85% × 11% × 15% = 1.4025%', 'Rate = 7 + 0.20 + 1.4025 + 1 + 0.8', '= 10.40%'] },
    explanation: 'Funding 7.00 + EL 0.20 + capital 1.40 + opex 1.00 + margin 0.80 = 10.40%.' }),
  i({ id: 'case-recover-writeoff', conceptIds: ['collateral-haircut'], difficulty: 2,
    prompt: 'The plant is sold after values fall a further 10%. Compared with the Stage 3 allowance held at default, the term-loan write-off will be…',
    payload: { type: 'predict', options: ['Lower', 'About the same', 'Higher'], answerIndex: 2, bindTo: 'facility:tl1:writtenOff' },
    explanation: 'Weaker sale proceeds plus interest that kept accruing mean the write-off exceeds the allowance held at default.' }),
  i({ id: 'case-monitor-stage', conceptIds: ['early-warning'], difficulty: 1,
    prompt: 'Seven months of on-time payments; the line is drawn harder and collateral values dip 5%. Where is the term loan?',
    payload: { type: 'predict', options: ['Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 0, bindTo: 'facility:tl1:stage' },
    explanation: 'No trigger has fired: payments are current, the rating is unchanged, and a small collateral dip changes LGD, not staging.' }),
  i({ id: 'case-default-wc', conceptIds: ['default-definition'], difficulty: 2,
    prompt: 'The working-capital line is still paid on time. After the borrower defaults, what stage is that line in?',
    payload: { type: 'predict', options: ['Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 2, bindTo: 'facility:wc1:stage' },
    explanation: 'Default is judged at obligor level, so every facility of the borrower becomes credit-impaired.' }),
  i({ id: 'case-default-s3ratio', conceptIds: ['default-definition'], difficulty: 3,
    prompt: 'Predict the bank’s Stage 3 ratio after the default (Stage 3 loans ÷ all loans), within 3 percentage points. Enter a decimal, e.g. 0.07.',
    payload: { type: 'predict', numeric: { tolerance: { kind: 'abs', value: 0.03 }, unit: 'ratio' }, bindTo: 'kpi:stage3Ratio' },
    explanation: 'Both SME facilities (about ₹26 crore) move to Stage 3 in a book of about ₹250 crore: roughly 10%.' }),
  i({ id: 'case-writeoff-sequence', conceptIds: ['lgd-realised'], difficulty: 2, prompt: 'Order what happened to the term loan after default.',
    payload: { type: 'sequence', steps: ['Default: Stage 3 allowance set', 'Collateral sold', 'Unrecovered balance written off', 'Later recovery booked as income'] },
    explanation: 'Allowance first, then realisation, then write-off; post-write-off recoveries go to profit and loss.' }),
  i({ id: 'case-book-ecl', conceptIds: ['ifrs9-stages'], difficulty: 1, prompt: 'The loans are booked today and nothing has gone wrong. What provision does the bank hold on the term loan?',
    payload: { type: 'predict', options: ['None — nothing has gone wrong yet', '12-month expected credit loss (Stage 1)', 'Lifetime expected credit loss', 'The full loan amount'], answerIndex: 1, bindTo: 'facility:tl1:stage' },
    explanation: 'IFRS 9 is forward-looking: a Stage 1 allowance and a P&L charge exist from day 1.' }),
  i({ id: 'case-slip-stage', conceptIds: ['sicr'], difficulty: 2, prompt: 'Two instalments are missed and the borrower is downgraded two notches. Where does the term loan go?',
    payload: { type: 'predict', options: ['Stays in Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 1, bindTo: 'facility:tl1:stage' },
    explanation: 'More than 30 days past due and a large PD increase are SICR triggers: Stage 2, but not yet default.' }),
  i({ id: 'case-slip-ecl', conceptIds: ['sicr'], difficulty: 3, prompt: 'By how much does the term loan’s provision grow when it moves to Stage 2?',
    payload: { type: 'predict', options: ['Stays about the same', 'Roughly doubles', 'Grows about 5–15 times', 'Grows more than 50 times'], answerIndex: 2, bindTo: 'facility:tl1:ecl' },
    explanation: 'Two effects multiply: a higher PD, and a lifetime horizon instead of 12 months.' }),
  i({ id: 'case-report-explain', conceptIds: ['reporting-purpose'], difficulty: 3, prompt: 'Using the case: explain what happened to the Stage 3 ratio and the CET1 ratio from default to write-off.',
    payload: { type: 'explain', modelAnswer: 'At default the Stage 3 ratio jumped and CET1 fell with the Stage 3 charge. After recovery and write-off the loans left the book, so the Stage 3 ratio fell back to zero, while CET1 kept the loss; later earnings and the post-write-off recovery rebuilt it.',
      keyPoints: [{ text: 'Stage 3 ratio jumps at default', essential: true }, { text: 'CET1 falls by the impairment charge', essential: true }, { text: 'Write-off removes loans, so the Stage 3 ratio falls', essential: true }, { text: 'Post-write-off recovery is income', essential: false }] },
    explanation: 'A falling Stage 3 ratio after write-offs is not an improvement in credit quality — read ratios with their movements.' }),
  i({ id: 'case-ba-stage2', conceptIds: ['requirement-to-test'], difficulty: 3, prompt: 'Write the requirement for the Stage 2 trigger used in the case. Then self-check against the key points.',
    payload: { type: 'recall', modelAnswer: 'Move a facility to Stage 2 when it is not in default and any trigger is true: more than 30 days past due, current 12-month PD ≥ 2× origination PD, or watchlist. Exit to Stage 1 only after all triggers are false for 3 consecutive months. Data: DPD, current and origination PD, watchlist flag. Test: a facility at 31 DPD moves to Stage 2; at 2 clear months it stays in Stage 2; at 3 it returns to Stage 1.',
      keyPoints: [{ text: 'All three triggers with thresholds', essential: true }, { text: 'Excludes defaulted facilities', essential: false }, { text: 'Exit rule with probation', essential: true }, { text: 'Required data fields', essential: false }, { text: 'At least one boundary test', essential: true }] },
    explanation: 'Thresholds, precedence, exits, data and a boundary test — that is a testable requirement.' }),
];
