import type { Item } from '../types';

export const embassyItems: Item[] = [
  { id: 'anchor-embassy', conceptIds: ['jurisdiction-rulebooks'], difficulty: 1, prompt: 'Palace Walk: four flags fly side by side. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'embassy-flags', options: ['Global standards vs local rulebooks', 'Securitisation', 'Data quality', 'The five Cs of credit'], answerIndex: 0 },
    explanation: 'One standard, four embassies, four versions.' },
  { id: 'embassy-choice', conceptIds: ['jurisdiction-rulebooks'], difficulty: 2, prompt: 'Before encoding a capital rule, what must you confirm first?',
    payload: { type: 'choice', options: ['The Basel paragraph only', 'The applicable local rulebook, version and effective date', 'What another bank does', 'The latest consultation paper'], answerIndex: 1 },
    explanation: 'Basel is a standard; local law, version and date decide what applies.' },
  { id: 'embassy-rule-recall', conceptIds: ['jurisdiction-rulebooks'], difficulty: 1, prompt: 'From memory: why can’t a bank apply Basel text directly?',
    payload: { type: 'recall', modelAnswer: 'Basel (and the IASB) have no legal power; national regulators implement the standards in local law, often with changes and on their own dates. The bank must follow its local rulebook.',
      keyPoints: [{ text: 'Basel has no legal force', essential: true }, { text: 'Local regulators implement it', essential: true }, { text: 'With changes and their own dates', essential: false }] },
    explanation: 'Standards are recommendations until a regulator makes them law.' },
  { id: 'embassy-irac-classify', conceptIds: ['india-irac'], difficulty: 2, prompt: 'Classify each loan under IRAC.',
    payload: { type: 'classify', buckets: ['Standard', 'Sub-standard', 'Doubtful'], entries: [
      { text: '45 days overdue', bucket: 0 }, { text: 'NPA for 5 months', bucket: 1 }, { text: 'NPA for 18 months', bucket: 2 }, { text: 'Paying on time', bucket: 0 }] },
    explanation: 'NPA after 90 days overdue; sub-standard for the first 12 months as an NPA; doubtful after that.' },
  { id: 'embassy-irac-calc', conceptIds: ['india-irac'], difficulty: 1, prompt: 'A sub-standard loan of ₹100 crore needs a 15% provision. How much (₹ crore)?',
    payload: { type: 'calculate', answer: 15, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['15% × 100 = 15'] },
    explanation: 'IRAC provisions step up with the asset category.' },
  { id: 'embassy-ukeu-choice', conceptIds: ['uk-eu-basel31'], difficulty: 2, prompt: 'The same final Basel III reforms start on different dates. Which pairing is right?',
    payload: { type: 'choice', options: ['EU CRR3 from 1 Jan 2025; UK Basel 3.1 from 1 Jan 2027', 'Both from 1 Jan 2023', 'UK first, EU in 2030', 'Neither has adopted them'], answerIndex: 0 },
    explanation: 'Same standard, different laws and timetables.' },
  { id: 'embassy-ukeu-recall', conceptIds: ['uk-eu-basel31'], difficulty: 2, prompt: 'From memory: what does a cross-border bank have to do when the EU and UK implement Basel differently?',
    payload: { type: 'recall', modelAnswer: 'Map the same portfolio to both rulebooks: different exposure classes, risk weights, transitional rules and dates — and report each regulator’s version.',
      keyPoints: [{ text: 'Map one portfolio to two rulebooks', essential: true }, { text: 'Differences in classes, weights, transitions, dates', essential: false }, { text: 'Report each regulator’s version', essential: true }] },
    explanation: 'Two rulebooks, one book of loans.' },
  { id: 'embassy-us-classify', conceptIds: ['us-framework'], difficulty: 2, prompt: 'United States: which part of the framework is each?',
    payload: { type: 'classify', buckets: ['Accounting', 'Capital', 'Stress testing'], entries: [
      { text: 'CECL lifetime expected losses', bucket: 0 }, { text: 'Rules from the Federal Reserve, OCC and FDIC', bucket: 1 }, { text: 'Stress capital buffer set by supervisory results', bucket: 2 }] },
    explanation: 'Provisions, capital rules, stress tests — three separate sources.' },
  { id: 'embassy-us-recall', conceptIds: ['us-framework'], difficulty: 2, prompt: 'From memory: name the US provisioning standard, the capital regulators, and how stress tests affect capital.',
    payload: { type: 'recall', modelAnswer: 'CECL (US GAAP) for provisions; the Federal Reserve, OCC and FDIC for capital rules; supervisory stress-test results set each large bank’s stress capital buffer.',
      keyPoints: [{ text: 'CECL', essential: true }, { text: 'Fed, OCC, FDIC', essential: false }, { text: 'Stress tests set the stress capital buffer', essential: true }] },
    explanation: 'Accounting, capital and stress testing arrive from different places.' },
  { id: 'embassy-sbr-choice', conceptIds: ['nbfc-sbr'], difficulty: 1, prompt: 'Under RBI scale-based regulation, which NBFCs face the most bank-like rules?',
    payload: { type: 'choice', options: ['Base layer', 'Middle layer', 'Upper layer', 'All layers equally'], answerIndex: 2 },
    explanation: 'Bigger and more connected means stricter; the top layer is reserved for exceptional cases.' },
  { id: 'embassy-sbr-recall', conceptIds: ['nbfc-sbr'], difficulty: 2, prompt: 'From memory: name the four layers of RBI scale-based regulation and the accounting standard NBFCs provision under.',
    payload: { type: 'recall', modelAnswer: 'Base, middle, upper and top layers, by size and risk. NBFCs provision under Ind AS 109, which is based on IFRS 9.',
      keyPoints: [{ text: 'Base, middle, upper, top', essential: true }, { text: 'Layer set by size and risk', essential: false }, { text: 'Ind AS 109 (IFRS 9-based)', essential: true }] },
    explanation: 'Your NBFC client’s layer decides its rulebook.' },
];
