import type { Item } from '../types';

export const engineroomItems: Item[] = [
  { id: 'engine-anchor', conceptIds: ['data-lineage'], difficulty: 1, prompt: 'Palace Walk: beneath the city, the pipes. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'engine-pipes', options: ['Data lineage', 'Securitisation', 'Credit valuation adjustment', 'Collateral and haircuts'], answerIndex: 0 },
    explanation: 'Pipes carry every number from source to report.' },
  { id: 'engine-lineage-sequence', conceptIds: ['data-lineage'], difficulty: 1, prompt: 'Trace a reported Stage 3 figure back from the report.',
    payload: { type: 'sequence', steps: ['Reported Stage 3 total', 'ECL engine output by facility', 'Staging rule applied to DPD and default flag', 'DPD computed in the data platform', 'Payment records in the loan system'] },
    explanation: 'Lineage walks backwards through every rule to the source record.' },
  { id: 'engine-lineage-recall', conceptIds: ['data-lineage'], difficulty: 2, prompt: 'From memory: what does lineage record, and what three things does it let you do?',
    payload: { type: 'recall', modelAnswer: 'Source fields, each transformation and rule, and the target field. It lets you explain a reported number, assess the impact of a change, and fix errors at their source.',
      keyPoints: [{ text: 'Source → transformations → target', essential: true }, { text: 'Explain a number', essential: false }, { text: 'Assess change impact', essential: false }, { text: 'Fix errors at source', essential: false }] },
    explanation: 'Explain, assess, fix.' },
  { id: 'engine-239-choice', conceptIds: ['bcbs239'], difficulty: 2, prompt: 'What is BCBS 239 mainly about?',
    payload: { type: 'choice', options: ['Minimum capital ratios', 'Risk data aggregation and risk reporting', 'Liquidity coverage', 'Accounting for leases'], answerIndex: 1 },
    explanation: 'Can the bank aggregate accurate risk data quickly, especially in a crisis?' },
  { id: 'engine-239-recall', conceptIds: ['bcbs239'], difficulty: 2, prompt: 'From memory: name four qualities BCBS 239 expects of risk data aggregation.',
    payload: { type: 'recall', modelAnswer: 'Accuracy and integrity, completeness, timeliness, adaptability — underpinned by governance and infrastructure.',
      keyPoints: [{ text: 'Accuracy', essential: true }, { text: 'Completeness', essential: false }, { text: 'Timeliness', essential: false }, { text: 'Adaptability', essential: false }] },
    explanation: 'Right, whole, fast, flexible.' },
  { id: 'engine-dq-calc', conceptIds: ['data-quality'], difficulty: 1, prompt: '10,000 secured loans; 250 have no collateral value. What is completeness for that field (%)?',
    payload: { type: 'calculate', answer: 97.5, tolerance: { kind: 'abs', value: 0.05 }, unit: '%', worked: ['Complete = 10,000 − 250 = 9,750', '9,750 ÷ 10,000 = 97.5%'] },
    explanation: 'Measured against a threshold, not assumed.' },
  { id: 'engine-dq-classify', conceptIds: ['data-quality'], difficulty: 2, prompt: 'Which data-quality dimension does each rule test?',
    payload: { type: 'classify', buckets: ['Completeness', 'Validity', 'Timeliness', 'Uniqueness'], entries: [
      { text: 'Collateral value is not blank', bucket: 0 }, { text: 'LTV is between 0% and 200%', bucket: 1 },
      { text: 'Valuation is less than 12 months old', bucket: 2 }, { text: 'No loan ID appears twice', bucket: 3 }] },
    explanation: 'Present, plausible, current, one of each.' },
  { id: 'engine-arch-sequence', conceptIds: ['risk-data-architecture'], difficulty: 1, prompt: 'Order the flow of risk data.',
    payload: { type: 'sequence', steps: ['Source systems (origination, loan management, collateral, ledger)', 'Data platform', 'Risk engines (ECL, capital)', 'Reports and returns'] },
    explanation: 'Born in source, gathered, calculated, reported.' },
  { id: 'engine-arch-recall', conceptIds: ['risk-data-architecture'], difficulty: 2, prompt: 'From memory: what must be agreed at every hop between systems?',
    payload: { type: 'recall', modelAnswer: 'The keys that join records, the grain (account, facility, obligor), the timing or as-of date, and the definitions of each field.',
      keyPoints: [{ text: 'Keys', essential: true }, { text: 'Grain', essential: true }, { text: 'Timing / as-of date', essential: false }, { text: 'Field definitions', essential: false }] },
    explanation: 'Most breaks happen at the joins.' },
  { id: 'engine-ctrl-classify', conceptIds: ['controls'], difficulty: 1, prompt: 'Preventive or detective?',
    payload: { type: 'classify', buckets: ['Preventive', 'Detective'], entries: [
      { text: 'Maker-checker approval before a limit change', bucket: 0 }, { text: 'Monthly reconciliation to the ledger', bucket: 1 },
      { text: 'Input validation rejects a negative collateral value', bucket: 0 }, { text: 'Exception report of loans missing a rating', bucket: 1 }] },
    explanation: 'Stop it happening, or catch it after.' },
  { id: 'engine-ctrl-recall', conceptIds: ['controls'], difficulty: 2, prompt: 'From memory: what does every control need to be relied on?',
    payload: { type: 'recall', modelAnswer: 'A clear design (what it prevents or detects), an owner, a frequency, and evidence that it ran — automated where possible.',
      keyPoints: [{ text: 'An owner', essential: true }, { text: 'Evidence that it ran', essential: true }, { text: 'Clear design and frequency', essential: false }] },
    explanation: 'No evidence, no control.' },
];
