import type { Item } from '../types';

export const fortressItems: Item[] = [
  { id: 'anchor-fortress', conceptIds: ['provisions-vs-capital'], difficulty: 1, prompt: 'Palace Walk: where do the capital walls stand?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'fort-walls', options: ['Capital Fortress', 'Provision Vault', 'The Mint', 'Town Hall'], answerIndex: 0 },
    explanation: 'Capital is the fortress wall; provisions live next door in the Vault.' },
  { id: 'fort-spot', conceptIds: ['provisions-vs-capital'], difficulty: 2, prompt: 'Provisions and capital: which statement is wrong?',
    payload: { type: 'spot', options: ['Provisions address expected loss.', 'Capital absorbs unexpected loss.', 'Provisions are cash set aside in a vault.', 'Losses reduce CET1 through profit and loss.'], answerIndex: 2 },
    explanation: 'An allowance is an accounting reduction of the asset, not a pile of cash.' },
  { id: 'fort-pvc-recall', conceptIds: ['provisions-vs-capital'], difficulty: 1, prompt: 'From memory: what does each buffer cover — provisions and capital?',
    payload: { type: 'recall', modelAnswer: 'Provisions cover expected loss by reducing the carrying value of loans. Capital is equity that absorbs unexpected loss above that.',
      keyPoints: [{ text: 'Provisions → expected loss', essential: true }, { text: 'Capital → unexpected loss', essential: true }, { text: 'Neither is a cash pile', essential: false }] },
    explanation: 'Two buffers, two jobs.' },
  { id: 'fort-explain', conceptIds: ['rwa-capital-ratio'], difficulty: 3, prompt: 'Explain why a default pushes the capital ratio down from both sides.',
    payload: { type: 'explain', modelAnswer: 'The loss (provision charge) reduces CET1 in the numerator, while the defaulted exposure can carry a higher risk weight, raising RWA in the denominator.',
      keyPoints: [{ text: 'The provision charge reduces CET1 (numerator)', essential: true }, { text: 'Defaulted exposures can carry higher risk weights', essential: true }, { text: 'Higher RWA raises the denominator', essential: false }] },
    explanation: 'Numerator down, denominator up.' },
  { id: 'fort-rwa-calc', conceptIds: ['rwa-capital-ratio'], difficulty: 2, prompt: 'Exposures: ₹100 crore at 100%, ₹200 crore at 35%, ₹50 crore at 150% risk weight. What are the RWA (₹ crore)?',
    payload: { type: 'calculate', answer: 245, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['100 × 1.00 = 100', '200 × 0.35 = 70', '50 × 1.50 = 75', 'RWA = 245'] },
    explanation: 'Risk weights scale each exposure before adding.' },
  { id: 'fort-ratio-calc', conceptIds: ['rwa-capital-ratio'], difficulty: 1, prompt: 'CET1 is ₹24.5 crore and RWA are ₹245 crore. What is the CET1 ratio (%)?',
    payload: { type: 'calculate', answer: 10, tolerance: { kind: 'abs', value: 0.05 }, unit: '%', worked: ['CET1 ratio = 24.5 ÷ 245', '= 10%'] },
    explanation: 'Capital divided by risk-weighted assets.' },
  { id: 'fort-stack-sequence', conceptIds: ['capital-stack'], difficulty: 1, prompt: 'Order by who absorbs losses first.',
    payload: { type: 'sequence', steps: ['Common Equity Tier 1', 'Additional Tier 1', 'Tier 2', 'Senior creditors and depositors'] },
    explanation: 'Equity first, deeply subordinated instruments next, senior claims last.' },
  { id: 'fort-stack-calc', conceptIds: ['capital-stack'], difficulty: 2, prompt: 'RWA are ₹1,000 crore. Under Basel III, how much CET1 is needed to meet the 4.5% minimum plus the 2.5% conservation buffer (₹ crore)?',
    payload: { type: 'calculate', answer: 70, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['4.5% + 2.5% = 7.0%', '7.0% × 1,000 = 70'] },
    explanation: 'Minimum plus buffer: 7% of RWA in CET1, before any countercyclical or systemic buffers.' },
  { id: 'fort-stack-recall', conceptIds: ['capital-stack'], difficulty: 2, prompt: 'From memory: state the Basel III minimum ratios and the conservation buffer.',
    payload: { type: 'recall', modelAnswer: 'CET1 4.5%, Tier 1 6%, total capital 8% of RWA, plus a 2.5% capital conservation buffer in CET1.',
      keyPoints: [{ text: 'CET1 4.5%', essential: true }, { text: 'Tier 1 6%', essential: false }, { text: 'Total capital 8%', essential: true }, { text: 'Conservation buffer 2.5%', essential: false }] },
    explanation: '4.5 / 6 / 8, plus 2.5.' },
  { id: 'fort-irb-choice', conceptIds: ['sa-vs-irb'], difficulty: 2, prompt: 'Under Foundation IRB, which parameter does the bank estimate itself?',
    payload: { type: 'choice', options: ['PD only', 'PD, LGD and EAD', 'LGD only', 'None — risk weights are prescribed'], answerIndex: 0 },
    explanation: 'Foundation: own PD, supervisory LGD and EAD. Advanced: own PD, LGD and EAD.' },
  { id: 'fort-irb-recall', conceptIds: ['sa-vs-irb'], difficulty: 2, prompt: 'From memory: how do the standardised approach, Foundation IRB and Advanced IRB differ — and what limits IRB?',
    payload: { type: 'recall', modelAnswer: 'Standardised: prescribed risk weights. F-IRB: bank estimates PD, supervisory LGD and EAD. A-IRB: bank estimates PD, LGD and EAD. The output floor stops IRB RWA falling below 72.5% of the standardised figure.',
      keyPoints: [{ text: 'Standardised = prescribed weights', essential: true }, { text: 'F-IRB = own PD only', essential: false }, { text: 'A-IRB = own PD, LGD, EAD', essential: false }, { text: 'Output floor 72.5% of standardised', essential: true }] },
    explanation: 'More of your own estimates, but never too far below the standardised answer.' },
  { id: 'fort-lev-calc', conceptIds: ['leverage-ratio'], difficulty: 1, prompt: 'Tier 1 capital ₹30 crore, total leverage exposure ₹1,000 crore. What is the leverage ratio (%)?',
    payload: { type: 'calculate', answer: 3, tolerance: { kind: 'abs', value: 0.01 }, unit: '%', worked: ['Leverage ratio = 30 ÷ 1,000', '= 3.0%'] },
    explanation: 'Exactly at the Basel minimum.' },
  { id: 'fort-lev-choice', conceptIds: ['leverage-ratio'], difficulty: 2, prompt: 'Why does Basel add a leverage ratio on top of risk-based capital?',
    payload: { type: 'choice', options: ['To replace risk weights', 'As a backstop in case risk weights understate risk', 'To measure liquidity', 'To cap dividends'], answerIndex: 1 },
    explanation: 'No weights, no model risk: a simple floor under the risk-based ratios.' },
  { id: 'fort-pillar-classify', conceptIds: ['three-pillars'], difficulty: 1, prompt: 'Which pillar?',
    payload: { type: 'classify', buckets: ['Pillar 1', 'Pillar 2', 'Pillar 3'], entries: [
      { text: 'Minimum capital for credit, market and operational risk', bucket: 0 }, { text: 'ICAAP and supervisory review', bucket: 1 },
      { text: 'Public disclosure of risk and capital', bucket: 2 }, { text: 'Supervisor’s add-on for concentration risk', bucket: 1 }] },
    explanation: 'Formula, judgement, transparency.' },
  { id: 'fort-pillar-recall', conceptIds: ['three-pillars'], difficulty: 1, prompt: 'From memory: name the three Basel pillars and what each does.',
    payload: { type: 'recall', modelAnswer: 'Pillar 1: minimum capital by formula. Pillar 2: the bank’s own assessment (ICAAP) and supervisory review of risks Pillar 1 misses. Pillar 3: public disclosure.',
      keyPoints: [{ text: 'Pillar 1 minimum capital', essential: true }, { text: 'Pillar 2 ICAAP and supervisory review', essential: true }, { text: 'Pillar 3 disclosure', essential: true }] },
    explanation: 'Rules, review, reveal.' },
];
