import type { Item } from '../types';

// PLACEHOLDER items (placeholder: true). The architect's content pack replaces this file.
const i = (x: Omit<Item, 'placeholder'>): Item => ({ ...x, placeholder: true });

export const items: Item[] = [
  // The Mint
  i({ id: 'anchor-mint', conceptIds: ['balance-sheet'], difficulty: 1, prompt: 'Palace Walk: at the Mint stand the balance-sheet scales. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'mint-scales', options: ['The bank balance sheet', 'Probability of default', 'Data lineage', 'IFRS 9 stages'], answerIndex: 0 },
    explanation: 'The scales weigh assets against liabilities plus equity.' }),
  i({ id: 'mint-pv', conceptIds: ['time-value'], difficulty: 1, prompt: 'A recovery of ₹100 crore arrives in exactly one year. At 10% a year, what is it worth today (₹ crore)?',
    payload: { type: 'calculate', answer: 90.9091, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['PV = 100 ÷ (1 + 0.10)¹', '= 100 ÷ 1.10', '= 90.91'] },
    explanation: '100 ÷ 1.10 = 90.91. The ₹9.09 gap is the cost of waiting.' }),
  // Market Quarter
  i({ id: 'case-apply-obligor', conceptIds: ['obligor-facility'], difficulty: 1, prompt: 'The auto-parts maker asks for a term loan and a working-capital line. How many obligors and facilities is that?',
    payload: { type: 'choice', options: ['One obligor, one facility', 'One obligor, two facilities', 'Two obligors, two facilities', 'Two obligors, one facility'], answerIndex: 1 },
    explanation: 'One legal borrower (obligor) holding two separate agreements (facilities).' }),
  i({ id: 'market-lifecycle', conceptIds: ['obligor-facility'], difficulty: 2, prompt: 'Put the credit lifecycle in order.',
    payload: { type: 'sequence', steps: ['Application', 'Underwriting and decision', 'Booking and disbursement', 'Servicing and monitoring', 'Distress and default', 'Recovery and write-off'] },
    explanation: 'Apply → decide → book → monitor → default → recover. Outcomes then feed back into policy and models.' }),
  i({ id: 'market-undrawn', conceptIds: ['funded-unfunded'], difficulty: 2, prompt: 'A ₹10 crore line has ₹6 crore drawn. With a 60% conversion factor on the undrawn part, what is the exposure at default (₹ crore)?',
    payload: { type: 'calculate', answer: 8.4, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Undrawn = 10 − 6 = 4', 'EAD = 6 + 0.60 × 4', '= 8.4'] },
    explanation: 'EAD = drawn + CCF × undrawn = 6 + 2.4 = 8.4.' }),
  // The Branch
  i({ id: 'case-analyse-dscr', conceptIds: ['repayment-capacity'], difficulty: 1, prompt: 'Cash available for debt service is ₹6.0 crore a year; scheduled interest plus principal is ₹4.8 crore. What is the DSCR?',
    payload: { type: 'calculate', answer: 1.25, tolerance: { kind: 'abs', value: 0.005 }, unit: '×', worked: ['DSCR = cash available ÷ debt service', '= 6.0 ÷ 4.8', '= 1.25'] },
    explanation: '6.0 ÷ 4.8 = 1.25: cash covers debt service 1.25 times.' }),
  i({ id: 'branch-profit-spot', conceptIds: ['repayment-capacity'], difficulty: 2, prompt: 'Which statement is wrong?',
    payload: { type: 'spot', options: ['DSCR compares cash with scheduled debt service.', 'A profitable borrower can always repay.', 'Working-capital needs can absorb operating cash.', 'DSCR below 1.0 means operations alone cannot cover debt service.'], answerIndex: 1 },
    explanation: 'Profit is not cash. Timing, working capital and existing debts can leave a profitable firm unable to pay.' }),
  i({ id: 'case-decide-price', conceptIds: ['risk-based-pricing'], difficulty: 3,
    prompt: 'Price the term loan (annual %). FTP 7%, PD 0.5%, LGD 40%, SME risk weight 85%, target CET1 11%, hurdle 15%, opex 1%, margin 0.8%.',
    payload: { type: 'calculate', answer: 10.4025, tolerance: { kind: 'abs', value: 0.05 }, unit: '%',
      worked: ['Expected loss = 0.5% × 40% = 0.20%', 'Capital charge = 85% × 11% × 15% = 1.4025%', 'Rate = 7 + 0.20 + 1.4025 + 1 + 0.8', '= 10.40%'] },
    explanation: 'Funding 7.00 + EL 0.20 + capital 1.40 + opex 1.00 + margin 0.80 = 10.40%.' }),
  // The Registry
  i({ id: 'registry-collateral', conceptIds: ['collateral-haircut'], difficulty: 1, prompt: 'Good collateral mainly reduces…',
    payload: { type: 'choice', options: ['The probability of default', 'The loss if default happens', 'The need to monitor the borrower', 'The interest rate risk'], answerIndex: 1 },
    explanation: 'Collateral cuts loss severity (LGD). It does not make default less likely.' }),
  i({ id: 'case-recover-writeoff', conceptIds: ['collateral-haircut'], difficulty: 2,
    prompt: 'The plant is sold after values fall a further 10%. Compared with the Stage 3 allowance held at default, the term-loan write-off will be…',
    payload: { type: 'predict', options: ['Lower', 'About the same', 'Higher'], answerIndex: 2, bindTo: 'facility:tl1:writtenOff' },
    explanation: 'Weaker sale proceeds plus interest that kept accruing mean the write-off exceeds the allowance held at default.' }),
  // The Watchtower
  i({ id: 'watch-buckets', conceptIds: ['dpd-delinquency'], difficulty: 1, prompt: 'Sort each account into its bucket.',
    payload: { type: 'classify', buckets: ['Current', '1–30', '31–60', '61–90', 'Default (> 90)'],
      entries: [{ text: '0 days late', bucket: 0 }, { text: '29 days late', bucket: 1 }, { text: '59 days late', bucket: 2 }, { text: '89 days late', bucket: 3 }, { text: '119 days late', bucket: 4 }] },
    explanation: 'More than 90 days past due is the payment trigger for default.' }),
  i({ id: 'case-monitor-stage', conceptIds: ['early-warning'], difficulty: 1,
    prompt: 'Seven months of on-time payments; the line is drawn harder and collateral values dip 5%. Where is the term loan?',
    payload: { type: 'predict', options: ['Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 0, bindTo: 'facility:tl1:stage' },
    explanation: 'No trigger has fired: payments are current, the rating is unchanged, and a small collateral dip changes LGD, not staging.' }),
  // Recovery Docks
  i({ id: 'case-default-wc', conceptIds: ['default-definition'], difficulty: 2,
    prompt: 'The working-capital line is still paid on time. After the borrower defaults, what stage is that line in?',
    payload: { type: 'predict', options: ['Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 2, bindTo: 'facility:wc1:stage' },
    explanation: 'Default is judged at obligor level, so every facility of the borrower becomes credit-impaired.' }),
  i({ id: 'case-default-s3ratio', conceptIds: ['default-definition'], difficulty: 3,
    prompt: 'Predict the bank’s Stage 3 ratio after the default (Stage 3 loans ÷ all loans), within 3 percentage points. Enter a decimal, e.g. 0.07.',
    payload: { type: 'predict', numeric: { tolerance: { kind: 'abs', value: 0.03 }, unit: 'ratio' }, bindTo: 'kpi:stage3Ratio' },
    explanation: 'Both SME facilities (about ₹26 crore) move to Stage 3 in a book of about ₹250 crore: roughly 10%.' }),
  i({ id: 'case-writeoff-sequence', conceptIds: ['lgd-realised'], difficulty: 2, prompt: 'Order what happened to the term loan after default.',
    payload: { type: 'sequence', steps: ['Default: Stage 3 allowance set', 'Collateral sold', 'Unrecovered balance written off', 'Later recovery booked as income'] },
    explanation: 'Allowance first, then realisation, then write-off; post-write-off recoveries go to profit and loss.' }),
  i({ id: 'recovery-writeoff-recall', conceptIds: ['lgd-realised'], difficulty: 2, prompt: 'From memory: what does a write-off do, and what does it not do?',
    payload: { type: 'recall', modelAnswer: 'It removes the unrecoverable balance from the balance sheet (using the allowance), but it does not cancel the borrower’s legal obligation; later recoveries are income.',
      keyPoints: [{ text: 'Removes the balance from the books', essential: true }, { text: 'Uses the allowance already held', essential: false }, { text: 'Does not cancel the legal debt', essential: true }, { text: 'Later recoveries are income', essential: false }] },
    explanation: 'Accounting removal ≠ legal forgiveness.' }),
  // The Observatory
  i({ id: 'obs-el', conceptIds: ['expected-loss'], difficulty: 1, prompt: 'PD 2%, LGD 40%, EAD ₹50 crore. What is the expected loss (₹ crore)?',
    payload: { type: 'calculate', answer: 0.4, tolerance: { kind: 'abs', value: 0.001 }, unit: '₹ crore', worked: ['EL = PD × LGD × EAD', '= 0.02 × 0.40 × 50', '= 0.4'] },
    explanation: '0.02 × 0.40 × 50 = 0.4.' }),
  i({ id: 'obs-pd-recall', conceptIds: ['pd'], difficulty: 1, prompt: 'From memory: what must always be stated alongside any PD?',
    payload: { type: 'recall', modelAnswer: 'The horizon (12-month or lifetime), the default definition, and the as-of date or population.',
      keyPoints: [{ text: 'The horizon', essential: true }, { text: 'The default definition', essential: true }, { text: 'As-of date or population', essential: false }] },
    explanation: 'A PD without its horizon and definition cannot be compared or used safely.' }),
  i({ id: 'obs-anchor', conceptIds: ['pd'], difficulty: 1, prompt: 'Palace Walk: where does probability of default live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'obs-telescope', options: ['The Observatory telescope', 'The Provision Vault doors', 'The Registry scissors', 'The Engine Room pipes'], answerIndex: 0 },
    explanation: 'PD looks forward, so it lives in the Observatory telescope.' }),
  // Provision Vault
  i({ id: 'case-book-ecl', conceptIds: ['ifrs9-stages'], difficulty: 1, prompt: 'The loans are booked today and nothing has gone wrong. What provision does the bank hold on the term loan?',
    payload: { type: 'predict', options: ['None — nothing has gone wrong yet', '12-month expected credit loss (Stage 1)', 'Lifetime expected credit loss', 'The full loan amount'], answerIndex: 1, bindTo: 'facility:tl1:stage' },
    explanation: 'IFRS 9 is forward-looking: a Stage 1 allowance and a P&L charge exist from day 1.' }),
  i({ id: 'case-slip-stage', conceptIds: ['sicr'], difficulty: 2, prompt: 'Two instalments are missed and the borrower is downgraded two notches. Where does the term loan go?',
    payload: { type: 'predict', options: ['Stays in Stage 1', 'Stage 2', 'Stage 3'], answerIndex: 1, bindTo: 'facility:tl1:stage' },
    explanation: 'More than 30 days past due and a large PD increase are SICR triggers: Stage 2, but not yet default.' }),
  i({ id: 'case-slip-ecl', conceptIds: ['sicr'], difficulty: 3, prompt: 'By how much does the term loan’s provision grow when it moves to Stage 2?',
    payload: { type: 'predict', options: ['Stays about the same', 'Roughly doubles', 'Grows about 5–15 times', 'Grows more than 50 times'], answerIndex: 2, bindTo: 'facility:tl1:ecl' },
    explanation: 'Two effects multiply: a higher PD, and a lifetime horizon instead of 12 months.' }),
  i({ id: 'vault-classify', conceptIds: ['ifrs9-stages'], difficulty: 2, prompt: 'Sort each loan into its IFRS 9 stage.',
    payload: { type: 'classify', buckets: ['Stage 1', 'Stage 2', 'Stage 3'],
      entries: [{ text: 'Newly originated, performing', bucket: 0 }, { text: '45 days past due', bucket: 1 }, { text: 'PD tripled since origination', bucket: 1 }, { text: '120 days past due', bucket: 2 }, { text: 'Borrower judged unlikely to pay', bucket: 2 }] },
    explanation: 'Deterioration → Stage 2; default (including UTP) → Stage 3.' }),
  // Model Lab
  i({ id: 'lab-choice', conceptIds: ['discrimination-calibration'], difficulty: 2, prompt: 'A model has a high Gini but predicts 1% PD where 4% of borrowers default. The problem is…',
    payload: { type: 'choice', options: ['Discrimination', 'Calibration', 'Both', 'Neither'], answerIndex: 1 },
    explanation: 'Ranking is fine; the level is wrong. That is calibration.' }),
  // Trading Floor
  i({ id: 'trading-choice', conceptIds: ['counterparty-exposure'], difficulty: 2, prompt: 'A swap has ₹100 crore notional and is worth +₹2 crore to the bank today. Current exposure to the counterparty is…',
    payload: { type: 'choice', options: ['₹100 crore', '₹2 crore', '₹102 crore', 'Zero'], answerIndex: 1 },
    explanation: 'Exposure is replacement cost (positive value), not notional.' }),
  // Capital Fortress
  i({ id: 'fort-spot', conceptIds: ['provisions-vs-capital'], difficulty: 2, prompt: 'Which statement is wrong?',
    payload: { type: 'spot', options: ['Provisions address expected loss.', 'Capital absorbs unexpected loss.', 'Provisions are cash set aside in a vault.', 'Losses reduce CET1 through profit and loss.'], answerIndex: 2 },
    explanation: 'An allowance is an accounting reduction of the asset, not a pile of cash.' }),
  i({ id: 'fort-explain', conceptIds: ['rwa-capital-ratio'], difficulty: 3, prompt: 'Explain why a default pushes the capital ratio down from both sides.',
    payload: { type: 'explain', modelAnswer: 'The loss (provision charge) reduces CET1 in the numerator, while the defaulted exposure can carry a higher risk weight, raising RWA in the denominator.',
      keyPoints: [{ text: 'The provision charge reduces CET1 (numerator)', essential: true }, { text: 'Defaulted exposures can carry higher risk weights', essential: true }, { text: 'Higher RWA raises the denominator', essential: false }] },
    explanation: 'Numerator down, denominator up.' }),
  // Storm Centre
  i({ id: 'storm-choice', conceptIds: ['concentration'], difficulty: 1, prompt: 'Which portfolio is most exposed to one shock?',
    payload: { type: 'choice', options: ['100 loans across 10 sectors', '100 loans to suppliers of one car maker', '100 loans across 5 regions', '100 small retail loans'], answerIndex: 1 },
    explanation: 'Many names sharing one driver behave like one big exposure.' }),
  // The Port
  i({ id: 'port-anchor', conceptIds: ['securitisation'], difficulty: 1, prompt: 'Palace Walk: where does securitisation live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'port-containers', options: ['The Port containers', 'The Mint scales', 'Town Hall table', 'The Watchtower clock'], answerIndex: 0 },
    explanation: 'Loans are packed into tranches and shipped out from the Port.' }),
  // Reporting Tower
  i({ id: 'case-report-explain', conceptIds: ['reporting-purpose'], difficulty: 3, prompt: 'Using the case: explain what happened to the Stage 3 ratio and the CET1 ratio from default to write-off.',
    payload: { type: 'explain', modelAnswer: 'At default the Stage 3 ratio jumped and CET1 fell with the Stage 3 charge. After recovery and write-off the loans left the book, so the Stage 3 ratio fell back to zero, while CET1 kept the loss; later earnings and the post-write-off recovery rebuilt it.',
      keyPoints: [{ text: 'Stage 3 ratio jumps at default', essential: true }, { text: 'CET1 falls by the impairment charge', essential: true }, { text: 'Write-off removes loans, so the Stage 3 ratio falls', essential: true }, { text: 'Post-write-off recovery is income', essential: false }] },
    explanation: 'A falling Stage 3 ratio after write-offs is not an improvement in credit quality — read ratios with their movements.' }),
  // Engine Room
  i({ id: 'engine-anchor', conceptIds: ['data-lineage'], difficulty: 1, prompt: 'Palace Walk: beneath the city, the pipes. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'engine-pipes', options: ['Data lineage', 'Securitisation', 'Credit spreads', 'Collateral haircuts'], answerIndex: 0 },
    explanation: 'Pipes carry every number from source to report.' }),
  // Town Hall
  i({ id: 'hall-choice', conceptIds: ['three-lines'], difficulty: 1, prompt: 'Who owns the credit risk of a new loan?',
    payload: { type: 'choice', options: ['Internal audit', 'The business that originates it', 'The regulator', 'The data team'], answerIndex: 1 },
    explanation: 'First line owns; second line challenges; third line assures.' }),
  // Embassy Row
  i({ id: 'embassy-choice', conceptIds: ['jurisdiction-rulebooks'], difficulty: 2, prompt: 'Before encoding a capital rule, what must you confirm first?',
    payload: { type: 'choice', options: ['The Basel paragraph only', 'The applicable local rulebook, version and effective date', 'What another bank does', 'The latest consultation paper'], answerIndex: 1 },
    explanation: 'Basel is a standard; local law, version and date decide what applies.' }),
  // BA Studio
  i({ id: 'case-ba-stage2', conceptIds: ['requirement-to-test'], difficulty: 3, prompt: 'Write the requirement for the Stage 2 trigger used in the case. Then self-check against the key points.',
    payload: { type: 'recall', modelAnswer: 'Move a facility to Stage 2 when it is not in default and any trigger is true: more than 30 days past due, current 12-month PD ≥ 2× origination PD, or watchlist. Exit to Stage 1 only after all triggers are false for 3 consecutive months. Data: DPD, current and origination PD, watchlist flag. Test: a facility at 31 DPD moves to Stage 2; at 2 clear months it stays in Stage 2; at 3 it returns to Stage 1.',
      keyPoints: [{ text: 'All three triggers with thresholds', essential: true }, { text: 'Excludes defaulted facilities', essential: false }, { text: 'Exit rule with probation', essential: true }, { text: 'Required data fields', essential: false }, { text: 'At least one boundary test', essential: true }] },
    explanation: 'Thresholds, precedence, exits, data and a boundary test — that is a testable requirement.' }),
];
