import type { Item } from '../types';

export const marketItems: Item[] = [
  { id: 'anchor-market', conceptIds: ['obligor-facility'], difficulty: 1, prompt: 'Palace Walk: in the Market Quarter, a set of boxes sits one inside another. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'market-boxes', options: ['Obligor → facility → account', 'Five Cs of credit', 'Collateral haircuts', 'Roll rates'], answerIndex: 0 },
    explanation: 'The nesting boxes: borrower holds agreements, agreements hold accounts.' },
  { id: 'market-nest-sequence', conceptIds: ['obligor-facility'], difficulty: 1, prompt: 'Order from the widest grain to the narrowest.',
    payload: { type: 'sequence', steps: ['Group of connected borrowers', 'Obligor', 'Facility', 'Account'] },
    explanation: 'Groups contain obligors; obligors hold facilities; facilities are booked in accounts.' },
  { id: 'market-obligor-recall', conceptIds: ['obligor-facility'], difficulty: 2, prompt: 'From memory: why is default usually judged at obligor level rather than loan by loan?',
    payload: { type: 'recall', modelAnswer: 'Because it is the borrower who cannot pay, not the individual loan. When the borrower defaults, all of its facilities are at risk, so all are treated as defaulted — even ones still being paid.',
      keyPoints: [{ text: 'The borrower, not the loan, fails to pay', essential: true }, { text: 'All the borrower’s facilities are treated as defaulted', essential: true }, { text: 'Stops one loan looking current while the borrower is failing', essential: false }] },
    explanation: 'Obligor-level default pulls every facility in together.' },
  { id: 'market-undrawn', conceptIds: ['funded-unfunded'], difficulty: 2, prompt: 'A ₹10 crore line has ₹6 crore drawn. With a 60% conversion factor on the undrawn part, what is the exposure at default (₹ crore)?',
    payload: { type: 'calculate', answer: 8.4, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Undrawn = 10 − 6 = 4', 'EAD = 6 + 0.60 × 4', '= 8.4'] },
    explanation: 'EAD = drawn + CCF × undrawn = 6 + 2.4 = 8.4.' },
  { id: 'market-unfunded-classify', conceptIds: ['funded-unfunded'], difficulty: 1, prompt: 'Funded or unfunded?',
    payload: { type: 'classify', buckets: ['Funded', 'Unfunded'], entries: [
      { text: 'Disbursed term loan', bucket: 0 }, { text: 'Bank guarantee issued for a customer', bucket: 1 }, { text: 'Undrawn part of an overdraft limit', bucket: 1 },
      { text: 'Letter of credit', bucket: 1 }, { text: 'Cash credit balance in use', bucket: 0 }] },
    explanation: 'Funded = money already out. Unfunded = a promise that can turn into money out.' },
  { id: 'market-segment-choice', conceptIds: ['segments'], difficulty: 1, prompt: 'A bank has two million credit-card applications a year. How are approvals most likely decided?',
    payload: { type: 'choice', options: ['A credit officer rates each applicant', 'Policy rules plus an application scorecard', 'The credit committee meets weekly', 'Collateral valuation'], answerIndex: 1 },
    explanation: 'Retail volume demands automated, rule-and-score decisions.' },
  { id: 'market-segment-spot', conceptIds: ['segments'], difficulty: 2, prompt: 'Segments: which statement is wrong?',
    payload: { type: 'spot', options: ['Retail loans are managed as pools of similar exposures.', 'Large corporates are analysed and rated individually.', 'Retail loans are normally rated one by one by a credit committee.', 'The segment decides which model and exposure class apply.'], answerIndex: 2 },
    explanation: 'Credit committees handle large individual exposures, not mass retail.' },
  { id: 'market-segment-recall', conceptIds: ['segments'], difficulty: 2, prompt: 'From memory: how does lending differ between retail and corporate, and what does the segment decide?',
    payload: { type: 'recall', modelAnswer: 'Retail: many small similar loans, managed as pools, decided by scorecards and policy rules. Corporate: fewer large borrowers, individually analysed and rated. The segment decides the model, approval route, monitoring and regulatory exposure class.',
      keyPoints: [{ text: 'Retail = pools, scorecards, rules', essential: true }, { text: 'Corporate = individual analysis and rating', essential: true }, { text: 'Segment decides model, approval, monitoring, exposure class', essential: false }] },
    explanation: 'Same bank, different machinery per segment.' },
  { id: 'market-util-calc', conceptIds: ['amortising-revolving'], difficulty: 1, prompt: 'A cash-credit limit is ₹50 lakh and ₹35 lakh is drawn. What is the utilisation (%)?',
    payload: { type: 'calculate', answer: 70, tolerance: { kind: 'abs', value: 0.5 }, unit: '%', worked: ['Utilisation = drawn ÷ limit', '= 35 ÷ 50', '= 70%'] },
    explanation: '35 ÷ 50 = 70%.' },
  { id: 'market-revolve-choice', conceptIds: ['amortising-revolving'], difficulty: 1, prompt: 'Which facility can the borrower draw again after repaying it?',
    payload: { type: 'choice', options: ['A home loan with monthly instalments', 'A bullet term loan', 'A revolving working-capital line', 'A vehicle loan'], answerIndex: 2 },
    explanation: 'Revolving facilities can be drawn, repaid and drawn again up to the limit.' },
];
