import type { Item } from '../types';

export const mintItems: Item[] = [
  { id: 'anchor-mint', conceptIds: ['balance-sheet'], difficulty: 1, prompt: 'Palace Walk: at the Mint stand the balance-sheet scales. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'mint-scales', options: ['The bank balance sheet', 'Days past due', 'Loan-to-value', 'Default definition'], answerIndex: 0 },
    explanation: 'The scales weigh assets against liabilities plus equity.' },
  { id: 'mint-bs-classify', conceptIds: ['balance-sheet'], difficulty: 1, prompt: 'Sort each item onto the bank’s balance sheet.',
    payload: { type: 'classify', buckets: ['Asset', 'Liability', 'Equity'], entries: [
      { text: 'Loans to customers', bucket: 0 }, { text: 'Customer deposits', bucket: 1 }, { text: 'Retained earnings', bucket: 2 },
      { text: 'Government bonds the bank holds', bucket: 0 }, { text: 'Borrowings from other banks', bucket: 1 }, { text: 'Share capital', bucket: 2 }] },
    explanation: 'What the bank owns or is owed = assets. What it owes = liabilities. What belongs to shareholders = equity.' },
  { id: 'mint-bs-loss', conceptIds: ['balance-sheet'], difficulty: 1, prompt: 'A bank’s loans lose ₹5 crore of value. Which part of the balance sheet absorbs it?',
    payload: { type: 'choice', options: ['Customer deposits', 'Equity', 'Borrowings', 'Cash'], answerIndex: 1 },
    explanation: 'Losses run through profit and loss into equity. Depositors are still owed in full — that is why equity must be big enough.' },
  { id: 'mint-nim-calc', conceptIds: ['net-interest-margin'], difficulty: 2,
    prompt: 'Interest income ₹900 crore, interest expense ₹540 crore, average interest-earning assets ₹12,000 crore. What is the NIM (%)?',
    payload: { type: 'calculate', answer: 3.0, tolerance: { kind: 'abs', value: 0.05 }, unit: '%', worked: ['NII = 900 − 540 = 360', 'NIM = 360 ÷ 12,000', '= 3.0%'] },
    explanation: 'NII of 360 on 12,000 of earning assets is 3.0%.' },
  { id: 'mint-nim-spot', conceptIds: ['net-interest-margin'], difficulty: 2, prompt: 'Net interest margin: which statement is wrong?',
    payload: { type: 'spot', options: ['NII = interest income − interest expense.', 'NIM is measured after credit losses and operating costs.', 'Credit losses are paid out of net interest income.', 'A 1% loss rate can consume a third of a 3% margin.'], answerIndex: 1 },
    explanation: 'NIM is before costs, credit losses and tax — which is exactly why losses matter so much.' },
  { id: 'mint-pv', conceptIds: ['time-value'], difficulty: 1, prompt: 'A recovery of ₹100 crore arrives in exactly one year. At 10% a year, what is it worth today (₹ crore)?',
    payload: { type: 'calculate', answer: 90.9091, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['PV = 100 ÷ (1 + 0.10)¹', '= 100 ÷ 1.10', '= 90.91'] },
    explanation: '100 ÷ 1.10 = 90.91. The ₹9.09 gap is the cost of waiting.' },
  { id: 'mint-pv2', conceptIds: ['time-value'], difficulty: 2, prompt: '₹121 crore arrives in two years. At 10% a year, what is it worth today (₹ crore)?',
    payload: { type: 'calculate', answer: 100, tolerance: { kind: 'abs', value: 0.05 }, unit: '₹ crore', worked: ['PV = 121 ÷ 1.10²', '= 121 ÷ 1.21', '= 100'] },
    explanation: 'Discount twice: 121 ÷ 1.21 = 100.' },
  { id: 'mint-tv-recall', conceptIds: ['time-value'], difficulty: 2, prompt: 'From memory: why does a slow recovery mean a bigger loss, even if the same cash eventually comes in?',
    payload: { type: 'recall', modelAnswer: 'Money received later is worth less today, so recoveries are discounted to the default date. The longer the wait, the smaller their present value and the larger the loss.',
      keyPoints: [{ text: 'Money later is worth less today', essential: true }, { text: 'Recoveries are discounted back', essential: true }, { text: 'Longer wait → smaller present value → bigger loss', essential: false }] },
    explanation: 'Time is a cost: that is why LGD discounts recoveries.' },
  { id: 'mint-eir-choice', conceptIds: ['effective-interest-rate'], difficulty: 2, prompt: 'A ₹100 loan at a 10% contract rate charges the borrower a ₹2 upfront fee. Its effective interest rate is…',
    payload: { type: 'choice', options: ['Higher than 10%', 'Exactly 10%', 'Lower than 10%', 'Undefined until maturity'], answerIndex: 0 },
    explanation: 'The bank really lends ₹98 net but earns interest on ₹100, so the rate that equates the cash flows is above 10%.' },
  { id: 'mint-eir-recall', conceptIds: ['effective-interest-rate'], difficulty: 3, prompt: 'From memory: what is the EIR, and where does IFRS 9 use it?',
    payload: { type: 'recall', modelAnswer: 'The rate that exactly discounts the expected future cash flows to the gross carrying amount, including integral fees and costs. IFRS 9 uses it to recognise interest revenue and to discount expected credit losses.',
      keyPoints: [{ text: 'Discounts expected cash flows to the carrying amount', essential: true }, { text: 'Includes integral fees and costs', essential: false }, { text: 'Used for interest revenue', essential: true }, { text: 'Used to discount ECL', essential: false }] },
    explanation: 'One rate, two jobs: income recognition and ECL discounting.' },
];
