import type { Item } from '../types';

export const modellabItems: Item[] = [
  { id: 'anchor-modellab', conceptIds: ['discrimination-calibration'], difficulty: 1, prompt: 'Palace Walk: on the Model Lab wall hangs a curve bowing above the diagonal. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'lab-roc', options: ['Discrimination vs calibration', 'The allowance walk', 'Loan-to-value', 'The three pillars'], answerIndex: 0 },
    explanation: 'The ROC curve on the wall: how well the model separates good from bad.' },
  { id: 'lab-choice', conceptIds: ['discrimination-calibration'], difficulty: 2, prompt: 'A model has a high Gini but predicts 1% PD where 4% of borrowers default. The problem is…',
    payload: { type: 'choice', options: ['Discrimination', 'Calibration', 'Both', 'Neither'], answerIndex: 1 },
    explanation: 'Ranking is fine; the level is wrong. That is calibration.' },
  { id: 'lab-dc-recall', conceptIds: ['discrimination-calibration'], difficulty: 2, prompt: 'From memory: define discrimination and calibration, and how each is tested.',
    payload: { type: 'recall', modelAnswer: 'Discrimination: does the model rank risky borrowers above safe ones — tested with Gini or AUC. Calibration: do predicted PDs match observed default rates — tested by back-testing by grade.',
      keyPoints: [{ text: 'Discrimination = ranking', essential: true }, { text: 'Tested with Gini / AUC', essential: false }, { text: 'Calibration = predicted vs observed level', essential: true }, { text: 'Tested by back-testing by grade', essential: false }] },
    explanation: 'Order versus level.' },
  { id: 'lab-score-calc', conceptIds: ['scorecard'], difficulty: 1, prompt: 'Base points 600. Age band +30, income band +45, a past delinquency −60. What is the score?',
    payload: { type: 'calculate', answer: 615, tolerance: { kind: 'abs', value: 0 }, unit: 'points', worked: ['600 + 30 + 45 − 60', '= 615'] },
    explanation: 'Points add up; negative characteristics subtract.' },
  { id: 'lab-cutoff-choice', conceptIds: ['scorecard'], difficulty: 2, prompt: 'The bank raises its scorecard cut-off from 600 to 640. What happens?',
    payload: { type: 'choice', options: ['More approvals, higher bad rate', 'Fewer approvals, lower bad rate among those approved', 'No change in approvals', 'The model’s Gini rises'], answerIndex: 1 },
    explanation: 'A higher bar approves fewer, safer applicants. The model itself is unchanged.' },
  { id: 'lab-gini-calc', conceptIds: ['gini-auc'], difficulty: 1, prompt: 'A model’s AUC is 0.80. What is its Gini?',
    payload: { type: 'calculate', answer: 0.6, tolerance: { kind: 'abs', value: 0.001 }, unit: '', worked: ['Gini = 2 × AUC − 1', '= 2 × 0.80 − 1', '= 0.60'] },
    explanation: 'Gini rescales AUC so that 0 is random and 1 is perfect.' },
  { id: 'lab-gini-spot', conceptIds: ['gini-auc'], difficulty: 2, prompt: 'Gini and AUC: which statement is wrong?',
    payload: { type: 'spot', options: ['AUC 0.5 is no better than random.', 'A Gini of 0.6 means 60% of defaults are predicted correctly.', 'Gini measures ranking, not PD levels.', 'A falling Gini can signal model decay.'], answerIndex: 1 },
    explanation: 'Gini is a ranking measure, not a hit rate.' },
  { id: 'lab-val-classify', conceptIds: ['model-validation'], difficulty: 2, prompt: 'Which part of validation is each activity?',
    payload: { type: 'classify', buckets: ['Conceptual soundness', 'Outcomes analysis', 'Ongoing monitoring'], entries: [
      { text: 'Review the data, method and assumptions', bucket: 0 }, { text: 'Compare last year’s predicted PDs with actual defaults', bucket: 1 },
      { text: 'Track score-distribution shift every quarter', bucket: 2 }, { text: 'Check that the variables make business sense', bucket: 0 }] },
    explanation: 'Is it built right, did it predict right, is it still working.' },
  { id: 'lab-val-recall', conceptIds: ['model-validation'], difficulty: 2, prompt: 'From memory: what are the three parts of model validation, and what must validators be?',
    payload: { type: 'recall', modelAnswer: 'Conceptual soundness, outcomes analysis (back-testing) and ongoing monitoring — done by validators independent of the model developers.',
      keyPoints: [{ text: 'Conceptual soundness', essential: false }, { text: 'Outcomes analysis / back-testing', essential: false }, { text: 'Ongoing monitoring', essential: false }, { text: 'Independent of the developers', essential: true }] },
    explanation: 'Independence is what makes it a challenge rather than a review of one’s own work.' },
  { id: 'lab-psi-calc', conceptIds: ['population-stability'], difficulty: 3, prompt: 'Two score bands. At development: 50% / 50%. Today: 60% / 40%. What is the PSI? (Σ (actual − expected) × ln(actual ÷ expected))',
    payload: { type: 'calculate', answer: 0.0405, tolerance: { kind: 'abs', value: 0.002 }, unit: '', worked: ['Band 1: (0.60 − 0.50) × ln(1.2) = 0.1 × 0.1823 = 0.0182', 'Band 2: (0.40 − 0.50) × ln(0.8) = −0.1 × −0.2231 = 0.0223', 'PSI = 0.0182 + 0.0223 = 0.0405'] },
    explanation: 'Both terms are positive by construction; 0.04 is well inside “stable”.' },
  { id: 'lab-psi-choice', conceptIds: ['population-stability'], difficulty: 1, prompt: 'A scorecard’s PSI this quarter is 0.31. What should happen?',
    payload: { type: 'choice', options: ['Nothing — PSI above 0.25 is normal', 'Investigate: the scored population has shifted significantly', 'Raise the cut-off automatically', 'Retire the model immediately without analysis'], answerIndex: 1 },
    explanation: 'Above 0.25 is a significant shift by the usual rule of thumb: find out why before deciding what to do.' },
];
