import type { Item } from '../types';

export const observatoryItems: Item[] = [
  { id: 'obs-anchor', conceptIds: ['pd'], difficulty: 1, prompt: 'Palace Walk: where does the PD telescope live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'obs-telescope', options: ['The Observatory', 'The Provision Vault', 'The Registry', 'The Engine Room'], answerIndex: 0 },
    explanation: 'PD looks forward, so it lives in the Observatory telescope.' },
  { id: 'obs-pd-recall', conceptIds: ['pd'], difficulty: 1, prompt: 'From memory: what must always be stated alongside any PD?',
    payload: { type: 'recall', modelAnswer: 'The horizon (12-month or lifetime), the default definition, and the as-of date or population it applies to.',
      keyPoints: [{ text: 'The horizon', essential: true }, { text: 'The default definition', essential: true }, { text: 'As-of date or population', essential: false }] },
    explanation: 'A PD without its horizon and definition cannot be compared or used safely.' },
  { id: 'obs-pd-choice', conceptIds: ['pd'], difficulty: 1, prompt: 'A borrower has a 2% 12-month PD. What does that mean?',
    payload: { type: 'choice', options: ['Exactly 2 of every 100 such borrowers will default', 'On average about 2% of similar borrowers default within 12 months', 'The bank will lose 2% of the loan', 'Default will happen after 2% of the term'], answerIndex: 1 },
    explanation: 'PD is an average rate across similar borrowers, not a count and not a loss.' },
  { id: 'obs-lgd-calc', conceptIds: ['lgd'], difficulty: 2, prompt: 'Exposure at default ₹80 crore; the present value of net recoveries is ₹50 crore. What is the LGD (%)?',
    payload: { type: 'calculate', answer: 37.5, tolerance: { kind: 'abs', value: 0.1 }, unit: '%', worked: ['LGD = 1 − 50 ÷ 80', '= 1 − 0.625', '= 37.5%'] },
    explanation: '30 lost out of 80 = 37.5%.' },
  { id: 'obs-lgd-choice', conceptIds: ['lgd'], difficulty: 2, prompt: 'Why is downturn LGD higher than average LGD?',
    payload: { type: 'choice', options: ['Interest rates are always lower in a downturn', 'Collateral values fall and recoveries take longer just when defaults rise', 'Regulators add a fixed 10%', 'Borrowers draw more on their lines'], answerIndex: 1 },
    explanation: 'Bad times hit both the chance of default and what can be recovered.' },
  { id: 'obs-ead-calc', conceptIds: ['ead-ccf'], difficulty: 1, prompt: 'A ₹50 crore revolving line has ₹20 crore drawn. With a 50% CCF, what is the EAD (₹ crore)?',
    payload: { type: 'calculate', answer: 35, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Undrawn = 50 − 20 = 30', 'EAD = 20 + 0.5 × 30', '= 35'] },
    explanation: 'Drawn plus the share of undrawn expected to be drawn by default.' },
  { id: 'obs-ead-spot', conceptIds: ['ead-ccf'], difficulty: 2, prompt: 'Exposure at default: which statement is wrong?',
    payload: { type: 'spot', options: ['A term loan’s EAD follows its repayment schedule.', 'A revolving line’s EAD is simply today’s drawn balance.', 'Borrowers tend to draw down as they weaken.', 'Capital rules prescribe CCFs; accounting estimates them.'], answerIndex: 1 },
    explanation: 'The undrawn part matters: that is what the CCF is for.' },
  { id: 'obs-el', conceptIds: ['expected-loss'], difficulty: 1, prompt: 'PD 2%, LGD 40%, EAD ₹50 crore. What is the expected loss (₹ crore)?',
    payload: { type: 'calculate', answer: 0.4, tolerance: { kind: 'abs', value: 0.001 }, unit: '₹ crore', worked: ['EL = PD × LGD × EAD', '= 0.02 × 0.40 × 50', '= 0.4'] },
    explanation: '0.02 × 0.40 × 50 = 0.4.' },
  { id: 'obs-el-recall', conceptIds: ['expected-loss'], difficulty: 2, prompt: 'From memory: write the expected-loss formula and the one condition its three inputs must share.',
    payload: { type: 'recall', modelAnswer: 'EL = PD × LGD × EAD. The three must use the same horizon and consistent definitions (of default and exposure).',
      keyPoints: [{ text: 'EL = PD × LGD × EAD', essential: true }, { text: 'Same horizon and consistent definitions', essential: true }, { text: 'It is an average, not a forecast for one loan', essential: false }] },
    explanation: 'Mixing a 12-month PD with a lifetime EAD makes the number meaningless.' },
  { id: 'obs-ul-choice', conceptIds: ['unexpected-loss'], difficulty: 1, prompt: 'Which buffer is meant to absorb unexpected loss?',
    payload: { type: 'choice', options: ['Loan-loss provisions', 'Capital', 'Deposits', 'The collateral'], answerIndex: 1 },
    explanation: 'Expected loss is priced and provided for; capital absorbs the bad years above it.' },
  { id: 'obs-ul-recall', conceptIds: ['unexpected-loss'], difficulty: 2, prompt: 'From memory: explain the difference between expected and unexpected loss, and what covers each.',
    payload: { type: 'recall', modelAnswer: 'Expected loss is the average loss, covered by pricing and provisions. Unexpected loss is the loss above that average in a bad year, at a high confidence level, covered by capital.',
      keyPoints: [{ text: 'EL = average loss', essential: true }, { text: 'Provisions and pricing cover EL', essential: false }, { text: 'UL = loss above EL at high confidence', essential: true }, { text: 'Capital covers UL', essential: true }] },
    explanation: 'Average versus bad year; provisions versus capital.' },
  { id: 'obs-pit-classify', conceptIds: ['pit-ttc'], difficulty: 2, prompt: 'Point-in-time or through-the-cycle?',
    payload: { type: 'classify', buckets: ['Point-in-time', 'Through-the-cycle'], entries: [
      { text: 'Rises in a recession, falls in a boom', bucket: 0 }, { text: 'Stable across the economic cycle', bucket: 1 },
      { text: 'Needed for forward-looking IFRS 9 ECL', bucket: 0 }, { text: 'Based on a long-run average default rate', bucket: 1 }] },
    explanation: 'PIT follows the weather; TTC describes the climate.' },
  { id: 'obs-pit-recall', conceptIds: ['pit-ttc'], difficulty: 2, prompt: 'From memory: why can’t one PD model serve both IFRS 9 and regulatory capital unchanged?',
    payload: { type: 'recall', modelAnswer: 'IFRS 9 needs point-in-time, forward-looking PDs that move with the economy; capital models lean on long-run (through-the-cycle) averages so capital does not swing with the cycle. One of them has to be adjusted.',
      keyPoints: [{ text: 'IFRS 9 needs PIT, forward-looking PDs', essential: true }, { text: 'Capital uses long-run / TTC averages', essential: true }, { text: 'So an adjustment is needed between them', essential: false }] },
    explanation: 'Different questions need different PDs.' },
  { id: 'obs-lifetime-calc', conceptIds: ['lifetime-pd'], difficulty: 2, prompt: 'A borrower’s annual PD is a constant 5%. What is the cumulative PD over three years (%)?',
    payload: { type: 'calculate', answer: 14.2625, tolerance: { kind: 'abs', value: 0.05 }, unit: '%', worked: ['Survival to year 3 = 0.95³ = 0.857375', 'Cumulative PD = 1 − 0.857375', '= 14.26%'] },
    explanation: 'Not 15%: you can only default once, so survival compounds.' },
  { id: 'obs-marginal-choice', conceptIds: ['lifetime-pd'], difficulty: 3, prompt: 'Same borrower (5% a year). What is the marginal PD in year 2 — the chance of defaulting during the second year?',
    payload: { type: 'choice', options: ['5.00%', '4.75%', '9.75%', '10.00%'], answerIndex: 1 },
    explanation: 'Survive year 1 (0.95) then default in year 2 (5%): 0.95 × 0.05 = 4.75%.' },
];
