import type { Item } from '../types';

export const portItems: Item[] = [
  { id: 'port-anchor', conceptIds: ['securitisation'], difficulty: 1, prompt: 'Palace Walk: where does securitisation live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'port-containers', options: ['The Port', 'The Mint', 'Town Hall', 'The Watchtower'], answerIndex: 0 },
    explanation: 'Loans are packed into containers (tranches) and shipped out from the Port.' },
  { id: 'port-sec-sequence', conceptIds: ['securitisation'], difficulty: 1, prompt: 'Order a securitisation.',
    payload: { type: 'sequence', steps: ['Originate and pool the loans', 'Transfer the pool to a special-purpose vehicle', 'The vehicle issues notes in tranches', 'Pool cash flows repay investors through the waterfall'] },
    explanation: 'Pool, transfer, issue, pay.' },
  { id: 'port-sec-recall', conceptIds: ['securitisation'], difficulty: 2, prompt: 'From memory: what can an originator gain from securitising loans, and on what condition?',
    payload: { type: 'recall', modelAnswer: 'Funding and, possibly, capital relief — but only if enough risk genuinely leaves the originator (and the accounting and regulatory tests are met).',
      keyPoints: [{ text: 'Funding', essential: false }, { text: 'Capital relief', essential: false }, { text: 'Only if risk genuinely transfers', essential: true }] },
    explanation: 'No transfer of risk, no relief.' },
  { id: 'port-tranche-calc', conceptIds: ['tranching'], difficulty: 3, prompt: 'Tranches: equity 0–5%, mezzanine 5–15%, senior 15–100%. The pool loses 12%. What share of the mezzanine tranche is lost (%)?',
    payload: { type: 'calculate', answer: 70, tolerance: { kind: 'abs', value: 0.5 }, unit: '%', worked: ['Equity absorbs the first 5 points (wiped out)', 'Mezzanine absorbs 12 − 5 = 7 of its 10 points', '7 ÷ 10 = 70%'] },
    explanation: 'Senior is untouched until losses pass 15%.' },
  { id: 'port-tranche-choice', conceptIds: ['tranching'], difficulty: 1, prompt: 'Which tranche is paid first and loses last?',
    payload: { type: 'choice', options: ['Equity', 'Mezzanine', 'Senior', 'They share equally'], answerIndex: 2 },
    explanation: 'Seniority: first in the payment queue, last in the loss queue.' },
  { id: 'port-srt-choice', conceptIds: ['risk-transfer'], difficulty: 2, prompt: 'A securitisation removes the loans from the balance sheet but the bank keeps the equity tranche. What might still be true?',
    payload: { type: 'choice', options: ['Capital relief is automatic', 'The regulator may deny significant risk transfer, so capital relief is limited', 'The loans must be put back', 'The deal is illegal'], answerIndex: 1 },
    explanation: 'Accounting and capital are separate tests; keeping the first loss often keeps most of the risk.' },
  { id: 'port-srt-recall', conceptIds: ['risk-transfer'], difficulty: 2, prompt: 'From memory: what are the two separate tests when loans are transferred, and what does each decide?',
    payload: { type: 'recall', modelAnswer: 'Accounting derecognition decides whether the loans leave the balance sheet (risks and rewards or control passed). Regulatory significant risk transfer decides whether capital can be reduced.',
      keyPoints: [{ text: 'Accounting derecognition → balance sheet', essential: true }, { text: 'Significant risk transfer → capital', essential: true }, { text: 'A deal can pass one and fail the other', essential: false }] },
    explanation: 'Two questions, two answers.' },
  { id: 'port-cds-choice', conceptIds: ['credit-protection'], difficulty: 1, prompt: 'A bank buys a credit default swap on its borrower. If the borrower defaults, who pays?',
    payload: { type: 'choice', options: ['The borrower’s guarantor', 'The protection seller', 'The central bank', 'Nobody — the premium is refunded'], answerIndex: 1 },
    explanation: 'The bank has swapped borrower risk for protection-seller risk.' },
  { id: 'port-cds-recall', conceptIds: ['credit-protection'], difficulty: 2, prompt: 'From memory: what risks remain after buying credit protection?',
    payload: { type: 'recall', modelAnswer: 'The protection seller may fail (counterparty risk), and mismatches in maturity, currency or reference obligation can leave parts of the loss uncovered. Wrong-way risk if the seller is linked to the borrower.',
      keyPoints: [{ text: 'Protection-seller (counterparty) risk', essential: true }, { text: 'Maturity, currency or reference mismatches', essential: true }, { text: 'Wrong-way risk', essential: false }] },
    explanation: 'Protection moves risk; it does not make it vanish.' },
];
