import type { Item } from '../types';

export const recoveryItems: Item[] = [
  { id: 'anchor-recovery', conceptIds: ['lgd-realised'], difficulty: 1, prompt: 'Palace Walk: at Recovery Docks a crane lifts what can be saved. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'recovery-crane', options: ['Realised loss and write-off', 'Effective interest rate', 'Segments', 'Loan-to-value'], answerIndex: 0 },
    explanation: 'The crane lifts recoveries; what is left behind is written off.' },
  { id: 'recovery-default-choice', conceptIds: ['default-definition'], difficulty: 2, prompt: 'A borrower is 40 days past due but has just filed for insolvency. Is it in default?',
    payload: { type: 'choice', options: ['No — not yet 90 days past due', 'Yes — unlikely to pay', 'Only once the court decides', 'Only on the facility that is late'], answerIndex: 1 },
    explanation: 'Unlikeliness to pay triggers default before 90 days, for every facility of the borrower.' },
  { id: 'recovery-default-recall', conceptIds: ['default-definition'], difficulty: 1, prompt: 'From memory: what are the two triggers of default?',
    payload: { type: 'recall', modelAnswer: 'More than 90 days past due on a material amount, or the bank judges the borrower unlikely to pay.',
      keyPoints: [{ text: 'More than 90 days past due', essential: true }, { text: 'Unlikely to pay', essential: true }, { text: 'Judged at obligor level', essential: false }] },
    explanation: 'Days and judgement.' },
  { id: 'recovery-cure-choice', conceptIds: ['collections-cure'], difficulty: 1, prompt: 'What does it mean for a delinquent loan to cure?',
    payload: { type: 'choice', options: ['The bank sells it', 'All arrears are cleared and the loan is up to date again', 'The borrower pays the latest instalment', 'The loan is restructured'], answerIndex: 1 },
    explanation: 'Cure = fully up to date. Probation periods then test that it stays that way.' },
  { id: 'recovery-cure-recall', conceptIds: ['collections-cure'], difficulty: 2, prompt: 'From memory: why do frameworks add a probation period after a cure?',
    payload: { type: 'recall', modelAnswer: 'Because many cured borrowers fall back quickly. A period of sustained good payment shows the recovery is real before the loan is treated as fully performing again.',
      keyPoints: [{ text: 'Cured borrowers often relapse', essential: true }, { text: 'Sustained good payment must be shown', essential: true }, { text: 'Only then back to fully performing', essential: false }] },
    explanation: 'One good month is not a recovery.' },
  { id: 'recovery-forb-classify', conceptIds: ['forbearance'], difficulty: 2, prompt: 'Forbearance or not?',
    payload: { type: 'classify', buckets: ['Forbearance', 'Not forbearance'], entries: [
      { text: 'Tenor extended because the borrower cannot meet instalments', bucket: 0 }, { text: 'Rate cut to keep a strong borrower from refinancing elsewhere', bucket: 1 },
      { text: 'Six-month repayment holiday after the borrower lost its main customer', bucket: 0 }, { text: 'Top-up loan to a performing borrower with strong cash flow', bucket: 1 }] },
    explanation: 'The test is financial difficulty plus a concession.' },
  { id: 'recovery-forb-spot', conceptIds: ['forbearance'], difficulty: 2, prompt: 'Forbearance: which statement is wrong?',
    payload: { type: 'spot', options: ['Forbearance is a concession to a borrower in financial difficulty.', 'Once restructured, a loan automatically counts as performing.', 'Forborne loans are flagged and tracked.', 'Restructuring can hide arrears.'], answerIndex: 1 },
    explanation: 'A restructuring is not a cure; the borrower still has to prove it can pay.' },
  { id: 'recovery-forb-recall', conceptIds: ['forbearance'], difficulty: 2, prompt: 'From memory: what makes a change to a loan forbearance, and why must it be flagged?',
    payload: { type: 'recall', modelAnswer: 'Two conditions: the borrower is in financial difficulty, and the bank grants a concession it would not otherwise give. It must be flagged because it can hide arrears and changes staging, default and reporting.',
      keyPoints: [{ text: 'Borrower in financial difficulty', essential: true }, { text: 'A concession the bank would not otherwise give', essential: true }, { text: 'Flagged because it can hide arrears and changes staging and reporting', essential: false }] },
    explanation: 'Difficulty plus concession — and a flag that follows the loan.' },
  { id: 'recovery-lgd-calc', conceptIds: ['lgd-realised'], difficulty: 3, prompt: 'Exposure at default ₹100 crore. One year later the bank recovers ₹60 crore and pays ₹5 crore of costs. Discount rate 10%. What is the LGD (%)?',
    payload: { type: 'calculate', answer: 50, tolerance: { kind: 'abs', value: 0.5 }, unit: '%', worked: ['Net recovery = 60 − 5 = 55', 'PV = 55 ÷ 1.10 = 50', 'LGD = 1 − 50 ÷ 100 = 50%'] },
    explanation: 'Costs and time both count: 60 received looks like 40% loss, but the true loss is 50%.' },
  { id: 'recovery-writeoff-recall', conceptIds: ['lgd-realised'], difficulty: 2, prompt: 'From memory: what does a write-off do, and what does it not do?',
    payload: { type: 'recall', modelAnswer: 'It removes the unrecoverable balance from the balance sheet (using the allowance), but it does not cancel the borrower’s legal obligation; later recoveries are income.',
      keyPoints: [{ text: 'Removes the balance from the books', essential: true }, { text: 'Uses the allowance already held', essential: false }, { text: 'Does not cancel the legal debt', essential: true }, { text: 'Later recoveries are income', essential: false }] },
    explanation: 'Accounting removal ≠ legal forgiveness.' },
];
