import type { Item } from '../types';

export const registryItems: Item[] = [
  { id: 'anchor-registry', conceptIds: ['collateral-haircut'], difficulty: 1, prompt: 'Palace Walk: in the Registry, a pair of scissors trims a valuation. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'registry-scissors', options: ['Collateral and haircuts', 'Covenants', 'Roll rates and vintages', 'Net interest income and margin'], answerIndex: 0 },
    explanation: 'The scissors cut market value down to what a sale can really recover.' },
  { id: 'registry-collateral', conceptIds: ['collateral-haircut'], difficulty: 1, prompt: 'Good collateral mainly reduces…',
    payload: { type: 'choice', options: ['The probability of default', 'The loss if default happens', 'The need to monitor the borrower', 'The interest-rate risk'], answerIndex: 1 },
    explanation: 'Collateral cuts loss severity (LGD). It does not make default less likely.' },
  { id: 'registry-haircut-calc', conceptIds: ['collateral-haircut'], difficulty: 1, prompt: 'A property is valued at ₹50 crore with a 30% haircut. What is its recoverable value (₹ crore)?',
    payload: { type: 'calculate', answer: 35, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Recoverable = 50 × (1 − 0.30)', '= 35'] },
    explanation: '50 × 0.70 = 35.' },
  { id: 'registry-haircut-recall', conceptIds: ['collateral-haircut'], difficulty: 2, prompt: 'From memory: why do banks apply a haircut to collateral values?',
    payload: { type: 'recall', modelAnswer: 'Because a forced sale fetches less than market value, selling takes time and costs money, and the value can fall before the sale happens.',
      keyPoints: [{ text: 'Forced-sale discount', essential: true }, { text: 'Costs and time to sell', essential: false }, { text: 'Value can fall before the sale', essential: true }] },
    explanation: 'Market value is a best case; recovery is what actually comes back.' },
  { id: 'registry-ltv-calc', conceptIds: ['ltv'], difficulty: 1, prompt: 'A ₹40 lakh home loan on a ₹50 lakh home. What is the LTV (%)?',
    payload: { type: 'calculate', answer: 80, tolerance: { kind: 'abs', value: 0.5 }, unit: '%', worked: ['LTV = loan ÷ value', '= 40 ÷ 50', '= 80%'] },
    explanation: '40 ÷ 50 = 80%.' },
  { id: 'registry-ltv-choice', conceptIds: ['ltv'], difficulty: 2, prompt: 'That home falls 20% in value and the loan balance is unchanged. What is the current LTV?',
    payload: { type: 'choice', options: ['64%', '80%', '96%', '100%'], answerIndex: 3 },
    explanation: 'Value 50 → 40, loan still 40: LTV = 100%. The cushion is gone.' },
  { id: 'registry-guar-choice', conceptIds: ['guarantees'], difficulty: 2, prompt: 'A company’s loan is guaranteed by its own promoter. Why does this protect less than it seems?',
    payload: { type: 'choice', options: ['Personal guarantees are never enforceable', 'The promoter’s wealth is tied to the company, so both tend to fail together', 'Guarantees only cover interest', 'The guarantor can cancel at any time'], answerIndex: 1 },
    explanation: 'A guarantee is only as good as the guarantor — and this one fails in the same scenario as the borrower.' },
  { id: 'registry-guar-spot', conceptIds: ['guarantees'], difficulty: 1, prompt: 'Guarantees: which statement is wrong?',
    payload: { type: 'spot', options: ['A guarantee gives the bank a second party to claim from.', 'A guarantee removes the borrower’s risk of default.', 'A guarantee is worth as much as the guarantor’s ability to pay.', 'Capital rules can substitute an eligible guarantor’s risk weight.'], answerIndex: 1 },
    explanation: 'The borrower can still default; the guarantee changes who pays after that.' },
  { id: 'registry-guar-recall', conceptIds: ['guarantees'], difficulty: 2, prompt: 'From memory: what decides how much a guarantee is really worth?',
    payload: { type: 'recall', modelAnswer: 'The guarantor’s own ability to pay, and how independent the guarantor is from the borrower — a guarantor who fails in the same scenario adds little. Enforceability and eligibility also matter.',
      keyPoints: [{ text: 'The guarantor’s own strength', essential: true }, { text: 'Independence from the borrower (do they fail together?)', essential: true }, { text: 'Legal enforceability and eligibility', essential: false }] },
    explanation: 'A guarantee is a second source of repayment only if that source survives the borrower’s trouble.' },
  { id: 'registry-perf-sequence', conceptIds: ['perfection-charge'], difficulty: 2, prompt: 'Order the life of a security interest.',
    payload: { type: 'sequence', steps: ['Create the charge in the security documents', 'Register (perfect) the charge', 'Monitor value and insurance', 'Enforce after default'] },
    explanation: 'Unregistered security may be worthless when it is finally needed.' },
  { id: 'registry-perf-recall', conceptIds: ['perfection-charge'], difficulty: 2, prompt: 'From memory: what three things must be true for security to actually protect the bank?',
    payload: { type: 'recall', modelAnswer: 'The charge must be validly created in the security documents, perfected by registration, and its ranking known (first, second or pari passu) — otherwise other creditors may take priority.',
      keyPoints: [{ text: 'Validly created', essential: false }, { text: 'Perfected by registration', essential: true }, { text: 'Ranking known and protected', essential: true }] },
    explanation: 'Created, registered, ranked.' },
  { id: 'registry-perf-choice', conceptIds: ['perfection-charge'], difficulty: 2, prompt: 'Two lenders hold charges over the same factory. It is sold. Who is repaid first?',
    payload: { type: 'choice', options: ['The larger lender', 'The lender with the first-ranking charge', 'They always share equally', 'Whoever enforces first'], answerIndex: 1 },
    explanation: 'Rank decides: first charge before second. Pari passu charges share pro rata.' },
];
