import type { Item } from '../types';

export const reportingItems: Item[] = [
  { id: 'anchor-reporting', conceptIds: ['reporting-purpose'], difficulty: 1, prompt: 'Palace Walk: the clock tower shows three faces to three audiences. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'report-clock', options: ['Three kinds of reporting', 'Wrong-way risk', 'Covenants', 'Loan-to-value'], answerIndex: 0 },
    explanation: 'Investors, supervisors and managers each read a different face.' },
  { id: 'report-purpose-classify', conceptIds: ['reporting-purpose'], difficulty: 1, prompt: 'Which kind of reporting?',
    payload: { type: 'classify', buckets: ['Financial', 'Prudential', 'Management'], entries: [
      { text: 'Annual report with audited accounts', bucket: 0 }, { text: 'Capital adequacy return to the regulator', bucket: 1 },
      { text: 'Weekly collections dashboard for the credit head', bucket: 2 }, { text: 'Large-exposures return', bucket: 1 }] },
    explanation: 'Investors, supervisors, managers.' },
  { id: 'report-purpose-recall', conceptIds: ['reporting-purpose'], difficulty: 2, prompt: 'From memory: why can the same loan show different numbers in the accounts, a regulatory return and a management report?',
    payload: { type: 'recall', modelAnswer: 'Each answers a different question for a different audience, so definitions, scope, measurement and timing differ. The differences should be reconciled and explained, not forced to match.',
      keyPoints: [{ text: 'Different audiences and purposes', essential: true }, { text: 'Different definitions, scope and timing', essential: true }, { text: 'Reconcile and explain, don’t force a match', essential: false }] },
    explanation: 'Same loan, three lenses.' },
  { id: 'report-returns-choice', conceptIds: ['regulatory-returns'], difficulty: 1, prompt: 'A return fails one of the regulator’s validation rules the day before the deadline. What should happen?',
    payload: { type: 'choice', options: ['Submit anyway', 'Override the rule', 'Investigate the data, fix it at source or document the exception, then submit', 'Skip that template'], answerIndex: 2 },
    explanation: 'Validation failures signal wrong data; the fix belongs at the source.' },
  { id: 'report-returns-recall', conceptIds: ['regulatory-returns'], difficulty: 2, prompt: 'From memory: what does every cell of a regulatory template need behind it?',
    payload: { type: 'recall', modelAnswer: 'A definition from the regulator’s instructions, a mapped data source with transformation rules, the validation rules it must pass, and an owner.',
      keyPoints: [{ text: 'Regulatory definition', essential: true }, { text: 'Mapped source and rules', essential: true }, { text: 'Validation rules', essential: false }, { text: 'An owner', essential: false }] },
    explanation: 'Definition, source, checks, owner.' },
  { id: 'report-recon-calc', conceptIds: ['reconciliation'], difficulty: 2, prompt: 'The risk system shows gross loans of ₹1,020 crore; the ledger shows ₹1,000 crore. Accrued interest held only in the risk system explains ₹15 crore. What is unexplained (₹ crore)?',
    payload: { type: 'calculate', answer: 5, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Difference = 1,020 − 1,000 = 20', 'Explained = 15', 'Unexplained = 5'] },
    explanation: 'The ₹5 crore break must be investigated against the tolerance.' },
  { id: 'report-recon-spot', conceptIds: ['reconciliation'], difficulty: 2, prompt: 'Reconciliation: which statement is wrong?',
    payload: { type: 'spot', options: ['Known differences are explained item by item.', 'An unexplained difference below any size can be ignored forever.', 'Breaks above tolerance are investigated.', 'An unexplained gap means one of the numbers is wrong.'], answerIndex: 1 },
    explanation: 'Tolerances decide urgency, not whether a break is real.' },
  { id: 'report-disc-choice', conceptIds: ['disclosures'], difficulty: 2, prompt: 'Which table must a bank reporting under IFRS publish about credit risk?',
    payload: { type: 'choice', options: ['A movement of the loss allowance, including by stage', 'Each borrower’s name and PD', 'The scorecard points table', 'Next year’s budget'], answerIndex: 0 },
    explanation: 'IFRS 7 requires allowance reconciliations and exposures by stage, not borrower-level data.' },
  { id: 'report-disc-recall', conceptIds: ['disclosures'], difficulty: 2, prompt: 'From memory: name the two families of public credit-risk disclosure and the consistency rule they share.',
    payload: { type: 'recall', modelAnswer: 'Accounting disclosures (IFRS 7: loans and allowances by stage, allowance movements) and Pillar 3 regulatory disclosures (capital, RWA, asset quality, mitigation). They must agree with the audited accounts and regulatory returns.',
      keyPoints: [{ text: 'Accounting (IFRS 7) disclosures', essential: true }, { text: 'Pillar 3 disclosures', essential: true }, { text: 'Must agree with accounts and returns', essential: false }] },
    explanation: 'Two families, one set of consistent numbers.' },
];
