import type { Item } from '../types';

export const stormItems: Item[] = [
  { id: 'anchor-storm', conceptIds: ['concentration'], difficulty: 1, prompt: 'Palace Walk: where does the concentration pie live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'storm-pie', options: ['Storm Centre', 'Market Quarter', 'The Port', 'Town Hall'], answerIndex: 0 },
    explanation: 'The storm hits wherever too much sits in one slice.' },
  { id: 'storm-choice', conceptIds: ['concentration'], difficulty: 1, prompt: 'Which portfolio is most exposed to one shock?',
    payload: { type: 'choice', options: ['100 loans across 10 sectors', '100 loans to suppliers of one car maker', '100 loans across 5 regions', '100 small retail loans'], answerIndex: 1 },
    explanation: 'Many names sharing one driver behave like one big exposure.' },
  { id: 'storm-conc-recall', conceptIds: ['concentration'], difficulty: 2, prompt: 'From memory: name four dimensions of concentration, and why Pillar 1 misses it.',
    payload: { type: 'recall', modelAnswer: 'Single name or group, sector, geography, collateral type (also product or funding source). Pillar 1 formulas assume a well-diversified book, so concentration is handled with limits and Pillar 2 capital.',
      keyPoints: [{ text: 'At least three dimensions (name, sector, geography, collateral)', essential: true }, { text: 'Pillar 1 assumes diversification', essential: true }, { text: 'Handled by limits and Pillar 2', essential: false }] },
    explanation: 'Formulas assume many small independent risks.' },
  { id: 'storm-corr-choice', conceptIds: ['correlation'], difficulty: 2, prompt: 'A bank spreads the same total lending across many more unrelated borrowers. What changes?',
    payload: { type: 'choice', options: ['Expected loss falls', 'Unexpected loss falls; expected loss stays about the same', 'Both rise', 'Nothing changes'], answerIndex: 1 },
    explanation: 'Diversification narrows the spread of outcomes, not the average.' },
  { id: 'storm-corr-recall', conceptIds: ['correlation'], difficulty: 2, prompt: 'From memory: what does higher default correlation do to the loss distribution?',
    payload: { type: 'recall', modelAnswer: 'It fattens the tail: bad years become worse because many borrowers default together. Expected loss is unchanged, but unexpected loss and required capital rise.',
      keyPoints: [{ text: 'Fatter tail / worse bad years', essential: true }, { text: 'Expected loss unchanged', essential: false }, { text: 'Unexpected loss and capital rise', essential: true }] },
    explanation: 'Correlation is what turns many small risks into one big one.' },
  { id: 'storm-stress-calc', conceptIds: ['stress-testing'], difficulty: 3, prompt: 'CET1 ₹100 crore, RWA ₹1,000 crore. A stress scenario causes ₹30 crore of losses and lifts RWA to ₹1,100 crore. What is the stressed CET1 ratio (%)?',
    payload: { type: 'calculate', answer: 6.3636, tolerance: { kind: 'abs', value: 0.02 }, unit: '%', worked: ['Stressed CET1 = 100 − 30 = 70', 'Stressed ratio = 70 ÷ 1,100', '= 6.36%'] },
    explanation: 'From 10% to 6.36%: losses cut the numerator and migration inflates the denominator.' },
  { id: 'storm-stress-sequence', conceptIds: ['stress-testing'], difficulty: 2, prompt: 'Order the steps of a credit stress test.',
    payload: { type: 'sequence', steps: ['Define a severe but plausible scenario', 'Translate it into stressed PDs and LGDs', 'Project losses, profits and RWA', 'Compute the stressed capital ratio', 'Decide management actions'] },
    explanation: 'Story → parameters → numbers → capital → action.' },
  { id: 'storm-le-calc', conceptIds: ['connected-counterparties'], difficulty: 1, prompt: 'Tier 1 capital is ₹400 crore. Under the Basel 25% large-exposures limit, what is the maximum exposure to one connected group (₹ crore)?',
    payload: { type: 'calculate', answer: 100, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Limit = 25% × 400', '= 100'] },
    explanation: 'The group, not each company, counts against the limit.' },
  { id: 'storm-group-choice', conceptIds: ['connected-counterparties'], difficulty: 2, prompt: 'Company A supplies 80% of its output to Company B; they share no owners. For large-exposure purposes they are…',
    payload: { type: 'choice', options: ['Always separate', 'Possibly one connected group, through economic dependence', 'One group only if they share a bank', 'One group only if the same auditor signs both'], answerIndex: 1 },
    explanation: 'Control or economic dependence can connect borrowers; if B fails, A likely follows.' },
  { id: 'storm-kpi-calc', conceptIds: ['portfolio-kpis'], difficulty: 1, prompt: 'Stage 3 gross loans ₹60 crore; total gross loans ₹1,500 crore. What is the Stage 3 ratio (%)?',
    payload: { type: 'calculate', answer: 4, tolerance: { kind: 'abs', value: 0.01 }, unit: '%', worked: ['Stage 3 ratio = 60 ÷ 1,500', '= 4.0%'] },
    explanation: 'Gross over gross.' },
  { id: 'storm-cor-calc', conceptIds: ['portfolio-kpis'], difficulty: 2, prompt: 'Annual impairment charge ₹45 crore; average gross loans ₹3,000 crore. What is the cost of risk (basis points)?',
    payload: { type: 'calculate', answer: 150, tolerance: { kind: 'abs', value: 0.5 }, unit: 'bps', worked: ['Cost of risk = 45 ÷ 3,000 = 1.5%', '= 150 bps'] },
    explanation: 'A charge (flow) over an average balance, annualised.' },
];
