import type { Item } from '../types';

export const studioItems: Item[] = [
  { id: 'anchor-studio', conceptIds: ['requirement-to-test'], difficulty: 1, prompt: 'Palace Walk: in your office, a board of cards runs from rule to evidence. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'studio-board', options: ['Rule → requirement → test → evidence', 'Counterparty exposure', 'The three pillars', 'Roll rates and vintages'], answerIndex: 0 },
    explanation: 'The requirement board: every rule ends as proof.' },
  { id: 'studio-req-spot', conceptIds: ['requirement-to-test'], difficulty: 2, prompt: 'Which requirement is not testable as written?',
    payload: { type: 'spot', options: ['Set stage = 2 when DPD > 30 at month-end.', 'The system should handle deteriorated loans appropriately.', 'Reject collateral values below zero with error code C01.', 'Recalculate ECL on the first business day of each month.'], answerIndex: 1 },
    explanation: '“Appropriately” cannot be proved or disproved. Thresholds, fields and outcomes can.' },
  { id: 'studio-req-recall', conceptIds: ['requirement-to-test'], difficulty: 2, prompt: 'From memory: what must a good credit-risk requirement state?',
    payload: { type: 'recall', modelAnswer: 'The rule and its source, the data fields it uses, thresholds and precedence, edge cases (including exact boundaries), and acceptance criteria a tester can prove.',
      keyPoints: [{ text: 'Rule and source', essential: false }, { text: 'Data fields', essential: false }, { text: 'Thresholds, precedence and boundaries', essential: true }, { text: 'Testable acceptance criteria', essential: true }] },
    explanation: 'If a tester cannot fail it, it is not a requirement.' },
  { id: 'studio-trace-sequence', conceptIds: ['traceability'], difficulty: 1, prompt: 'Order a traceability chain.',
    payload: { type: 'sequence', steps: ['Regulation or policy clause', 'Requirement', 'Data and design', 'Test case', 'Test result and evidence'] },
    explanation: 'Source to proof, link by link.' },
  { id: 'studio-trace-recall', conceptIds: ['traceability'], difficulty: 2, prompt: 'From memory: what two things does a traceability matrix prove?',
    payload: { type: 'recall', modelAnswer: 'Coverage — every source rule has requirements and passing tests — and impact — what a change to any rule or field will affect.',
      keyPoints: [{ text: 'Coverage (nothing missed)', essential: true }, { text: 'Impact of change', essential: true }] },
    explanation: 'Nothing missed; nothing surprising.' },
  { id: 'studio-map-classify', conceptIds: ['data-mapping'], difficulty: 2, prompt: 'Which part of a mapping specification is each?',
    payload: { type: 'classify', buckets: ['Source', 'Transformation', 'Default rule', 'Grain'], entries: [
      { text: 'Loan system field PAST_DUE_DAYS', bucket: 0 }, { text: 'Stage = 2 if DPD > 30', bucket: 1 },
      { text: 'If rating is missing, use the worst grade', bucket: 2 }, { text: 'One row per facility per month', bucket: 3 }] },
    explanation: 'Where from, what done, what if missing, at what level.' },
  { id: 'studio-map-recall', conceptIds: ['data-mapping'], difficulty: 2, prompt: 'From memory: what does a source-to-target mapping record for each target field?',
    payload: { type: 'recall', modelAnswer: 'The source system and field, the transformation rule, what happens when the source is missing (default), and the grain.',
      keyPoints: [{ text: 'Source system and field', essential: true }, { text: 'Transformation rule', essential: true }, { text: 'Missing-value default', essential: false }, { text: 'Grain', essential: false }] },
    explanation: 'Most reporting defects trace to a gap in one of these.' },
  { id: 'studio-uat-choice', conceptIds: ['uat'], difficulty: 1, prompt: 'The rule is “Stage 2 when DPD > 30”. Which UAT case is most important to add?',
    payload: { type: 'choice', options: ['DPD = 0', 'DPD = 30 and DPD = 31', 'DPD = 200', 'A loan with no payments due'], answerIndex: 1 },
    explanation: 'Boundaries are where off-by-one bugs live: 30 must stay Stage 1, 31 must move.' },
  { id: 'studio-uat-recall', conceptIds: ['uat'], difficulty: 2, prompt: 'From memory: what makes UAT complete?',
    payload: { type: 'recall', modelAnswer: 'Scenarios traced to requirements, including boundary and negative cases; prepared test data; defects logged, triaged and retested; formal, evidenced sign-off.',
      keyPoints: [{ text: 'Boundary and negative cases', essential: true }, { text: 'Defects retested', essential: false }, { text: 'Evidenced sign-off', essential: true }] },
    explanation: 'Scenarios, fixes, signature.' },
  { id: 'studio-brd-classify', conceptIds: ['brd-frd'], difficulty: 1, prompt: 'Business or functional requirement?',
    payload: { type: 'classify', buckets: ['Business requirement', 'Functional requirement'], entries: [
      { text: 'Deteriorated loans must carry lifetime ECL', bucket: 0 }, { text: 'Set STAGE = 2 when DPD > 30 or PD ratio ≥ 2', bucket: 1 },
      { text: 'Reduce manual effort in month-end provisioning', bucket: 0 }, { text: 'Show the stage history on the facility screen', bucket: 1 }] },
    explanation: 'What and why, versus how the system behaves.' },
  { id: 'studio-brd-recall', conceptIds: ['brd-frd'], difficulty: 1, prompt: 'From memory: what is the difference between a business and a functional requirement?',
    payload: { type: 'recall', modelAnswer: 'A business requirement states what the business needs and why. A functional requirement states how the system must behave to meet it, precisely enough to build and test.',
      keyPoints: [{ text: 'Business = what and why', essential: true }, { text: 'Functional = how the system behaves', essential: true }] },
    explanation: 'The BA translates the first into the second.' },
];
