import type { Item } from '../types';

export const townhallItems: Item[] = [
  { id: 'anchor-townhall', conceptIds: ['three-lines'], difficulty: 1, prompt: 'Palace Walk: where does the table with three chairs stand?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'hall-table', options: ['Town Hall', 'BA Studio', 'The Branch', 'Reporting Tower'], answerIndex: 0 },
    explanation: 'Three chairs, three lines of defence.' },
  { id: 'hall-choice', conceptIds: ['three-lines'], difficulty: 1, prompt: 'Who owns the credit risk of a new loan?',
    payload: { type: 'choice', options: ['Internal audit', 'The business that originates it', 'The regulator', 'The data team'], answerIndex: 1 },
    explanation: 'First line owns; second line challenges; third line assures.' },
  { id: 'hall-lines-classify', conceptIds: ['three-lines'], difficulty: 1, prompt: 'Which line of defence?',
    payload: { type: 'classify', buckets: ['First line', 'Second line', 'Third line'], entries: [
      { text: 'Relationship manager structures and proposes a loan', bucket: 0 }, { text: 'Credit risk sets sector limits and challenges proposals', bucket: 1 },
      { text: 'Internal audit tests the credit process', bucket: 2 }, { text: 'Model validation reviews the PD model', bucket: 1 }] },
    explanation: 'Own, challenge, assure.' },
  { id: 'hall-lines-recall', conceptIds: ['three-lines'], difficulty: 1, prompt: 'From memory: describe the three lines of defence.',
    payload: { type: 'recall', modelAnswer: 'First line: the business owns and manages the risk and its controls. Second line: risk management sets policy and limits, monitors and challenges. Third line: internal audit independently assures the whole system.',
      keyPoints: [{ text: 'First line owns the risk', essential: true }, { text: 'Second line sets limits and challenges', essential: true }, { text: 'Third line assures independently', essential: true }] },
    explanation: 'Own, challenge, assure.' },
  { id: 'hall-appetite-choice', conceptIds: ['risk-appetite'], difficulty: 2, prompt: 'The Stage 3 ratio crosses its risk-appetite early-warning trigger but not the hard limit. What happens?',
    payload: { type: 'choice', options: ['Nothing until the hard limit', 'It is escalated to the named owner, who reports and proposes actions', 'Lending stops immediately', 'The limit is raised'], answerIndex: 1 },
    explanation: 'Triggers exist to act before a limit is breached.' },
  { id: 'hall-appetite-recall', conceptIds: ['risk-appetite'], difficulty: 2, prompt: 'From memory: how does board risk appetite reach day-to-day lending?',
    payload: { type: 'recall', modelAnswer: 'The board sets appetite metrics with triggers and limits; these cascade into business and portfolio limits; breaches are escalated to named owners within set times.',
      keyPoints: [{ text: 'Board metrics with triggers and limits', essential: true }, { text: 'Cascade into business limits', essential: true }, { text: 'Breach escalation to owners', essential: false }] },
    explanation: 'From board statement to desk limit.' },
  { id: 'hall-policy-sequence', conceptIds: ['committees-policy'], difficulty: 2, prompt: 'Order from widest authority to narrowest.',
    payload: { type: 'sequence', steps: ['Board (approves policy and appetite)', 'Board risk committee', 'Management credit committee', 'Individual delegated authority'] },
    explanation: 'Authority flows down; accountability flows up.' },
  { id: 'hall-policy-recall', conceptIds: ['committees-policy'], difficulty: 2, prompt: 'From memory: who approves the credit policy, and what proves governance actually worked?',
    payload: { type: 'recall', modelAnswer: 'The board (through its risk committee) approves credit policy and appetite; committees and delegated authorities apply it. Minutes and decision records are the evidence.',
      keyPoints: [{ text: 'Board approves policy', essential: true }, { text: 'Committees and delegated authorities apply it', essential: false }, { text: 'Minutes and records are the evidence', essential: true }] },
    explanation: 'If it is not recorded, it did not happen.' },
  { id: 'hall-conduct-spot', conceptIds: ['conduct'], difficulty: 1, prompt: 'Conduct: which statement is wrong?',
    payload: { type: 'spot', options: ['Pricing and terms must be clear to the borrower.', 'Collections can use any pressure as long as the loan is repaid.', 'Affordability checks protect customers and the bank.', 'Conduct failures can bring fines even if credit losses are low.'], answerIndex: 1 },
    explanation: 'Fair collections are a conduct requirement in their own right.' },
  { id: 'hall-conduct-recall', conceptIds: ['conduct'], difficulty: 2, prompt: 'From memory: name three conduct requirements that become system requirements.',
    payload: { type: 'recall', modelAnswer: 'Examples: clear disclosure of pricing and terms, affordability checks, cooling-off or look-up periods, limits on collection contact, fair treatment of customers in difficulty.',
      keyPoints: [{ text: 'Disclosure of pricing and terms', essential: false }, { text: 'Affordability checks', essential: false }, { text: 'Fair collections limits', essential: false }, { text: 'At least three concrete examples', essential: true }] },
    explanation: 'Conduct rules are built into screens, letters and workflows.' },
];
