import type { Item } from '../types';

export const tradingItems: Item[] = [
  { id: 'anchor-trading', conceptIds: ['counterparty-exposure'], difficulty: 1, prompt: 'Palace Walk: on the Trading Floor, a see-saw tips whichever way markets move. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'trading-seesaw', options: ['Counterparty exposure', 'The allowance walk', 'Data lineage', 'Scorecards'], answerIndex: 0 },
    explanation: 'Exposure tips to whichever side is owed money.' },
  { id: 'trading-choice', conceptIds: ['counterparty-exposure'], difficulty: 2, prompt: 'A swap has ₹100 crore notional and is worth +₹2 crore to the bank today. Current exposure to the counterparty is…',
    payload: { type: 'choice', options: ['₹100 crore', '₹2 crore', '₹102 crore', 'Zero'], answerIndex: 1 },
    explanation: 'Exposure is replacement cost (positive value), not notional.' },
  { id: 'trading-exp-recall', conceptIds: ['counterparty-exposure'], difficulty: 2, prompt: 'From memory: why is counterparty exposure harder to measure than a loan’s exposure?',
    payload: { type: 'recall', modelAnswer: 'Because it equals the trade’s positive market value, which moves with markets: it can grow, shrink or flip to the other side before the counterparty defaults. Notional is not the exposure.',
      keyPoints: [{ text: 'Exposure = positive replacement value', essential: true }, { text: 'It moves with markets and is uncertain', essential: true }, { text: 'It can flip between the parties', essential: false }] },
    explanation: 'A loan’s exposure is scheduled; a derivative’s is a market variable.' },
  { id: 'trading-net-calc', conceptIds: ['netting-collateral'], difficulty: 2, prompt: 'Three trades with one counterparty are worth +₹10, −₹6 and +₹3 crore to the bank. With an enforceable netting agreement, what is the exposure (₹ crore)?',
    payload: { type: 'calculate', answer: 7, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Net value = 10 − 6 + 3 = 7', 'Exposure = max(net, 0) = 7', '(Without netting: 10 + 3 = 13)'] },
    explanation: 'Netting cuts exposure from 13 to 7.' },
  { id: 'trading-margin-choice', conceptIds: ['netting-collateral'], difficulty: 1, prompt: 'The net exposure is ₹7 crore and the counterparty has posted ₹5 crore of variation margin. What exposure remains?',
    payload: { type: 'choice', options: ['₹12 crore', '₹7 crore', '₹2 crore', 'Zero'], answerIndex: 2 },
    explanation: 'Margin covers most of today’s value; initial margin would cover future moves.' },
  { id: 'trading-saccr-calc', conceptIds: ['pfe-saccr'], difficulty: 2, prompt: 'Under SA-CCR, replacement cost is ₹4 crore and PFE is ₹6 crore. What is the EAD (₹ crore)?',
    payload: { type: 'calculate', answer: 14, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['EAD = 1.4 × (RC + PFE)', '= 1.4 × (4 + 6)', '= 14'] },
    explanation: 'The 1.4 alpha scales today’s and tomorrow’s exposure together.' },
  { id: 'trading-pfe-choice', conceptIds: ['pfe-saccr'], difficulty: 2, prompt: 'Why does a bank measure potential future exposure, not just today’s value?',
    payload: { type: 'choice', options: ['Because regulators ignore today’s value', 'Because exposure can grow before the counterparty defaults', 'Because PFE is always smaller', 'Because notional changes daily'], answerIndex: 1 },
    explanation: 'Default can come later, when the trade may be worth much more.' },
  { id: 'trading-wwr-choice', conceptIds: ['wrong-way-risk'], difficulty: 2, prompt: 'Which trade shows wrong-way risk?',
    payload: { type: 'choice', options: ['A currency swap with a highly rated exporter', 'Protection on a bank bought from that bank’s own affiliate', 'An interest-rate swap fully covered by daily margin', 'A deposit placed with a central bank'], answerIndex: 1 },
    explanation: 'If the bank fails, its affiliate is likely failing too — exactly when the protection is needed.' },
  { id: 'trading-wwr-recall', conceptIds: ['wrong-way-risk'], difficulty: 2, prompt: 'From memory: define wrong-way risk and why models understate it.',
    payload: { type: 'recall', modelAnswer: 'Exposure to a counterparty rises as that counterparty’s credit quality falls. Standard models treat exposure and default as independent, so they understate losses when both move together.',
      keyPoints: [{ text: 'Exposure rises as the counterparty weakens', essential: true }, { text: 'Models assume independence', essential: true }, { text: 'So losses are understated', essential: false }] },
    explanation: 'Correlation between exposure and default is the whole problem.' },
  { id: 'trading-cva-recall', conceptIds: ['cva'], difficulty: 3, prompt: 'From memory: what is CVA, and how can it cause losses with no default?',
    payload: { type: 'recall', modelAnswer: 'CVA is the market value of the counterparty’s default risk on the trades (roughly expected exposure × PD × LGD, from market spreads). When the counterparty’s credit spread widens, CVA rises and the trades lose value — a loss without any default.',
      keyPoints: [{ text: 'Market value of counterparty default risk', essential: true }, { text: 'Driven by exposure and credit spreads', essential: false }, { text: 'Spread widening = loss without default', essential: true }] },
    explanation: 'That mark-to-market risk is why CVA has its own capital charge.' },
  { id: 'trading-cva-choice', conceptIds: ['cva'], difficulty: 2, prompt: 'A counterparty’s credit spread widens sharply. Nothing else changes. What happens to CVA?',
    payload: { type: 'choice', options: ['It falls', 'It rises, and the bank books a loss', 'It is unaffected until default', 'It becomes zero'], answerIndex: 1 },
    explanation: 'Higher market-implied default risk means a bigger deduction from trade value.' },
];
