import type { Item } from '../types';

export const vaultItems: Item[] = [
  { id: 'anchor-vault', conceptIds: ['ifrs9-stages'], difficulty: 1, prompt: 'Palace Walk: at the Provision Vault, three round doors stand side by side. What lives here?',
    payload: { type: 'anchor', mode: 'whatLivesHere', anchor: 'vault-doors', options: ['IFRS 9 stages', 'The capital stack', 'Scorecards', 'Covenants'], answerIndex: 0 },
    explanation: 'Door 1, door 2, door 3: the three stages.' },
  { id: 'vault-classify', conceptIds: ['ifrs9-stages'], difficulty: 2, prompt: 'Sort each loan into its IFRS 9 stage.',
    payload: { type: 'classify', buckets: ['Stage 1', 'Stage 2', 'Stage 3'], entries: [
      { text: 'Newly originated, performing', bucket: 0 }, { text: '45 days past due', bucket: 1 }, { text: 'PD tripled since origination', bucket: 1 },
      { text: '120 days past due', bucket: 2 }, { text: 'Borrower judged unlikely to pay', bucket: 2 }] },
    explanation: 'Deterioration → Stage 2; default (including UTP) → Stage 3.' },
  { id: 'vault-stages-recall', conceptIds: ['ifrs9-stages'], difficulty: 1, prompt: 'From memory: describe the three IFRS 9 stages and the ECL horizon for each.',
    payload: { type: 'recall', modelAnswer: 'Stage 1: performing, 12-month ECL from day one. Stage 2: significant increase in credit risk, lifetime ECL. Stage 3: credit-impaired (default), lifetime ECL, interest on the net amount.',
      keyPoints: [{ text: 'Stage 1: 12-month ECL', essential: true }, { text: 'Stage 2: SICR, lifetime ECL', essential: true }, { text: 'Stage 3: credit-impaired, lifetime ECL', essential: true }, { text: 'Stage 3 interest on the net amount', essential: false }] },
    explanation: 'Horizon changes at Stage 2; the income basis changes at Stage 3.' },
  { id: 'vault-sicr-choice', conceptIds: ['sicr'], difficulty: 1, prompt: 'What is the IFRS 9 backstop for a significant increase in credit risk?',
    payload: { type: 'choice', options: ['More than 30 days past due (rebuttable presumption)', 'More than 90 days past due', 'Any rating downgrade', 'PD above 5%'], answerIndex: 0 },
    explanation: '30 days past due is presumed to be SICR unless the bank can rebut it. 90 days is the default backstop.' },
  { id: 'vault-sicr-recall', conceptIds: ['sicr'], difficulty: 2, prompt: 'From memory: how is SICR assessed?',
    payload: { type: 'recall', modelAnswer: 'By comparing the current risk of default with the risk at initial recognition: a relative increase in PD above a threshold, qualitative triggers (watchlist, forbearance), and the 30-days-past-due backstop. Exits need the triggers to clear.',
      keyPoints: [{ text: 'Compared with risk at origination', essential: true }, { text: 'Relative PD increase threshold', essential: false }, { text: 'Qualitative triggers', essential: false }, { text: '30 DPD backstop', essential: true }] },
    explanation: 'Change since origination, not today’s level.' },
  { id: 'vault-sicr-spot', conceptIds: ['sicr'], difficulty: 2, prompt: 'SICR: which statement is wrong?',
    payload: { type: 'spot', options: ['SICR compares current risk with risk at initial recognition.', 'SICR is judged only on today’s PD level, whatever it was at origination.', 'Forbearance can be a qualitative SICR trigger.', 'Loans can move back to Stage 1 when the triggers clear.'], answerIndex: 1 },
    explanation: 'A 3% PD loan originated at 3% has not deteriorated; one originated at 0.5% has.' },
  { id: 'vault-ecl-calc', conceptIds: ['ecl-measurement'], difficulty: 2, prompt: 'One-year horizon: PD 2%, LGD 40%, EAD ₹100 crore, loss at year end, EIR 8%. What is the 12-month ECL (₹ crore)?',
    payload: { type: 'calculate', answer: 0.7407, tolerance: { kind: 'abs', value: 0.002 }, unit: '₹ crore', worked: ['Undiscounted = 0.02 × 0.40 × 100 = 0.8', 'Discounted = 0.8 ÷ 1.08', '= 0.7407'] },
    explanation: 'Expected loss, discounted at the EIR.' },
  { id: 'vault-ecl-recall', conceptIds: ['ecl-measurement'], difficulty: 2, prompt: 'From memory: name the four properties an IFRS 9 ECL estimate must have.',
    payload: { type: 'recall', modelAnswer: 'Unbiased and probability-weighted; reflects the time value of money; uses reasonable and supportable information about past events, current conditions and forecasts of future conditions.',
      keyPoints: [{ text: 'Unbiased', essential: false }, { text: 'Probability-weighted', essential: true }, { text: 'Time value of money', essential: false }, { text: 'Reasonable and supportable forward-looking information', essential: true }] },
    explanation: 'Weighted, discounted, forward-looking.' },
  { id: 'vault-scen-calc', conceptIds: ['forward-looking-scenarios'], difficulty: 2, prompt: 'ECL under three scenarios: base ₹10 crore (60%), upside ₹8 crore (20%), downside ₹20 crore (20%). What is the reported ECL (₹ crore)?',
    payload: { type: 'calculate', answer: 11.6, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['0.6 × 10 = 6.0', '0.2 × 8 = 1.6', '0.2 × 20 = 4.0', 'Total = 11.6'] },
    explanation: 'Weighted ECL (11.6) is above the base case (10) because the downside hurts more than the upside helps.' },
  { id: 'vault-scen-choice', conceptIds: ['forward-looking-scenarios'], difficulty: 3, prompt: 'Why is probability-weighted ECL usually higher than the ECL of the base scenario alone?',
    payload: { type: 'choice', options: ['Regulators require a margin of prudence', 'Losses rise faster in bad scenarios than they fall in good ones', 'The base scenario is always optimistic', 'Scenario weights must add to more than 100%'], answerIndex: 1 },
    explanation: 'Credit losses are non-linear in the economy, so averaging outcomes beats averaging the economy.' },
  { id: 'vault-walk-calc', conceptIds: ['allowance-walk'], difficulty: 1, prompt: 'Opening allowance ₹50 crore. Impairment charge ₹12 crore. Write-offs ₹8 crore. What is the closing allowance (₹ crore)?',
    payload: { type: 'calculate', answer: 54, tolerance: { kind: 'abs', value: 0.01 }, unit: '₹ crore', worked: ['Closing = opening + charge − write-offs', '= 50 + 12 − 8', '= 54'] },
    explanation: 'Write-offs use up allowance; they do not hit P&L a second time.' },
  { id: 'vault-walk-spot', conceptIds: ['allowance-walk'], difficulty: 2, prompt: 'The allowance walk: which statement is wrong?',
    payload: { type: 'spot', options: ['The allowance is a balance-sheet stock.', 'The P&L impairment charge equals the closing allowance.', 'Write-offs reduce the allowance.', 'The movement table explains every change in the allowance.'], answerIndex: 1 },
    explanation: 'The charge is the flow that, with write-offs, moves opening to closing.' },
  { id: 'vault-cecl-classify', conceptIds: ['cecl-vs-ifrs9'], difficulty: 2, prompt: 'IFRS 9, CECL, or both?',
    payload: { type: 'classify', buckets: ['IFRS 9 only', 'CECL only', 'Both'], entries: [
      { text: 'Lifetime expected losses on every loan from day one', bucket: 1 }, { text: 'Three stages', bucket: 0 },
      { text: '12-month ECL for performing loans', bucket: 0 }, { text: 'Uses forward-looking information', bucket: 2 }] },
    explanation: 'Stages are IFRS 9’s idea; CECL goes lifetime for everything.' },
  { id: 'vault-cecl-recall', conceptIds: ['cecl-vs-ifrs9'], difficulty: 2, prompt: 'From memory: what is the key difference between IFRS 9 and CECL at origination?',
    payload: { type: 'recall', modelAnswer: 'At origination IFRS 9 books 12-month ECL (Stage 1); CECL books lifetime expected losses on every loan. So CECL front-loads more allowance.',
      keyPoints: [{ text: 'IFRS 9: 12-month ECL in Stage 1', essential: true }, { text: 'CECL: lifetime from day one', essential: true }, { text: 'CECL front-loads more allowance', essential: false }] },
    explanation: 'Same forward-looking idea, different day-one horizon.' },
];
