import type { Item } from '../types';

export const watchtowerItems: Item[] = [
  { id: 'anchor-watchtower', conceptIds: ['dpd-delinquency'], difficulty: 1, prompt: 'Palace Walk: where does the days-past-due clock live?',
    payload: { type: 'anchor', mode: 'whereDoesItLive', anchor: 'watch-clock', options: ['The Watchtower', 'Recovery Docks', 'The Mint', 'The Branch'], answerIndex: 0 },
    explanation: 'The Watchtower watches every payment date.' },
  { id: 'watch-buckets', conceptIds: ['dpd-delinquency'], difficulty: 1, prompt: 'Sort each account into its bucket.',
    payload: { type: 'classify', buckets: ['Current', '1–30', '31–60', '61–90', 'Default (> 90)'], entries: [
      { text: '0 days late', bucket: 0 }, { text: '29 days late', bucket: 1 }, { text: '59 days late', bucket: 2 }, { text: '89 days late', bucket: 3 }, { text: '119 days late', bucket: 4 }] },
    explanation: 'More than 90 days past due is the payment trigger for default.' },
  { id: 'watch-dpd-calc', conceptIds: ['dpd-delinquency'], difficulty: 2, prompt: 'The oldest unpaid instalment was due on 5 March. Today is 20 April. How many days past due?',
    payload: { type: 'calculate', answer: 46, tolerance: { kind: 'abs', value: 0 }, unit: 'days', worked: ['5 → 31 March = 26 days', '1 → 20 April = 20 days', '26 + 20 = 46'] },
    explanation: 'Count from the oldest unpaid due date: 46 days, the 31–60 bucket.' },
  { id: 'watch-dpd-spot', conceptIds: ['dpd-delinquency'], difficulty: 2, prompt: 'Days past due: which statement is wrong?',
    payload: { type: 'spot', options: ['DPD is measured from the oldest unpaid amount.', 'Paying this month’s instalment resets DPD to zero even if last month’s is unpaid.', 'Payments are normally applied to the oldest dues first.', 'More than 90 DPD is the usual payment trigger for default.'], answerIndex: 1 },
    explanation: 'The oldest unpaid amount keeps ageing until it is paid.' },
  { id: 'watch-ews-classify', conceptIds: ['early-warning'], difficulty: 1, prompt: 'Warning signal or not?',
    payload: { type: 'classify', buckets: ['Early-warning signal', 'Not a warning'], entries: [
      { text: 'Line usage jumped from 50% to 98% in a month', bucket: 0 }, { text: 'Cheques returned unpaid', bucket: 0 }, { text: 'Sales grew as planned after a new branch opened', bucket: 1 },
      { text: 'Audited financials three months late', bucket: 0 }, { text: 'Promoter pledged their shares', bucket: 0 }] },
    explanation: 'Stress shows up in payments, usage, information and behaviour before instalments are missed.' },
  { id: 'watch-ews-recall', conceptIds: ['early-warning'], difficulty: 2, prompt: 'From memory: name four kinds of early-warning signal.',
    payload: { type: 'recall', modelAnswer: 'Payment signals (bounces, late payments elsewhere), usage signals (lines used to the limit), financial signals (falling sales, covenant breaches, late financials), external signals (downgrades, adverse news, share pledges).',
      keyPoints: [{ text: 'Payment signals', essential: true }, { text: 'Usage signals', essential: false }, { text: 'Financial signals', essential: false }, { text: 'External signals', essential: false }] },
    explanation: 'Four families; each needs a data source and a threshold.' },
  { id: 'watch-roll-calc', conceptIds: ['roll-rates'], difficulty: 1, prompt: 'Last month ₹200 crore sat in the 1–30 bucket. This month ₹50 crore of it is in 31–60. What is the roll rate (%)?',
    payload: { type: 'calculate', answer: 25, tolerance: { kind: 'abs', value: 0.5 }, unit: '%', worked: ['Roll rate = rolled forward ÷ bucket last month', '= 50 ÷ 200', '= 25%'] },
    explanation: 'A quarter of the bucket got worse.' },
  { id: 'watch-vintage-choice', conceptIds: ['roll-rates'], difficulty: 2, prompt: 'Loans booked in March show twice the six-month default rate of January’s loans, at the same months on book. What does this point to?',
    payload: { type: 'choice', options: ['Normal seasonality', 'Something changed in how March loans were originated', 'The collections team got worse', 'Nothing — vintages always differ'], answerIndex: 1 },
    explanation: 'Same age, different outcome: look at the policy, channel or market for that cohort.' },
  { id: 'watch-review-choice', conceptIds: ['annual-review'], difficulty: 1, prompt: 'A corporate borrower’s rating was last updated 20 months ago. What is the problem?',
    payload: { type: 'choice', options: ['None, if payments are current', 'The bank is measuring risk with stale information; the review is overdue', 'The rating is automatically downgraded', 'The loan must be recalled'], answerIndex: 1 },
    explanation: 'Reviews refresh financials, rating, covenants and collateral. Overdue reviews are a control failure.' },
  { id: 'watch-review-recall', conceptIds: ['annual-review'], difficulty: 2, prompt: 'From memory: what does a periodic credit review refresh?',
    payload: { type: 'recall', modelAnswer: 'Financial statements, the rating, covenant compliance, collateral valuation and the limit renewal.',
      keyPoints: [{ text: 'Financials', essential: false }, { text: 'The rating', essential: true }, { text: 'Covenant compliance', essential: false }, { text: 'Collateral valuation', essential: false }] },
    explanation: 'Fresh data, fresh rating, fresh security check.' },
];
