/**
 * CREDIT RISK OS 2.0 — CASE 01: ASSET QUALITY & PROVISIONING TRANSFORMATION
 * Domain-specific configuration and dataset conforming to shared framework CaseDefinition.
 */

import {
  CaseDefinition,
  CaseMetadata,
  CaseStakeholder,
  CaseEvidence,
  ProcessNode,
  BusinessRequirement,
  BusinessRule,
  SourceToTargetMapping,
  InvestigationTask,
  CaseDefect,
  UATTestCase,
  TraceabilityChain,
  ReconciliationSummary,
  SignOffRequirement,
  GovernanceConfig,
  CasePhase,
} from '../_framework/types';

export type {
  CaseDefinition,
  CaseMetadata,
  CaseStakeholder,
  CaseEvidence,
  ProcessNode,
  BusinessRequirement,
  BusinessRule,
  SourceToTargetMapping,
  InvestigationTask,
  CaseDefect,
  UATTestCase,
  TraceabilityChain,
  ReconciliationSummary,
  SignOffRequirement,
  GovernanceConfig,
  CasePhase,
};

// Aliases for legacy component import compatibility
export type EvidenceItem = CaseEvidence;
export type SeededDefect = CaseDefect;
export type SignOffApprover = SignOffRequirement;

export const CASE_01_METADATA: CaseMetadata = {
  id: 'CASE-001',
  code: 'CASE-2026-01',
  title: 'Asset Quality & Provisioning Transformation',
  type: 'Regulatory Change + Data + Business Analysis',
  primaryDomains: ['RBI IRACP', 'SMA/NPA Classification', 'Provisioning', 'Data Quality', 'Source-to-Target Mapping', 'UAT Testing'],
  institution: 'Indus Apex Bank India',
  simulatedDate: '31 July 2026',
  businessOwner: 'Chief Risk Officer & Head of Finance Operations',
  targetDeadline: '15 August 2026 (Pre-Reporting Cutoff)',
  problemStatement: 'Month-end Risk and Finance reporting identified mismatches in asset-quality classification and required provisions across corporate credit facilities. Servicing DPD, manual watchlist files, and risk warehouse rules produce conflicting SMA/NPA states downstream.',
};

export const STAKEHOLDERS: CaseStakeholder[] = [
  {
    id: 'STK-01',
    name: 'Vikram Malhotra',
    title: 'Credit Risk SME & Policy Lead',
    department: 'First Line Credit Risk Oversight',
    roleDescription: 'Owns credit policy interpretation, SMA/NPA classification rules, and watchlist escalation guidelines under RBI IRACP Master Circulars.',
    keyConcern: 'Ensuring DPD backstops and 90+ DPD NPA classifications are enforced deterministically without unapproved manual downgrades or delays.',
    decisionsOwned: ['SMA/NPA Policy Interpretation', 'Regulatory Override Approval', 'Watchlist Escalation Thresholds'],
    evidenceProvided: ['EV-02 (Credit Policy Rule Memorandum)'],
  },
  {
    id: 'STK-02',
    name: 'Ananya Sharma',
    title: 'Finance & Impairment Controller',
    department: 'Financial Control & General Ledger Operations',
    roleDescription: 'Owns balance sheet impairment reserves, General Ledger provision posting, and month-end Risk-to-Finance reconciliation sign-offs.',
    keyConcern: 'Reconciling the ₹18.8 Cr provision variance between Risk Warehouse extracts and Finance GL filings before regulatory filing.',
    decisionsOwned: ['General Ledger Provision Balance Sign-off', 'Variance Tolerance Sign-off'],
    evidenceProvided: ['EV-01 (Month-End Risk vs Finance Reconciliation Note)'],
  },
  {
    id: 'STK-03',
    name: 'Rajesh Kulkarni',
    title: 'Collections & Credit Operations Lead',
    department: 'Loan Servicing & Delinquency Management',
    roleDescription: 'Owns core banking servicing feeds, daily DPD snapshot processing, and borrower payment clearing logs.',
    keyConcern: 'Eliminating stale DPD snapshots caused by midnight batch timing gaps between Core Banking (CBS) and Collections.',
    decisionsOwned: ['Source DPD Cutoff Timing', 'Servicing System Account Status Code Mapping'],
    evidenceProvided: ['EV-03 (Core Banking & Servicing DPD Daily Extract)'],
  },
  {
    id: 'STK-04',
    name: 'Siddharth Varma',
    title: 'Data Engineering Lead',
    department: 'Enterprise Data Platform & BCBS 239',
    roleDescription: 'Owns data ingestion pipelines, canonical credit data mart schemas, and BCBS 239 source-to-target lineage traceability.',
    keyConcern: 'Resolving duplicate join keys in `RISK_CUSTOMER_MASTER` that double-count outstanding balances downstream.',
    decisionsOwned: ['Source-to-Target Data Transformation Pipeline', 'Canonical Data Dictionary Specs'],
    evidenceProvided: ['EV-04 (Legacy Source-to-Target Data Lineage Spec)'],
  },
  {
    id: 'STK-05',
    name: 'Priya Sundaram',
    title: 'Risk Technology Lead',
    department: 'Risk Systems Architecture',
    roleDescription: 'Owns calculation engine software execution, business rule table deployment, and engine output schemas.',
    keyConcern: 'Deploying the automated IRACP classification engine to replace legacy manual spreadsheet overrides.',
    decisionsOwned: ['Rules Engine Code Deployment', 'System Interface Specs'],
    evidenceProvided: ['EV-05 (Software Bug Incident Note)'],
  },
  {
    id: 'STK-06',
    name: 'Rohan Mehta',
    title: 'QA & UAT Testing Lead',
    department: 'Quality Assurance & Business Testing',
    roleDescription: 'Coordinates business acceptance testing, manages boundary test cases, and tracks defect remediation evidence.',
    keyConcern: 'Ensuring 100% of boundary test cases (30 DPD, 60 DPD, 90 DPD, collateral split) pass before release sign-off.',
    decisionsOwned: ['UAT Test Execution Sign-off', 'Defect Closure Verification'],
    evidenceProvided: ['EV-05 (Software Bug Incident Note)'],
  },
  {
    id: 'STK-07',
    name: 'Dr. Meera Nambiar',
    title: 'Regulatory & Compliance Policy SME',
    department: 'Regulatory Compliance & Legal Oversight',
    roleDescription: 'Validates that banking software implementation adheres strictly to Reserve Bank of India (RBI) supervisory circulars.',
    keyConcern: 'Confirming no unapproved manual overrides bypass regulatory NPA classification or required provision rates.',
    decisionsOwned: ['Supervisory Rule Compliance Sign-off', 'Audit Trail Integrity Approval'],
    evidenceProvided: ['EV-06 (Executive Steering Committee Policy Resolution)'],
  },
  {
    id: 'STK-08',
    name: 'Learner (Lead Business Analyst)',
    title: 'Transformation Lead Business Analyst',
    department: 'Credit Risk & Regulatory Delivery Programme',
    roleDescription: 'Lead BA assigned to investigate asset quality discrepancies, author business requirements, design STTM, coordinate UAT, and obtain sign-offs.',
    keyConcern: 'Delivering an end-to-end controlled target state with complete traceability before the reporting cutoff.',
    decisionsOwned: ['BRD Requirements Register', 'Source-to-Target Mapping (STTM)', 'Traceability Matrix (RTM)'],
    evidenceProvided: ['Business Requirements Document (BRD)', 'Requirements Traceability Matrix (RTM)'],
  },
];

export const EVIDENCE_PACK: CaseEvidence[] = [
  {
    id: 'EV-01',
    code: 'EVID-REC-01',
    title: 'Month-End Risk vs Finance Reconciliation Variance Note',
    type: 'Memo',
    summary: 'Identifies a ₹18.8 Cr provision reserve discrepancy between Risk Warehouse extracts (₹74.8 Cr) and Finance General Ledger filings (₹56.0 Cr) as of 31 July 2026.',
    providedBy: 'Ananya Sharma (Finance Controller)',
    fullText: 'During the 31 July 2026 pre-close reconciliation, Finance identified that facility PUN-MFG-4403 (Western Precision) was reported as Standard (0.40% provision) in Finance GL extracts, whereas Risk Analytics flagged it as SMA-1 (38 DPD). Furthermore, facility DEL-MED-7706 (Aethel Healthcare, 112 DPD) carried only a 15% secured provision in Finance spreadsheets instead of the mandatory 25% unsecured Substandard NPA rate, creating a net ₹18.8 Cr understatement of required reserves.',
    keyInsights: ['PUN-MFG-4403 DPD mismatch across feeds', 'DEL-MED-7706 unsecured provision under-calculated', 'Net ₹18.8 Cr reserve deficit requiring urgent fix'],
  },
  {
    id: 'EV-02',
    code: 'EVID-POL-02',
    title: 'Credit Policy Rule Memorandum — RBI IRACP Standards',
    type: 'Policy Doc',
    summary: 'Defines mandatory DPD backstops and provisioning percentages for Scheduled Commercial Banks under RBI IRACP circulars.',
    providedBy: 'Vikram Malhotra (Credit Risk SME)',
    fullText: 'Mandatory Rule Specs:\n1. DPD <= 0: Standard (Farm/MSE 0.25%, CRE 1.00%, CRE Resi 0.75%, Other 0.40%).\n2. DPD 1 to 30: SMA-0 (Standard Rate).\n3. DPD 31 to 60: SMA-1 (Standard Rate).\n4. DPD 61 to 90: SMA-2 (Standard Rate).\n5. DPD > 90: Substandard NPA (Secured 15%, Unsecured 25%).\n6. Substandard > 12 months: Doubtful-1 (Secured 25%, Unsecured 100%).\n7. Doubtful 1-3 years: Doubtful-2 (Secured 40%, Unsecured 100%).\n8. Doubtful > 3 years: Doubtful-3 (Secured 100%, Unsecured 100%).\n9. Loss Assets: 100% provision regardless of collateral.',
    keyInsights: ['DPD > 90 triggers Substandard NPA', 'Unsecured Substandard requires 25% provision', 'SMA-1/2 carries standard provisioning rate but mandates early warning reporting'],
  },
  {
    id: 'EV-03',
    code: 'EVID-DAT-03',
    title: 'Core Banking (CBS) & Servicing Daily DPD Extract',
    type: 'Data Extract',
    summary: 'Raw servicing system DPD snapshot vs Risk Warehouse ingestion timestamp log.',
    providedBy: 'Rajesh Kulkarni (Collections Lead)',
    fullText: 'CBS Servicing extract for account PUN-MFG-4403 shows DPD = 42 days on 31 July 2026 23:59:59. However, Risk Warehouse batch script ingested the table at 18:00:00 (prior to evening payment clearing run), capturing DPD = 28 days (SMA-0). This timing gap caused a 14-day DPD lag downstream.',
    keyInsights: ['Batch snapshot timing gap causes 14-day DPD lag', 'Ingestion cutoff must align with end-of-day clearing'],
  },
  {
    id: 'EV-04',
    code: 'EVID-MAP-04',
    title: 'Legacy Source-to-Target Data Lineage Specification',
    type: 'Data Extract',
    summary: 'Reveals legacy data transformation logic mapping `cbs_dpd` to `asset_class_code`.',
    providedBy: 'Siddharth Varma (Data Engineering Lead)',
    fullText: 'Legacy Mapping Defect:\nThe SQL script `sp_calc_asset_quality.sql` contains condition `IF DPD >= 90 THEN SET STATUS = "NPA"`. Because it used `>= 90` instead of `> 90`, account CHN-RES-5507 on exactly 90 DPD was prematurely classified as NPA. Additionally, `account_id` joins on `RISK_CUSTOMER_MASTER` were missing the `facility_id` composite key, resulting in 2 duplicate facility rows.',
    keyInsights: ['Boundary operator error: `>= 90` instead of `> 90`', 'Missing composite join key creates duplicate rows'],
  },
  {
    id: 'EV-05',
    code: 'EVID-BUG-05',
    title: 'Software Bug Incident Note — Boundary Conditions & Collateral Rate',
    type: 'Defect Note',
    summary: 'Technical bug report detailing why unsecured Substandard NPAs received 15% secured rate instead of 25%.',
    providedBy: 'Rohan Mehta (QA Lead)',
    fullText: 'Defect DEF-AQ-004 Log:\nIn `iracp_calc_engine.c`, the provisioning branch for Substandard assets evaluated `if (isSecured == true || realisableSecurity > 0)` without checking if `realisableSecurity < outstanding`. For unsecured facility DEL-MED-7706 (Realisable Security = 0), the code evaluated the secured branch (15%) due to an uninitialized boolean flag. Result: Under-provisioning by ₹8.0 Cr.',
    keyInsights: ['Uninitialized secured flag caused 15% rate on 0 security asset', 'Fix requires explicit `securedPortion = Math.min(outstanding, realisableSecurity)`'],
  },
  {
    id: 'EV-06',
    code: 'EVID-MIN-06',
    title: 'Executive Steering Committee Policy Resolution',
    type: 'Minutes',
    summary: 'Clarifies regulatory override approval rules and effective-date precedence.',
    providedBy: 'Dr. Meera Nambiar (Regulatory SME)',
    fullText: 'Resolved by Committee:\n1. No manual regulatory override of asset classification shall be valid without explicit written sign-off from Credit Risk SME (Vikram Malhotra) and recorded approval metadata.\n2. In cases of conflict between Servicing DPD and manual watchlist status, the higher risk classification (worst-case precedence) shall govern.',
    keyInsights: ['Manual overrides require approval metadata', 'Worst-case precedence governs status conflicts'],
  },
];

export const CURRENT_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Loan Servicing System (CBS)',
    owner: 'Collections & Credit Operations (Rajesh Kulkarni)',
    desc: 'Captures daily repayment transactions and DPD counters. Ingestion snapshot triggers at 18:00 before evening clearing.',
    breakPoint: 'Timing gap: EOD clearing payments cleared at 23:59 are omitted, causing a 14-day DPD lag.',
  },
  {
    step: '02',
    title: 'Daily DPD Batch Extract',
    owner: 'Data Engineering Lead (Siddharth Varma)',
    desc: 'Ingests `cbs_dpd` into raw staging tables. Joins servicing accounts to customer master on single `obligor_id` key.',
    breakPoint: 'Missing composite join key (`obligor_id` + `facility_id`) generates 2 duplicate facility rows.',
  },
  {
    step: '03',
    title: 'Legacy Risk Warehouse',
    owner: 'Risk Technology Lead (Priya Sundaram)',
    desc: 'Executes legacy SQL script `sp_calc_asset_quality.sql` applying DPD classification rules.',
    breakPoint: 'Boundary operator defect: Used `>= 90` instead of `> 90`, prematurely declaring 90 DPD assets as NPA.',
  },
  {
    step: '04',
    title: 'Manual Classification Adjustment',
    owner: 'Credit Risk SME (Vikram Malhotra)',
    desc: 'Credit Risk analysts manually apply Excel overrides to correct timing lags and qualitative watchlist flags.',
    breakPoint: 'Un-governed override: Manual overrides lack structured approval metadata or audit log retention.',
  },
  {
    step: '05',
    title: 'Provisioning Spreadsheet',
    owner: 'Finance & Impairment Controller (Ananya Sharma)',
    desc: 'Finance extracts risk warehouse tables into Excel workbooks to compute required balance sheet reserves.',
    breakPoint: 'Unsecured Substandard rate defect: Unsecured NPA facility received 15% rate instead of mandatory 25%.',
  },
  {
    step: '06',
    title: 'Finance GL Reporting',
    owner: 'Financial Controller',
    desc: 'General Ledger provision totals posted to regulatory returns and executive dashboards.',
    breakPoint: 'Net ₹18.8 Cr reserve deficit between Risk Warehouse extracts and Finance GL filings.',
  },
];

export const TARGET_STATE_NODES: ProcessNode[] = [
  {
    step: '01',
    title: 'Core Banking / Collections Source',
    owner: 'Collections & Operations (Rajesh Kulkarni)',
    desc: 'Servicing DPD snapshot captured post EOD clearing completion at 23:59:59 with explicit transaction timestamp.',
    controlPoint: 'Source validation check: Blocks ingestion if EOD clearing is pending or incomplete.',
  },
  {
    step: '02',
    title: 'Controlled Ingestion & Canonical Mart',
    owner: 'Data Engineering Lead (Siddharth Varma)',
    desc: 'Ingests CBS servicing data into canonical schema using composite join key (`obligor_id` + `facility_id`).',
    controlPoint: 'Deduplication & Schema Validation: Rejects duplicate join rows before feeding risk engine.',
  },
  {
    step: '03',
    title: 'Automated IRACP Asset Quality Rules Engine',
    owner: 'Risk Technology Lead (Priya Sundaram)',
    desc: 'Executes `_engine/iracp.ts` applying exact RBI DPD operators (`DPD > 30`, `DPD > 60`, `DPD > 90`).',
    controlPoint: 'Boundary Operator Audit: Enforces exact 90 DPD boundary (exactly 90 DPD remains Standard).',
  },
  {
    step: '04',
    title: 'IRACP Provision Calculation Engine',
    owner: 'Credit Risk SME (Vikram Malhotra)',
    desc: 'Decomposes outstanding balance into secured and unsecured portions against realisable collateral valuation.',
    controlPoint: 'Collateral Haircut Check: Automatically applies 25% unsecured Substandard rate if security is ₹0.',
  },
  {
    step: '05',
    title: 'Approved Governance & Override Store',
    owner: 'Regulatory Compliance SME (Dr. Meera Nambiar)',
    desc: 'Captures manual qualitative overrides only when accompanied by mandatory written sign-off metadata.',
    controlPoint: 'Audit Log Integrity: Un-approved manual overrides are rejected with audit log alerts.',
  },
  {
    step: '06',
    title: 'Risk Data Mart & Finance GL Publication',
    owner: 'Finance & Impairment Controller (Ananya Sharma)',
    desc: 'Publishes validated asset-quality classifications and provisions directly to Finance General Ledger and RBI regulatory filings.',
    controlPoint: 'Automated Risk-to-Finance Reconciliation: Guarantees zero unexplained provision variance.',
  },
];

export const BUSINESS_REQUIREMENTS: BusinessRequirement[] = [
  {
    id: 'REQ-AQ-001',
    title: 'Automated IRACP DPD Classification Engine',
    requirementText: 'The system shall automatically derive asset-quality status (Standard, SMA-0, SMA-1, SMA-2, Substandard, Doubtful-1, Doubtful-2, Doubtful-3, Loss) based on RBI IRACP DPD backstops.',
    owner: 'Vikram Malhotra (Credit Risk SME)',
    regulatoryDriver: 'RBI Master Circular - IRACP Prudential Norms',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: '100% of accounts with DPD 1-30 are SMA-0; 31-60 are SMA-1; 61-90 are SMA-2; >90 are Substandard NPA.',
    linkedRuleId: 'RULE-AQ-01',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-001',
  },
  {
    id: 'REQ-AQ-002',
    title: 'Exact DPD Boundary Operator Specification',
    requirementText: 'The asset classification engine shall enforce exact DPD operators: DPD > 30 for SMA-1, DPD > 60 for SMA-2, and DPD > 90 for NPA Substandard classification.',
    owner: 'Priya Sundaram (Risk Technology Lead)',
    regulatoryDriver: 'RBI Master Circular - IRACP Section 2.1',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Account with exactly 90 DPD remains SMA-2 (Standard); account with 91 DPD becomes Substandard NPA.',
    linkedRuleId: 'RULE-AQ-02',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-006',
  },
  {
    id: 'REQ-AQ-003',
    title: 'Secured vs Unsecured Provision Decomposition',
    requirementText: 'The provisioning engine shall calculate required provisions by splitting outstanding balance into secured portion (up to realisable security value) and unsecured portion.',
    owner: 'Ananya Sharma (Finance Controller)',
    regulatoryDriver: 'RBI Master Circular - IRACP Section 5.3',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Secured substandard receives 15%; unsecured substandard receives 25%. Unsecured doubtful receives 100%.',
    linkedRuleId: 'RULE-AQ-06',
    linkedMappingId: 'MAP-AQ-04',
    linkedTestId: 'UAT-AQ-008',
  },
  {
    id: 'REQ-AQ-004',
    title: 'Category-Based Standard Asset Provision Rates',
    requirementText: 'Standard asset provisions shall be calculated using product category rates: Farm/MSE/Housing 0.25%, CRE 1.00%, CRE Residential 0.75%, Other Commercial 0.40%.',
    owner: 'Ananya Sharma (Finance Controller)',
    regulatoryDriver: 'RBI Master Circular - IRACP Section 5.5',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'CRE loan ₹450 Cr receives 1.00% (₹4.50 Cr); MSE loan ₹100 Cr receives 0.25% (₹0.25 Cr).',
    linkedRuleId: 'RULE-AQ-08',
    linkedMappingId: 'MAP-AQ-05',
    linkedTestId: 'UAT-AQ-009',
  },
  {
    id: 'REQ-AQ-005',
    title: 'Source Snapshot Timing & Clearing Synchronization',
    requirementText: 'Data ingestion pipelines shall capture CBS servicing DPD snapshots post end-of-day payment clearing run at 23:59:59 to prevent DPD lag.',
    owner: 'Rajesh Kulkarni (Collections Lead)',
    regulatoryDriver: 'BCBS 239 Data Timeliness Principle 6',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Data Warehouse DPD matches EOD clearing DPD with zero timing discrepancy.',
    linkedRuleId: 'RULE-AQ-03',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-011',
  },
  {
    id: 'REQ-AQ-006',
    title: 'Composite Join Key Integrity & Deduplication',
    requirementText: 'Data mapping pipelines shall join servicing accounts to risk master using composite key (`obligor_id` + `facility_id`) to eliminate duplicate rows.',
    owner: 'Siddharth Varma (Data Engineering Lead)',
    regulatoryDriver: 'BCBS 239 Risk Data Aggregation Principle 3',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Zero duplicate facility rows; total portfolio outstanding matches Core Banking GL sum exactly.',
    linkedRuleId: 'RULE-AQ-01',
    linkedMappingId: 'MAP-AQ-02',
    linkedTestId: 'UAT-AQ-012',
  },
  {
    id: 'REQ-AQ-007',
    title: 'Regulatory Override Approval & Audit Trail',
    requirementText: 'Manual overrides of asset quality classification shall require approved metadata (approver ID, approval date, business justification) and audit log retention.',
    owner: 'Dr. Meera Nambiar (Compliance SME)',
    regulatoryDriver: 'RBI Governance & Audit Lineage Mandate',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Unapproved manual override is rejected by rules engine; approved override records user ID and timestamp.',
    linkedRuleId: 'RULE-AQ-09',
    linkedMappingId: 'MAP-AQ-06',
    linkedTestId: 'UAT-AQ-014',
  },
  {
    id: 'REQ-AQ-008',
    title: 'Worst-Case Precedence Resolution Rule',
    requirementText: 'When conflict arises between servicing DPD status and qualitative watchlist flag, the engine shall apply worst-case risk precedence.',
    owner: 'Vikram Malhotra (Credit Risk SME)',
    regulatoryDriver: 'RBI IRACP Qualitative Deterioration Rule',
    priority: 'HIGH',
    status: 'Approved',
    acceptanceCriteria: 'Account with DPD 15 (SMA-0) but qualitative restructuring watchlist flag defaults to higher risk classification.',
    linkedRuleId: 'RULE-AQ-05',
    linkedMappingId: 'MAP-AQ-03',
    linkedTestId: 'UAT-AQ-015',
  },
  {
    id: 'REQ-AQ-009',
    title: 'Classification Reason Code Publication',
    requirementText: 'Every output asset classification and provision record shall include an explicit standardized reason code for auditability.',
    owner: 'Priya Sundaram (Risk Technology Lead)',
    regulatoryDriver: 'BCBS 239 Reporting Transparency',
    priority: 'MEDIUM',
    status: 'Approved',
    acceptanceCriteria: 'All 8 portfolio facility outputs populate a valid reason code (e.g. `AQ_DPD_31_60_SMA1`, `AQ_SUB_UNSECURED_25`).',
    linkedRuleId: 'RULE-AQ-03',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-016',
  },
  {
    id: 'REQ-AQ-010',
    title: 'Risk-to-Finance Automated Reconciliation',
    requirementText: 'The target system shall execute automated end-to-end reconciliation between Risk Warehouse provisions and Finance GL filings prior to period close.',
    owner: 'Ananya Sharma (Finance Controller)',
    regulatoryDriver: 'RBI Prudential Financial Reporting Standard',
    priority: 'CRITICAL',
    status: 'Approved',
    acceptanceCriteria: 'Reconciliation report generates zero unexplained variance; any variance triggers automated alert.',
    linkedRuleId: 'RULE-AQ-10',
    linkedMappingId: 'MAP-AQ-06',
    linkedTestId: 'UAT-AQ-010',
  },
];

export const BUSINESS_RULES: BusinessRule[] = [
  { id: 'RULE-AQ-01', ruleCode: 'RULE-AQ-01', category: 'Asset Quality', condition: 'DPD == 0', outputClassification: 'Standard', provisionRatePercent: 0.40, reasonCode: 'AQ_PERFORMING_STD', priority: 1 },
  { id: 'RULE-AQ-02', ruleCode: 'RULE-AQ-02', category: 'Asset Quality', condition: 'DPD > 0 AND DPD <= 30', outputClassification: 'SMA-0', provisionRatePercent: 0.40, reasonCode: 'AQ_DPD_01_30_SMA0', priority: 2 },
  { id: 'RULE-AQ-03', ruleCode: 'RULE-AQ-03', category: 'Asset Quality', condition: 'DPD > 30 AND DPD <= 60', outputClassification: 'SMA-1', provisionRatePercent: 0.40, reasonCode: 'AQ_DPD_31_60_SMA1', priority: 3 },
  { id: 'RULE-AQ-04', ruleCode: 'RULE-AQ-04', category: 'Asset Quality', condition: 'DPD > 60 AND DPD <= 90', outputClassification: 'SMA-2', provisionRatePercent: 0.40, reasonCode: 'AQ_DPD_61_90_SMA2', priority: 4 },
  { id: 'RULE-AQ-05', ruleCode: 'RULE-AQ-05', category: 'Asset Quality', condition: 'DPD > 90 AND NPAMonths <= 12', outputClassification: 'Substandard NPA', provisionRatePercent: 15.0, reasonCode: 'AQ_DPD_GT_90_SUB', priority: 5 },
  { id: 'RULE-AQ-06', ruleCode: 'RULE-AQ-06', category: 'Provisioning', condition: 'AssetClass == "Substandard" AND UnsecuredPortion > 0', outputClassification: 'Substandard Unsecured', provisionRatePercent: 25.0, reasonCode: 'AQ_SUB_UNSECURED_25', priority: 6 },
  { id: 'RULE-AQ-07', ruleCode: 'RULE-AQ-07', category: 'Provisioning', condition: 'AssetClass == "Doubtful-1" AND UnsecuredPortion > 0', outputClassification: 'Doubtful-1 Unsecured', provisionRatePercent: 100.0, reasonCode: 'AQ_DBT1_UNSEC_100', priority: 7 },
  { id: 'RULE-AQ-08', ruleCode: 'RULE-AQ-08', category: 'Provisioning', condition: 'Category == "CRE" AND AssetClass == "Standard"', outputClassification: 'CRE Standard', provisionRatePercent: 1.00, reasonCode: 'AQ_CRE_STD_100', priority: 8 },
  { id: 'RULE-AQ-09', ruleCode: 'RULE-AQ-09', category: 'Override', condition: 'HasManualOverride == true AND HasApprovalMetadata == true', outputClassification: 'Approved Override Status', provisionRatePercent: 0.0, reasonCode: 'AQ_MANUAL_OVERRIDE_APPROVED', priority: 9 },
  { id: 'RULE-AQ-10', ruleCode: 'RULE-AQ-10', category: 'Reconciliation', condition: 'RiskProvision != GLProvision', outputClassification: 'Reconciliation Discrepancy Alert', provisionRatePercent: 0.0, reasonCode: 'AQ_REC_VARIANCE_ALERT', priority: 10 },
];

export const SOURCE_TARGET_MAPPINGS: SourceToTargetMapping[] = [
  {
    id: 'MAP-AQ-01',
    sourceSystem: 'CBS_LOAN_ACCOUNT',
    sourceTable: 'tbl_loan_master',
    sourceColumn: 'days_past_due',
    dataType: 'INTEGER',
    grain: 'Account Level',
    transformationLogic: 'CASE WHEN dpd > 90 THEN "Substandard" WHEN dpd > 60 THEN "SMA-2" WHEN dpd > 30 THEN "SMA-1" WHEN dpd > 0 THEN "SMA-0" ELSE "Standard" END',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'asset_quality_status',
    nullRule: 'Default to 0 if null',
    effectiveDateRule: 'Snapshot as at EOD 23:59:59',
    dqRule: 'dpd >= 0 AND dpd <= 3650',
    status: 'Target Approved',
  },
  {
    id: 'MAP-AQ-02',
    sourceSystem: 'CBS_LOAN_ACCOUNT',
    sourceTable: 'tbl_loan_master',
    sourceColumn: 'outstanding_bal',
    dataType: 'NUMERIC(18,2)',
    grain: 'Account Level',
    transformationLogic: 'JOIN tbl_loan_master ON obligor_id AND facility_id (Composite Key)',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'outstanding_inr_cr',
    nullRule: 'Reject record if null',
    effectiveDateRule: 'Current Balance as at Cutoff',
    dqRule: 'outstanding_bal >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-AQ-03',
    sourceSystem: 'COLLECTIONS_DELINQUENCY',
    sourceTable: 'tbl_delinquency_log',
    sourceColumn: 'npa_declared_date',
    dataType: 'DATE',
    grain: 'Account Level',
    transformationLogic: 'DATEDIFF(month, npa_declared_date, CURRENT_DATE) TO DERIVE NPA_MONTHS',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'npa_months',
    nullRule: 'Null if Standard/SMA',
    effectiveDateRule: 'Original NPA Declaration Date',
    dqRule: 'npa_declared_date <= CURRENT_DATE',
    status: 'Target Approved',
  },
  {
    id: 'MAP-AQ-04',
    sourceSystem: 'COLLATERAL_REGISTER',
    sourceTable: 'tbl_collateral_master',
    sourceColumn: 'realisable_valuation',
    dataType: 'NUMERIC(18,2)',
    grain: 'Collateral Asset Level',
    transformationLogic: 'secured_portion = MIN(outstanding, realisable_valuation); unsecured_portion = MAX(0, outstanding - secured_portion)',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'secured_portion_inr_cr',
    nullRule: 'Default realisable_valuation to 0 if null',
    effectiveDateRule: 'Latest Approved Valuation Date',
    dqRule: 'realisable_valuation >= 0',
    status: 'Target Approved',
  },
  {
    id: 'MAP-AQ-05',
    sourceSystem: 'RISK_CUSTOMER_MASTER',
    sourceTable: 'tbl_facility_product',
    sourceColumn: 'exposure_category',
    dataType: 'VARCHAR(30)',
    grain: 'Facility Level',
    transformationLogic: 'LOOKUP IRACP_PROVISION_RATES WHERE exposure_category AND asset_quality_status',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'iracp_provision_rate_percent',
    nullRule: 'Default to "Other-Commercial"',
    effectiveDateRule: 'Facility Origination Category',
    dqRule: 'IN ("CRE", "CRE-Residential", "Farm-MSE-Housing", "Other-Commercial")',
    status: 'Target Approved',
  },
  {
    id: 'MAP-AQ-06',
    sourceSystem: 'RISK_WAREHOUSE',
    sourceTable: 'tbl_manual_overrides',
    sourceColumn: 'override_status_code',
    dataType: 'VARCHAR(20)',
    grain: 'Override Instance',
    transformationLogic: 'IF approved_by IS NOT NULL AND approval_date IS NOT NULL THEN APPLY override ELSE REJECT',
    targetTable: 'RISK_ASSET_QUALITY_MART',
    targetField: 'final_asset_quality_status',
    nullRule: 'Ignore override if null',
    effectiveDateRule: 'Approval Date <= Reporting Cutoff',
    dqRule: 'approved_by IS NOT NULL',
    status: 'Target Approved',
  },
];

export const INVESTIGATION_TASKS: InvestigationTask[] = [
  {
    id: 'INV-A',
    code: 'INVESTIGATION-A',
    title: 'Source DPD vs Downstream Asset Quality Discrepancy',
    description: 'Find accounts where Core Banking Servicing DPD indicates delinquency but downstream Risk Warehouse classifies the facility as Standard.',
    sampleQuery: 'SELECT facility_number, obligor_name, cbs_dpd, warehouse_status FROM tbl_loan_master WHERE cbs_dpd > 30 AND warehouse_status = "Standard";',
    sampleResultRows: [
      { facility_number: 'PUN-MFG-4403', obligor_name: 'Western Precision Auto Components', cbs_dpd: 42, warehouse_status: 'Standard', variance: '14-Day Batch Timing Gap' },
      { facility_number: 'CHN-RES-5507', obligor_name: 'Coromandel Residential Developers', cbs_dpd: 38, warehouse_status: 'Standard', variance: 'Stale Snapshot Date' },
    ],
    expectedFinding: 'Timing gap in batch ETL script causes 31-60 DPD accounts (SMA-1) to be ingested as 0 DPD Standard assets.',
    discoveredDefectId: 'DEF-AQ-001',
  },
  {
    id: 'INV-B',
    code: 'INVESTIGATION-B',
    title: 'Duplicate Facility Join Key Exposure',
    description: 'Detect duplicate facility records in risk warehouse tables caused by joining only on `obligor_id` instead of composite key (`obligor_id` + `facility_id`).',
    sampleQuery: 'SELECT facility_number, COUNT(*) as row_count, SUM(outstanding_inr_cr) FROM tbl_loan_master GROUP BY facility_number HAVING COUNT(*) > 1;',
    sampleResultRows: [
      { facility_number: 'MUM-CRE-8801', obligor_name: 'Sahyadri Commercial Logistics', row_count: 2, outstanding_inr_cr: 900.0, variance: 'Double-counted ₹450 Cr Outstanding' },
    ],
    expectedFinding: 'Missing composite join key doubles facility MUM-CRE-8801 outstanding exposure from ₹450 Cr to ₹900 Cr.',
    discoveredDefectId: 'DEF-AQ-002',
  },
  {
    id: 'INV-C',
    code: 'INVESTIGATION-C',
    title: 'Stale DPD Snapshot & EOD Payment Clearing Verification',
    description: 'Identify accounts where DPD was captured prior to evening 23:59:59 clearing runs.',
    sampleQuery: 'SELECT facility_number, etl_ingest_time, cbs_clearing_time, dpd_diff FROM tbl_etl_log WHERE etl_ingest_time < cbs_clearing_time;',
    sampleResultRows: [
      { facility_number: 'PUN-MFG-4403', etl_ingest_time: '18:00:00', cbs_clearing_time: '23:59:59', dpd_diff: 14 },
    ],
    expectedFinding: 'ETL ingestion ran 6 hours prior to payment clearing, retaining pre-clearing DPD.',
    discoveredDefectId: 'DEF-AQ-003',
  },
  {
    id: 'INV-D',
    code: 'INVESTIGATION-D',
    title: 'Risk Warehouse vs General Ledger Provision Reconciliation',
    description: 'Reconcile total required provisions between Risk Engine output and Finance General Ledger balance.',
    sampleQuery: 'SELECT SUM(risk_provision_inr_cr) as risk_total, SUM(gl_provision_inr_cr) as gl_total FROM tbl_reconciliation_summary;',
    sampleResultRows: [
      { risk_total: 74.8, gl_total: 56.0, variance_inr_cr: 18.8, status: 'RECONCILIATION DEFICIT' },
    ],
    expectedFinding: 'Finance GL carries a net ₹18.8 Cr provision deficit due to un-updated Substandard NPA rates on unsecured facility DEL-MED-7706.',
    discoveredDefectId: 'DEF-AQ-004',
  },
  {
    id: 'INV-E',
    code: 'INVESTIGATION-E',
    title: 'Unsecured Substandard Collateral Valuation Audit',
    description: 'Verify realisable security valuation applied to Substandard NPA accounts.',
    sampleQuery: 'SELECT facility_number, outstanding_inr_cr, realisable_security, applied_rate FROM tbl_collateral_audit WHERE asset_status = "Substandard";',
    sampleResultRows: [
      { facility_number: 'DEL-MED-7706', outstanding_inr_cr: 80.0, realisable_security: 0.0, applied_rate: 15.0, correct_rate: 25.0, deficit_inr_cr: 8.0 },
    ],
    expectedFinding: 'Facility DEL-MED-7706 with ₹0 security received 15% secured rate instead of mandatory 25% unsecured Substandard rate.',
    discoveredDefectId: 'DEF-AQ-004',
  },
];

export const SEEDED_DEFECTS: CaseDefect[] = [
  {
    id: 'DEF-AQ-001',
    code: 'DEF-2026-01',
    title: 'Operator Boundary Defect — DPD >= 90 Premature NPA Trigger',
    severity: 'CRITICAL',
    category: 'Rule Boundary',
    facilityNumber: 'CHN-RES-5507',
    obligorName: 'Coromandel Residential Developers Ltd',
    linkedEvidenceId: 'EV-04',
    linkedReqId: 'REQ-AQ-002',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-006',
    expectedBehaviour: 'Account with exactly 90 DPD remains SMA-2 (Standard asset). DPD > 90 required for Substandard NPA.',
    actualBehaviour: 'Legacy SQL code used `DPD >= 90`, prematurely classifying 90 DPD account as Substandard NPA.',
    rootCause: 'Boundary operator syntax error in legacy transformation script `sp_calc_asset_quality.sql`.',
    remediationFix: 'Update boundary operator from `>= 90` to `> 90` in `_engine/iracp.ts`.',
    regressionTest: 'UAT-AQ-006 (Verify 90 DPD boundary evaluates to SMA-2 Standard).',
    financialImpactInrCr: 28.5,
    status: 'Open',
  },
  {
    id: 'DEF-AQ-002',
    code: 'DEF-2026-02',
    title: 'Duplicate Composite Key Join — Outstanding Overstatement',
    severity: 'BLOCKER',
    category: 'Data Quality',
    facilityNumber: 'MUM-CRE-8801',
    obligorName: 'Sahyadri Commercial Logistics Group Ltd',
    linkedEvidenceId: 'EV-04',
    linkedReqId: 'REQ-AQ-006',
    linkedMappingId: 'MAP-AQ-02',
    linkedTestId: 'UAT-AQ-012',
    expectedBehaviour: 'Facility MUM-CRE-8801 appears once with ₹450 Cr outstanding balance.',
    actualBehaviour: 'Single join on `obligor_id` generated 2 duplicate rows, reporting ₹900 Cr outstanding and ₹9.0 Cr provision.',
    rootCause: 'Missing composite join key in `sp_build_mart.sql` (`obligor_id` without `facility_id`).',
    remediationFix: 'Enforce composite key join `ON obligor_id AND facility_id` in canonical mart pipeline.',
    regressionTest: 'UAT-AQ-012 (Verify composite key deduplication & exact ₹450 Cr outstanding).',
    financialImpactInrCr: 450.0,
    status: 'Open',
  },
  {
    id: 'DEF-AQ-003',
    code: 'DEF-2026-03',
    title: 'Batch Snapshot Timing Lag — Stale DPD Ingestion',
    severity: 'MAJOR',
    category: 'Effective Date',
    facilityNumber: 'PUN-MFG-4403',
    obligorName: 'Western Precision Auto Components Ltd',
    linkedEvidenceId: 'EV-03',
    linkedReqId: 'REQ-AQ-005',
    linkedMappingId: 'MAP-AQ-01',
    linkedTestId: 'UAT-AQ-011',
    expectedBehaviour: 'Ingest EOD cleared DPD = 42 days (SMA-1 classification).',
    actualBehaviour: 'Ingested 18:00 pre-clearing snapshot DPD = 28 days (SMA-0 classification), understating risk.',
    rootCause: 'Batch cron job triggered at 18:00 prior to evening 23:59:59 payment clearing runs.',
    remediationFix: 'Reschedule ETL ingestion trigger to 23:59:59 post EOD payment clearing completion.',
    regressionTest: 'UAT-AQ-011 (Verify EOD payment clearing snapshot DPD = 42 SMA-1).',
    financialImpactInrCr: 0.0,
    status: 'Open',
  },
  {
    id: 'DEF-AQ-004',
    code: 'DEF-2026-04',
    title: 'Unsecured Substandard NPA Provisioning Rate Error',
    severity: 'BLOCKER',
    category: 'Calculation Rate',
    facilityNumber: 'DEL-MED-7706',
    obligorName: 'Aethel Healthcare & Hospitals Ltd',
    linkedEvidenceId: 'EV-05',
    linkedReqId: 'REQ-AQ-003',
    linkedMappingId: 'MAP-AQ-04',
    linkedTestId: 'UAT-AQ-008',
    expectedBehaviour: 'Unsecured Substandard NPA facility receives mandatory 25% provision (₹20.0 Cr).',
    actualBehaviour: 'Uninitialized secured boolean applied 15% secured rate (₹12.0 Cr), creating a ₹8.0 Cr deficit.',
    rootCause: 'Engine evaluated `isSecured` flag without computing `realisableSecurity < outstanding`.',
    remediationFix: 'Explicitly compute `securedPortion = Math.min(outstanding, realisableSecurity)` before applying 25% rate to unsecured portion.',
    regressionTest: 'UAT-AQ-008 (Verify 25% provision rate applied to ₹80 Cr unsecured Substandard NPA).',
    financialImpactInrCr: 8.0,
    status: 'Open',
  },
];

export const UAT_TEST_PACK: UATTestCase[] = [
  { id: 'UAT-AQ-001', code: 'UAT-AQ-001', title: 'Verify 0 DPD Standard Asset Classification', linkedReqId: 'REQ-AQ-001', precondition: 'Account DPD = 0', testInput: 'DPD: 0, Product: Other-Commercial', expectedResult: 'Status: Standard, Provision Rate: 0.40%', actualResult: 'Status: Standard, Provision Rate: 0.40%', status: 'PASSED' },
  { id: 'UAT-AQ-002', code: 'UAT-AQ-002', title: 'Verify 30 DPD Boundary (SMA-0 Upper Limit)', linkedReqId: 'REQ-AQ-001', precondition: 'Account DPD = 30', testInput: 'DPD: 30, Product: Other-Commercial', expectedResult: 'Status: SMA-0, Provision Rate: 0.40%', actualResult: 'Status: SMA-0, Provision Rate: 0.40%', status: 'PASSED' },
  { id: 'UAT-AQ-003', code: 'UAT-AQ-003', title: 'Verify 31 DPD Boundary (SMA-1 Lower Limit)', linkedReqId: 'REQ-AQ-001', precondition: 'Account DPD = 31', testInput: 'DPD: 31, Product: Other-Commercial', expectedResult: 'Status: SMA-1, Provision Rate: 0.40%', actualResult: 'Status: SMA-1, Provision Rate: 0.40%', status: 'PASSED' },
  { id: 'UAT-AQ-004', code: 'UAT-AQ-004', title: 'Verify 60 DPD Boundary (SMA-1 Upper Limit)', linkedReqId: 'REQ-AQ-001', precondition: 'Account DPD = 60', testInput: 'DPD: 60, Product: Other-Commercial', expectedResult: 'Status: SMA-1, Provision Rate: 0.40%', actualResult: 'Status: SMA-1, Provision Rate: 0.40%', status: 'PASSED' },
  { id: 'UAT-AQ-005', code: 'UAT-AQ-005', title: 'Verify 61 DPD Boundary (SMA-2 Lower Limit)', linkedReqId: 'REQ-AQ-001', precondition: 'Account DPD = 61', testInput: 'DPD: 61, Product: Other-Commercial', expectedResult: 'Status: SMA-2, Provision Rate: 0.40%', actualResult: 'Status: SMA-2, Provision Rate: 0.40%', status: 'PASSED' },
  { id: 'UAT-AQ-006', code: 'UAT-AQ-006', title: 'Verify 90 DPD Boundary (SMA-2 vs Substandard NPA)', linkedReqId: 'REQ-AQ-002', precondition: 'Account DPD = 90', testInput: 'DPD: 90, Product: CRE-Residential', expectedResult: 'Status: SMA-2 (Standard), Provision Rate: 0.75%', actualResult: 'Status: Substandard NPA (Legacy Operator Defect)', status: 'FAILED', linkedDefectId: 'DEF-AQ-001' },
  { id: 'UAT-AQ-007', code: 'UAT-AQ-007', title: 'Verify 91 DPD Boundary (Substandard NPA Lower Limit)', linkedReqId: 'REQ-AQ-002', precondition: 'Account DPD = 91', testInput: 'DPD: 91, Product: Other-Commercial', expectedResult: 'Status: Substandard NPA, Provision Rate: 15.0%', actualResult: 'Status: Substandard NPA, Provision Rate: 15.0%', status: 'PASSED' },
  { id: 'UAT-AQ-008', code: 'UAT-AQ-008', title: 'Verify Unsecured Substandard NPA Provision (25%)', linkedReqId: 'REQ-AQ-003', precondition: 'Account DPD = 112, Realisable Security = 0', testInput: 'Outstanding: ₹80 Cr, Security: ₹0 Cr', expectedResult: 'Status: Substandard NPA, Provision: ₹20.0 Cr (25%)', actualResult: 'Status: Substandard NPA, Provision: ₹12.0 Cr (15%)', status: 'FAILED', linkedDefectId: 'DEF-AQ-004' },
  { id: 'UAT-AQ-009', code: 'UAT-AQ-009', title: 'Verify Category CRE Provision Rate (1.00%)', linkedReqId: 'REQ-AQ-004', precondition: 'Standard CRE loan', testInput: 'Outstanding: ₹450 Cr, Category: CRE', expectedResult: 'Provision: ₹4.50 Cr (1.00%)', actualResult: 'Provision: ₹4.50 Cr (1.00%)', status: 'PASSED' },
  { id: 'UAT-AQ-010', code: 'UAT-AQ-010', title: 'Verify Category MSE Provision Rate (0.25%)', linkedReqId: 'REQ-AQ-004', precondition: 'Standard MSE loan', testInput: 'Outstanding: ₹100 Cr, Category: Farm-MSE-Housing', expectedResult: 'Provision: ₹0.25 Cr (0.25%)', actualResult: 'Provision: ₹0.25 Cr (0.25%)', status: 'PASSED' },
  { id: 'UAT-AQ-011', code: 'UAT-AQ-011', title: 'Verify EOD Payment Clearing DPD Synchronization', linkedReqId: 'REQ-AQ-005', precondition: 'EOD payment cleared at 23:59', testInput: 'CBS DPD: 42, ETL Time: 23:59:59', expectedResult: 'Ingested DPD: 42 (SMA-1)', actualResult: 'Ingested DPD: 28 (SMA-0 pre-clearing)', status: 'FAILED', linkedDefectId: 'DEF-AQ-003' },
  { id: 'UAT-AQ-012', code: 'UAT-AQ-012', title: 'Verify Composite Key Deduplication', linkedReqId: 'REQ-AQ-006', precondition: 'Single facility MUM-CRE-8801', testInput: 'Join Key: obligor_id + facility_id', expectedResult: 'Rows: 1, Outstanding: ₹450 Cr', actualResult: 'Rows: 2, Outstanding: ₹900 Cr', status: 'FAILED', linkedDefectId: 'DEF-AQ-002' },
  { id: 'UAT-AQ-013', code: 'UAT-AQ-013', title: 'Verify Secured Substandard NPA Provision (15%)', linkedReqId: 'REQ-AQ-003', precondition: 'Substandard NPA with 100% Security', testInput: 'Outstanding: ₹100 Cr, Security: ₹120 Cr', expectedResult: 'Secured Provision: ₹15.0 Cr (15%)', actualResult: 'Secured Provision: ₹15.0 Cr (15%)', status: 'PASSED' },
  { id: 'UAT-AQ-014', code: 'UAT-AQ-014', title: 'Verify Unapproved Manual Override Rejection', linkedReqId: 'REQ-AQ-007', precondition: 'Manual override without metadata', testInput: 'Override Status: Standard, Approver: NULL', expectedResult: 'Override Rejected, Rule Engine Status Maintained', actualResult: 'Override Rejected, Rule Engine Status Maintained', status: 'PASSED' },
  { id: 'UAT-AQ-015', code: 'UAT-AQ-015', title: 'Verify Worst-Case Precedence Resolution', linkedReqId: 'REQ-AQ-008', precondition: 'DPD 15 (SMA-0) + Watchlist Restructuring Flag', testInput: 'Servicing DPD: 15, Watchlist: True', expectedResult: 'Governing Status: Worst-Case Restructuring Flag', actualResult: 'Governing Status: Worst-Case Restructuring Flag', status: 'PASSED' },
  { id: 'UAT-AQ-016', code: 'UAT-AQ-016', title: 'Verify Reason Code Output Population', linkedReqId: 'REQ-AQ-009', precondition: 'Rule calculation complete', testInput: 'Account: BLR-SME-1104', expectedResult: 'Reason Code: AQ_PERFORMING_STD', actualResult: 'Reason Code: AQ_PERFORMING_STD', status: 'PASSED' },
];

export const TRACEABILITY_MATRIX: TraceabilityChain[] = [
  { id: 'RTM-01', regulatoryDriver: 'RBI IRACP Master Circular Sec 2.1', reqId: 'REQ-AQ-001', ruleId: 'RULE-AQ-01', mappingId: 'MAP-AQ-01', component: '_engine/iracp.ts (classifyIRACPAsset)', testId: 'UAT-AQ-001', signoffOwner: 'Vikram Malhotra' },
  { id: 'RTM-02', regulatoryDriver: 'RBI IRACP Master Circular Sec 2.1', reqId: 'REQ-AQ-002', ruleId: 'RULE-AQ-02', mappingId: 'MAP-AQ-01', component: '_engine/iracp.ts (classifyIRACPAsset)', testId: 'UAT-AQ-006', defectId: 'DEF-AQ-001', signoffOwner: 'Priya Sundaram' },
  { id: 'RTM-03', regulatoryDriver: 'RBI IRACP Master Circular Sec 5.3', reqId: 'REQ-AQ-003', ruleId: 'RULE-AQ-06', mappingId: 'MAP-AQ-04', component: '_engine/iracp.ts (calculateIRACPProvision)', testId: 'UAT-AQ-008', defectId: 'DEF-AQ-004', signoffOwner: 'Ananya Sharma' },
  { id: 'RTM-04', regulatoryDriver: 'RBI IRACP Master Circular Sec 5.5', reqId: 'REQ-AQ-004', ruleId: 'RULE-AQ-08', mappingId: 'MAP-AQ-05', component: '_engine/iracp.ts (calculateIRACPProvision)', testId: 'UAT-AQ-009', signoffOwner: 'Ananya Sharma' },
  { id: 'RTM-05', regulatoryDriver: 'BCBS 239 Data Timeliness Principle 6', reqId: 'REQ-AQ-005', ruleId: 'RULE-AQ-03', mappingId: 'MAP-AQ-01', component: 'ETL Batch Script `sp_ingest_cbs.sql`', testId: 'UAT-AQ-011', defectId: 'DEF-AQ-003', signoffOwner: 'Rajesh Kulkarni' },
  { id: 'RTM-06', regulatoryDriver: 'BCBS 239 Data Aggregation Principle 3', reqId: 'REQ-AQ-006', ruleId: 'RULE-AQ-01', mappingId: 'MAP-AQ-02', component: 'ETL Transformation `sp_build_mart.sql`', testId: 'UAT-AQ-012', defectId: 'DEF-AQ-002', signoffOwner: 'Siddharth Varma' },
  { id: 'RTM-07', regulatoryDriver: 'RBI Governance & Audit Lineage Mandate', reqId: 'REQ-AQ-007', ruleId: 'RULE-AQ-09', mappingId: 'MAP-AQ-06', component: 'Override Store `tbl_manual_overrides`', testId: 'UAT-AQ-014', signoffOwner: 'Dr. Meera Nambiar' },
  { id: 'RTM-08', regulatoryDriver: 'RBI Prudential Financial Reporting', reqId: 'REQ-AQ-010', ruleId: 'RULE-AQ-10', mappingId: 'MAP-AQ-06', component: 'Reconciliation Engine `sp_risk_finance_rec.sql`', testId: 'UAT-AQ-010', signoffOwner: 'Ananya Sharma' },
];

export const RECONCILIATION_SUMMARY: ReconciliationSummary = {
  asOfDate: '31 July 2026',
  beforeFix: {
    facilityCount: 9, // Includes 1 duplicate row
    grossOutstandingInrCr: 3095.0, // Includes ₹450 Cr duplicate
    npaOutstandingInrCr: 280.0, // Includes 90 DPD false NPA ₹200 Cr
    requiredProvisionInrCr: 56.0, // Understated GL provision
    unexplainedVarianceInrCr: 18.8,
    reconciliationStatus: 'DEFICIT ALERT (VARIANCE > 0)',
  },
  afterFix: {
    facilityCount: 8,
    grossOutstandingInrCr: 2645.0,
    npaOutstandingInrCr: 80.0, // Exact 1 Substandard NPA (DEL-MED-7706)
    requiredProvisionInrCr: 74.8, // Correct target reserve
    unexplainedVarianceInrCr: 0.0,
    reconciliationStatus: 'RECONCILED (ZERO VARIANCE)',
  },
};

export const SIGN_OFF_APPROVERS: SignOffRequirement[] = [
  { id: 'SO-01', stakeholderTitle: 'Credit Risk Policy SME', approverName: 'Vikram Malhotra', role: 'First Line Credit Policy Owner', status: 'PENDING', comments: 'Pending verification of DEF-AQ-001 boundary fix (90 vs 91 DPD).' },
  { id: 'SO-02', stakeholderTitle: 'Finance & Impairment Controller', approverName: 'Ananya Sharma', role: 'Finance General Ledger Owner', status: 'PENDING', comments: 'Pending zero-variance reconciliation sign-off post DEF-AQ-004 unsecured rate fix.' },
  { id: 'SO-03', stakeholderTitle: 'Data Engineering Lead', approverName: 'Siddharth Varma', role: 'ETL Pipeline & Lineage Owner', status: 'PENDING', comments: 'Pending composite key deduplication verification on MUM-CRE-8801.' },
  { id: 'SO-04', stakeholderTitle: 'QA & UAT Testing Lead', approverName: 'Rohan Mehta', role: 'Business Acceptance QA Owner', status: 'PENDING', comments: 'Pending 100% UAT test suite execution pass.' },
  { id: 'SO-05', stakeholderTitle: 'Regulatory Compliance Lead', approverName: 'Dr. Meera Nambiar', role: 'Supervisory Compliance Owner', status: 'PENDING', comments: 'Pending audit trail verification of manual override store.' },
];

export const GOVERNANCE_CONFIG: GovernanceConfig = {
  blockingSeverities: ['BLOCKER', 'CRITICAL'],
  requiredUatPassPercent: 100,
  maxAllowedVarianceInrCr: 0.0,
  requireRtmCoveragePercent: 100,
};

export const CASE_01_DEFINITION: CaseDefinition = {
  metadata: CASE_01_METADATA,
  stakeholders: STAKEHOLDERS,
  evidence: EVIDENCE_PACK,
  currentStateNodes: CURRENT_STATE_NODES,
  targetStateNodes: TARGET_STATE_NODES,
  requirements: BUSINESS_REQUIREMENTS,
  rules: BUSINESS_RULES,
  mappings: SOURCE_TARGET_MAPPINGS,
  investigationTasks: INVESTIGATION_TASKS,
  defects: SEEDED_DEFECTS,
  uatTestPack: UAT_TEST_PACK,
  traceabilityMatrix: TRACEABILITY_MATRIX,
  reconciliationSummary: RECONCILIATION_SUMMARY,
  signoffs: SIGN_OFF_APPROVERS,
  governanceConfig: GOVERNANCE_CONFIG,
};
